'use strict';
(()=>{
 const $=id=>document.getElementById(id), U=CalculatorUI,F=CalculatorAnalysis.format;
 let worker=null,serial=0,pending=new Map(),generation=0;
 function reset(reason){if(worker)worker.terminate();worker=null;generation++;for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error(reason));}pending.clear();}
 function request(data){if(!worker){worker=new Worker('/tools/calculator-assets/advanced-worker.js');worker.onmessage=e=>{const job=pending.get(e.data.id);if(!job)return;clearTimeout(job.timer);pending.delete(e.data.id);e.data.error?job.reject(Error(e.data.error)):job.resolve(e.data.result);};worker.onerror=()=>reset('Math engine could not load. Reload the page and try again.');}
  return new Promise((resolve,reject)=>{const id=++serial,timer=setTimeout(()=>reset('Calculation timed out; shared variables were reset. Use a smaller input.'),6000);pending.set(id,{resolve,reject,timer});worker.postMessage({...data,id});});
 }
 function status(id,text,error=false){$(id).textContent=text;$(id).dataset.error=String(error);}
 function num(id){const value=strictNumber($(id).value);if(!Number.isFinite(value))throw Error('Enter a finite number for '+($(id).labels?.[0]?.textContent||id));return value;}
 function expressions(){return $('graph-expressions').value.split('\n').map(s=>s.trim()).filter(Boolean);}
 const lightColors=['#217fba','#9b4c09','#146954','#9b2872','#5a51b7','#a62222','#3c6804','#006979','#775123','#663b88'];
 const darkColors=['#79bfff','#ffbd75','#6ed6be','#ee9ace','#b2abff','#ffaaaa','#a9d876','#81d8e1','#d6b78f','#d8a7fb'];
 const color=i=>(document.documentElement.dataset.theme==='light'?lightColors:darkColors)[i];
 let graph=null,graphVersion=0,tableVersion=0,tape='',catalog=[];
 function invalidateGraph(){graphVersion++;tableVersion++;analysisRequest++;graph=null;$('graph-view').replaceChildren();$('graph-table').replaceChildren();$('graph-answer').textContent='';$('graph-trace-value').textContent='';$('graph-save').disabled=true;status('graph-status','Inputs changed. Draw graph to update.');}
 function bounds(){return ['xmin','xmax','ymin','ymax'].map(k=>num('graph-'+k));}
 function drawView(){
  if(!graph)return;const [xmin,xmax,ymin,ymax]=graph.bounds,W=900,H=500,left=75,right=865,top=35,bottom=440,X=x=>left+(x-xmin)/(xmax-xmin)*(right-left),Y=y=>bottom-(y-ymin)/(ymax-ymin)*(bottom-top);
  let s=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Function graph"><title>Graph window with ${graph.curves.length} curves</title><defs><clipPath id="graph-clip"><rect x="${left}" y="${top}" width="${right-left}" height="${bottom-top}"/></clipPath></defs>`;
  for(let i=0;i<=10;i++){const x=xmin+(xmax-xmin)*i/10,y=ymin+(ymax-ymin)*i/10;s+=`<path class="axis" opacity=".25" d="M${X(x)} ${top}V${bottom} M${left} ${Y(y)}H${right}"/>`;if(i%2===0)s+=`<text x="${X(x)}" y="465" text-anchor="middle">${U.esc(Number(x.toPrecision(4)))}</text><text x="65" y="${Y(y)+4}" text-anchor="end">${U.esc(Number(y.toPrecision(4)))}</text>`;}
  if(xmin<=0&&xmax>=0)s+=`<path class="axis" d="M${X(0)} ${top}V${bottom}"/>`;if(ymin<=0&&ymax>=0)s+=`<path class="axis" d="M${left} ${Y(0)}H${right}"/>`;
  graph.curves.forEach((curve,i)=>{let d='',prev=null;for(const p of curve.points){if(!p||p.some(v=>!Number.isFinite(v))){prev=null;continue;}const x=X(p[0]),y=Y(p[1]);if(!Number.isFinite(x)||!Number.isFinite(y)||Math.abs(x)>1e7||Math.abs(y)>1e7){prev=null;continue;}const jump=prev&&Math.abs(y-prev[1])>H*1.5;d+=(prev&&!jump?'L':'M')+x.toFixed(3)+' '+y.toFixed(3);prev=[x,y];}s+=`<path clip-path="url(#graph-clip)" d="${d}" stroke="${color(i)}" fill="none" stroke-width="2.4"/>`;if(graph.mode==='sequence')curve.points.filter(Boolean).forEach(p=>s+=`<circle clip-path="url(#graph-clip)" cx="${X(p[0])}" cy="${Y(p[1])}" r="3" fill="${color(i)}"/>`);});
  const curve=graph.curves[Number($('graph-curve').value)||0],index=Math.min(Number($('graph-trace').value),curve.points.length-1),p=curve.points[index];
  if(p){s+=`<circle clip-path="url(#graph-clip)" cx="${X(p[0])}" cy="${Y(p[1])}" r="6" stroke="var(--text)" fill="${color(Number($('graph-curve').value)||0)}" stroke-width="2"/>`;$('graph-trace-value').textContent=`Sample ${index+1}: x = ${F(p[0])}, y = ${F(p[1])}`;}else $('graph-trace-value').textContent='Undefined at this sample.';
  s+='<text x="475" y="493" text-anchor="middle">X</text><text x="16" y="24">Y</text></svg>';
  $('graph-view').innerHTML=`<figure class="analysis-figure">${s}<figcaption>${graph.curves.map((c,i)=>`<span style="color:${color(i)}">Curve ${i+1}: ${U.esc(c.label)}</span>`).join(' · ')}</figcaption></figure>`;
  $('graph-view').querySelector('svg').onclick=e=>{const rect=e.currentTarget.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*W,py=(e.clientY-rect.top)/rect.height*H;let nearest=0,distance=Infinity;curve.points.forEach((p,i)=>{if(!p)return;const d=(X(p[0])-px)**2+(Y(p[1])-py)**2;if(d<distance){nearest=i;distance=d;}});$('graph-trace').value=nearest;drawView();};
 }
 async function draw(){analysisRequest++;tableVersion++;$('graph-trace-value').textContent='';const version=++graphVersion;graph=null;$('graph-save').disabled=true;$('graph-view').replaceChildren();$('graph-table').replaceChildren();$('graph-answer').textContent='';status('graph-status','Calculating graph…');try{const mode=$('graph-mode').value;const result=await request({action:'graph',mode,angle:$('graph-angle').value,expressions:expressions(),bounds:bounds(),start:mode==='function'?0:num('graph-start'),end:mode==='function'?1:num('graph-end'),initial:mode==='sequence'?num('graph-initial'):1});if(version!==graphVersion)return;graph=result;$('graph-curve').innerHTML=graph.curves.map((c,i)=>`<option value="${i}">Curve ${i+1}</option>`).join('');$('graph-trace').max=graph.curves[0].points.length-1;$('graph-trace').value=Math.floor(Number($('graph-trace').max)/2);drawView();$('graph-save').disabled=false;status('graph-status','Graph updated. Use the trace slider or click the plot. Undefined points are omitted.');}catch(e){if(version===graphVersion)status('graph-status',e.message,true);}}
 new MutationObserver(()=>{if(graph)drawView();}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
 $('graph-run').onclick=draw;
 $('graph-trace').oninput=drawView;$('graph-curve').onchange=()=>{if(graph)$('graph-trace').max=graph.curves[Number($('graph-curve').value)].points.length-1;drawView();};
 for(const id of ['expressions','angle','xmin','xmax','ymin','ymax','start','end','initial'])$('graph-'+id).addEventListener('input',invalidateGraph);
 $('graph-mode').onchange=()=>{const mode=$('graph-mode').value;$('graph-parameters').hidden=mode==='function';$('graph-initial').disabled=mode!=='sequence';$('graph-help').textContent=mode==='function'?'Use x; one expression per line. Piecewise: x < 0 ? -x : x.':mode==='parametric'?'One curve per line: cos(t); sin(t). Separate x(t) and y(t) with a semicolon.':mode==='polar'?'Use theta for the angle: 2*sin(3*theta). Parameter range uses the selected angle unit.':'Enter recurrence using previous u: u*1.1. The first point is the initial value at n start; subsequent points use n and previous u.';invalidateGraph();};
 $('graph-example').onclick=()=>{const mode=$('graph-mode').value;$('graph-expressions').value={function:'x^2 - 4\n2*x',parametric:'3*cos(t); 2*sin(t)',polar:'4*sin(3*theta)',sequence:'u*1.1'}[mode];$('graph-angle').value='RAD';$('graph-start').value='0';$('graph-end').value=mode==='sequence'?'20':String(2*Math.PI);$('graph-initial').value='1';['xmin','ymin'].forEach(k=>$('graph-'+k).value=mode==='sequence'?'0':'-5');['xmax','ymax'].forEach(k=>$('graph-'+k).value=mode==='sequence'?'25':'5');draw();};
 $('graph-reset').onclick=()=>{['xmin','ymin'].forEach(k=>$('graph-'+k).value='-10');['xmax','ymax'].forEach(k=>$('graph-'+k).value='10');draw();};
 function zoom(factor){try{const b=bounds();for(const [lo,hi]of [[0,1],[2,3]]){const mid=(b[lo]+b[hi])/2,span=(b[hi]-b[lo])*factor/2;b[lo]=mid-span;b[hi]=mid+span;}['xmin','xmax','ymin','ymax'].forEach((k,i)=>$('graph-'+k).value=b[i]);draw();}catch(e){status('graph-status',e.message,true);}}
 $('graph-zoom-in').onclick=()=>zoom(.5);$('graph-zoom-out').onclick=()=>zoom(2);
 $('graph-fit').onclick=()=>{if(!graph){status('graph-status','Draw a graph before fitting the Y window.',true);return;}const values=graph.curves.flatMap(c=>c.points.filter(Boolean).map(p=>p[1])).filter(Number.isFinite).sort((a,b)=>a-b);const lo=values[Math.floor(values.length*.02)],hi=values[Math.floor((values.length-1)*.98)],pad=(hi-lo)*.1||1;$('graph-ymin').value=lo-pad;$('graph-ymax').value=hi+pad;draw();};
 $('graph-save').onclick=()=>{if(!graph)return;const svg=$('graph-view').querySelector('svg').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.axis{stroke:#68788a;stroke-width:1}text{fill:#172638;font:13px monospace}svg{background:white}';svg.prepend(style);svg.querySelectorAll('[stroke="var(--text)"]').forEach(e=>e.setAttribute('stroke','#172638'));U.download('engineering-graph.svg',svg.outerHTML,'image/svg+xml');};
 let analysisRequest=0;
 for(const id of ['operation','a','b'])$('graph-'+id).addEventListener('input',()=>{analysisRequest++;$('graph-answer').textContent='Inputs changed. Calculate again.';});
 $('graph-calculate').onclick=async()=>{const ticket=++analysisRequest;try{if($('graph-mode').value!=='function')throw Error('Numerical graph analysis currently applies to Cartesian function mode.');const ex=expressions(),op=$('graph-operation').value;if(op==='intersect'&&ex.length<2)throw Error('Enter two functions for intersection.');$('graph-answer').textContent='Calculating…';const r=await request({action:'calculus',operation:op,expression:ex[0],second:ex[1],angle:$('graph-angle').value,a:num('graph-a'),b:['value','derivative'].includes(op)?0:num('graph-b')});if(ticket===analysisRequest)$('graph-answer').textContent=r.text;}catch(e){if(ticket===analysisRequest)$('graph-answer').textContent=e.message;}};
 for(const id of ['start','step','count'])$('graph-table-'+id).addEventListener('input',()=>{tableVersion++;$('graph-table').replaceChildren();});
 $('graph-table-run').onclick=async()=>{const ticket=++tableVersion,version=graphVersion;$('graph-table').replaceChildren();try{if($('graph-mode').value!=='function')throw Error('Function tables require Cartesian function mode.');const ex=expressions();const rows=await request({action:'table',angle:$('graph-angle').value,expressions:ex,start:num('graph-table-start'),step:num('graph-table-step'),count:num('graph-table-count')});if(version!==graphVersion||ticket!==tableVersion)return;$('graph-table').innerHTML=U.table({title:'Function table',headers:['X',...ex.map((_,i)=>'Y'+(i+1))],rows:rows.map(r=>r.map(v=>v==null?'Undefined':v))});}catch(e){if(version===graphVersion&&ticket===tableVersion)status('graph-status',e.message,true);}};
 const examples={matrix:'A = [2,1;1,3]\ninv(A)',linear:'lusolve([2,1;1,3],[5,7])',complex:'(2+3i)*(1-i)\nabs(3+4i)\narg(1+i)',lists:'L1=[2,4,6,8,10]\nmean(L1)\nstd(L1)\ncumSum(L1)',roots:'polynomialRoot(-6,11,-6,1)',calculus:'nDeriv("x^3",2)\nfnInt("sin(x)",0,pi)\nsolve("x^2-2",0,2)',units:'25.4 mm to inch\n100 degC to degF',probability:'combinations(10,3)\nbinomcdf(20,0.1,2)\nnormalcdf(-1,1,0,1)',cash:'npv(0.1,[-1000,400,400,400])\nirr([-1000,400,400,400],0,1)'};
 $('math-load').onclick=()=>{$('math-input').value=examples[$('math-example').value];status('math-status','Example loaded. Evaluate to calculate.');};
 $('math-run').onclick=async()=>{const expression=$('math-input').value;status('math-status','Calculating…');try{const r=await request({action:'evaluate',expression,angle:$('math-angle').value});tape+=(tape?'\n\n':'')+expression+'\n= '+r.text;tape=tape.slice(-50000);$('math-output').textContent=tape;$('math-variables').textContent='Session variables: '+r.variables.join(', ');status('math-status','Calculation complete.');}catch(e){status('math-status',e.message,true);}};
 $('math-clear').onclick=async()=>{try{await request({action:'reset'});$('math-variables').textContent='';invalidateGraph();status('math-status','Session variables cleared.');}catch(e){status('math-status',e.message,true);}};
 $('math-save').onclick=()=>U.download('engineering-calculation-tape.txt',tape||'No calculations yet.');
 function renderCatalog(){const query=$('math-search').value.toLowerCase(),filtered=catalog.filter(s=>s.toLowerCase().includes(query)).slice(0,30);$('math-catalog').innerHTML=filtered.map(s=>`<button type="button" class="btn ghost" data-function="${U.esc(s)}">${U.esc(s)}(…)</button>`).join('')||'<p>No matching supported functions.</p>';}
 $('math-search').oninput=renderCatalog;$('math-catalog').onclick=e=>{const b=e.target.closest('[data-function]');if(!b)return;const area=$('math-input'),start=area.selectionStart,end=area.selectionEnd;area.setRangeText(b.dataset.function+'(',start,end,'end');area.focus();};
 // Load the large math engine only when an advanced workspace is used.
 document.querySelectorAll('[data-page="pg-math"]').forEach(t=>t.addEventListener('click',async()=>{if(catalog.length)return;try{catalog=await request({action:'catalog'});renderCatalog();}catch(e){status('math-status',e.message,true);}}));
 function financeChange(){financeVersion++;$('finance-output').textContent='';$('finance-table').replaceChildren();status('finance-status','Inputs changed. Solve TVM to update.');for(const key of ['n','rate','pv','pmt','fv'])$('finance-'+key).disabled=key===$('finance-solve').value;}
 let financeVersion=0;$('pg-finance').addEventListener('input',financeChange);$('finance-solve').onchange=financeChange;financeChange();
 $('finance-run').onclick=async()=>{const version=++financeVersion;$('finance-output').textContent='';$('finance-table').replaceChildren();status('finance-status','Solving…');try{const solve=$('finance-solve').value,values={};for(const k of ['n','rate','pv','pmt','fv','py','cy'])values[k]=k===solve?0:num('finance-'+k);values.begin=$('finance-begin').value==='1';if(values.py<=0||values.cy<=0)throw Error('Payment and compounding frequencies must be positive.');const result=await request({action:'finance',values,solve});if(version!==financeVersion)return;values[solve]=result.value;$('finance-output').textContent=result.text;status('finance-status','Solved using the cash-flow sign convention.');
 if(values.n>0&&values.n<=600&&Number.isInteger(values.n)&&values.pv>0&&values.pmt<0){const r=Math.expm1(values.cy/values.py*Math.log1p(values.rate/100/values.cy));let balance=values.pv,totalInterest=0,rows=[];for(let period=1;period<=values.n;period++){let interest=values.begin?(balance+values.pmt)*r:balance*r;balance=balance+values.pmt+interest;totalInterest+=interest;rows.push([period,-values.pmt,interest,-values.pmt-interest,balance]);}$('finance-table').innerHTML=U.table({title:`Amortization — total interest ${F(totalInterest)}`,headers:['Period','Payment out','Interest','Principal','Balance'],rows});}
 }catch(e){if(version===financeVersion)status('finance-status',e.message,true);}};
 let programVersion=0;
 for(const id of ['source','angle'])$('program-'+id).addEventListener('input',()=>{programVersion++;$('program-output').textContent='';status('program-status','Inputs changed. Run program again.');});
 $('program-run').onclick=async()=>{const ticket=++programVersion;status('program-status','Running…');$('program-output').textContent='';try{const r=await request({action:'program',source:$('program-source').value,angle:$('program-angle').value});if(ticket!==programVersion)return;$('program-output').textContent=r.text;status('program-status',`Completed (${r.steps} execution steps).`);}catch(e){if(ticket===programVersion)status('program-status',e.message,true);}};
 $('program-save').onclick=()=>U.download('engineering-program.txt',$('program-source').value);
})();
