'use strict';
(()=>{
 const C=QualityCost,D=GuidedData,U=CalculatorUI,esc=U.esc,el=id=>document.getElementById('cost-'+id);
 const settings=['currency','productionUnit','baseline','current','assumptions','cash','avoidance','capacity','initial','recurring','years','discount','sensitivity'];
 let result=null,version=0,provenance={};
 const money=v=>v==null?'Unavailable':Number(v).toLocaleString('en-CA',{minimumFractionDigits:2,maximumFractionDigits:2}),pct=v=>v==null?'Unavailable':(100*v).toFixed(2)+'%';
 function status(s,error=false){el('status').textContent=s;el('status').dataset.error=String(error);}
 function invalidate(message='Inputs changed. Analyze again for current results.') {result=null;el('output').hidden=true;el('report').disabled=el('csv').disabled=true;status(message);}
 const guarded=fn=>(...args)=>{try{return fn(...args);}catch(e){status(e.message,true);}};
 function inputs(){return Object.fromEntries(['cost','production','benefits'].map(k=>[k,el(k).value]));}
 function options(){return {...Object.fromEntries(settings.map(k=>[k,el(k).value])),complete:el('complete').checked,provenance};}
 function read(){const i=inputs();return C.read(i.cost,i.production,i.benefits);}
 function periods(data,reset=false){for(const id of ['baseline','current']){const prior=reset?'':el(id).value;el(id).replaceChildren();data.periods.forEach(p=>el(id).add(new Option(p,p)));if(prior&&!data.periods.includes(prior))el(id).add(new Option(prior+' (not present)',prior));el(id).value=prior||(id==='baseline'?data.periods[0]:data.periods.find(p=>p!==data.periods[0])||'');}}
 for(const id of [...settings,'complete','cost','production','benefits'])for(const event of ['input','change'])el(id).addEventListener(event,()=>{version++;if(['cost','production','benefits'].includes(id)){provenance[id]='Edited locally; earlier import mapping no longer applies.';el('source').textContent=JSON.stringify(provenance);el('complete').checked=false;}invalidate();});
 el('periods').onclick=guarded(()=>{const data=read();periods(data);invalidate('Tables read. Select baseline/comparison periods and review completeness before analysis.');});
 function table(title,headers,rows){return U.table({title,headers,rows});}
 function pareto(rows,type,currency){const total=rows.reduce((n,v)=>n+v[type],0),max=rows[0]?.[type]||1;
  return `<section class="cost-pareto"><h3>${type==='cost'?'Cost':'Frequency'} Pareto — comparison period</h3><p class="hint">${type==='cost'?esc(currency):'Allocated events'} · top 12 causes shown; full ranking is in the report and CSV. ${total?'':'No positive values to rank.'}</p>${rows.slice(0,12).map(r=>`<div class="cost-bar-row"><span>${esc(r.category+' · '+r.cause)}</span><span>${esc(type==='cost'?money(r.cost):r.events)} · cumulative ${pct(r.cumulative)}</span><div class="cost-bar-track"><div class="cost-bar-fill" style="width:${Math.max(0,Math.min(100,100*r[type]/max))}%"></div></div></div>`).join('')}</section>`;
 }
 function render(r){
  const cu=r.currency;el('output').hidden=false;
  el('summary').innerHTML=`<strong>${esc(r.current.period)} versus ${esc(r.base.period)}</strong><p>Baseline product cost rates are applied to comparison-period production. This adjusts volume and product mix, but does not isolate price changes or establish project causation.</p>`;
  el('metrics').innerHTML=[['Total cost of quality',money(r.current.coq)+' '+cu],['Cost of poor quality',money(r.current.copq)+' '+cu],['Mix-adjusted COQ reduction',money(r.current.adjustedCOQ)+' '+cu],['Mix-adjusted COPQ reduction',money(r.current.adjustedCOPQ)+' '+cu]].map(([k,v])=>`<div class="cost-metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');
  el('categories').innerHTML=table('Comparison-period quality cost',[ 'Category',cu,'Share of COQ'],C.categories.map((c,i)=>[c,money(r.current.cat[i]),pct(r.current.coq?r.current.cat[i]/r.current.coq:null)]));
  el('period-table').innerHTML=table('All periods — order from production table',['Period',`Volume (${r.productionUnit})`,'COQ','COPQ','COQ / unit','COQ / revenue','Adjusted COQ reduction'],r.periodRows.slice(0,200).map(v=>[v.period,v.volume,money(v.coq),money(v.copq),money(v.perUnit),pct(v.percentRevenue),money(v.adjustedCOQ)]));
  el('mix').innerHTML=table('Comparison product mix',['Product','Volume','Mix share','Baseline COPQ / unit'],r.mix.slice(0,200).map(v=>[v.product,v.volume,pct(v.share),money(v.baselineRate)]));
  el('pareto').innerHTML=pareto(r.costPareto,'cost',cu)+pareto(r.frequencyPareto,'events',cu);
  el('business').innerHTML=`<p><strong>Projected, not verified.</strong> ${r.business.inputs.years}-year horizon at ${r.business.inputs.discount}% annual discount. Cash flows are discounted at year-end; simple payback assumes cash accrues uniformly within each year.</p>`+table('Cash benefit sensitivity',['Scenario','Annual net cash','NPV','Undiscounted net','Cash ROI','Simple payback (years)'],r.business.scenarios.map(s=>[s.name,money(s.net),money(s.npv),money(s.netTotal),pct(s.roi),s.payback==null?'Not within horizon':Number(s.payback.toFixed(3))]))+`<p>Separate annual forecasts: cost avoidance ${money(r.business.inputs.avoidance)} ${esc(cu)}; released-capacity valuation ${money(r.business.inputs.capacity)} ${esc(cu)}. Neither is added to cash results. The forecast form is independent of projected register rows; they are not summed.</p>`;
  el('flows').innerHTML=table('Base-case cash flows — '+cu,['Year','Cash benefit','Cash cost','Net cash','Present value','Cumulative net'],r.business.scenarios[1].flows.map(v=>[v.year,money(v.cash),money(v.cost),money(v.net),money(v.present),money(v.cumulative)]));
  const b=r.benefits;el('verification').innerHTML=`<p><strong>User-recorded verification; evidence has not been checked by this tool.</strong> Project-wide totals cover every register period, including initial costs in the baseline period. “Actual recorded” includes Realized and Verified once; Verified is a subset.</p>`+table('Benefit register — '+cu,['Type','Projected register','Realized, unverified','User-recorded verified','Actual recorded'],C.types.map((t,i)=>[t,money(b.projected[i]),money(b.realized[i]),money(b.verified[i]),money(b.actual[i])]))+`<p>Actual recorded net cash: <strong>${money(b.actualNet)} ${esc(cu)}</strong>. User-recorded verified net cash: <strong>${money(b.verifiedNet)} ${esc(cu)}</strong>. Net = cash savings − implementation costs − recurring costs in the corresponding status scope. Missing or unverified costs can overstate the verified subtotal.</p>`+table('Verification by actual period',['Period','Actual cash benefits','Verified cash benefits','Verified project costs','Pending entries'],b.verification.slice(0,200).map(v=>[v.period,money(v.realizedCash),money(v.verifiedCash),money(v.verifiedCost),v.pending]));
  el('notes').innerHTML=`<p><strong>Recorded assumptions:</strong> ${esc(r.notes)}</p>`+r.warnings.map(n=>`<p>${esc(n)}</p>`).join('')+'<p>Period and mix tables show up to 200 rows; report/CSV retain all rows. Monetary displays round to two decimals; calculations retain floating-point precision.</p>';
  el('report').disabled=el('csv').disabled=false;status('Analysis complete. Review the adjusted cost comparison, projected cash case and separately recorded benefits.');el('status').focus({preventScroll:true});el('status').scrollIntoView?.({block:'start',behavior:'instant'});
 }
 el('run').onclick=()=>{invalidate();try{const data=read();periods(data);result=C.run(data,options());render(result);}catch(e){invalidate();status(e.message,true);}};
 el('save').onclick=guarded(()=>{read();const project={format:'upskillsprint-quality-cost',version:1,saved:new Date().toISOString(),inputs:inputs(),settings:options()};const raw=JSON.stringify(project,null,2);D.check(raw.length<=3500000,'Project exceeds 3.5 MB.');U.download('upskillsprint-quality-cost.json',raw,'application/json');status('Workspace download prepared. Save this file to retain inputs, settings and verification records.');});
 el('restore').onchange=async()=>{const f=el('restore').files?.[0];if(!f)return;const token=++version;try{D.check(f.size<=3500000,'Project exceeds 3.5 MB.');const raw=await f.text();if(token!==version)return;const v=C.restore(raw);
  if(Object.values(inputs()).some(s=>s.trim())&&!window.confirm('Replace the current Cost & Savings inputs with this saved project? Save the current workspace first if needed.'))return;
  for(const [k,value]of Object.entries(v.inputs))if(['cost','production','benefits'].includes(k))el(k).value=value;
  periods(read(),true);for(const k of settings){const value=v.settings[k];if(typeof value==='string'&&value.length<=500){if(el(k).tagName==='SELECT'&&![...el(k).options].some(o=>o.value===value))el(k).add(new Option(value+' (not present)',value));el(k).value=value;}}
  provenance=typeof v.settings.provenance==='object'&&v.settings.provenance?JSON.parse(JSON.stringify(v.settings.provenance)):{};el('source').textContent=JSON.stringify(provenance);el('complete').checked=false;invalidate('Workspace restored. Review period choices and completeness; no analysis was run automatically.');
 }catch(e){if(token===version)status(e.message,true);}finally{el('restore').value='';}};
 el('copy').onclick=guarded(()=>{
  const target=el('copy-target').value,{dataset:d,settings:o}=window.GuidedWorkspace.snapshot(),cols=C.headers[target];
  D.check(d.columns.length===cols.length&&d.columns.every((v,i)=>v.trim().toLowerCase()===cols[i].toLowerCase()),'Rename/reorder the guided columns to: '+cols.join(','));
  const rows=[],refs=[];d.rows.forEach((r,i)=>{if(d.excluded.includes(i))return;if(o.filterColumn!==''&&o.filterColumn!=null&&r[Number(o.filterColumn)]!==o.filterValue)return;rows.push(r);refs.push(d.sourceRows[i]);});
  const raw=D.csv([cols,...rows]);D.check(raw.length<=1000000,'The copied table exceeds 1 MB.');version++;el(target).value=raw;provenance[target]={name:d.name,revision:d.revision,source:d.source,sourceRows:refs,omitted:d.rows.length-rows.length,filterColumn:o.filterColumn,filterValue:o.filterValue};el('source').textContent=`Copied ${d.name}, revision ${d.revision}: ${rows.length} rows, ${d.rows.length-rows.length} omitted.`;el('complete').checked=false;invalidate('Copied the active dataset. Read tables to update periods and validate all fields.');
 });
 el('example').onclick=()=>{
  version++;const rows=[],add=(period,product,cat,cause,q,unit,rate,events)=>rows.push([period,product,cat,cause,q,unit,rate,events]);
  for(const [period,product,scrap,rework,downtime,warranty,prevent,appraise]of [
   ['Baseline','A',4000,4000,1000,1000,400,600],['Baseline','B',4000,4000,0,2000,200,300],
   ['January','A',3000,2400,500,500,600,600],['January','B',6000,4000,0,1200,350,300],
   ['February','A',3000,2000,500,800,650,600],['February','B',4000,3200,0,1200,350,300]]){
   add(period,product,'Internal failure','Scrap',scrap/500,'tonnes',500,Math.round(scrap/500));add(period,product,'Internal failure','Rework',rework/50,'hours',50,Math.round(rework/100));if(downtime)add(period,product,'Internal failure','Downtime',downtime/250,'hours',250,Math.round(downtime/250));add(period,product,'External failure','Warranty',warranty,'currency',1,Math.round(warranty/100));add(period,product,'Prevention','Training',prevent/50,'hours',50,0);add(period,product,'Appraisal','Inspection',appraise/50,'hours',50,0);
  }
  el('cost').value=D.csv([C.headers.cost,...rows]);el('production').value=D.csv([C.headers.production,['Baseline','A',1000,100000],['Baseline','B',500,75000],['January','A',800,80000],['January','B',700,105000],['February','A',900,90000],['February','B',600,90000]]);
  el('benefits').value=D.csv([C.headers.benefits,['C-001','Baseline','Implementation cost',12000,'Verified','Training example owner','DEMO invoice','2026-02-01','Fictitious paid project invoice'],['B-001','January','Cash savings',3000,'Verified','Training example owner','DEMO ledger reconciliation','2026-02-10','Fictitious cash reduction attributed after reconciliation'],['C-002','January','Recurring cost',400,'Verified','Training example owner','DEMO operating invoice','2026-02-10','Fictitious incremental operating cost'],['B-002','February','Cash savings',4500,'Realized','Training example owner','Pending review','','Not verified; reconcile invoices and product mix'],['N-001','February','Released capacity',1800,'Realized','Training example owner','DEMO hour study','','30 hours at 60; capacity only, no payroll reduction'],['F-001','Forecast','Cost avoidance',6000,'Projected','Training example owner','','','Avoided future expenditure; separate from cash']]);
  const defaults={currency:'CAD',productionUnit:'tonnes',assumptions:'Fictitious monthly steel-product example. Common tonnes and constant valuation rates; A/B mix adjusted separately. Event counts allocated without overlap. Cash benefits require separate invoice/ledger reconciliation.',cash:'50000',avoidance:'6000',capacity:'12000',initial:'12000',recurring:'8000',years:'3',discount:'10',sensitivity:'20'};for(const[k,v]of Object.entries(defaults))el(k).value=v;
  provenance={example:'Fictitious training data, not evidence of real savings.'};el('source').textContent=provenance.example;periods(read(),true);el('current').value='February';el('complete').checked=true;invalidate('Fictitious manufacturing example loaded. Review assumptions and run the analysis.');
 };
 el('report').onclick=guarded(()=>{if(result)U.download('upskillsprint-quality-cost-report.txt',C.report(result));});
 el('csv').onclick=guarded(()=>{
  if(!result)return;const r=result,rows=[['Section','Period / scenario','Metric','Value','Unit']],add=(section,period,metric,value,unit=r.currency)=>rows.push([section,period,metric,value??'Unavailable',unit]);
  for(const v of r.periodRows){for(const [label,k]of [['COQ','coq'],['COPQ','copq'],['Revenue','revenue'],['COQ per unit','perUnit'],['Adjusted COQ reduction','adjustedCOQ'],['Adjusted COPQ reduction','adjustedCOPQ']])add('Costs',v.period,label,v[k]);add('Costs',v.period,'Production',v.volume,r.productionUnit);add('Costs',v.period,'COQ / revenue',v.percentRevenue,'fraction');C.categories.forEach((c,i)=>add('Category',v.period,c,v.cat[i]));}
  for(const v of r.mix){add('Product mix',v.product,'Volume',v.volume,r.productionUnit);add('Product mix',v.product,'Share',v.share,'fraction');add('Product mix',v.product,'Baseline volume',v.baselineVolume,r.productionUnit);add('Product mix',v.product,'Baseline COPQ per unit',v.baselineRate);}
  for(const s of r.business.scenarios){add('Projected',s.name,'Cash NPV',s.npv);add('Projected',s.name,'Annual net cash',s.net);add('Projected',s.name,'Undiscounted net',s.netTotal);add('Projected',s.name,'Cash ROI',s.roi,'fraction');add('Projected',s.name,'Simple payback',s.payback??'Not within horizon','years');for(const v of s.flows)for(const [label,k]of [['Cash benefit','cash'],['Cash cost','cost'],['Net cash','net'],['Present value','present'],['Cumulative net','cumulative']])add('Cash flow',s.name+' year '+v.year,label,v[k]);}
  for(const [i,t]of C.types.entries())for(const status of ['projected','realized','verified','actual'])add('Register',status,t,r.benefits[status][i]);add('Register','Actual recorded','Net cash',r.benefits.actualNet);add('Register','User-recorded verified','Net cash',r.benefits.verifiedNet);
  for(const v of r.benefits.verification){add('Verification',v.period,'Actual cash benefits',v.realizedCash);add('Verification',v.period,'Verified cash benefits',v.verifiedCash);add('Verification',v.period,'Verified costs',v.verifiedCost);add('Verification',v.period,'Pending entries',v.pending,'count');}
  for(const [type,list,measure]of [['Cost Pareto',r.costPareto,'cost'],['Frequency Pareto',r.frequencyPareto,'events']])for(const v of list){add(type,r.current.period,v.category+' · '+v.cause,v[measure],measure==='cost'?r.currency:'events');add(type+' cumulative',r.current.period,v.category+' · '+v.cause,v.cumulative,'fraction');}
  U.download('upskillsprint-quality-cost-results.csv',D.csv(rows),'text/csv;charset=utf-8');
 });
})();
