(function(){
'use strict';
const ACTION='a,button,[role="button"],input[type="button"],input[type="submit"]';
const LEAD=/^(?:[\s\u00a0]*(?:←|⟵|↩|↶|⬅|⇐|⟸|<-+)[\s\u00a0]*)+/u;
const TRAIL=/(?:[\s\u00a0]*(?:→|⟶|➜|➝|➞|➡|⟹|-+>)[\s\u00a0]*)+$/u;
const ONLY=/^(?:[\s\u00a0]*(?:←|⟵|↩|↶|⬅|⇐|⟸|→|⟶|➜|➝|➞|➡|⟹|<-+|-+>)[\s\u00a0]*)+$/u;
const ROUTE='/tools/material-specification-compliance-checker';
const STORE='upskill-theme';
let queued=false;
function cleanPath(p){return /\/index\.html$/i.test(p)?p.replace(/index\.html$/i,''):p.replace(/\.html$/i,'')}
function path(){return cleanPath(location.pathname).replace(/\/$/,'')||'/'}
function checker(){return path()===ROUTE}
function globalStyle(){if(document.getElementById('uc-global-style'))return;const s=document.createElement('style');s.id='uc-global-style';s.textContent='.uc-no-after::after,.uc-no-before::before{content:none!important;display:none!important}';document.head.appendChild(s)}
function loadCss(){if(!checker()||document.querySelector('link[href="/material-checker-polish.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/material-checker-polish.css';document.head.appendChild(l)}
function cleanAction(el){if(!(el instanceof Element))return;if(el instanceof HTMLInputElement){const v=el.value.replace(LEAD,'').replace(TRAIL,'').trim();if(v!==el.value)el.value=v}else{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];let n;while((n=w.nextNode()))nodes.push(n);for(let i=0;i<nodes.length;i++){if(!nodes[i].nodeValue||!nodes[i].nodeValue.trim())continue;const v=nodes[i].nodeValue.replace(LEAD,'').trimStart();if(v!==nodes[i].nodeValue)nodes[i].nodeValue=v;break}for(let i=nodes.length-1;i>=0;i--){if(!nodes[i].nodeValue||!nodes[i].nodeValue.trim())continue;const v=nodes[i].nodeValue.replace(TRAIL,'').trimEnd();if(v!==nodes[i].nodeValue)nodes[i].nodeValue=v;break}}
try{const a=getComputedStyle(el,'::after').content.replace(/^["']|["']$/g,'').trim();const b=getComputedStyle(el,'::before').content.replace(/^["']|["']$/g,'').trim();el.classList.toggle('uc-no-after',ONLY.test(a));el.classList.toggle('uc-no-before',ONLY.test(b))}catch(e){}
if(el instanceof HTMLAnchorElement&&!el.hasAttribute('download')){const h=el.getAttribute('href');if(h&&!h.startsWith('#')&&!/^(?:mailto:|tel:|javascript:|data:)/i.test(h)){try{const u=new URL(h,location.href);if(u.origin===location.origin&&/\.html$/i.test(u.pathname)){u.pathname=cleanPath(u.pathname);el.setAttribute('href',u.pathname+u.search+u.hash)}}catch(e){}}}}
function scanArrows(root){if(root instanceof Element&&root.matches(ACTION))cleanAction(root);if(root.querySelectorAll)root.querySelectorAll(ACTION).forEach(cleanAction)}
function cleanUrls(){if(/\.html$/i.test(location.pathname)){try{history.replaceState(history.state,document.title,cleanPath(location.pathname)+location.search+location.hash)}catch(e){}}document.querySelectorAll('link[rel="canonical"],meta[property="og:url"]').forEach(el=>{const raw=el.tagName==='LINK'?el.href:el.content;try{const u=new URL(raw,location.href);if(u.origin===location.origin&&/\.html$/i.test(u.pathname)){u.pathname=cleanPath(u.pathname);if(el.tagName==='LINK')el.href=u.href;else el.content=u.href}}catch(e){}})}
function theme(){try{const s=localStorage.getItem(STORE);if(s==='dark'||s==='light')return s}catch(e){}return matchMedia&&matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'}
function syncTheme(){const dark=document.documentElement.dataset.theme==='dark';document.querySelectorAll('[data-theme-toggle],.uc-toggle').forEach(t=>{t.setAttribute('aria-checked',String(dark));t.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');t.title=dark?'Switch to light mode':'Switch to dark mode'})}
function graphTheme(t){const dark=t==='dark',paper=dark?'#111c2d':'#fff',ink=dark?'#f4f7fb':'#172033',muted=dark?'#a9b6c8':'#66758a',line=dark?'#2b3b50':'#d7e1ec';if(window.Plotly&&Plotly.relayout)document.querySelectorAll('.js-plotly-plot').forEach(p=>{try{Plotly.relayout(p,{paper_bgcolor:paper,plot_bgcolor:paper,'font.color':ink,'xaxis.color':muted,'xaxis.gridcolor':line,'yaxis.color':muted,'yaxis.gridcolor':line})}catch(e){}});if(window.Chart&&Chart.getChart)document.querySelectorAll('canvas').forEach(c=>{try{const x=Chart.getChart(c);if(!x)return;Object.values(x.options.scales||{}).forEach(s=>{s.ticks=s.ticks||{};s.grid=s.grid||{};s.ticks.color=muted;s.grid.color=line});if(x.options.plugins?.legend?.labels)x.options.plugins.legend.labels.color=ink;x.update('none')}catch(e){}});dispatchEvent(new Event('resize'))}
function applyTheme(t,save){t=t==='dark'?'dark':'light';document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t;if(save)try{localStorage.setItem(STORE,t)}catch(e){}syncTheme();graphTheme(t);try{dispatchEvent(new CustomEvent('upskill:themechange',{detail:{theme:t}}))}catch(e){}}
function navLinks(){return [['/start-here','Start Here'],['/lessons','Lessons'],['/engineering-tools','Engineering Tools'],['/services','Services'],['/request-topic','Request a Topic'],['/about','About'],['/faq','FAQ'],['/contact','Contact']].map(x=>'<a href="'+x[0]+'"'+(x[0]==='/engineering-tools'?' aria-current="page"':'')+'>'+x[1]+'</a>').join('')}
function toggle(){return '<div class="uc-theme" aria-label="Colour theme"><svg class="sun" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"></path></svg><button type="button" class="uc-toggle" data-theme-toggle role="switch" aria-checked="false"><span class="uc-sr">Toggle dark and light mode</span></button><svg class="moon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg></div>'}
function chrome(){if(!checker()||document.querySelector('.uc-sitebar'))return;document.documentElement.classList.add('upskill-material-checker');loadCss();const old=[...document.querySelectorAll('header')].find(h=>/UpSkill\s+Sprint/i.test(h.textContent||''));if(old)old.classList.add('uc-old-header');const skip=document.createElement('a');skip.className='uc-skip';skip.href='#uc-content';skip.textContent='Skip to tool content';const check=document.createElement('input');check.type='checkbox';check.id='uc-mnav';check.className='uc-mnav-check';check.setAttribute('aria-hidden','true');const h=document.createElement('header');h.className='uc-sitebar';h.innerHTML='<a class="uc-brand" href="/"><img src="/assets/logo-icon.png" alt="UpSkill Sprint Consulting logo"><span>UpSkill Sprint Consulting</span></a><nav class="uc-desktop-nav" aria-label="Primary navigation">'+navLinks()+'</nav><div class="uc-actions">'+toggle()+'<label for="uc-mnav" class="uc-menu" aria-label="Open menu"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"></path></svg></label></div>';const m=document.createElement('nav');m.className='uc-mobile-nav';m.setAttribute('aria-label','Mobile navigation');m.innerHTML=navLinks();document.body.prepend(skip,check,h,m);const main=document.querySelector('main,[role="main"]');if(main)main.id='uc-content';applyTheme(theme(),false)}
function formClasses(root){if(!root)return;root.querySelectorAll('input:not([type="checkbox"]):not([type="radio"]),select,textarea').forEach(c=>(c.closest('label')||c.parentElement)?.classList.add('uc-field'));root.querySelectorAll('input[type="checkbox"],input[type="radio"]').forEach(c=>(c.closest('label')||c.parentElement)?.classList.add('uc-check'));const cand=[...root.querySelectorAll('div')].filter(d=>!d.closest('table')&&d.children.length>1&&d.querySelectorAll('input:not([type="checkbox"]):not([type="radio"]),select,textarea').length>1&&[...d.children].filter(x=>x.querySelector?.('input:not([type="checkbox"]):not([type="radio"]),select,textarea')).length>1);cand.forEach(d=>{if(!cand.some(o=>o!==d&&d.contains(o)))d.classList.add('uc-grid')});root.querySelectorAll('label').forEach(l=>{const t=(l.textContent||'').replace(/\s+/g,' '),d=l.closest('.uc-field')||l.closest('div');if(d&&/original certified specification|target specification\s*\/\s*grade|material description/i.test(t))d.classList.add('uc-wide')})}
function polish(){if(!checker())return;document.documentElement.classList.add('upskill-material-checker');loadCss();chrome();const title=[...document.querySelectorAll('h1')].find(x=>/Material Specification Compliance Checker/i.test(x.textContent||''));const hero=title&&(title.closest('section')||title.parentElement);if(hero)hero.classList.add('uc-hero');document.querySelectorAll('main>section,main>div>section,[role="main"]>section').forEach(s=>{if(s!==hero&&s.querySelector('h2,h3,input,select,textarea,table,button'))s.classList.add('uc-card')});const wb=[...document.querySelectorAll('h2,h3')].find(x=>/Independent compliance workbench/i.test(x.textContent||''));const card=wb&&(wb.closest('section')||wb.closest('[class*="card"]')||wb.closest('[class*="panel"]'));if(card){card.classList.add('uc-card');const boxes=[...card.querySelectorAll('input[type="checkbox"]')],holders=boxes.map(b=>b.closest('label')||b.parentElement).filter(Boolean),common=holders[0]?.parentElement;if(common&&holders.every(x=>x.parentElement===common))common.classList.add('uc-check-grid')}document.querySelectorAll('section,[class*="card"],[class*="panel"],[class*="workbench"]').forEach(s=>{formClasses(s);s.querySelectorAll('table').forEach(t=>t.parentElement?.classList.add('uc-table'))});document.querySelectorAll('h2,h3,h4,strong').forEach(x=>{if(/Important engineering-use notice|Accuracy control/i.test(x.textContent||''))(x.closest('div,aside,section'))?.classList.add('uc-notice')});document.querySelectorAll('p,div').forEach(x=>{if(/Row-by-row units take priority/i.test(x.textContent||'')&&x.children.length<3)x.classList.add('uc-helper','uc-full')});document.querySelectorAll('button,[role="button"],input[type="button"],input[type="submit"]').forEach(b=>{if(/Evaluate selected sections/i.test(b.textContent||b.value||''))b.classList.add('uc-primary');if(b.parentElement?.querySelectorAll('button,[role="button"],input[type="button"],input[type="submit"]').length>1)b.parentElement.classList.add('uc-actions-row')});if(!document.querySelector('.uc-back')){const d=document.createElement('div');d.className='uc-back';d.innerHTML='<a href="/engineering-tools">Back to Engineering Tools</a>';const f=document.querySelector('footer');f?.parentNode?f.parentNode.insertBefore(d,f):document.body.appendChild(d)}syncTheme()}
function tools(){if(path()!=='/engineering-tools')return;[{id:'materials-quality',p:'/tools/material-specification-compliance-checker',a:'Open checker'},{id:'engineering-calculators',p:'/tools/engineering-statistics-calculator',a:'Open calculator'},{id:'converters',p:'/tools/unit-converter',a:'Open converter'}].forEach(x=>{const c=document.getElementById(x.id);if(!c)return;c.href=x.p;c.classList.remove('is-planned');const s=c.querySelector('.tool-status');if(s){s.textContent='Available';s.classList.add('available')}const a=c.querySelector('.tool-link');if(a){a.textContent=x.a;a.classList.remove('secondary');a.classList.add('primary')}})}
function run(){scanArrows(document);cleanUrls();polish();tools()}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})}
function init(){globalStyle();cleanUrls();if(checker()){document.documentElement.classList.add('upskill-material-checker');loadCss();applyTheme(theme(),false)}run();document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target.closest('[data-theme-toggle],.uc-toggle'):null;if(!t||!checker())return;e.preventDefault();e.stopImmediatePropagation();applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark',true)},true);new MutationObserver(ms=>{if(ms.some(m=>m.type==='characterData'||m.addedNodes.length))queue()}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});addEventListener('load',queue,{once:true});setTimeout(queue,250);setTimeout(queue,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}());
