(function(){'use strict';
const ACTION='a,button,[role="button"],input[type="button"],input[type="submit"]',LEAD=/^(?:[\s\u00a0]*(?:←|⟵|↩|↶|⬅|⇐|⟸|<-+)[\s\u00a0]*)+/u,TRAIL=/(?:[\s\u00a0]*(?:→|⟶|➜|➝|➞|➡|⟹|-+>)[\s\u00a0]*)+$/u,ONLY=/^(?:[\s\u00a0]*(?:←|⟵|↩|↶|⬅|⇐|⟸|→|⟶|➜|➝|➞|➡|⟹|<-+|-+>)[\s\u00a0]*)+$/u,HTML=/\.html$/i;let queued=false;
function cleanPath(p){return /\/index\.html$/i.test(p)?p.replace(/index\.html$/i,''):p.replace(HTML,'')}
function style(){if(document.getElementById('upskill-arrow-cleanup-styles'))return;const s=document.createElement('style');s.id='upskill-arrow-cleanup-styles';s.textContent='.upskill-no-after::after,.upskill-no-before::before{content:none!important;display:none!important}';document.head.appendChild(s)}
function pseudo(x){return!x||x==='none'||x==='normal'?'':x.replace(/^[\'\"]|[\'\"]$/g,'').trim()}
function action(el){if(!(el instanceof Element))return;if(el instanceof HTMLInputElement)el.value=el.value.replace(LEAD,'').replace(TRAIL,'').trim();else{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),n=[];let x;while((x=w.nextNode()))n.push(x);for(let i=0;i<n.length;i++){if(n[i].nodeValue&&n[i].nodeValue.trim()){n[i].nodeValue=n[i].nodeValue.replace(LEAD,'').trimStart();break}}for(let i=n.length-1;i>=0;i--){if(n[i].nodeValue&&n[i].nodeValue.trim()){n[i].nodeValue=n[i].nodeValue.replace(TRAIL,'').trimEnd();break}}}try{el.classList.toggle('upskill-no-after',ONLY.test(pseudo(getComputedStyle(el,'::after').content)));el.classList.toggle('upskill-no-before',ONLY.test(pseudo(getComputedStyle(el,'::before').content)))}catch(e){}if(el instanceof HTMLAnchorElement&&!el.hasAttribute('download')){const h=el.getAttribute('href');if(h&&!h.startsWith('#')&&!/^(?:mailto:|tel:|javascript:|data:)/i.test(h))try{const u=new URL(h,location.href);if(u.origin===location.origin&&HTML.test(u.pathname)){u.pathname=cleanPath(u.pathname);el.setAttribute('href',u.pathname+u.search+u.hash)}}catch(e){}}}
function scan(root=document){if(root instanceof Element&&root.matches(ACTION))action(root);root.querySelectorAll?.(ACTION).forEach(action);document.querySelectorAll('link[rel="canonical"],meta[property="og:url"]').forEach(el=>{const raw=el.tagName==='LINK'?el.href:el.content;try{const u=new URL(raw,location.href);if(u.origin===location.origin&&HTML.test(u.pathname)){u.pathname=cleanPath(u.pathname);el.tagName==='LINK'?el.href=u.href:el.content=u.href}}catch(e){}})}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;scan()})}
function loadGradeSpecificationRegistration(){const p=location.pathname.replace(/\/+$/,'');if(!(/\/(?:lessons|engineering-tools)(?:\.html)?$/.test(p))||document.querySelector('script[src="/grade-specification-site-registration.js"]'))return;const s=document.createElement('script');s.src='/grade-specification-site-registration.js';document.head.appendChild(s)}
function init(){style();if(HTML.test(location.pathname))try{history.replaceState(history.state,document.title,cleanPath(location.pathname)+location.search+location.hash)}catch(e){}scan();loadGradeSpecificationRegistration();new MutationObserver(queue).observe(document.documentElement,{subtree:true,childList:true,characterData:true});addEventListener('load',queue,{once:true})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();