/* Build-only curriculum authoring. This directory MUST NOT be published. */
const sum = (rows, col) => rows.reduce((total, row) => total + row[col], 0);
const mean = (rows, col) => sum(rows, col) / rows.length;
const rounded = (number, digits = 2) => Math.round((number + Number.EPSILON) * 10 ** digits) / 10 ** digits;
const vector = values => values.map(value => [value]);
const fn = (name, purpose, syntax, args, example, result, useCase, mistake) => ({name, purpose, syntax, arguments:args, example, result, useCase, mistake});
const columns = list => list.map(([name, description]) => ({name, description}));
function task(id, prompt, output, type, formulas, answer, model, hints, alternatives = []) {
  return {public:{id, prompt, output, type, formulas}, private:{id, answer, tolerance:1e-6, orderInsensitive:false, model:model.replace(/ \[fill down.*$/, ''), modelNote:model.includes('[fill down') ? model.match(/\[([^\]]+)\]/)[1] : `Enter at ${output}.`, alternatives, hints}};
}
const scalar = (id, prompt, row, formulas, answer, model, hints, alternatives) => task(id, prompt, `Answers!B${row}`, typeof answer === 'number' ? 'number' : 'text', formulas, answer, model, hints, alternatives);
const arrayTask = (id, prompt, output, formulas, values, model, hints, alternatives) => task(id, prompt, output, 'array', formulas, vector(values), model, hints, alternatives);
const bonusTask = (prompt, output, formulas, answer, model, hints) => task('bonus', prompt, output, typeof answer === 'number' ? 'number' : 'text', formulas, answer, model, hints);

export const levels = [
  {level:1,title:'Foundations',formulas:['SUM','AVERAGE','COUNT','COUNTA','MIN','MAX','ROUND','ROUNDUP','ROUNDDOWN','IF','ABS','Absolute and relative references'],titles:['Heat totals and averages','Order counts and complete records','Mechanical test extremes','Inventory rounding decisions','Thickness decisions with fixed references']},
  {level:2,title:'Logic & conditional aggregation',formulas:['AND','OR','NOT','IFS','IFERROR','SUMIFS','COUNTIFS','AVERAGEIFS','SUMIF','MAXIFS','MINIFS'],titles:['Supplier eligibility logic','Downtime triage and safe ratios','Sales with multiple conditions','Repair averages and targeted costs','Shipment extremes and missing groups']},
  {level:3,title:'Lookups',formulas:['XLOOKUP','INDEX','MATCH','Two-way lookups','Approximate spec bands'],titles:['Look up a product specification','Match an employee allowance','Combine two specification dimensions','Map results to specification bands','Build an error-aware lookup report']},
  {level:4,title:'Text',formulas:['TRIM','CLEAN','UPPER','PROPER','LEFT','RIGHT','MID','TEXTBEFORE','TEXTAFTER','TEXTSPLIT','TEXTJOIN','SUBSTITUTE','TEXT'],titles:['Clean inspection identifiers','Standardize customer names','Extract product code segments','Split a shipment manifest','Assemble readable quality reports']},
  {level:5,title:'Dates & time',formulas:['DATE','EOMONTH','EDATE','NETWORKDAYS','WORKDAY','WEEKNUM','DATEDIF','Shift calculations'],titles:['Build a test schedule','Plan month-end inventory','Calculate business-day deadlines','Analyze employee service dates','Calculate overnight shift durations']},
  {level:6,title:'Dynamic arrays',formulas:['FILTER','SORT','SORTBY','UNIQUE','SEQUENCE','CHOOSECOLS','CHOOSEROWS','VSTACK','HSTACK','TAKE','DROP'],titles:['Filter inspection exceptions','Sort a business priority queue','Build unique heat summaries','Combine rolling and inspection extracts','Reshape Charpy orientations side by side']},
  {level:7,title:'Array logic',formulas:['SUMPRODUCT','Boolean arrays','Multi-criteria lookups','XMATCH','Nested FILTER conditions'],titles:['Calculate weighted production rates','Build a multi-criteria order lookup','Audit array conditions','Match specifications in two dimensions','Filter a full quality exception report']},
  {level:8,title:'Structure & reuse',formulas:['LET','LAMBDA','MAP','BYROW','BYCOL','REDUCE','SCAN','Named formulas'],titles:['Name intermediate calculations','Create a reusable margin formula','Score samples row by row','Calculate cumulative losses','Build a reusable calculation library']},
  {level:9,title:'Analysis & reporting',formulas:['GROUPBY','PIVOTBY','STDEV.S','PERCENTILE.INC','CORREL','SPC limits','Cp','Cpk'],titles:['Group production summaries','Pivot business outcomes','Measure variation and percentiles','Explore correlations responsibly','Calculate process capability with stated assumptions']},
  {level:10,title:'Mastery',formulas:['Nested formulas','Four-function combinations','Error-proofing','Formula-driven dashboards','Capstone'],titles:['Build a robust inspection summary','Reconcile multiple business tables','Audit a complex formula chain','Create a formula-driven mini dashboard','Complete the integrated manufacturing capstone']}
];

/** Independent fixed streams: each scenario has different dimensions, identifiers and units. */
export function createPackages(randomFor) {
  const packages = [];
  const add = (level, assignment, scenario, lesson, defs, makeRows, tasksFor, parameters = []) => {
    const id = `L${level}-A${assignment}`;
    const rand = randomFor(id);
    const data = makeRows(rand);
    const specs = tasksFor(data);
    const tasks = specs.slice(0,-1);
    packages.push({id,level,assignment,title:levels[level-1].titles[assignment-1],formulas:lesson.functions.map(x=>x.name),minutes:25 + (level-1)*10 + (assignment-1)*5,scenario,lesson,columns:columns(defs),rows:data,parameters,tasks:tasks.map(x=>x.public),bonus:specs.at(-1).public,private:{version:1,tasks:tasks.map(x=>x.private),bonus:specs.at(-1).private}});
  };

  add(1,1,
    'Neralis Meltworks is checking 24 fictitious EAF heats from its Kestrel plant. The superintendent needs total output, average tap time and one pooled metal-yield result. Every mass is in metric tonnes; each row is one heat.',
    {intro:'A formula starts with =. A range such as Data!D2:D25 includes both endpoints. Build totals and means from cells so the result follows the data, instead of typing a calculated answer.',functions:[
      fn('SUM','Add numeric values.','=SUM(number1, [number2], ...)','number1 is a number, cell or range; later arguments are optional additional inputs.','=SUM(14,18,22)',54,'Total tonnes, units or costs.','Exclude headings and unrelated numeric columns; text in referenced cells is ignored.'),
      fn('AVERAGE','Calculate an arithmetic mean.','=AVERAGE(number1, [number2], ...)','number1 supplies the first number or range; optional inputs add more observations.','=AVERAGE(14,18,22)',18,'Typical tap time or measured mass.','Referenced blanks are ignored, but zero is included. An average of individual yields differs from pooled yield.')
    ],combine:'For pooled yield, divide total tapped mass by total charged mass and multiply by 100. Arithmetic operators * and / combine results. The ratio of totals weights larger heats correctly. Use Data! before ranges when entering formulas on Answers.'},
    [['Heat_no','Invented unique heat identifier.'],['Tap_date','ISO date of tap in September 2026.'],['Charged_t','Total metallic charge, metric tonnes.'],['Tapped_t','Liquid steel tapped, metric tonnes.'],['Tap_duration_min','Heat tap duration, minutes.']],
    r=>Array.from({length:24},(_,i)=>{const charge=r.int(92,126);return [`NM-${7101+i}`,`2026-09-${String(1+i).padStart(2,'0')}`,charge,rounded(charge*r.int(89,96)/100,2),r.int(47,78)];}),
    rows=>[
      scalar('t1','Calculate the total tapped mass for all 24 heats, in metric tonnes.',2,['SUM'],sum(rows,3),'=SUM(Data!D2:D25)',['Check that all 24 tapped-mass rows, and no charged-mass rows, are included.','Use the totaling function on the Tapped_t column.','=SUM(Data!____)']),
      scalar('t2','Calculate the average tap duration for all 24 heats, in minutes. Submit the unrounded numeric value.',3,['AVERAGE'],mean(rows,4),'=AVERAGE(Data!E2:E25)',['The result must be a mean in minutes, rather than a total.','Use AVERAGE on all tap-duration observations.','=AVERAGE(Data!____)']),
      scalar('t3','Calculate pooled metal yield as 100 times total tapped mass divided by total charged mass. Submit the unrounded percentage number, for example 93.4 rather than 0.934.',4,['SUM'],100*sum(rows,3)/sum(rows,2),'=SUM(Data!D2:D25)/SUM(Data!C2:C25)*100',['Use total tapped mass as the numerator and total charged mass as the denominator.','Combine two SUM calculations before multiplying by 100.','=SUM(Data!____)/SUM(Data!____)*100']),
      scalar('t4','Calculate the difference between average charged mass and average tapped mass, in tonnes. Submit an unrounded number.',5,['AVERAGE'],mean(rows,2)-mean(rows,3),'=AVERAGE(Data!C2:C25)-AVERAGE(Data!D2:D25)',['The difference is charged minus tapped and stays in tonnes.','Subtract the average of one mass column from the other.','=AVERAGE(Data!____)-AVERAGE(Data!____)'],['=(SUM(Data!C2:C25)-SUM(Data!D2:D25))/24']),
      bonusTask('Calculate aggregate tapped tonnes per hour using total tap duration, rather than averaging individual heat rates.','Answers!B7',['SUM'],60*sum(rows,3)/sum(rows,4),'=SUM(Data!D2:D25)/SUM(Data!E2:E25)*60',['Convert the pooled minutes denominator to hours.','Divide total mass by total time, then convert minutes to hours.','=SUM(Data!____)/SUM(Data!____)*60'])
    ]);

  add(1,2,
    'Velora Office Supply is reconciling 26 fictitious customer orders. Every order has a text order code, a shipment reference, a units count and a value in Canadian dollars. A complete order register should count records without mistaking text codes for numbers.',
    {intro:'Counting answers a different question from totaling. Clean text identifiers are valid data: a code such as VO-501 is not a number and should not be coerced into one.',functions:[
      fn('COUNT','Count numeric cells in a referenced range.','=COUNT(value1, [value2], ...)','value1 is the first range or input; optional values add further ranges or inputs.','=COUNT(6,9,12)',3,'Count numeric quantity or test-result entries.','Text identifiers in a referenced range do not count; zero does.'),
      fn('COUNTA','Count cells that are not empty.','=COUNTA(value1, [value2], ...)','value1 is a range or value; optional arguments add more inputs.','=COUNTA("VO-7","VO-8","VO-9")',3,'Count populated order IDs or shipment references.','A formula returning empty text is still counted; COUNTA is not a unique-record counter.')
    ],combine:'Reuse SUM to compute total order value. Dividing that total by COUNTA of order IDs gives value per recorded order. Relative references move when copied: Data!D2 becomes Data!D3 one row down. Count only data rows, because COUNTA would include a text header.'},
    [['Order_code','Invented text order identifier.'],['Customer_code','Invented customer account code.'],['Shipment_ref','Invented dispatch reference; every row is populated.'],['Units','Positive integer ordered units.'],['Order_value_CAD','Order value, Canadian dollars.']],
    r=>Array.from({length:26},(_,i)=>[`VO-${501+i}`,`VC-${r.int(301,309)}`,`VS-${9901+i}`,r.int(4,67),rounded(r.int(12000,195000)/100,2)]),
    rows=>[
      scalar('t1','Count numeric entries in the Units column. Do not total the units.',2,['COUNT'],rows.length,'=COUNT(Data!D2:D27)',['A record count should not change because one order has more units.','Use COUNT for numeric entries.','=COUNT(Data!____)']),
      scalar('t2','Count populated Order_code cells, excluding the heading.',3,['COUNTA'],rows.length,'=COUNTA(Data!A2:A27)',['Order codes are text, but every data cell is populated.','Use the nonempty-cell count rather than the numeric-cell count.','=COUNTA(Data!____)']),
      scalar('t3','Count numeric entries in Order_code. The task concerns the stored cell type, not the digits inside each text code.',4,['COUNT'],0,'=COUNT(Data!A2:A27)',['Digits embedded in a text identifier are not numeric cells.','Apply COUNT to the text-code range without converting it.','=COUNT(Data!____)']),
      scalar('t4','Calculate value per recorded order: total Order_value_CAD divided by the count of populated Order_code cells. Submit the unrounded number.',5,['SUM','COUNTA'],mean(rows,4),'=SUM(Data!E2:E27)/COUNTA(Data!A2:A27)',['Use order value in the numerator and record count in the denominator.','Reuse SUM and divide it by COUNTA of order IDs.','=SUM(Data!____)/COUNTA(Data!____)'],['=AVERAGE(Data!E2:E27)']),
      bonusTask('Calculate average units per recorded shipment using total units and the count of Shipment_ref entries.','Answers!B7',['SUM','COUNTA'],mean(rows,3),'=SUM(Data!D2:D27)/COUNTA(Data!C2:C27)',['The denominator is the shipment-record count, not order value.','Combine SUM of units with COUNTA of shipment references.','=SUM(Data!____)/COUNTA(Data!____)'])
    ]);

  add(1,3,
    'Orvanta Tube Lab is reviewing 28 fictitious tensile specimens from the Talren rolling line. Yield strength and tensile strength are measured in MPa; elongation is a percentage. The report needs observed extremes and spread, without declaring compliance with any real specification.',
    {intro:'An observed extreme is a descriptive result. It is not automatically a specification limit or a control limit. Select the relevant measured column and keep its units.',functions:[
      fn('MIN','Return the smallest numeric value.','=MIN(number1, [number2], ...)','number1 is a value or range; optional arguments include additional values or ranges.','=MIN(432,457,441)',432,'Find the lowest measured strength or price.','Text and blanks in references are ignored; a real zero participates.'),
      fn('MAX','Return the largest numeric value.','=MAX(number1, [number2], ...)','number1 supplies the first numeric input or range; later inputs are optional.','=MAX(532,548,539)',548,'Find the highest observed test value.','Maximum does not identify which specimen produced it; that needs a later lookup technique.')
    ],combine:'Observed range is MAX minus MIN of the same measured column. Reuse AVERAGE to express that range relative to the mean. A cross-column strength ratio is dimensionless because both inputs use MPa; it is a descriptive comparison only.'},
    [['Sample_code','Invented unique tensile sample ID.'],['Heat_no','Invented source heat identifier.'],['Yield_MPa','Measured yield strength, MPa.'],['Tensile_MPa','Measured ultimate tensile strength, MPa.'],['Elongation_pct','Measured total elongation, percentage points.']],
    r=>Array.from({length:28},(_,i)=>{const y=r.int(385,478);return [`OT-S${2101+i}`,`OT-H${8201+Math.floor(i/4)}`,y,y+r.int(78,130),rounded(r.int(170,286)/10,1)];}),
    rows=>[
      scalar('t1','Find the lowest Yield_MPa across all specimens.',2,['MIN'],Math.min(...rows.map(x=>x[2])),'=MIN(Data!C2:C29)',['Use the yield column and retain MPa as the unit.','Use MIN over the complete yield range.','=MIN(Data!____)']),
      scalar('t2','Find the highest Tensile_MPa across all specimens.',3,['MAX'],Math.max(...rows.map(x=>x[3])),'=MAX(Data!D2:D29)',['Yield and tensile strength are different measured columns.','Use MAX on tensile strength.','=MAX(Data!____)']),
      scalar('t3','Calculate the observed elongation range: largest minus smallest Elongation_pct, in percentage points.',4,['MAX','MIN'],Math.max(...rows.map(x=>x[4]))-Math.min(...rows.map(x=>x[4])),'=MAX(Data!E2:E29)-MIN(Data!E2:E29)',['The range is a positive spread within the elongation column.','Subtract MIN from MAX using identical ranges.','=MAX(Data!____)-MIN(Data!____)']),
      scalar('t4','Calculate maximum tensile strength divided by minimum yield strength. Submit the unrounded dimensionless ratio.',5,['MAX','MIN'],Math.max(...rows.map(x=>x[3]))/Math.min(...rows.map(x=>x[2])),'=MAX(Data!D2:D29)/MIN(Data!C2:C29)',['Use different strength columns in the stated numerator and denominator.','Combine the correct MAX and MIN results with division.','=MAX(Data!____)/MIN(Data!____)']),
      bonusTask('Calculate 100 times the yield-strength range divided by mean yield strength. Submit the unrounded percentage number.','Answers!B7',['MAX','MIN','AVERAGE'],100*(Math.max(...rows.map(x=>x[2]))-Math.min(...rows.map(x=>x[2])))/mean(rows,2),'=(MAX(Data!C2:C29)-MIN(Data!C2:C29))/AVERAGE(Data!C2:C29)*100',['Keep the entire range calculation together before dividing.','Use parentheses around MAX minus MIN, then divide by AVERAGE.','=(MAX(Data!____)-MIN(Data!____))/AVERAGE(Data!____)*100'])
    ]);

  add(1,4,
    'Ruvella Parts Depot is planning stock for 30 fictitious items. Demand is in units, while replenishment uses complete packs; stock can contain a partial pack. Unit costs include extra decimal places so the invoice policy can round each line to cents.',
    {intro:'Changing number format only changes display. Rounding changes the calculated value. Enter the first row formula and fill down so relative row references move to the next item.',functions:[
      fn('ROUND','Round to the nearest stated decimal position.','=ROUND(number, num_digits)','number is the input; num_digits is decimal places, 0 for an integer or negative for tens/hundreds.','=ROUND(18.276,2)',18.28,'Round monetary line values to cents.','Formatting as currency is not mathematical rounding.'),
      fn('ROUNDUP','Round away from zero.','=ROUNDUP(number, num_digits)','number is the value; num_digits sets the retained decimal position.','=ROUNDUP(53/12,0)',5,'Order enough complete packs for positive demand.','Up means away from zero, including for negative numbers.'),
      fn('ROUNDDOWN','Round toward zero.','=ROUNDDOWN(number, num_digits)','number supplies the input; num_digits controls the retained decimal position.','=ROUNDDOWN(53/12,0)',4,'Count complete packs in positive stock.','Down means toward zero; it is not the mathematical floor for negatives.')
    ],combine:'Reuse SUM after rounding each line if the policy rounds lines individually. Rounding the grand total can differ. Data!B2/Data!D2 moves to row 3 when copied; fix references only when the same constant must be used in every row.'},
    [['SKU','Invented unique stocked item code.'],['Demand_units','Forecast units needed; positive integer.'],['Stock_units','Physical stock on hand, including partial packs.'],['Pack_size_units','Positive units supplied per complete pack.'],['Unit_cost_CAD','Cost per unit in Canadian dollars, three decimal places.']],
    r=>Array.from({length:30},(_,i)=>[`RP-${1601+i}`,r.int(31,190),r.int(42,240),[6,8,12,16,20][i%5],r.int(4250,39675)/1000]),
    rows=>[
      scalar('t1','Round the first item’s Unit_cost_CAD to two decimal places.',2,['ROUND'],rounded(rows[0][4]),'=ROUND(Data!E2,2)',['Round the numeric cost itself, not only its cell format.','Use ROUND with two decimal places.','=ROUND(Data!____,2)']),
      arrayTask('t2','For the first five items, calculate the number of complete packs to order to meet Demand_units. Return one integer per row in dataset order.','Answers!B3:B7',['ROUNDUP'],rows.slice(0,5).map(x=>Math.ceil(x[1]/x[3])),'=ROUNDUP(Data!B2/Data!D2,0) [fill down from Answers!B3 to B7]',['Any positive remainder requires another complete pack.','Divide demand by pack size, then round away from zero to an integer.','=ROUNDUP(Data!B2/____,0)']),
      arrayTask('t3','For the first five items, calculate complete packs contained in Stock_units. Ignore any incomplete remainder. Return integers in dataset order.','Answers!B9:B13',['ROUNDDOWN'],rows.slice(0,5).map(x=>Math.floor(x[2]/x[3])),'=ROUNDDOWN(Data!C2/Data!D2,0) [fill down from Answers!B9 to B13]',['A partial pack cannot be counted as a complete pack.','Divide stock by pack size and round toward zero.','=ROUNDDOWN(Data!C2/____,0)']),
      arrayTask('t4','For the first five items, calculate Stock_units times Unit_cost_CAD, rounding each item value to two decimal places. Return values in dataset order.','Answers!B15:B19',['ROUND'],rows.slice(0,5).map(x=>rounded(x[2]*x[4])),'=ROUND(Data!C2*Data!E2,2) [fill down from Answers!B15 to B19]',['Multiply stock by the row’s cost before rounding each line.','Use ROUND around the line-value multiplication and fill down.','=ROUND(Data!C2*____,2)']),
      bonusTask('Total the five individually rounded stock values from task 4. Round that total to two decimal places.','Answers!B21',['SUM','ROUND'],rounded(rows.slice(0,5).reduce((s,x)=>s+rounded(x[2]*x[4]),0)),'=ROUND(SUM(Answers!B15:B19),2)',['Use the rounded lines from task 4 as the inputs.','Reuse SUM over the five answer cells, then retain two decimals.','=ROUND(SUM(Answers!____),2)'])
    ]);

  add(1,5,
    'Kesvani Gauge Works is checking 32 fictitious pipe-wall samples against a training-only target of 12.70 mm with tolerance ±0.20 mm. These values are not a real product standard. The workbook stores target in Parameters!B2 and tolerance in Parameters!B3; keep those cells fixed when copying.',
    {intro:'A decision formula separates the condition from its two outcomes. Exact boundary measurements pass this training rule. An absolute reference such as Parameters!$B$2 keeps both column and row fixed when copied; Data!C2 stays relative and moves with each sample.',functions:[
      fn('IF','Choose one result when a condition is true and another when false.','=IF(logical_test, value_if_true, [value_if_false])','logical_test evaluates TRUE/FALSE; value_if_true is the first outcome; optional value_if_false is the other.','=IF(12.7>=12.5,"Pass","Hold")','Pass','Classify results using a stated threshold.','Quote text outputs and choose >= or <= deliberately at the boundary.'),
      fn('ABS','Return distance from zero without a sign.','=ABS(number)','number is the numeric input, such as measured value minus target.','=ABS(12.48-12.70)',0.22,'Measure deviation magnitude for a two-sided tolerance.','Taking ABS of the measurement alone does not measure deviation from target.')
    ],combine:'Nest ABS inside IF to check the distance from target. Reuse AVERAGE for batch centering and MIN/MAX for a two-sided batch check. Fix target and tolerance with $; keep each measurement relative. CSV users should create Parameters with labels in A2/A3 and the stated numeric values in B2/B3.'},
    [['Sample_code','Invented wall-thickness sample code.'],['Product_code','Invented training product code.'],['Measured_mm','Measured wall thickness in mm.'],['Piece_mass_kg','Measured piece mass, kg.']],
    r=>Array.from({length:32},(_,i)=>[`KG-S${4301+i}`,`KG-P${r.int(701,705)}`,i===0?12.50:i===1?12.90:rounded(r.int(1238,1302)/100,2),r.int(421,702)/10]),
    rows=>[
      scalar('t1','Calculate the absolute distance of the first sample’s Measured_mm from the fixed target, in mm. Reference Parameters!B2.',2,['ABS'],rounded(Math.abs(rows[0][2]-12.7),2),'=ABS(Data!C2-Parameters!$B$2)',['Deviation is measured minus target, with its sign removed.','Use ABS on the subtraction and fix the target cell.','=ABS(Data!C2-____)']),
      scalar('t2','Calculate the absolute distance between mean Measured_mm for all 32 samples and the fixed target. Submit the unrounded value in mm.',3,['ABS','AVERAGE'],Math.abs(mean(rows,2)-12.7),'=ABS(AVERAGE(Data!C2:C33)-Parameters!$B$2)',['Take the mean first, then its distance from target. This is not the average of individual absolute deviations.','Nest AVERAGE inside ABS after subtracting the target.','=ABS(AVERAGE(Data!____)-Parameters!$B$2)']),
      arrayTask('t3','Classify the first eight samples as Pass when their distance from target is at most the tolerance; otherwise Hold. Return exact labels in dataset order. Reference the fixed Parameters cells. Round each deviation to two decimal places before comparing, matching the measurement precision.','Answers!B5:B12',['IF','ABS','ROUND'],rows.slice(0,8).map(x=>Math.abs(x[2]-12.7)<=0.2+1e-7?'Pass':'Hold'),'=IF(ROUND(ABS(Data!C2-Parameters!$B$2),2)<=Parameters!$B$3,"Pass","Hold") [fill down from Answers!B5 to B12]',['The two exact tolerance boundaries pass. Apply the same fixed target and tolerance to every row.','Nest ABS in IF; keep measurement relative and both Parameters cells absolute.','=IF(ROUND(ABS(Data!C2-____),2)<=Parameters!$B$3,"Pass","Hold")']),
      scalar('t4','Return Release if the minimum measured thickness is at least target minus tolerance AND the maximum is at most target plus tolerance. Otherwise return Hold. Use nested decisions or another valid approach; evaluate all 32 samples.',14,['IF','MIN','MAX'],Math.min(...rows.map(x=>x[2]))>=12.5 && Math.max(...rows.map(x=>x[2]))<=12.9?'Release':'Hold','=IF(MIN(Data!C2:C33)>=Parameters!$B$2-Parameters!$B$3,IF(MAX(Data!C2:C33)<=Parameters!$B$2+Parameters!$B$3,"Release","Hold"),"Hold")',['Both the lower and upper bounds must pass for the whole batch.','Use nested IF with MIN and MAX; either failed boundary returns Hold.','=IF(MIN(Data!____)>=Parameters!$B$2-Parameters!$B$3,IF(____,"Release","Hold"),"Hold")']),
      bonusTask('Return Centred if mean thickness is within 0.05 mm of target, inclusive; otherwise Investigate. Reference Parameters!B2.','Answers!B16',['IF','ABS','AVERAGE'],Math.abs(mean(rows,2)-12.7)<=.05?'Centred':'Investigate','=IF(ABS(AVERAGE(Data!C2:C33)-Parameters!$B$2)<=0.05,"Centred","Investigate")',['This checks the batch mean, not whether all individual samples pass.','Use AVERAGE inside an absolute-deviation IF decision.','=IF(ABS(AVERAGE(Data!____)-Parameters!$B$2)<=0.05,"Centred","Investigate")'])
    ],[{cell:'B2',name:'Target_mm',value:12.7},{cell:'B3',name:'Tolerance_mm',value:.2}]);

  add(2,1,
    'Novrila Procurement is screening 22 fictitious suppliers. An order can proceed only with approval, no credit hold, lead time at most 10 days and quality score at least 95%. Separate alerts explain why a supplier needs review.',
    {intro:'Logic functions return TRUE/FALSE. Reuse IF to translate that logical result into an operational label. AND requires every condition; OR needs any condition; NOT reverses one logical result.',functions:[
      fn('AND','Test that every condition is true.','=AND(logical1, [logical2], ...)','logical1 is the first test; optional logical arguments add tests.','=AND(8<=10,96>=95)','TRUE','Require multiple release or eligibility conditions.','One false condition makes the whole test false.'),
      fn('OR','Test that at least one condition is true.','=OR(logical1, [logical2], ...)','logical1 is the first test; optional arguments add alternatives.','=OR(12>10,97<95)','TRUE','Flag any late or low-quality supplier.','OR does not require both conditions to be true.'),
      fn('NOT','Reverse a logical value.','=NOT(logical)','logical is one expression that evaluates TRUE/FALSE.','=NOT("No"="Yes")','TRUE','Allow an action when a blocking condition is absent.','NOT reverses the whole enclosed test; place parentheses deliberately.')
    ],combine:'Use IF(AND(...), outcome1, outcome2) as a pattern on other data, then construct your own task formulas. Quote labels. A >=95 score includes 95, and <=10 includes 10. Copying a row-based formula should change the supplier row without changing its business rules.'},
    [['Supplier_code','Invented unique supplier identifier.'],['Lead_days','Promised lead time, calendar days.'],['Quality_score_pct','Supplier quality score, percent.'],['Approved','Yes or No approval status.'],['Credit_hold','Yes indicates procurement is blocked.']],
    r=>Array.from({length:22},(_,i)=>[`NP-${6601+i}`,i===0?10:r.int(4,16),i===0?95:r.int(90,100),i%4===0?'No':'Yes',i%5===0?'Yes':'No']),
    rows=>[
      scalar('t1','For the first supplier, return Eligible when Lead_days is at most 10 and Quality_score_pct is at least 95; otherwise Review. Ignore approval and credit status for this task.',2,['IF','AND'],rows[0][1]<=10&&rows[0][2]>=95?'Eligible':'Review','=IF(AND(Data!B2<=10,Data!C2>=95),"Eligible","Review")',['Both lead-time and quality conditions must pass; equality passes.','Use AND inside the earlier IF function.','=IF(AND(Data!B2<=____,Data!C2>=95),"Eligible","Review")']),
      arrayTask('t2','For the first eight suppliers, return Alert if Lead_days exceeds 10 OR Quality_score_pct is below 95. Otherwise return Clear. Keep dataset order.','Answers!B4:B11',['IF','OR'],rows.slice(0,8).map(x=>x[1]>10||x[2]<95?'Alert':'Clear'),'=IF(OR(Data!B2>10,Data!C2<95),"Alert","Clear") [fill down from Answers!B4 to B11]',['Either adverse condition triggers the alert. Equality alone is not adverse.','Use OR for alternatives inside IF.','=IF(OR(Data!B2>____,Data!C2<95),"Alert","Clear")']),
      arrayTask('t3','For the first eight suppliers, return Allowed when Credit_hold is not Yes, otherwise Blocked. Keep dataset order and use a logical reversal.','Answers!B13:B20',['IF','NOT'],rows.slice(0,8).map(x=>x[4]!=='Yes'?'Allowed':'Blocked'),'=IF(NOT(Data!E2="Yes"),"Allowed","Blocked") [fill down from Answers!B13 to B20]',['Check the credit-hold column only; do not mix this result with supplier approval.','Use NOT around the credit-hold equality test, inside IF.','=IF(NOT(Data!____="Yes"),"Allowed","Blocked")']),
      arrayTask('t4','For the first eight suppliers, return Order only when Approved is Yes, Credit_hold is not Yes, Lead_days is at most 10 and Quality_score_pct is at least 95. Otherwise return Do not order. Keep dataset order.','Answers!B22:B29',['IF','AND','NOT'],rows.slice(0,8).map(x=>x[3]==='Yes'&&x[4]!=='Yes'&&x[1]<=10&&x[2]>=95?'Order':'Do not order'),'=IF(AND(Data!D2="Yes",NOT(Data!E2="Yes"),Data!B2<=10,Data!C2>=95),"Order","Do not order") [fill down from Answers!B22 to B29]',['Four conditions must hold simultaneously. A good score cannot cancel a credit hold.','Combine AND with NOT for the blocked condition, then return the IF labels.','=IF(AND(Data!D2="Yes",____,Data!B2<=10,Data!C2>=95),"Order","Do not order")']),
      bonusTask('For the first supplier, return Escalate if it is approved but either has a credit hold or fails the lead-time/quality screen. Otherwise return Routine.','Answers!B31',['IF','AND','OR','NOT'],rows[0][3]==='Yes'&&(rows[0][4]==='Yes'||rows[0][1]>10||rows[0][2]<95)?'Escalate':'Routine','=IF(AND(Data!D2="Yes",OR(Data!E2="Yes",Data!B2>10,Data!C2<95)),"Escalate","Routine")',['Approval is required for escalation; then any one adverse condition suffices.','Nest OR inside AND, then wrap the combined test in IF.','=IF(AND(Data!D2="Yes",OR(____)),"Escalate","Routine")'])
    ]);

  add(2,2,
    'Pelvaris Mill is triaging 24 fictitious downtime events. Some events lose zero units, which is a valid measurement rather than missing data. Supervisors need duration bands and cost-per-lost-unit decisions that explain zero-denominator cases.',
    {intro:'Ordered decision rules and safe error handling keep a report readable. Do not convert every error into zero: zero cost and an undefined cost-per-unit ratio mean different things.',functions:[
      fn('IFS','Return the result for the first true condition.','=IFS(logical_test1, value_if_true1, [logical_test2, value_if_true2], ...)','Each test is paired with its result; later test/result pairs are optional.','=IFS(18<=10,"Short",18<=30,"Medium",TRUE,"Long")','Medium','Classify duration into ordered bands.','Put narrower conditions first; TRUE at the end supplies a catch-all outcome.'),
      fn('IFERROR','Use a stated fallback if an expression produces an Excel error.','=IFERROR(value, value_if_error)','value is the calculation; value_if_error is returned only when that calculation errors.','=IFERROR(40/0,"No lost units")','No lost units','Explain an undefined ratio without breaking a dashboard.','IFERROR also hides unexpected errors; verify references before adding a fallback.')
    ],combine:'Reuse ROUND for currency-per-unit outputs and IF for a threshold decision. IFS assigns duration labels in increasing upper-bound order. IFERROR belongs outside the entire ratio calculation or ratio-based decision. A zero-denominator fallback should remain text, not a misleading number.'},
    [['Event_code','Invented unique downtime event code.'],['Line','Invented line code.'],['Duration_min','Observed downtime duration, minutes.'],['Units_lost','Nonnegative units lost; zero is a valid observed result.'],['Labor_cost_CAD','Event labour recovery cost, Canadian dollars.']],
    r=>Array.from({length:24},(_,i)=>[`PM-E${1701+i}`,['Talven','Korrin','Istral'][i%3],i===0?10:r.int(4,67),i%4===0?0:r.int(6,48),r.int(7600,48600)/100]),
    rows=>[
      scalar('t1','Classify the first event’s Duration_min as Short for at most 10 minutes, Medium for more than 10 through 30 minutes, or Long for more than 30 minutes.',2,['IFS'],rows[0][2]<=10?'Short':rows[0][2]<=30?'Medium':'Long','=IFS(Data!C2<=10,"Short",Data!C2<=30,"Medium",TRUE,"Long")',['Check the inclusive upper bounds and evaluate the shortest band first.','Use IFS with ordered tests and a final TRUE catch-all.','=IFS(Data!C2<=____,"Short",Data!C2<=30,"Medium",TRUE,"Long")']),
      arrayTask('t2','For the first six events, calculate Labor_cost_CAD per Units_lost, rounded to two decimals. Return No lost units when the ratio is undefined. Keep dataset order.','Answers!B4:B9',['IFERROR','ROUND'],rows.slice(0,6).map(x=>x[3]===0?'No lost units':rounded(x[4]/x[3])),'=IFERROR(ROUND(Data!E2/Data!D2,2),"No lost units") [fill down from Answers!B4 to B9]',['Zero lost units needs the exact explanatory label; nonzero rows need a rounded cost-per-unit value.','Wrap ROUND of the division inside IFERROR.','=IFERROR(ROUND(Data!E2/____,2),"No lost units")']),
      arrayTask('t3','For the first six events, classify Duration_min as Critical for at least 45 minutes, Priority for at least 20 but less than 45, otherwise Routine. Keep dataset order.','Answers!B11:B16',['IFS'],rows.slice(0,6).map(x=>x[2]>=45?'Critical':x[2]>=20?'Priority':'Routine'),'=IFS(Data!C2>=45,"Critical",Data!C2>=20,"Priority",TRUE,"Routine") [fill down from Answers!B11 to B16]',['The longest-duration rule must be tested before the wider >=20 rule.','Use IFS in descending lower-bound order.','=IFS(Data!C2>=____,"Critical",Data!C2>=20,"Priority",TRUE,"Routine")']),
      arrayTask('t4','For the first eight events, return Review when the unrounded Labor_cost_CAD per Units_lost exceeds 15, otherwise Accept. Return No loss when the ratio is undefined. Keep dataset order.','Answers!B18:B25',['IFERROR','IF'],rows.slice(0,8).map(x=>x[3]===0?'No loss':x[4]/x[3]>15?'Review':'Accept'),'=IFERROR(IF(Data!E2/Data!D2>15,"Review","Accept"),"No loss") [fill down from Answers!B18 to B25]',['Compare the unrounded ratio. A zero denominator must not be treated as Accept.','Wrap the IF decision containing division with IFERROR.','=IFERROR(IF(Data!E2/____>15,"Review","Accept"),"No loss")']),
      bonusTask('Calculate overall labour cost per lost unit across all 24 events, rounded to two decimals. Include labour cost from zero-loss events in the total cost.','Answers!B27',['IFERROR','ROUND','SUM'],rounded(sum(rows,4)/sum(rows,3)),'=IFERROR(ROUND(SUM(Data!E2:E25)/SUM(Data!D2:D25),2),"No lost units")',['Pool costs and lost units separately; do not average individual ratios.','Reuse SUM twice, then ROUND the aggregate ratio with a clear fallback.','=IFERROR(ROUND(SUM(Data!____)/SUM(Data!____),2),"No lost units")'])
    ]);

  add(2,3,
    'Averiq Stationery is reviewing 26 fictitious September sales lines. The commercial team needs results for a region, channel and product category together. Revenue already represents the whole sales line, so it must not be multiplied by units again.',
    {intro:'Conditional aggregation screens rows first and then summarizes only matching rows. Multiple criterion pairs operate as AND. Keep every result and criterion range aligned to the same data rows.',functions:[
      fn('SUMIFS','Add numeric values whose rows meet every criterion.','=SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)','sum_range holds values; each criteria_range and criteria pair screens the corresponding rows.','=SUMIFS(D2:D4,B2:B4,"Cove")','320 when D2:D4 contains 120,80,200 and B2:B4 contains Cove,Vale,Cove','Sum revenue for a region and channel.','The sum range comes first, and all ranges need matching size and row alignment.'),
      fn('COUNTIFS','Count rows that satisfy every criterion.','=COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)','Each range/criterion pair adds a required condition; subsequent pairs are optional.','=COUNTIFS(B2:B4,"Cove")','2 when B2:B4 contains Cove,Vale,Cove','Count matching orders or inspected samples.','COUNTIFS counts rows, not units. Quote criteria such as ">=500".')
    ],combine:'Reuse ROUND and IFERROR when dividing conditional revenue by conditional row count. A criterion written as ">="&cell connects an operator to a cell value. Apply identical conditions to numerator and denominator; omitting one condition can produce a plausible but wrong average.'},
    [['Sales_line','Invented unique sales-line identifier.'],['Region','Invented sales territory: Cove or Vale.'],['Channel','Wholesale or Retail sales channel.'],['Category','Supplies or Fixtures product category.'],['Units','Sold units on this line.'],['Revenue_CAD','Total sales-line revenue, Canadian dollars.']],
    r=>Array.from({length:26},(_,i)=>[`AS-${3101+i}`,i%2===0?'Cove':'Vale',i%3===0?'Wholesale':'Retail',i%4<2?'Supplies':'Fixtures',r.int(3,32),r.int(18000,148000)/100]),
    rows=>{const c=rows.filter(x=>x[1]==='Cove');const cw=c.filter(x=>x[2]==='Wholesale');const cws=cw.filter(x=>x[3]==='Supplies');return [
      scalar('t1','Total Revenue_CAD for Region Cove, including both channels and both categories.',2,['SUMIFS'],sum(c,5),'=SUMIFS(Data!F2:F27,Data!B2:B27,"Cove")',['Filter the region only; do not restrict channel or category yet.','Use SUMIFS with revenue first and one criterion pair.','=SUMIFS(Data!F2:F27,Data!____,"Cove")']),
      scalar('t2','Count sales lines that are both Region Cove and Channel Wholesale. Count rows rather than sold units.',3,['COUNTIFS'],cw.length,'=COUNTIFS(Data!B2:B27,"Cove",Data!C2:C27,"Wholesale")',['Each matching line contributes one, regardless of its units or revenue.','Use COUNTIFS with both required conditions.','=COUNTIFS(Data!B2:B27,"Cove",Data!____,"Wholesale")']),
      scalar('t3','Total Revenue_CAD for Region Cove, Channel Wholesale and Category Supplies together.',4,['SUMIFS'],sum(cws,5),'=SUMIFS(Data!F2:F27,Data!B2:B27,"Cove",Data!C2:C27,"Wholesale",Data!D2:D27,"Supplies")',['All three conditions must apply to the same row.','Use three aligned criterion pairs in SUMIFS.','=SUMIFS(Data!F2:F27,Data!B2:B27,"Cove",Data!C2:C27,"Wholesale",____,"Supplies")']),
      scalar('t4','Calculate revenue per sales line for Region Cove and Channel Wholesale, rounded to two decimals. Divide that group’s total revenue by its matching line count. Use No sales if no matching rows exist.',5,['SUMIFS','COUNTIFS','ROUND','IFERROR'],rounded(mean(cw,5)),'=IFERROR(ROUND(SUMIFS(Data!F2:F27,Data!B2:B27,"Cove",Data!C2:C27,"Wholesale")/COUNTIFS(Data!B2:B27,"Cove",Data!C2:C27,"Wholesale"),2),"No sales")',['The total and the count must describe exactly the same group.','Combine SUMIFS/COUNTIFS, then reuse ROUND and IFERROR.','=IFERROR(ROUND(SUMIFS(____)/COUNTIFS(____),2),"No sales")']),
      bonusTask('Total Revenue_CAD for Region Cove lines with Revenue_CAD at least 500, including the 500 boundary.','Answers!B7',['SUMIFS'],sum(c.filter(x=>x[5]>=500),5),'=SUMIFS(Data!F2:F27,Data!B2:B27,"Cove",Data!F2:F27,">=500")',['The revenue criterion screens each line; do not screen the grand total.','Apply a quoted >= criterion to the revenue range as another SUMIFS pair.','=SUMIFS(Data!F2:F27,Data!B2:B27,"Cove",Data!F2:F27,____)'])
    ];});

  add(2,4,
    'Tervalon Pipe Services is examining 28 fictitious repair records. The team wants typical repair time for selected cells and shifts, plus cost attributed to one defect family. A training-only prioritization rule combines a group average with total Seam-repair cost.',
    {intro:'A conditional mean uses only matching observations. Its denominator is the number of matching numeric values, rather than every row in the table. Clean data still requires careful choice of group.',functions:[
      fn('AVERAGEIFS','Average numeric values whose rows meet every criterion.','=AVERAGEIFS(average_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)','average_range holds measurements; aligned criteria range/value pairs define the eligible rows.','=AVERAGEIFS(D2:D4,B2:B4,"Day")','26 when D2:D4 contains 18,26,34 and B2:B4 contains Day,Night,Day','Mean repair duration for a cell and shift.','No matching numeric observations produces #DIV/0!, not a meaningful zero.'),
      fn('SUMIF','Sum values for one condition.','=SUMIF(range, criteria, [sum_range])','range is screened; criteria is the condition; optional sum_range supplies values instead of range itself.','=SUMIF(B2:B4,"Seam",D2:D4)','200 when B2:B4 contains Seam,Edge,Seam and D2:D4 contains 90,60,110','Attribute costs to one defect family.','SUMIF puts the criterion range first; SUMIFS puts the sum range first.')
    ],combine:'Reuse IFERROR to label missing groups, ROUND to present a mean, and IF with AND for a two-part decision. Multiple conditions belong in AVERAGEIFS; a single cost-category condition can use SUMIF. Do not confuse an average duration with a summed duration.'},
    [['Repair_code','Invented unique repair ID.'],['Cell','Mill-1 or Mill-2 repair cell.'],['Shift','Day or Night shift.'],['Defect_family','Training defect category: Seam, Edge or Surface.'],['Repair_min','Repair time, minutes.'],['Repair_cost_CAD','Repair cost, Canadian dollars.']],
    r=>Array.from({length:28},(_,i)=>[`TP-R${5201+i}`,i%2===0?'Mill-2':'Mill-1',i%4<2?'Night':'Day',['Seam','Edge','Surface'][i%3],r.int(18,75),r.int(8900,58200)/100]),
    rows=>{const m=rows.filter(x=>x[1]==='Mill-2');const mn=m.filter(x=>x[2]==='Night');const seam=rows.filter(x=>x[3]==='Seam');return [
      scalar('t1','Calculate unrounded mean Repair_min for Cell Mill-2, across all shifts and defect families.',2,['AVERAGEIFS'],mean(m,4),'=AVERAGEIFS(Data!E2:E29,Data!B2:B29,"Mill-2")',['Select Mill-2 records only; do not sum their minutes.','Use AVERAGEIFS with the duration range first.','=AVERAGEIFS(Data!E2:E29,Data!____,"Mill-2")']),
      scalar('t2','Calculate mean Repair_cost_CAD for Cell Mill-2, Shift Night and Defect_family Seam, rounded to two decimals. Use No repairs if the group has no numeric observations.',3,['AVERAGEIFS','ROUND','IFERROR'],rounded(mean(mn.filter(x=>x[3]==='Seam'),5)),'=IFERROR(ROUND(AVERAGEIFS(Data!F2:F29,Data!B2:B29,"Mill-2",Data!C2:C29,"Night",Data!D2:D29,"Seam"),2),"No repairs")',['Apply all three conditions to the mean cost.','Use AVERAGEIFS with three pairs, then ROUND and IFERROR.','=IFERROR(ROUND(AVERAGEIFS(Data!F2:F29,____),2),"No repairs")']),
      scalar('t3','Total Repair_cost_CAD for Defect_family Seam, across both cells and shifts.',4,['SUMIF'],sum(seam,5),'=SUMIF(Data!D2:D29,"Seam",Data!F2:F29)',['The screened column is defect family; the values to add are costs.','Use SUMIF with its distinct criterion-first argument order.','=SUMIF(Data!____,"Seam",Data!F2:F29)']),
      scalar('t4','Return Prioritize if mean Repair_min for Mill-2 Night records exceeds 40 AND total Repair_cost_CAD for all Seam records exceeds 1500. Otherwise return Monitor. These are separate groups, as stated.',5,['IF','AND','AVERAGEIFS','SUMIF'],mean(mn,4)>40&&sum(seam,5)>1500?'Prioritize':'Monitor','=IF(AND(AVERAGEIFS(Data!E2:E29,Data!B2:B29,"Mill-2",Data!C2:C29,"Night")>40,SUMIF(Data!D2:D29,"Seam",Data!F2:F29)>1500),"Prioritize","Monitor")',['Use the specified average group and the separate all-Seam cost group. Both thresholds are strict > tests.','Reuse IF and AND around one AVERAGEIFS test and one SUMIF test.','=IF(AND(AVERAGEIFS(____)>40,SUMIF(____)>1500),"Prioritize","Monitor")']),
      bonusTask('Calculate the percentage of total repair cost attributed to Seam records, rounded to two decimals. Submit a percentage number, not a fraction.','Answers!B7',['SUMIF','SUM','ROUND'],rounded(100*sum(seam,5)/sum(rows,5)),'=ROUND(SUMIF(Data!D2:D29,"Seam",Data!F2:F29)/SUM(Data!F2:F29)*100,2)',['Divide the Seam cost total by the total of all repairs, then multiply by 100.','Combine SUMIF with earlier SUM and ROUND.','=ROUND(SUMIF(____)/SUM(Data!F2:F29)*100,2)'])
    ];});

  add(2,5,
    'Solvani Distribution is reviewing 30 fictitious shipment records. Delivered and In transit records must not be mixed when judging observed lead times. One invented carrier has no delivered shipments, so the report must distinguish an absent group from a genuine zero-day result.',
    {intro:'Conditional extremes describe a selected group. MAXIFS and MINIFS return zero when no rows match, so first check group existence before treating an extreme as an observed lead time.',functions:[
      fn('MAXIFS','Return the largest numeric value among rows meeting all criteria.','=MAXIFS(max_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)','max_range holds numeric observations; aligned criteria pairs specify the eligible rows.','=MAXIFS(D2:D4,B2:B4,"Done")','5 when D2:D4 contains 3,9,5 and B2:B4 contains Done,Open,Done','Find the longest delivered-shipment lead time.','No matches returns zero; that does not prove a real zero-day delivery.'),
      fn('MINIFS','Return the smallest numeric value among rows meeting all criteria.','=MINIFS(min_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)','min_range is the measurement range; each range/criterion pair adds a required condition.','=MINIFS(D2:D4,B2:B4,"Done")','3 when D2:D4 contains 3,9,5 and B2:B4 contains Done,Open,Done','Find the shortest observed lead time in a group.','All ranges must share size and row alignment; use COUNTIFS to distinguish an empty group.')
    ],combine:'Reuse COUNTIFS and IF to handle absent groups explicitly. Subtract MINIFS from MAXIFS for a selected group’s observed range. Reuse AND for a service decision only after confirming records exist. These training results are descriptive; they are not control limits.'},
    [['Shipment_code','Invented unique shipment identifier.'],['Carrier','Invented carrier code: Zephra, Ordel or Vanta.'],['Region','Invented delivery area: North or South.'],['Status','Delivered or In transit.'],['Lead_days','Measured or elapsed calendar days, positive integer.'],['Freight_CAD','Shipment freight cost, Canadian dollars.']],
    r=>Array.from({length:30},(_,i)=>{const carrier=['Zephra','Ordel','Vanta'][i%3];return [`SD-${8801+i}`,carrier,i%2===0?'North':'South',carrier==='Vanta'||i%5===0?'In transit':'Delivered',r.int(1,11),r.int(6400,41200)/100];}),
    rows=>{const z=rows.filter(x=>x[1]==='Zephra'&&x[3]==='Delivered');const zn=z.filter(x=>x[2]==='North');return [
      scalar('t1','Find the longest Lead_days for Carrier Zephra with Status Delivered, across both regions.',2,['MAXIFS'],Math.max(...z.map(x=>x[4])),'=MAXIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!D2:D31,"Delivered")',['Do not include In transit records, even if they have a longer elapsed time.','Use MAXIFS with carrier and delivered-status criteria.','=MAXIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!____,"Delivered")']),
      scalar('t2','Find the shortest Lead_days for Carrier Zephra, Region North and Status Delivered together.',3,['MINIFS'],Math.min(...zn.map(x=>x[4])),'=MINIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!C2:C31,"North",Data!D2:D31,"Delivered")',['All three conditions describe the selected delivery group.','Use MINIFS with three aligned range/criterion pairs.','=MINIFS(Data!E2:E31,Data!B2:B31,"Zephra",____,"North",Data!D2:D31,"Delivered")']),
      scalar('t3','Calculate longest minus shortest Lead_days for Zephra North Delivered shipments. Use the same three-condition group for both extremes.',4,['MAXIFS','MINIFS'],Math.max(...zn.map(x=>x[4]))-Math.min(...zn.map(x=>x[4])),'=MAXIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!C2:C31,"North",Data!D2:D31,"Delivered")-MINIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!C2:C31,"North",Data!D2:D31,"Delivered")',['Subtract extremes from exactly the same group, including region and status.','Combine MAXIFS and MINIFS with identical criterion pairs.','=MAXIFS(____)-MINIFS(____)']),
      scalar('t4','For Carrier Vanta with Status Delivered, return its longest Lead_days if at least one matching row exists; otherwise return No matching shipments. Do not use zero as the absence label.',5,['IF','COUNTIFS','MAXIFS'],'No matching shipments','=IF(COUNTIFS(Data!B2:B31,"Vanta",Data!D2:D31,"Delivered")>0,MAXIFS(Data!E2:E31,Data!B2:B31,"Vanta",Data!D2:D31,"Delivered"),"No matching shipments")',['No matching deliveries is different from a measured zero-day delivery.','Guard MAXIFS with an IF test on COUNTIFS.','=IF(COUNTIFS(____)>0,MAXIFS(____),"No matching shipments")']),
      bonusTask('Return Met when at least one Zephra North Delivered record exists and its longest Lead_days is at most 5. Otherwise return Review.','Answers!B7',['IF','AND','COUNTIFS','MAXIFS'],zn.length>0&&Math.max(...zn.map(x=>x[4]))<=5?'Met':'Review','=IF(AND(COUNTIFS(Data!B2:B31,"Zephra",Data!C2:C31,"North",Data!D2:D31,"Delivered")>0,MAXIFS(Data!E2:E31,Data!B2:B31,"Zephra",Data!C2:C31,"North",Data!D2:D31,"Delivered")<=5),"Met","Review")',['Confirm the group exists before applying the five-day rule.','Combine a count check and conditional maximum inside AND, then IF.','=IF(AND(COUNTIFS(____)>0,MAXIFS(____)<=5),"Met","Review")'])
    ];});
  return packages;
}

export const referenceSources = [
  ['Excel functions by category','https://support.microsoft.com/en-us/excel/excel-functions-by-category'],
  ...['sum','average','count','counta','min','max','round','roundup','rounddown','if','abs','and','or','not','ifs','iferror','sumifs','countifs','averageifs','sumif','maxifs','minifs'].map(name=>[`${name.toUpperCase()} function`, `https://support.microsoft.com/en-us/excel/functions/${name}-function`]),
  ['Relative, absolute and mixed references','https://support.microsoft.com/en-us/excel/switch-between-relative-absolute-and-mixed-references']
].map(([title,url])=>({title,url}));
