/* Build-only placement and practice authoring. Never publish this directory. */
const round=(n,d=2)=>Math.round((n+Number.EPSILON)*10**d)/10**d;
const numeric=v=>typeof v==='number'&&Number.isFinite(v);
const sum=(rows,c)=>rows.reduce((n,r)=>n+(numeric(r[c])?r[c]:0),0);
const vector=a=>a.map(v=>[v]);
const names=['Foundations','Logic and conditional aggregation','Exact lookups','Text cleaning','Dates and time','Dynamic arrays','Array logic','Structure and reuse','Analysis and reporting','Integrated formulas'];
const column=(name,description)=>({name,description});
const formula=(name,syntax,explanation,example,result)=>({name,syntax,explanation,example,result});
const Q=(level,prompt,choices,correctOption,explanation)=>({id:`q${level}`,skillId:`level-${level}`,level,prompt,options:choices.map((text,i)=>({id:'abcd'[i],text})),private:{correctOption,explanation}});

export const diagnosticQuestions=[
 Q(1,'A training range contains the numbers 10, 0, a genuinely empty cell, and 20. What does AVERAGE return?',['15','7.5','10','An error'],'c','AVERAGE includes numeric zero and ignores a genuinely empty cell: (10+0+20)/3 = 10.'),
 Q(2,'You need total repair cost where Shift is Day AND Defect is Scratch. Which formula expresses both conditions?', ['=SUMIFS(Cost,Shift,"Day",Defect,"Scratch")','=SUM(Cost)','=SUMIF(Shift,"Day",Cost)+SUMIF(Defect,"Scratch",Cost)','=COUNTIFS(Shift,"Day",Defect,"Scratch")'],'a','SUMIFS applies both criteria to each row and sums the matching costs. Adding separate conditional sums includes unwanted rows and can double-count.'),
 Q(3,'A product lookup must return Ambiguous when its key occurs twice. Which approach follows that rule?',['Use the last match','Use the first match','Treat duplicates as absent','Count exact matches, then look up only when the count is one'],'d','A first-match or last-match lookup hides duplicate keys. Count matching keys before selecting a value.'),
 Q(4,'An inspector code has extra spaces and a line break. Which formula removes the nonprinting line break, trims spaces and converts letters to capitals?',['=PROPER(A2)','=UPPER(TRIM(CLEAN(A2)))','=LEFT(A2,3)','=TEXT(A2,"0")'],'b','CLEAN removes the nonprinting line break, TRIM removes excess ordinary spaces, and UPPER standardizes letters.'),
 Q(5,'A single shift starts at 22:00 and ends at 06:00 the next day. It lasts less than 24 hours. Which elapsed duration is correct?',['-16 hours','16 hours','8 hours','32 hours'],'c','For a shift shorter than one day, MOD(end-start,1)*24 returns eight hours. The assumption is essential because MOD discards whole days.'),
 Q(6,'FILTER returns all inspection rows with numeric thickness below 12 mm. Several records share one heat number. Which duplicate rule preserves the requested report?',['Keep every matching source record','Keep only one record per heat','Keep the first heat regardless of thickness','Average each heat before filtering'],'a','An exception report requested at record level retains every matching row. Deduplicating or averaging would change the report grain.'),
 Q(7,'Two batches have 90 good units of 100 inspected, and 50 good units of 1,000 inspected. What is the pooled good yield, rounded to two decimal places as a percentage number?',['47.50','70.00','14.00','12.73'],'d','Pooled yield is 100*(90+50)/(100+1000), rounded to 12.73. An average of the batch percentages weights both batches equally.'),
 Q(8,'A long formula uses the same filtered array three times. What does LET allow you to do?',['Convert every output to text','Name the intermediate array and reuse it inside the formula','Store the result permanently even after inputs change','Remove all missing-data checks'],'b','LET names intermediate values within one formula, improving readability and allowing reuse. Names do not remove validation requirements.'),
 Q(9,'Two measurement columns have blanks in different rows and valid numeric zeros. Before CORREL, which population should be used?',['Only rows with positive numbers','Filter each column independently','Rows where both measurements are numeric, keeping zero','Replace every blank with zero'],'c','Use the same complete-pair mask for both arrays. This preserves row alignment, retains numeric zeros and excludes missing measurements.'),
 Q(10,'An integrated training rule requires Review if any required input is missing. Otherwise it returns Hold below the limit, or Pass at or above it. A row has missing cost data and a below-limit test. Which status comes first?',['Review','Hold','Pass','Zero'],'a','The missing-input rule has precedence. Evaluate completeness first, then apply the numeric acceptance comparison. These are fictitious training rules.')
];

/** Twenty fixed practice datasets, independently seeded from all core packages. */
export function createLearningDrills(randomFor){
 const drills=[];
 const add=(level,variant,title,scenario,lesson,columns,rows,prompt,answer,model,alternatives,hints,formulas)=>{
  const id=`R${level}-A${variant}`,array=Array.isArray(answer),matrix=array?(Array.isArray(answer[0])?answer:vector(answer)):null;
  const output=matrix?`Answers!B2:${String.fromCharCode(65+matrix[0].length)}${matrix.length+1}`:'Answers!B2';
  const contract=matrix?`Return ${matrix.length} rows × ${matrix[0].length} column${matrix[0].length===1?'':'s'}, without a header, in ${output}.`:`Return one ${typeof answer==='number'?'numeric value':'text value'} in ${output}.`;
  drills.push({id,version:1,skillId:`level-${level}`,level,title,scenario:`${scenario} All records and limits are fictitious training assumptions.`,lesson,columns,rows,task:{id:'t1',prompt:`${prompt} ${contract} Use an Excel formula; any equivalent approach is accepted. Submit the formula and the complete output.`,output,type:matrix?'array':typeof answer==='number'?'number':'text',formulas},private:{version:1,skillId:`level-${level}`,task:{id:'t1',answer:matrix||answer,tolerance:1e-6,model,alternatives,hints}}});
 };
 for(let v=1;v<=2;v++){
  let r=randomFor(`reinforcement-v1-level-1-variant-${v}`);
  let rows=Array.from({length:20},(_,i)=>[`RX${v}-${i+1}`,i===2?'':i===4?0:r.int(12,38)]);
  add(1,v,`Average event duration ${v}`,'An invented pipe-inspection team records event durations in minutes. Each row is a separate event, including repeated durations.',
   {intro:'AVERAGE adds numeric observations and divides by their count. A measured zero is an observation; an empty cell is missing. Use the data range rather than typing a calculated answer.',formulas:[formula('AVERAGE','=AVERAGE(number1, [number2], ...)','number1 is a number, cell or range. Optional further arguments add observations. Referenced text and blanks are ignored; zero counts.','=AVERAGE(6,0,12)',6),formula('ROUND','=ROUND(number, num_digits)','number is the result; num_digits sets decimal places. Round the final mean only.','=ROUND(2.346,2)',2.35)]},
   [column('Event_no','Unique invented event identifier.'),column('Duration_min','Numeric duration in minutes. Empty means not recorded; zero means measured zero.')],rows,
   'Calculate the mean of Duration_min across all 20 events, excluding blank cells and including numeric zero. Repeated durations are separate observations. Round the final mean to two decimal places.',
   round(sum(rows,1)/rows.filter(x=>numeric(x[1])).length),'=ROUND(AVERAGE(Data!B2:B21),2)',['=ROUND(SUM(Data!B2:B21)/COUNT(Data!B2:B21),2)'],['Include the measured zero but exclude the genuinely empty cell.','Use AVERAGE across B2:B21, then round once.','=ROUND(AVERAGE(____),2)'],['AVERAGE','ROUND']);

  r=randomFor(`reinforcement-v1-level-2-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>[`DY${v}-${i+1}`,i%2?'Night':'Day',i%3?'Repair':'Setup',i===2?'':i===6?0:r.int(8,90)]);
  const selected=rows.filter(x=>x[1]==='Day'&&x[2]==='Repair');
  add(2,v,`Total selected downtime ${v}`,'A fictitious rolling line logs downtime by shift and cause. Each event is independent; repeated shift and cause values are expected.',
   {intro:'SUMIFS adds a numeric column only where every criterion matches the same row. Keep sum and criteria ranges aligned. Do not add two separate conditional totals for an AND rule. Separate miniature example: A2:A4 contains Day, Night, Day; B2:B4 contains 4, 7, 3.',formulas:[formula('SUMIFS','=SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)','sum_range contains amounts. Each criteria_range aligns with it; the following criterion defines which rows qualify. Additional pairs are optional.','=SUMIFS(B2:B4,A2:A4,"Day")',7)]},
   [column('Event_no','Unique event identifier.'),column('Shift','Exact Day or Night text.'),column('Cause','Exact Repair or Setup text.'),column('Downtime_min','Minutes. Blank contributes no numeric amount; numeric zero contributes zero.')],rows,
   'Total Downtime_min for Shift = Day AND Cause = Repair. Keep every qualifying record, including repeated categories. Ignore blank amounts and retain zero. Return the exact integer total, without rounding.',sum(selected,3),
   '=SUMIFS(Data!D2:D21,Data!B2:B21,"Day",Data!C2:C21,"Repair")',['=SUMPRODUCT(--(Data!B2:B21="Day"),--(Data!C2:C21="Repair"),N(Data!D2:D21))'],['Both criteria must match the same event.','Use SUMIFS with the downtime column and two aligned criteria ranges.','=SUMIFS(____,Data!B2:B21,"Day",____,"Repair")'],['SUMIFS']);

  r=randomFor(`reinforcement-v1-level-3-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>[`LK${v}-${String(i+1).padStart(3,'0')}`,`Product ${i+1}`,i===13?0:r.int(40,180)]);
  const target=v===1?'LK1-014':'LK2-999',found=rows.find(x=>x[0]===target);
  add(3,v,`Find a product allowance ${v}`,'An invented allowance register has one unique product key per row. All allowance values are numeric CAD amounts; zero is a permitted allowance.',
   {intro:'An exact lookup matches a key, not a row position. Explicitly define what happens when the key is absent. A numeric zero returned from an existing record remains zero.',formulas:[formula('XLOOKUP','=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])','lookup_value is the key; aligned lookup_array and return_array contain keys and results. Optional if_not_found handles absence, match_mode 0 means exact, and search_mode controls search direction.','=XLOOKUP("B",{"A";"B"},{7;0},"Missing",0)',0)]},
   [column('Product_code','Unique exact text key, including leading-zero numeric segments.'),column('Description','Product label.'),column('Allowance_CAD','Numeric allowance in CAD, including a legitimate zero. No blanks.')],rows,
   `Look up the Allowance_CAD for exact Product_code ${target}. An absent key must return the text Missing. Keys are unique, so there is no duplicate selection. Preserve a matched numeric zero; do not round a numeric allowance.`,found?found[2]:'Missing',
   `=XLOOKUP("${target}",Data!A2:A21,Data!C2:C21,"Missing",0)`,[`=IFNA(INDEX(Data!C2:C21,MATCH("${target}",Data!A2:A21,0)),"Missing")`],['Match the complete product code exactly; an absent code differs from a zero allowance.','Use exact XLOOKUP with an explicit Missing fallback.','=XLOOKUP(____,Data!A2:A21,Data!C2:C21,"Missing",0)'],['XLOOKUP']);

  rows=Array.from({length:20},(_,i)=>[`TX${v}-${i+1}`,i===2?'':i===4?'   ':i===6?'0':i%3===0?`  qa${v}-${String(i%7).padStart(2,'0')} \n`:i%3===1?`Qa${v}-  ${i%7}`:`qa${v}-${i%7}`]);
  const cleaned=x=>String(x).replace(/[\x00-\x1f]/g,'').trim().replace(/ +/g,' ').toUpperCase();
  add(4,v,`Normalize inspector codes ${v}`,'An invented inspection register contains codes with ordinary spaces and nonprinting line breaks. Repeated codes represent separate records.',
   {intro:'Clean text before comparing it. CLEAN removes nonprinting characters, TRIM removes leading/trailing ordinary spaces and reduces repeated internal spaces, and UPPER standardizes letter case. Do not delete legitimate internal spaces.',formulas:[formula('CLEAN','=CLEAN(text)','text is a cell or string with nonprinting ASCII characters to remove.','=CLEAN("QA"&CHAR(10)&"7")','QA7'),formula('TRIM','=TRIM(text)','text is trimmed of ordinary edge spaces and repeated internal spaces.','=TRIM("  QA  7  ")','QA 7'),formula('UPPER','=UPPER(text)','text letters become capitals; digits and punctuation remain.','=UPPER("qa-7")','QA-7')]},
   [column('Record_no','Unique record identifier.'),column('Inspector_text','Raw code. Empty and space-only values are missing; text 0 is a valid code.')],rows,
   'For every row, remove nonprinting ASCII characters, trim ordinary spaces, collapse repeated internal spaces and uppercase letters. If the cleaned code is empty, return Missing. Preserve text 0 and legitimate single internal spaces. Keep dataset order and every duplicate record. Enter at B2 and fill down through B21; return text without rounding.',rows.map(x=>cleaned(x[1])||'Missing'),
   '=IF(TRIM(CLEAN(Data!B2))="","Missing",UPPER(TRIM(CLEAN(Data!B2)))) [fill down through Answers!B21]',['=LET(t,UPPER(TRIM(CLEAN(Data!B2))),IF(t="","Missing",t)) [fill down through Answers!B21]'],['Space-only codes are missing, but the literal text 0 is valid.','Apply CLEAN, TRIM and UPPER before the empty-code decision.','=IF(TRIM(CLEAN(____))="","Missing",UPPER(TRIM(CLEAN(____))))'],['CLEAN','TRIM','UPPER','IF']);

  rows=Array.from({length:20},(_,i)=>[`DT${v}-${i+1}`,2028,1+(i%4),i===1?29:1+((i*3+v)%27)]);
  // Explicitly include the leap-day boundary without depending on locale parsing.
  rows[1]=[`DT${v}-2`,2028,2,29];
  add(5,v,`Build unambiguous test dates ${v}`,'A fictitious test schedule stores year, month and day as separate integers. All listed dates are valid, including a leap-day case.',
   {intro:'DATE builds an Excel date from numeric components without ambiguous text parsing. TEXT formats that date for an ISO-style output. For date arithmetic keep the DATE result numeric; this task deliberately requests an ISO text label.',formulas:[formula('DATE','=DATE(year, month, day)','year, month and day are numeric components. DATE produces a numeric date serial.','=DATE(2024,2,29)','2024-02-29'),formula('TEXT','=TEXT(value, format_text)','value is the number or date to format. format_text controls the returned text.','=TEXT(DATE(2024,2,29),"yyyy-mm-dd")','2024-02-29')]},
   [column('Test_no','Unique test identifier.'),column('Year','Four-digit numeric year.'),column('Month','Numeric month, 1 through 12.'),column('Day','Valid numeric day for the listed month/year.')],rows,
   'Construct each date from Year, Month and Day, then return ISO text yyyy-mm-dd. Use all 20 rows in source order, without deduplication. Inputs have no blanks or zeros and are valid dates; do not infer dates from identifiers. Enter at B2 and fill down through B21. No rounding applies.',rows.map(x=>new Date(Date.UTC(x[1],x[2]-1,x[3])).toISOString().slice(0,10)),
   '=TEXT(DATE(Data!B2,Data!C2,Data!D2),"yyyy-mm-dd") [fill down through Answers!B21]',['=TEXT(DATE(Data!B2,Data!C2,1)+Data!D2-1,"yyyy-mm-dd") [fill down through Answers!B21]'],['Keep the leap-day row valid and format all labels with four-digit years.','Use DATE for components, then TEXT for ISO formatting.','=TEXT(DATE(____,Data!C2,____),"yyyy-mm-dd")'],['DATE','TEXT']);

  r=randomFor(`reinforcement-v1-level-6-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>[`FL${v}-${String(i+1).padStart(3,'0')}`,`RH${v}-${i%4}`,i===2?'':i===4?0:i===6?12:round(r.int(110,132)/10,1)]);
  const exceptions=rows.filter(x=>numeric(x[2])&&x[2]<12).map(x=>x[0]);
  add(6,v,`Filter thickness exceptions ${v}`,'An invented pipe-inspection register has 20 separate measurements. Several records share a heat, but every record must remain independently traceable.',
   {intro:'FILTER returns records meeting an aligned Boolean mask. Multiplication combines AND conditions. Check ISNUMBER so a missing measurement cannot be treated as zero. Leave the entire spill area empty before entering the formula.',formulas:[formula('FILTER','=FILTER(array, include, [if_empty])','array is the returned range; include is an aligned TRUE/FALSE mask. Optional if_empty defines the no-match result.','=FILTER({"A";"B";"C"},{TRUE;FALSE;TRUE},"None")','A then C'),formula('ISNUMBER','=ISNUMBER(value)','value is tested for a numeric type. Numeric zero is TRUE; empty/text inputs are FALSE.','=ISNUMBER(0)',true)]},
   [column('Record_no','Unique measurement identifier.'),column('Heat_no','Repeating invented heat identifier.'),column('Thickness_mm','Numeric thickness in mm. Empty means missing; zero is a recorded training measurement.')],rows,
   'Return only Record_no values whose Thickness_mm is numeric and strictly below the training threshold 12 mm. Equality is excluded; numeric zero is included and blanks are excluded. Keep source order and all qualifying records even when heats repeat. Spill one formula from B2. Do not round or add a header; if a future dataset has no matches, return the single text None.',exceptions,
   '=FILTER(Data!A2:A21,ISNUMBER(Data!C2:C21)*(Data!C2:C21<12),"None")',['=FILTER(Data!A2:A21,(Data!C2:C21<>"")*(Data!C2:C21<12),"None")'],['A blank measurement cannot be reported as a measured zero; equality at 12 is not below the limit.','Combine ISNUMBER with the strict comparison in FILTER.','=FILTER(Data!A2:A21,ISNUMBER(____)*(____<12),"None")'],['FILTER','ISNUMBER']);

  r=randomFor(`reinforcement-v1-level-7-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>{const n=i===4?0:r.int(60,650);return[`WY${v}-${i+1}`,i%2?'Night':'Day',n,n?Math.max(0,n-r.int(0,25)):0];});
  const day=rows.filter(x=>x[1]==='Day');
  add(7,v,`Calculate a weighted Day yield ${v}`,'An invented finishing team records independent production batches. Batch sizes differ, and the requested population is Day batches only.',
   {intro:'A pooled yield divides selected good units by the same population of inspected units. SUMPRODUCT can multiply a Boolean selection mask by an aligned quantity column. A mean of batch percentages gives each batch equal weight and answers a different question.',formulas:[formula('SUMPRODUCT','=SUMPRODUCT(array1, [array2], ...)','Aligned arrays are multiplied entry by entry and their products are summed. Additional arrays are optional; double unary converts TRUE/FALSE to 1/0.','=SUMPRODUCT({2;3},{4;5})',23),formula('ROUND','=ROUND(number, num_digits)','Round the final ratio to the requested precision.','=ROUND(18.765,2)',18.77)]},
   [column('Batch_no','Unique batch identifier.'),column('Shift','Exact Day or Night.'),column('Inspected_units','Numeric nonnegative units; zero is a zero-volume batch.'),column('Good_units','Numeric units, between zero and Inspected_units.')],rows,
   'Calculate 100 × total Good_units / total Inspected_units for Day batches only. Use the identical Day population in both totals, retaining every repeated shift record and legitimate zero-volume batch. All quantities are numeric, without blanks; the selected inspected total is positive. Round the final percentage number to two decimals (for example 93.25, not 0.9325).',round(100*sum(day,3)/sum(day,2)),
   '=ROUND(100*SUMPRODUCT(--(Data!B2:B21="Day"),Data!D2:D21)/SUMPRODUCT(--(Data!B2:B21="Day"),Data!C2:C21),2)',['=ROUND(100*SUMIFS(Data!D2:D21,Data!B2:B21,"Day")/SUMIFS(Data!C2:C21,Data!B2:B21,"Day"),2)'],['The numerator and denominator must include the same Day batches.','Use a Day mask in two SUMPRODUCT totals and divide the totals.','=ROUND(100*SUMPRODUCT(____,Data!D2:D21)/SUMPRODUCT(____,Data!C2:C21),2)'],['SUMPRODUCT','ROUND']);

  r=randomFor(`reinforcement-v1-level-8-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>{const sales=i===4?0:r.int(150,900);return[`MG${v}-${i+1}`,sales,sales?round(sales*r.int(35,80)/100):0];});
  add(8,v,`Name a pooled margin calculation ${v}`,'An invented business register stores independent sales and direct costs in CAD. The requested margin uses totals across all records.',
   {intro:'LET assigns meaningful local names to intermediate values, then returns the final calculation. Names exist only inside that formula. Pooled margin is (total sales − total cost) / total sales. A zero sales total needs an explicit missing-result rule.',formulas:[formula('LET','=LET(name1, name_value1, [name2, name_value2], ..., calculation)','Provide local name/value pairs, followed by the expression to return. Names must be valid Excel names and can be reused in the final calculation.','=LET(sales,120,cost,90,(sales-cost)/sales)',0.25),formula('SUM','=SUM(number1, [number2], ...)','Add numeric values across the selected range. Zero remains a valid contribution.','=SUM(10,0,15)',25)]},
   [column('Record_no','Unique independent sales record.'),column('Sales_CAD','Numeric nonnegative sales in CAD.'),column('Direct_cost_CAD','Numeric direct cost in CAD; zero-sales rows have zero cost.')],rows,
   'Return pooled margin = (total Sales_CAD − total Direct_cost_CAD) / total Sales_CAD for all 20 records. Keep all repeated amount values as separate records, including numeric zero. No inputs are blank. Round only the final decimal ratio to three places (0.25 means 25%). If total sales were zero, return the text Missing. Practice using LET to name the two totals.',round((sum(rows,1)-sum(rows,2))/sum(rows,1),3),
   '=LET(sales,SUM(Data!B2:B21),cost,SUM(Data!C2:C21),IF(sales=0,"Missing",ROUND((sales-cost)/sales,3)))',['=LET(totalSales,SUM(Data!B2:B21),totalCost,SUM(Data!C2:C21),IF(totalSales<>0,ROUND(1-totalCost/totalSales,3),"Missing"))'],['Divide the difference of totals by total sales; do not average row margins.','Name sales and cost with LET, then guard the sales denominator.','=LET(sales,____,cost,____,IF(sales=0,"Missing",ROUND((sales-cost)/sales,3)))'],['LET','SUM','IF','ROUND']);

  r=randomFor(`reinforcement-v1-level-9-variant-${v}`);
  if(v===1){
   rows=Array.from({length:20},(_,i)=>[`SD-${i+1}`,i===2?'':i===4?0:r.int(12,42)]);
   const a=rows.map(x=>x[1]).filter(numeric),m=a.reduce((n,x)=>n+x,0)/a.length,sd=Math.sqrt(a.reduce((n,x)=>n+(x-m)**2,0)/(a.length-1));
   add(9,v,'Estimate sample variation','A fictitious inspection experiment records event durations in minutes. The rows are observations, with numeric zero permitted and one missing measurement.',
    {intro:'STDEV.S describes sample spread using n−1 in its denominator. It ignores referenced blanks and includes numeric zero. At least two numeric observations are needed. This descriptive measure alone does not establish process stability or production acceptance.',formulas:[formula('STDEV.S','=STDEV.S(number1, [number2], ...)','number1 is a numeric sample or range. Further optional arguments add observations. The sample denominator is n−1.','=STDEV.S(8,10,12)',2),formula('ROUND','=ROUND(number, num_digits)','Round the completed statistic once.','=ROUND(1.23456,3)',1.235)]},
    [column('Observation_no','Unique independent observation.'),column('Duration_min','Numeric duration in minutes. Blank is missing; zero is measured zero.')],rows,
    'Calculate sample standard deviation of Duration_min over all 20 records. Exclude blanks and include zero; repeated durations remain separate observations. Use n−1, not the population denominator. Round only the final result to three decimals. These data have at least two numeric observations.',round(sd,3),
    '=ROUND(STDEV.S(Data!B2:B21),3)',['=ROUND(SQRT(DEVSQ(Data!B2:B21)/(COUNT(Data!B2:B21)-1)),3)'],['A sample statistic uses n−1 and retains numeric zero.','Use STDEV.S rather than STDEV.P, followed by ROUND.','=ROUND(STDEV.S(____),3)'],['STDEV.S','ROUND']);
  }else{
   rows=Array.from({length:20},(_,i)=>{const a=i===4?0:r.int(10,38);return[`CR-${i+1}`,i===2?'':a,i===7?'':2*a+r.int(-8,8)];});
   const a=rows.filter(x=>numeric(x[1])&&numeric(x[2])),mx=sum(a,1)/a.length,my=sum(a,2)/a.length,corr=a.reduce((n,x)=>n+(x[1]-mx)*(x[2]-my),0)/Math.sqrt(a.reduce((n,x)=>n+(x[1]-mx)**2,0)*a.reduce((n,x)=>n+(x[2]-my)**2,0));
   add(9,v,'Keep correlation pairs aligned','A fictitious experiment pairs two instrument readings per observation. Missing readings occur in different rows; numeric zero is permitted. Units are arbitrary training units.',
    {intro:'CORREL measures linear association between aligned numeric pairs. Filter both columns with the same completeness mask so unrelated rows never become pairs. Keep numeric zero. Nonzero variation and at least two complete pairs are required; correlation does not prove causation.',formulas:[formula('CORREL','=CORREL(array1, array2)','The two arrays contain corresponding numeric observations, with equal length and nonzero variation.','=CORREL({0;1;2},{0;2;4})',1),formula('FILTER','=FILTER(array, include, [if_empty])','Use one aligned mask to select complete pairs from each numeric column.','=FILTER({4;7;9},{TRUE;FALSE;TRUE})','4 then 9')]},
    [column('Observation_no','Unique paired observation.'),column('Reading_X_units','Numeric X reading; blank means missing, zero is valid.'),column('Reading_Y_units','Numeric Y reading; blank means missing, zero is valid.')],rows,
    'Calculate Pearson correlation using only rows where Reading_X_units AND Reading_Y_units are numeric. Keep every complete pair in source order, including numeric zero and repeated readings. Never filter the two arrays independently or replace missing readings with zero. Both retained arrays have nonzero variation and at least two rows. Round the final correlation to three decimals.',round(corr,3),
    '=LET(x,Data!B2:B21,y,Data!C2:C21,keep,ISNUMBER(Data!B2:B21)*ISNUMBER(Data!C2:C21),ROUND(CORREL(FILTER(x,keep),FILTER(y,keep)),3))',['=ROUND(CORREL(FILTER(Data!B2:B21,ISNUMBER(Data!B2:B21)*ISNUMBER(Data!C2:C21)),FILTER(Data!C2:C21,ISNUMBER(Data!B2:B21)*ISNUMBER(Data!C2:C21))),3)'],['The same complete-pair rows must be retained in both arrays.','Build ISNUMBER(X)*ISNUMBER(Y) on the original source ranges, then use it in both FILTER calls.','=LET(x,Data!B2:B21,y,Data!C2:C21,keep,____,ROUND(CORREL(FILTER(x,keep),FILTER(y,keep)),3))'],['CORREL','FILTER','ISNUMBER','ROUND']);
  }

  r=randomFor(`reinforcement-v1-level-10-variant-${v}`);
  rows=Array.from({length:20},(_,i)=>[`CP${v}-${i+1}`,i===2?'':i===4?0:i===6?-3:r.int(1,45),i===7?'':i===9?0:r.int(125,995)/100]);
  add(10,v,`Build guarded line revenue ${v}`,'A fictitious sales register contains sales and returns. Negative quantity is an allowed return; a zero price is an allowed free item. A missing quantity or price requires review of that line.',
   {intro:'Combine named inputs, type checks and a guarded calculation. LET makes quantity and price readable. ISNUMBER distinguishes valid numeric zero from missing input. AND requires both inputs; IF returns Missing before arithmetic. ROUND applies only to valid line revenue.',formulas:[formula('LET','=LET(name1, name_value1, [name2, name_value2], ..., calculation)','Name each input locally, then return the guarded calculation.','=LET(q,3,p,2.5,q*p)',7.5),formula('AND','=AND(logical1, [logical2], ...)','All supplied conditions must be TRUE. Optional conditions add requirements.','=AND(ISNUMBER(0),ISNUMBER(4))',true),formula('IF','=IF(logical_test, value_if_true, [value_if_false])','Test completeness before multiplying. Return the appropriate result branch.','=IF(ISNUMBER(""),7,"Missing")','Missing')]},
   [column('Order_line','Unique independent order-line identifier.'),column('Quantity_units','Numeric units; negative is a return, zero is allowed, blank is missing.'),column('Unit_price_CAD','Numeric CAD per unit; zero is allowed, blank is missing.')],rows,
   'For each row, return Quantity_units × Unit_price_CAD rounded to two decimals when both inputs are numeric. Otherwise return Missing. Preserve negative returns, numeric zero and every independent record in source order. Do not turn blanks into zero, deduplicate or take absolute values. Enter at B2 and fill down through B21. Practice combining at least four Excel functions.',rows.map(x=>numeric(x[1])&&numeric(x[2])?round(x[1]*x[2]):'Missing'),
   '=LET(q,Data!B2,p,Data!C2,IF(AND(ISNUMBER(Data!B2),ISNUMBER(Data!C2)),ROUND(q*p,2),"Missing")) [fill down through Answers!B21]',['=IF(AND(ISNUMBER(Data!B2),ISNUMBER(Data!C2)),ROUND(PRODUCT(Data!B2,Data!C2),2),"Missing") [fill down through Answers!B21]'],['Validate both original source cells before multiplying; zero and negative quantities remain numeric.','Combine LET, ISNUMBER, AND, IF and ROUND; apply type checks directly to the original cells.','=LET(q,Data!B2,p,Data!C2,IF(AND(____,____),ROUND(q*p,2),"Missing"))'],['LET','ISNUMBER','AND','IF','ROUND']);
 }
 return drills;
}

export function learningCatalog(drills){
 return {version:1,diagnostic:{id:'placement-v1',title:'Find your next Excel practice',questions:diagnosticQuestions.map(({private:unused,...question})=>question)},skills:names.map((title,i)=>({id:`level-${i+1}`,level:i+1,title,corePackageId:`L${i+1}-A1`,drills:drills.filter(d=>d.level===i+1).map(({id,title})=>({id,title}))}))};
}
