// Build-only curriculum. Models, hints and expected outputs never enter the publish directory.
const sum=(rows,col)=>rows.reduce((n,r)=>n+(typeof r[col]==='number'?r[col]:0),0);
const round=(n,d=2)=>Math.round((n+Number.EPSILON)*10**d)/10**d;
const mean=a=>a.reduce((n,v)=>n+v,0)/a.length;
const sd=a=>Math.sqrt(a.reduce((n,v)=>n+(v-mean(a))**2,0)/(a.length-1));
const pct=(a,p)=>{const b=[...a].sort((x,y)=>x-y),i=(b.length-1)*p,k=Math.floor(i);return b[k]+(b[Math.min(k+1,b.length-1)]-b[k])*(i-k);};
const corr=(a,b)=>{const x=mean(a),y=mean(b);return a.reduce((n,v,i)=>n+(v-x)*(b[i]-y),0)/Math.sqrt(a.reduce((n,v)=>n+(v-x)**2,0)*b.reduce((n,v)=>n+(v-y)**2,0));};
const vec=a=>a.map(v=>[v]),norm=s=>s.trim().toUpperCase(),numeric=v=>typeof v==='number';
const distinct=rows=>[...new Map(rows.map(r=>[JSON.stringify(r),r])).values()];
const letter=n=>String.fromCharCode(64+n);
const sheet=(name,headers,rows)=>({name,headers,rows});
const F={
 SUMPRODUCT:['Sum aligned products.','=SUMPRODUCT(array1, [array2], ...)','array1 is the first bounded numeric array; optional arrays have identical dimensions and multiply elementwise.','=SUMPRODUCT({2,3},{4,5})',23,'Calculate weighted yield or condition counts.','Align rows. Coerce Boolean conditions with --; distinguish blanks from measured zero.'],
 SUM:['Add numeric inputs.','=SUM(number1, [number2], ...)','number1 supplies a number or range; optional arguments add inputs.','=SUM(4,7)',11,'Reconcile a source total.','Do not add subtotals to their own detail.'],
 XMATCH:['Find a relative position.','=XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])','Supply key and one-dimensional range; match mode 0 exact, -1 next smaller, 1 next larger, 2 wildcard; search 1 forward, -1 reverse, 2 ascending binary, -2 descending binary.','=XMATCH("B",{"A","B"},0,1)',2,'Match both dimensions of a specification.','Binary modes require sorted keys. A first match does not prove uniqueness.'],
 XLOOKUP:['Return a value for a key.','=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])','Supply key, aligned lookup and return arrays, optional missing result; match mode 0 exact, -1 next smaller, 1 next larger, 2 wildcard; search 1 forward, -1 reverse, 2/-2 sorted binary.','=XLOOKUP("B",{"A","B"},{12,18},"Missing",0,1)',18,'Retrieve an unambiguous order.','Count duplicate matches before selecting a value.'],
 ISNUMBER:['Test the stored value type.','=ISNUMBER(value)','value is the cell or expression to test.','=ISNUMBER(0)',true,'Keep measured zero and exclude blank results.','A numeric-looking text string is not a number.'],
 IFNA:['Handle an unavailable exact match.','=IFNA(value, value_if_na)','value is the expression checked for #N/A; value_if_na is the result to return only for that error.','=IFNA(XMATCH("Absent",{"A","B"},0),"Missing")','Missing','Label an absent grade or orientation without hiding other formula errors.','Unlike IFERROR, IFNA handles only #N/A; errors such as #REF! still need correction.'],
 INDEX:['Select a row and column.','=INDEX(array, row_num, [column_num])','array is the source; row_num and optional column_num are positions within it.','=INDEX({7,9;11,13},2,1)',11,'Read a two-dimensional training matrix.','Worksheet row numbers differ from positions within the array.'],
 FILTER:['Select records with a Boolean mask.','=FILTER(array, include, [if_empty])','array is the source; include is an aligned row/column mask; optional if_empty supplies a deliberate fallback.','=FILTER({5;8;2},{TRUE;FALSE;TRUE},"None")','5 then 2','Build a quality exception queue.','Use multiplication for AND and addition for OR; errors in the mask propagate.'],
 SORTBY:['Sort using aligned keys.','=SORTBY(array, by_array1, [sort_order1], [by_array2], [sort_order2], ...)','Supply output and sort keys; optional order is 1 ascending or -1 descending; additional key/order pairs resolve ties.','=SORTBY({"A";"B"},{2;1},1)','B then A','Order exceptions by cost and identifier.','Sort keys must describe the same filtered records.'],
 LET:['Name intermediate expressions.','=LET(name1, name_value1, [name2, name_value2], ..., calculation)','Provide a valid name/value pair, optional further pairs, and the final expression using those names; up to 126 pairs.','=LET(amount,12,fee,3,amount-fee)',9,'Calculate a guarded yield once.','Names cannot collide with cell references; the last argument returns the result.'],
 LAMBDA:['Define a reusable calculation.','=LAMBDA([parameter1, parameter2, ...], calculation)','Optional parameters name inputs (up to 253); calculation returns the result. Call an inline function with arguments or assign it a name in Name Manager.','=LAMBDA(amount,fee,amount-fee)(12,3)',9,'Reuse a margin or orientation-mean rule.','An uncalled inline LAMBDA returns #CALC!; call argument counts must match.'],
 MAP:['Transform corresponding array elements.','=MAP(array1, [array2, ...], lambda)','array1 and optional aligned arrays supply values; the final LAMBDA has one parameter per array and returns one result per position.','=MAP({2;4},LAMBDA(item,item*3))','6 then 12','Apply a reusable margin calculation.','Each call must return one value; mismatched parameters error.'],
 BYROW:['Calculate one result per row.','=BYROW(array, lambda(row))','array supplies rows; lambda receives one row and must return one scalar.','=BYROW({2,4;3,7},LAMBDA(readings,SUM(readings)))','6 then 10','Score repeated sample readings.','Returning multiple cells per row creates #CALC!.'],
 BYCOL:['Calculate one result per column.','=BYCOL(array, lambda(column))','array supplies columns; lambda receives one column and returns one scalar.','=BYCOL({2,4;3,7},LAMBDA(readings,SUM(readings)))','5, 11','Summarize reading positions.','Column summaries and row summaries have different shapes.'],
 SCAN:['Return every accumulated result.','=SCAN([initial_value], array, lambda(accumulator, value, body))','Optional initial_value starts the accumulator; array supplies ordered values; lambda names accumulator and current value, then calculates the next accumulator.','=SCAN(0,{3;5;2},LAMBDA(acc,item,acc+item))','3 then 8 then 10','Track cumulative COPQ after each event.','Input order matters. Credits stay negative unless the rule deliberately excludes them.'],
 REDUCE:['Return a final accumulation.','=REDUCE([initial_value], array, lambda(accumulator, value, body))','Optional initial_value starts the accumulator; array supplies values; lambda names accumulator and current value and returns the next accumulator.','=REDUCE(0,{3;5;2},LAMBDA(acc,item,acc+item))',10,'Total selected costs with a reusable rule.','Start products at 1 and sums at 0. Unlike SCAN, only the final value is returned.'],
 GROUPBY:['Aggregate records by row keys.','=GROUPBY(row_fields, values, function, [field_headers], [total_depth], [sort_order], [filter_array], [field_relationship])','row_fields are grouping columns; values are aligned measures; function aggregates. Headers: 0 none, 1 input hidden, 2 generated, 3 input shown (default auto). Total depth: 0 none, ±1 grand, ±2 subtotals (negative at top; default auto). Sort indices are signed column positions; filter_array is an aligned Boolean mask. Relationship: 0 hierarchy, 1 flat table.','=GROUPBY({"A";"A";"B"},{2;3;7},SUM,0,0,1)','A,5 then B,7','Summarize production batches.','Specify totals and headers explicitly; aggregates combine duplicate keys.'],
 PIVOTBY:['Aggregate across row and column keys.','=PIVOTBY(row_fields, col_fields, values, function, [field_headers], [row_total_depth], [row_sort_order], [col_total_depth], [col_sort_order], [filter_array], [relative_to])','Row/column fields group aligned values; function aggregates. Headers: 0 none, 1 input hidden, 2 generated, 3 input shown (default auto). Row/column total depth: 0 none, ±1 grand, ±2 subtotals (negative at top; default auto). Signed sort indices order axes; filter_array includes rows. For two-argument aggregators, relative_to: 0 column, 1 row, 2 grand, 3 parent column, 4 parent row total.','=DROP(PIVOTBY({"A";"A"},{"L";"T"},{8;6},SUM,0,0,1,0,1),1)','A,8,6','Place Charpy orientations side by side.','Column labels remain part of the pivot result. Define blank and duplicate rules.'],
 COUNT:['Count numeric observations.','=COUNT(value1, [value2], ...)','value1 supplies a value or range; optional arguments add inputs.','=COUNT(0,5,"Missing")',2,'Count numeric replicates before averaging.','Zero counts; text and blanks in references do not.'],
 'STDEV.S':['Estimate sample standard deviation.','=STDEV.S(number1, [number2], ...)','number1 is a numeric sample or range; optional arguments add observations; the denominator is n−1.','=STDEV.S(8,10,12)',2,'Describe observed variation.','At least two numeric values are needed. Sample spread does not prove stability.'],
 'PERCENTILE.INC':['Find an inclusive sample percentile.','=PERCENTILE.INC(array, k)','array supplies numeric observations; k is a proportion from 0 through 1; intermediate positions use linear interpolation.','=PERCENTILE.INC({4;8;12},0.75)',10,'Summarize a high-end thickness value.','Use 0.9 for the 90th percentile, not 90.'],
 CORREL:['Measure linear association.','=CORREL(array1, array2)','Supply aligned numeric pairs; both arrays require equal length and nonzero variation.','=CORREL({1;2;3},{3;6;9})',1,'Explore paired operating variables.','Filter both arrays with the same completeness mask. Correlation does not establish causation.'],
 AVERAGE:['Calculate the arithmetic mean.','=AVERAGE(number1, [number2], ...)','number1 supplies a value/range; optional arguments add observations.','=AVERAGE(8,10,12)',10,'Estimate a training sample mean.','Blanks are excluded and numeric zero is included.'],
 ROUND:['Round to a stated precision.','=ROUND(number, num_digits)','number is the result; num_digits is decimal places (negative for places left of the decimal point).','=ROUND(12.346,2)',12.35,'Present currency or replicate means.','Round at the specified stage; display formatting does not change the value.']
};
export const ORIENTATION_IDS=Object.freeze(['L7-A3','L8-A5','L9-A2','L10-A5']);
function charpy(r,prefix,pairs=10){const perHeat=pairs===12?6:5;return Array.from({length:pairs*4},(_,i)=>{const key=Math.floor(i/4),orientation=i%4<2?' LPA ':'twa';return[String(key%perHeat+1).padStart(3,'0'),`${prefix}-H${Math.floor(key/perHeat)+1}`,orientation,key===0&&i%4>=2?'':i===0||i===8||i===9?0:i===5?'':i===12||i===13?27:i===14||i===15?20:r.int(16,48)];});}
function orientationMeans(rows,keys){return keys.map(([sample,heat])=>['LPA','TWA'].map(o=>{const a=rows.filter(r=>r[0]===sample&&r[1]===heat&&norm(r[2])===o&&numeric(r[3])).map(r=>r[3]);return a.length?round(mean(a)):'Missing';}));}
export function phase3Packages(randomFor){
 const packages=[];
 function add(level,assignment,title,scenario,names,intro,combine,defs,makeRows,makeTasks,makeSheets=()=>[]){
  const id=`L${level}-A${assignment}`,rows=makeRows(randomFor(id)),sheets=makeSheets(rows),columns=defs.map(([name,description])=>({name,description}));let cursor=2;
  const T=(prompt,answer,model,formulas,hints,alternatives=[],note='')=>{const matrix=Array.isArray(answer)?(Array.isArray(answer[0])?answer:vec(answer)):null,h=matrix?.length||1,w=matrix?.[0]?.length||1,start=cursor;cursor+=h+2;const output=`Answers!B${start}`+(matrix?`:${letter(w+1)}${start+h-1}`:'');return{public:{prompt,output,type:matrix?'array':typeof answer==='number'?'number':'text',formulas},private:{answer:matrix||answer,model,tolerance:1e-6,orderInsensitive:false,hints,alternatives,...(note?{note}:{})}};};
  const specs=makeTasks(rows,T,sheets);specs.forEach((t,i)=>t.public.id=t.private.id=i===4?'bonus':`t${i+1}`);
  const lesson={intro,functions:names.map(name=>{const[purpose,syntax,args,example,result,useCase,mistake]=F[name];return{name,purpose,syntax,arguments:args,example,result,useCase,mistake};}),combine};
  packages.push({id,level,assignment,title,formulas:names,minutes:45+(level-7)*10+assignment*5,scenario,lesson,columns,rows,parameters:[],sheets,...(ORIENTATION_IDS.includes(id)?{orientationReshape:true}:{}),tasks:specs.slice(0,4).map(t=>t.public),bonus:specs[4].public,private:{version:1,tasks:specs.slice(0,4).map(t=>({...t.private,prompt:t.public.prompt,output:t.public.output})),bonus:{...specs[4].private,prompt:specs[4].public.prompt,output:specs[4].public.output}}});
 }
 const H=(rule,technique,skeleton)=>[rule,technique,skeleton],first=rows=>rows.slice(0,8);

 add(7,1,'Calculate weighted production rates','Avenro Rolling records 40 fictitious production batches. Yield is good units divided by inspected units, expressed as a percentage number. Batches are independent records; repeated shift names aggregate and all input quantities are numeric.',['SUMPRODUCT','SUM'],
  'A weighted result gives each batch its appropriate denominator weight. Multiplying aligned arrays is useful for quantity-times-rate totals and Boolean selection.',
  'Review SUM and ROUND. Multiply a Boolean mask by numeric quantities to select rows. Compare a ratio of totals with an unweighted average: they answer different questions. Any valid Excel formula is accepted; submit unrounded results unless rounding is requested.',
  [['Batch_no','Unique invented batch identifier.'],['Shift','Day or Night; repeats are separate batches.'],['Inspected_units','Positive count inspected.'],['Good_units','Accepted count under a fictitious training rule.'],['Hours_h','Positive batch operating hours.'],['Rate_CAD_per_h','Fictitious operating cost per hour, CAD/h.']],
  r=>Array.from({length:40},(_,i)=>{const n=r.int(80,600);return[`AV-${i+1}`,i%2?'Night':'Day',n,n-r.int(0,25),r.int(10,45)/10,r.int(90,140)];}),
  (rows,T)=>[
   T('Calculate pooled good yield: 100 × total Good_units / total Inspected_units across all 40 batches.',100*sum(rows,3)/sum(rows,2),'=SUM(Data!D2:D41)/SUM(Data!C2:C41)*100',['SUM'],H('Weight batches by inspected units.','Divide the two source totals.','=SUM(____)/SUM(____)*100'),['=SUMPRODUCT(Data!D2:D41)/SUMPRODUCT(Data!C2:C41)*100']),
   T('Calculate total operating cost as the sum of each batch’s Hours_h × Rate_CAD_per_h. Submit unrounded CAD.',rows.reduce((n,r)=>n+r[4]*r[5],0),'=SUMPRODUCT(Data!E2:E41,Data!F2:F41)',['SUMPRODUCT'],H('Every batch has its own hours and rate.','Use aligned SUMPRODUCT arrays.','=SUMPRODUCT(____,Data!F2:F41)')),
   T('Calculate total Good_units for Day batches only.',sum(rows.filter(r=>r[1]==='Day'),3),'=SUMPRODUCT(--(Data!B2:B41="Day"),Data!D2:D41)',['SUMPRODUCT'],H('Exclude Night batches but retain repeated Day records.','Multiply the Day mask by good units.','=SUMPRODUCT(--(____="Day"),____)'),['=SUMIFS(Data!D2:D41,Data!B2:B41,"Day")']),
   T('Calculate Day operating cost per Day good unit: selected hours × rates / selected good units. Submit unrounded CAD/unit.',rows.filter(r=>r[1]==='Day').reduce((n,r)=>n+r[4]*r[5],0)/sum(rows.filter(r=>r[1]==='Day'),3),'=SUMPRODUCT(--(Data!B2:B41="Day"),Data!E2:E41,Data!F2:F41)/SUMPRODUCT(--(Data!B2:B41="Day"),Data!D2:D41)',['SUMPRODUCT'],H('Use the same Day population in numerator and denominator.','Divide two conditional SUMPRODUCT totals.','=SUMPRODUCT(____)/SUMPRODUCT(____)')),
   T('Review ROUND: return total good units per total operating hour, rounded to two decimals.',round(sum(rows,3)/sum(rows,4)),'=ROUND(SUM(Data!D2:D41)/SUM(Data!E2:E41),2)',['ROUND','SUM'],H('This is pooled production rate, not mean batch rate.','Divide totals then ROUND.','=ROUND(SUM(____)/SUM(____),2)'))
  ]);

 add(7,2,'Build a multi-criteria order lookup','Belvori Sales has 36 fictitious order lines. Customer and Product jointly identify an order request only when exactly one line matches; duplicate combinations are ambiguous. Requests includes unique, duplicate and absent combinations.',['XMATCH','XLOOKUP'],
  'Combining exact conditions produces a lookup mask. A value of one means all requested conditions match, but several ones still mean an ambiguous request.',
  'Review COUNTIFS before a lookup. Use XMATCH(1,mask,0) for a position or XLOOKUP(1,mask,return_range) for a value. Do not silently pick the first duplicate. Any valid Excel formula is accepted.',
  [['Order_no','Unique invented order identifier.'],['Customer','Customer key.'],['Product','Product key; customer/product may repeat.'],['Units','Positive ordered units.'],['Price_CAD','Price per unit, CAD.']],
  r=>Array.from({length:36},(_,i)=>[`BV-${i+1}`,i<6?['C1','C2','C2','C3','C4','C5'][i]:`C${6+Math.floor((i-6)/3)}`,i<6?['P1','P2','P2','P3','P4','P5'][i]:`P${i%3+1}`,r.int(5,80),r.int(12,90)]),
  (rows,T,s)=>{const req=s[0].rows,matches=q=>rows.filter(r=>r[1]===q[0]&&r[2]===q[1]);return[
   T('For all six Requests rows, return matching-line counts as a 6 × 1 column in request order.',req.map(q=>matches(q).length),'=COUNTIFS(Data!$B$2:$B$37,Requests!A2,Data!$C$2:$C$37,Requests!B2)',['COUNTIFS'],H('Count both matching conditions and retain duplicates.','Use COUNTIFS with two criteria.','=COUNTIFS(____,Requests!A2,____,Requests!B2)'),[],'Fill down for all six requests.'),
   T('For all six requests, return Order_no only for exactly one match; return Review key for zero or multiple matches.',req.map(q=>matches(q).length===1?matches(q)[0][0]:'Review key'),'=IF(COUNTIFS(Data!$B$2:$B$37,Requests!A2,Data!$C$2:$C$37,Requests!B2)=1,XLOOKUP(1,(Data!$B$2:$B$37=Requests!A2)*(Data!$C$2:$C$37=Requests!B2),Data!$A$2:$A$37),"Review key")',['IF','XLOOKUP','COUNTIFS'],H('An absent or duplicate combination needs review.','Guard the Boolean XLOOKUP with match count.','=IF(COUNTIFS(____)=____,XLOOKUP(1,____,____),"Review key")'),[],'Fill down in request order.'),
   T('Return the first request’s 1-based matching position within Data rows, using both conditions.',1,'=XMATCH(1,(Data!B2:B37=Requests!A2)*(Data!C2:C37=Requests!B2),0)',['XMATCH'],H('The position is relative to data rows, excluding the header.','Match one in the combined mask.','=XMATCH(1,____,0)'),['=MATCH(1,(Data!B2:B37=Requests!A2)*(Data!C2:C37=Requests!B2),0)']),
   T('Return all complete Data rows matching the second request, in source order. Keep both duplicate lines (2 × 5).',matches(req[1]),'=FILTER(Data!A2:E37,(Data!B2:B37=Requests!A3)*(Data!C2:C37=Requests!B3),"None")',['FILTER'],H('Both matching lines belong in the report.','Use a two-condition FILTER.','=FILTER(Data!A2:E37,____,"None")')),
   T('Review SUMIFS: total Units across every line matching the second request.',sum(matches(req[1]),3),'=SUMIFS(Data!D2:D37,Data!B2:B37,Requests!A3,Data!C2:C37,Requests!B3)',['SUMIFS'],H('Aggregate duplicate lines; do not select only one.','Use SUMIFS with both keys.','=SUMIFS(____,____,Requests!A3,____,Requests!B3)'))
  ];},()=>[sheet('Requests',['Customer','Product'],[['C1','P1'],['C2','P2'],['C3','P3'],['C99','P1'],['C4','P4'],['C5','P5']])]);

 add(7,3,'Audit Charpy arrays by sample and heat','Cervani Testworks has 40 fictitious Charpy measurements for ten sample/heat pairs. Normalize Orientation with TRIM and UPPER; average numeric duplicate measurements for each pair/orientation, rounded to two decimals. No numeric measurement means Missing; measured zero remains numeric.',['SUMPRODUCT','ISNUMBER'],
  'An array mask can require both identifiers, a normalized orientation and a numeric measurement. Counting that population first prevents a blank group from masquerading as zero energy.',
  'Review TRIM, UPPER, AVERAGEIFS and HSTACK. Keys provides the unique sample/heat scaffold in source order. Normalize orientation inside the mask; both keys are always required. Any valid formula is accepted. Keep leading-zero sample IDs as text.',
  [['sample_no','Text sample identifier; reused across heats.'],['heat_no','Invented heat identifier.'],['Orientation','LPA/TWA with deliberate case and outer-space differences.'],['Energy_J','Numeric energy in joules; blank means unmeasured, zero is measured.']],r=>charpy(r,'CV'),
  (rows,T,s)=>{const keys=s[0].rows,counts=keys.map(k=>['LPA','TWA'].map(o=>rows.filter(r=>r[0]===k[0]&&r[1]===k[1]&&norm(r[2])===o&&numeric(r[3])).length)),values=orientationMeans(rows,keys);return[
   T('Normalize Orientation for the first eight source records, as an 8 × 1 column in source order.',first(rows).map(r=>norm(r[2])),'=UPPER(TRIM(Data!C2:C9))',['UPPER','TRIM'],H('Remove outer spaces and standardize letter case.','Nest TRIM inside UPPER.','=UPPER(____(Data!C2:C9))')),
   T('In Keys order, return numeric replicate counts for LPA then TWA (10 × 2). Blank energy does not count; zero does.',counts,'=SUMPRODUCT(--(Data!$A$2:$A$41=Keys!$A2),--(Data!$B$2:$B$41=Keys!$B2),--(UPPER(TRIM(Data!$C$2:$C$41))="LPA"),--ISNUMBER(Data!$D$2:$D$41))',['SUMPRODUCT','ISNUMBER'],H('Use sample, heat, orientation and numeric status together.','SUMPRODUCT combines four masks.','=SUMPRODUCT(--(____),--(____),--(____),--ISNUMBER(____))'),[],'Fill down; repeat for TWA in the second output column.'),
   T('In Keys order, return LPA and TWA numeric means, rounded to two decimals (10 × 2). Use Missing when a count is zero.',values,'=IF(SUMPRODUCT(--(Data!$A$2:$A$41=Keys!$A2),--(Data!$B$2:$B$41=Keys!$B2),--(UPPER(TRIM(Data!$C$2:$C$41))="LPA"),--ISNUMBER(Data!$D$2:$D$41))=0,"Missing",ROUND(AVERAGE(FILTER(Data!$D$2:$D$41,(Data!$A$2:$A$41=Keys!$A2)*(Data!$B$2:$B$41=Keys!$B2)*(UPPER(TRIM(Data!$C$2:$C$41))="LPA")*ISNUMBER(Data!$D$2:$D$41))),2))',['IF','SUMPRODUCT','FILTER','AVERAGE','ROUND'],H('Average all numeric replicates and retain missing groups.','Guard a numeric-only FILTER before averaging.','=IF(SUMPRODUCT(____)=0,"Missing",ROUND(AVERAGE(FILTER(____,____)),2))'),[],'Fill down; repeat with TWA for the second column.'),
   T('Assemble sample_no, heat_no, LPA_mean_J, TWA_mean_J in Keys order, without headers (10 × 4). Preserve text sample IDs.',keys.map((k,i)=>[...k,...values[i]]),'=HSTACK(Keys!A2:B11,Answers!B24:C33)',['HSTACK'],H('Keep both identifiers beside the two means.','HSTACK the key scaffold and task-3 results.','=HSTACK(____,____)'),['=CHOOSE({1,2,3,4},Keys!A2:A11,Keys!B2:B11,Answers!B24:B33,Answers!C24:C33)']),
   T('Review COUNTIFS: count Missing orientation cells in the task-3 result only.',values.flat().filter(v=>v==='Missing').length,'=COUNTIFS(Answers!B24:C33,"Missing")',['COUNTIFS'],H('Count orientation cells rather than raw blank replicates.','Apply COUNTIFS to task 3.','=COUNTIFS(____,"Missing")'))
  ];},rows=>[sheet('Keys',['sample_no','heat_no'],distinct(rows.map(r=>r.slice(0,2))))]);

 add(7,4,'Match specifications in two dimensions','Dorlavi Inspection has 36 fictitious Charpy records and a grade-by-orientation Matrix. A blank or unlisted grade/orientation returns Missing. The matrix limits are training assumptions; a measured energy at or above its unique limit is Pass.',['XMATCH','INDEX','IFNA'],
  'Two-way matching selects a row key and a column key independently. Exact matching should find named dimensions rather than relying on their current order.',
  'IFNA labels an unavailable exact match while leaving other formula errors visible. Review IF and COUNTIFS. Place two exact XMATCH positions inside INDEX. Check energy availability before comparing; a missing measurement must remain Missing. Any valid formula is accepted.',
  [['Sample_no','Unique invented sample identifier.'],['Grade','G1–G4 or deliberately unknown.'],['Orientation','LPA/TWA or deliberately unknown.'],['Energy_J','Numeric joules or blank unmeasured result.']],r=>Array.from({length:36},(_,i)=>[`DV-${i+1}`,i===4?'GX':`G${i%4+1}`,i===5?'Unknown':i%2?'TWA':'LPA',i===6?'':i===0?27:r.int(15,54)]),
  (rows,T,s)=>{const get=r=>{const a=s[0].rows.find(x=>x[0]===r[1]);return a&&['LPA','TWA'].includes(r[2])?a[r[2]==='LPA'?1:2]:'Missing';},status=r=>get(r)==='Missing'||!numeric(r[3])?'Missing':r[3]>=get(r)?'Pass':'Hold';return[
   T('For the first eight records, return the exact grade position within Matrix data rows, or Missing for an absent grade.',first(rows).map(r=>['G1','G2','G3','G4'].includes(r[1])?+r[1].slice(1):'Missing'),'=IFNA(XMATCH(Data!B2,Matrix!$A$2:$A$5,0),"Missing")',['XMATCH','IFNA'],H('Unknown grades have no position.','Use exact XMATCH with IFNA.','=IFNA(XMATCH(____,____,0),"Missing")'),[],'Fill down eight rows.'),
   T('For the first eight records, return the matched energy limit in joules, or Missing if either dimension is absent.',first(rows).map(get),'=IFNA(INDEX(Matrix!$B$2:$C$5,XMATCH(Data!B2,Matrix!$A$2:$A$5,0),XMATCH(Data!C2,Matrix!$B$1:$C$1,0)),"Missing")',['INDEX','XMATCH','IFNA'],H('Match grade to rows and orientation to columns.','Put two XMATCH expressions inside INDEX.','=IFNA(INDEX(____,XMATCH(____),XMATCH(____)),"Missing")'),['=IFNA(INDEX(Matrix!$B$2:$C$5,MATCH(Data!B2,Matrix!$A$2:$A$5,0),MATCH(Data!C2,Matrix!$B$1:$C$1,0)),"Missing")'],'Fill down eight rows.'),
   T('For the first eight records, return Pass when measured energy is at least the matched limit, Hold below it, or Missing for absent energy/dimensions.',first(rows).map(status),'=IF(OR(Answers!B12="Missing",NOT(ISNUMBER(Data!D2))),"Missing",IF(Data!D2>=Answers!B12,"Pass","Hold"))',['IF','ISNUMBER'],H('Equality passes; absent energy does not become zero.','Guard the task-2 limit and energy before IF.','=IF(OR(____),"Missing",IF(____,"Pass","Hold"))'),[],'Use the corresponding task-2 limit; fill down eight rows.'),
   T('Count Missing statuses in the first eight task-3 outputs.',first(rows).filter(r=>status(r)==='Missing').length,'=COUNTIFS(Answers!B22:B29,"Missing")',['COUNTIFS'],H('Count absent input or dimension statuses in the requested eight rows.','Review COUNTIFS on task 3.','=COUNTIFS(____,"Missing")')),
   T('Review INDEX: return the Matrix requirement for G4 and TWA.',35,'=INDEX(Matrix!B2:C5,4,2)',['INDEX'],H('G4 is the fourth matrix data row; TWA is the second measure column.','Use relative INDEX positions.','=INDEX(____,4,2)'))
  ];},()=>[sheet('Matrix',['Grade','LPA','TWA'],[['G1',27,20],['G2',34,25],['G3',40,30],['G4',47,35]])]);

 add(7,5,'Filter a full quality exception report','Elvani Pipeworks has 60 fictitious inspections. Training thickness is 9.5–10.5 mm inclusive and strength is at least 450 MPa. Blank strength means Review; measured failures mean Hold; all others are Pass. Repeat heats retain every inspection.',['FILTER','SORTBY'],
  'A compound filter can retain several kinds of exception while preserving source records. Sort the resulting report using keys taken from the same filtered population.',
  'Review IF, ISNUMBER, CHOOSECOLS and SUMIFS. Use a nested FILTER to select one heat from a broader exception set. Any valid formula is accepted; results have no headers and use the order specified by each task.',
  [['Inspection_no','Unique padded identifier for stable text sorting.'],['Heat_no','Repeated invented heat key.'],['Thickness_mm','Numeric wall thickness, mm.'],['Strength_MPa','Numeric tensile strength or blank unmeasured result.'],['Rework_CAD','Fictitious potential rework cost, CAD.']],r=>Array.from({length:60},(_,i)=>[`EV-${String(i+1).padStart(3,'0')}`,`EV-H${i%5+1}`,i===0?9.5:i===1?10.5:r.int(93,107)/10,i%11===0?'':i===1?450:r.int(425,495),r.int(100,800)]),
  (rows,T)=>{const status=r=>!numeric(r[3])?'Review':r[2]<9.5||r[2]>10.5||r[3]<450?'Hold':'Pass',exceptions=rows.filter(r=>status(r)!=='Pass'),target=exceptions.filter(r=>r[1]==='EV-H2');return[
   T('For every source record, return Pass, Hold or Review (60 × 1), in source order.',rows.map(status),'=IF(NOT(ISNUMBER(Data!D2)),"Review",IF(OR(Data!C2<9.5,Data!C2>10.5,Data!D2<450),"Hold","Pass"))',['IF','ISNUMBER'],H('Blank strength is Review and exact limits are inclusive.','Guard missing strength before the failure conditions.','=IF(____,"Review",IF(OR(____),"Hold","Pass"))'),[],'Fill down all 60 rows.'),
   T('Return every full Data row whose task-1 status is Hold or Review, sorted by Inspection_no ascending. Keep repeated heats.',exceptions,'=SORTBY(FILTER(Data!A2:E61,Answers!B2:B61<>"Pass"),FILTER(Data!A2:A61,Answers!B2:B61<>"Pass"),1)',['FILTER','SORTBY'],H('Retain every non-Pass record.','Filter output and sort key with the same mask.','=SORTBY(FILTER(____,____),FILTER(____,____),1)')),
   T('Calculate total Rework_CAD for Hold records only. Review costs are pending and excluded.',sum(rows.filter(r=>status(r)==='Hold'),4),'=SUMIFS(Data!E2:E61,Answers!B2:B61,"Hold")',['SUMIFS'],H('Review and Pass costs do not belong in the Hold total.','Review SUMIFS using task-1 statuses.','=SUMIFS(____,____,"Hold")')),
   T('From the full exception population, return full Data rows for heat EV-H2 in source order. Use nested filtering; any equivalent formula is accepted.',target,'=FILTER(FILTER(Data!A2:E61,Answers!B2:B61<>"Pass"),FILTER(Data!B2:B61,Answers!B2:B61<>"Pass")="EV-H2","None")',['FILTER'],H('Both exception status and heat must match.','Filter the exceptions first, then their aligned heat key.','=FILTER(FILTER(____,____),FILTER(____,____)="EV-H2","None")'),['=FILTER(Data!A2:E61,(Answers!B2:B61<>"Pass")*(Data!B2:B61="EV-H2"),"None")']),
   T('Review COUNTIFS: count task-1 Review records.',rows.filter(r=>status(r)==='Review').length,'=COUNTIFS(Answers!B2:B61,"Review")',['COUNTIFS'],H('Count missing-strength reviews, not all exceptions.','Use COUNTIFS on task 1.','=COUNTIFS(____,"Review")'))
  ];});

 add(8,1,'Name intermediate yield calculations','Felvori Meltworks records 44 fictitious heats with charged and tapped tonnes. Blank tapped mass is unmeasured; complete heats have a positive charged mass. Pooled yield includes only complete heats, and melt loss costs 620 CAD per lost tonne.',['LET','ISNUMBER'],
  'Names inside LET make a repeated expression easier to audit. A completeness mask should govern both sides of a pooled ratio so incomplete records cannot distort it.',
  'Review FILTER, SORTBY and ROUND. Name the population and its quantities once, then return the result. Missing results remain Missing, not zero loss. Any valid formula is accepted. Pooled yield is a percentage number.',
  [['Heat_no','Unique invented heat key.'],['Charged_t','Positive charged mass, metric tonnes.'],['Tapped_t','Tapped metric tonnes, or blank unmeasured mass.'],['Tap_min','Numeric process duration, minutes.']],r=>Array.from({length:44},(_,i)=>{const charge=r.int(90,125);return[`FV-${String(i+1).padStart(3,'0')}`,charge,i%9===0?'':round(charge*r.int(90,97)/100),r.int(45,80)];}),
  (rows,T)=>{const valid=rows.filter(r=>numeric(r[2])),loss=r=>numeric(r[2])?round(r[1]-r[2]):'Missing',report=valid.map(r=>[r[0],round(r[1]-r[2]),round(r[2]/r[1]*100)]).sort((a,b)=>b[2]-a[2]||a[0].localeCompare(b[0]));return[
   T('For the first eight heats, return Charged_t − Tapped_t rounded to two decimals, or Missing for blank tapped mass.',first(rows).map(loss),'=LET(charged,Data!B2,tapped,Data!C2,IF(ISNUMBER(Data!C2),ROUND(charged-tapped,2),"Missing"))',['LET','ISNUMBER','IF','ROUND'],H('An unmeasured tapped mass is not a zero value.','Name both quantities, but apply ISNUMBER directly to the original tapped-mass cell.','=LET(charged,____,tapped,____,IF(____,ROUND(charged-tapped,2),"Missing"))'),[],'Fill down eight rows.'),
   T('Return pooled yield for complete heats only: 100 × selected tapped tonnes / selected charged tonnes. Submit unrounded.',sum(valid,2)/sum(valid,1)*100,'=LET(ok,ISNUMBER(Data!C2:C45),SUM(FILTER(Data!C2:C45,ok))/SUM(FILTER(Data!B2:B45,ok))*100)',['LET','FILTER','SUM'],H('The denominator must exclude the same incomplete heats as the numerator.','Reuse one completeness mask in both FILTER calls.','=LET(ok,____,SUM(FILTER(____,ok))/SUM(FILTER(____,ok))*100)'),['=SUMPRODUCT(Data!C2:C45)/SUMPRODUCT(--ISNUMBER(Data!C2:C45),Data!B2:B45)*100']),
   T('Return Heat_no, loss_t and yield_pct for all complete heats. Round both metrics to two decimals; sort by rounded yield descending, then Heat_no ascending. No headers.',report,'=LET(valid,FILTER(Data!A2:C45,ISNUMBER(Data!C2:C45)),charged,CHOOSECOLS(valid,2),tapped,CHOOSECOLS(valid,3),yield,ROUND(tapped/charged*100,2),SORTBY(HSTACK(CHOOSECOLS(valid,1),ROUND(charged-tapped,2),yield),yield,-1,CHOOSECOLS(valid,1),1))',['LET','FILTER','HSTACK','SORTBY','ROUND'],H('Sort the displayed rounded yield and resolve ties by heat.','Name the filtered data and aligned sort keys.','=LET(valid,FILTER(____,____),charged,____,tapped,____,yield,____,SORTBY(HSTACK(____),yield,-1,____,1))')),
   T('Calculate complete-heat melt-loss cost: 620 × total charged-minus-tapped tonnes. Round the final CAD total to cents.',round((sum(valid,1)-sum(valid,2))*620),'=LET(ok,ISNUMBER(Data!C2:C45),ROUND((SUM(FILTER(Data!B2:B45,ok))-SUM(FILTER(Data!C2:C45,ok)))*620,2))',['LET','FILTER','SUM','ROUND'],H('Only complete heats have a known melt loss.','Use the same mask for charged and tapped totals.','=LET(ok,____,ROUND((SUM(FILTER(____,ok))-SUM(FILTER(____,ok)))*620,2))')),
   T('Review COUNT: count numeric tapped-mass observations.',valid.length,'=COUNT(Data!C2:C45)',['COUNT'],H('Exclude unmeasured cells.','Use COUNT on tapped mass.','=COUNT(____)'))
  ];});

 add(8,2,'Create a reusable margin formula','Gorvani Sales records 40 fictitious product lines with revenue and cost in CAD. Blank cost means Missing; zero revenue means Zero revenue, unless cost is missing first. Otherwise margin is 100 × (revenue − cost) / revenue.',['LAMBDA','MAP'],
  'A LAMBDA captures a rule; MAP applies that rule to corresponding values. State exception precedence before reusing a calculation across a whole column.',
  'Review IF, ISNUMBER and ROUND. Name revenue, cost and costKnown parameters; compute costKnown with ISNUMBER on the original source before MAP can coerce a blank. Call the function inline or define MarginPct in Name Manager. Missing cost takes precedence over zero revenue. Any valid formula is accepted; margin is a percentage number.',
  [['Line_no','Unique invented line identifier.'],['Revenue_CAD','Nonnegative revenue, CAD; zero is valid.'],['Cost_CAD','Numeric cost in CAD, or blank unknown cost.']],r=>Array.from({length:40},(_,i)=>[`GV-${i+1}`,i===1||i===4?0:r.int(400,2500),i===4||i%13===0?'':r.int(300,1800)]),
  (rows,T)=>{const margin=r=>!numeric(r[2])?'Missing':r[1]===0?'Zero revenue':round((r[1]-r[2])/r[1]*100),fn='LAMBDA(revenue,cost,costKnown,IF(NOT(costKnown),"Missing",IF(revenue=0,"Zero revenue",ROUND((revenue-cost)/revenue*100,2))))';return[
   T('Call a reusable margin calculation for the second source line. Return a percentage rounded to two decimals or the stated exception label.',margin(rows[1]),`=${fn}(Data!B3,Data!C3,ISNUMBER(Data!C3))`,['LAMBDA','IF','ISNUMBER'],H('The second row has valid cost and zero revenue.','Handle missing cost before the zero denominator.','=LAMBDA(revenue,cost,costKnown,IF(____,"Missing",IF(____,"Zero revenue",____)))(Data!B3,Data!C3,ISNUMBER(Data!C3))')),
   T('Return margins for the first eight source lines (8 × 1), with the stated rounding and exception precedence.',first(rows).map(margin),`=MAP(Data!B2:B9,Data!C2:C9,ISNUMBER(Data!C2:C9),${fn})`,['MAP','LAMBDA'],H('Map each revenue to its cost and source numeric-status flag.','Pass three aligned arrays and a three-parameter LAMBDA.','=MAP(____,____,ISNUMBER(____),LAMBDA(revenue,cost,costKnown,____))')),
   T('For the first eight lines, return Strong for numeric rounded margin ≥ 20, Thin below 20, or Review for either exception label.',first(rows).map(r=>numeric(margin(r))?margin(r)>=20?'Strong':'Thin':'Review'),'=MAP(Answers!B5:B12,LAMBDA(margin,IF(ISNUMBER(margin),IF(margin>=20,"Strong","Thin"),"Review")))',['MAP','LAMBDA','IF'],H('Classify the rounded margin; labels require Review.','Map task-2 values using ISNUMBER and IF.','=MAP(____,LAMBDA(margin,IF(____,IF(____,"Strong","Thin"),"Review")))')),
   T('Return total known profit across all 40 lines, including zero-revenue lines with numeric cost. Exclude unknown cost. Submit unrounded CAD.',rows.filter(r=>numeric(r[2])).reduce((n,r)=>n+r[1]-r[2],0),'=SUM(MAP(Data!B2:B41,Data!C2:C41,ISNUMBER(Data!C2:C41),LAMBDA(revenue,cost,costKnown,IF(costKnown,revenue-cost,0))))',['SUM','MAP','LAMBDA'],H('Zero revenue can have a known loss; missing cost cannot.','Map only numeric-cost profits before summing.','=SUM(MAP(____,____,ISNUMBER(____),LAMBDA(revenue,cost,costKnown,IF(____,revenue-cost,0))))'),['=SUM(FILTER(Data!B2:B41,ISNUMBER(Data!C2:C41)))-SUM(FILTER(Data!C2:C41,ISNUMBER(Data!C2:C41)))']),
   T('Review COUNTIFS: count Review classifications in the first-eight task-3 results.',first(rows).filter(r=>!numeric(margin(r))).length,'=COUNTIFS(Answers!B15:B22,"Review")',['COUNTIFS'],H('Both missing cost and zero revenue are review classifications.','Count Review in task 3.','=COUNTIFS(____,"Review")'))
  ];});

 add(8,3,'Score repeated readings row by row','Hervali Lab has 40 fictitious samples with three energy readings each. Blank is unmeasured; zero is a measured result. Row minimum and mean are available only when all three readings are numeric; the training pass count is the number of numeric readings ≥ 27 J.',['BYROW','BYCOL'],
  'Row-wise calculations summarize one sample at a time. Column-wise calculations summarize a reading position across samples. Both helpers require a scalar result for each call.',
  'Review COUNT, MIN, AVERAGE, SUM and ROUND. Guard complete-row metrics with COUNT=3. For column means, ignore blanks and retain zeros. Any valid formula is accepted; source order is the output order.',
  [['Sample_no','Unique invented sample key.'],['Reading_1_J','First numeric energy reading, J, or blank.'],['Reading_2_J','Second numeric reading, J, or blank.'],['Reading_3_J','Third numeric reading, J, or blank.']],r=>Array.from({length:40},(_,i)=>[`HV-${i+1}`,i===0?0:r.int(16,48),i%9===0?'':r.int(16,48),i===1?27:r.int(16,48)]),
  (rows,T)=>[
   T('For the first eight samples, return the minimum reading if all three are numeric; otherwise Missing (8 × 1).',first(rows).map(r=>r.slice(1).every(numeric)?Math.min(...r.slice(1)):'Missing'),'=BYROW(IF(ISNUMBER(Data!B2:D9),Data!B2:D9,"Missing"),LAMBDA(readings,IF(COUNT(readings)=3,MIN(readings),"Missing")))',['BYROW','LAMBDA','IF','COUNT','MIN'],H('Incomplete rows need Missing even if other readings are present.','Preserve a text missing marker before testing the numeric count.','=BYROW(IF(ISNUMBER(____),____,"Missing"),LAMBDA(readings,IF(____,MIN(readings),"Missing")))')),
   T('For the first eight samples, return the mean of all three readings rounded to two decimals, or Missing for an incomplete row.',first(rows).map(r=>r.slice(1).every(numeric)?round(mean(r.slice(1))):'Missing'),'=BYROW(IF(ISNUMBER(Data!B2:D9),Data!B2:D9,"Missing"),LAMBDA(readings,IF(COUNT(readings)=3,ROUND(AVERAGE(readings),2),"Missing")))',['BYROW','LAMBDA','ROUND','AVERAGE'],H('Do not average a partial sample for this metric.','Preserve missing markers, guard completeness, then round the row mean.','=BYROW(IF(ISNUMBER(____),____,"Missing"),LAMBDA(readings,IF(COUNT(readings)=____,ROUND(AVERAGE(readings),2),"Missing")))')),
   T('For all 40 samples, count numeric readings ≥ 27 J, regardless of whether the other readings are blank (40 × 1).',rows.map(r=>r.slice(1).filter(v=>numeric(v)&&v>=27).length),'=BYROW(Data!B2:D41,LAMBDA(readings,SUM(--ISNUMBER(readings)*--(readings>=27))))',['BYROW','LAMBDA','SUM','ISNUMBER'],H('Equality counts, blank does not, zero is below the threshold.','Sum the numeric-and-threshold Boolean mask per row.','=BYROW(____,LAMBDA(readings,SUM(____)))'),['=COUNTIFS(Data!B2:D2,">=27")'],'Alternative: fill down 40 rows.'),
   T('Return mean Reading_1_J, Reading_2_J and Reading_3_J across all samples as one 1 × 3 row. Ignore blanks, retain zeros, and round each mean to two decimals.',[Array.from({length:3},(_,i)=>round(mean(rows.map(r=>r[i+1]).filter(numeric))))],'=BYCOL(IF(ISNUMBER(Data!B2:D41),Data!B2:D41,"Missing"),LAMBDA(readings,ROUND(AVERAGE(readings),2)))',['BYCOL','LAMBDA','AVERAGE','ROUND'],H('This summarizes columns, not individual samples.','Preserve blank status as text, then return a rounded mean per column.','=BYCOL(IF(ISNUMBER(____),____,"Missing"),LAMBDA(readings,ROUND(AVERAGE(readings),2)))')),
   T('Review SUM: total passing-reading counts from task 3.',rows.reduce((n,r)=>n+r.slice(1).filter(v=>numeric(v)&&v>=27).length,0),'=SUM(Answers!B22:B61)',['SUM'],H('Each task-3 row contributes its count.','Sum the task-3 output column.','=SUM(____)'))
  ]);

 add(8,4,'Calculate cumulative losses and credits','Irvani Quality records 50 fictitious COPQ events in chronological source order. Positive CAD values are costs and negative values are recovery credits. Net loss retains credits; gross cost deliberately excludes them. No cells are missing.',['SCAN','REDUCE'],
  'SCAN exposes the running accumulation after each event. REDUCE returns the final accumulation. Different rules can track net cost and gross cost without erasing credits from the source.',
  'Review IF, MAX and COUNTIFS. Start sums at zero and keep source order for running totals. Use a scalar LAMBDA body for each step. Any valid formula is accepted; submit unrounded CAD values.',
  [['Event_no','Unique chronological event key.'],['COPQ_CAD','Positive cost or negative recovery credit, CAD.']],r=>Array.from({length:50},(_,i)=>[`IV-${String(i+1).padStart(3,'0')}`,i%7===1?-r.int(50,180):r.int(90,600)]),
  (rows,T)=>{let net=0,gross=0;const running=rows.slice(0,10).map(r=>net+=r[1]),positive=rows.slice(0,10).map(r=>gross+=Math.max(0,r[1]));return[
   T('Return cumulative net COPQ after each of the first ten events (10 × 1), retaining negative credits.',running,'=SCAN(0,Data!B2:B11,LAMBDA(acc,cost,acc+cost))',['SCAN','LAMBDA'],H('A recovery credit reduces the running net value.','SCAN adds the signed cost to its accumulator.','=SCAN(0,____,LAMBDA(acc,cost,____))')),
   T('Return final net COPQ across all 50 events, including credits.',sum(rows,1),'=REDUCE(0,Data!B2:B51,LAMBDA(acc,cost,acc+cost))',['REDUCE','LAMBDA'],H('Include every signed event once.','REDUCE returns the final accumulator.','=REDUCE(0,____,LAMBDA(acc,cost,____))'),['=SUM(Data!B2:B51)']),
   T('Return cumulative gross cost after each of the first ten events. Add positive costs; credits leave gross cost unchanged.',positive,'=SCAN(0,Data!B2:B11,LAMBDA(acc,cost,acc+MAX(cost,0)))',['SCAN','LAMBDA','MAX'],H('This metric excludes credits without changing the raw data.','Add only the nonnegative part at each step.','=SCAN(0,____,LAMBDA(acc,cost,acc+____)))')),
   T('Return final gross cost across all 50 events, excluding negative credits.',rows.reduce((n,r)=>n+Math.max(0,r[1]),0),'=REDUCE(0,Data!B2:B51,LAMBDA(acc,cost,IF(cost>0,acc+cost,acc)))',['REDUCE','LAMBDA','IF'],H('A credit is excluded from this gross metric.','Condition the accumulator update on positive cost.','=REDUCE(0,____,LAMBDA(acc,cost,IF(____,acc+cost,acc)))'),['=SUMIFS(Data!B2:B51,Data!B2:B51,">0")']),
   T('Review COUNTIFS: count negative recovery-credit events.',rows.filter(r=>r[1]<0).length,'=COUNTIFS(Data!B2:B51,"<0")',['COUNTIFS'],H('Count credit events, not their dollar value.','Use a negative-value COUNTIFS criterion.','=COUNTIFS(____,"<0")'))
  ];});

 add(8,5,'Build a reusable Charpy calculation library','Jervali Testworks has 40 fictitious duplicate Charpy measurements. Define MeanEnergy(sampleKey,heatKey,orientation) in Name Manager or use its inline equivalent. It averages numeric replicates for both keys and normalized orientation, rounds to two decimals, and returns Missing when no numeric result exists.',['LAMBDA','LET'],
  'Reusable calculations need an explicit input contract. Keep all identifying keys as parameters rather than relying on an incidental worksheet row.',
  'Review MAP, FILTER, ISNUMBER and HSTACK. MeanEnergy can name its mask in LET and reuse it to count and average the population. Named formulas are workbook-local: create the definition before calling it. Any equivalent formula is accepted. Text sample IDs retain leading zeros.',
  [['sample_no','Text sample identifier reused across heats.'],['heat_no','Invented heat identifier.'],['Orientation','LPA/TWA with inconsistent case/spaces.'],['Energy_J','Numeric joules, blank unmeasured, zero measured.']],r=>charpy(r,'JV'),
  (rows,T,s)=>{const keys=s[0].rows,values=orientationMeans(rows,keys),definition='LAMBDA(sampleKey,heatKey,orientation,LET(mask,(Data!$A$2:$A$41=sampleKey)*(Data!$B$2:$B$41=heatKey)*(UPPER(TRIM(Data!$C$2:$C$41))=UPPER(TRIM(orientation)))*ISNUMBER(Data!$D$2:$D$41),IF(SUM(mask)=0,"Missing",ROUND(AVERAGE(FILTER(Data!$D$2:$D$41,mask)),2))))';return[
   T('Return LPA mean energy for every Keys row (10 × 1), using both identifiers and the stated duplicate/missing rule.',values.map(r=>r[0]),'=MAP(Keys!A2:A11,Keys!B2:B11,LAMBDA(sampleKey,heatKey,MeanEnergy(sampleKey,heatKey,"LPA")))',['MAP','LAMBDA','LET'],H('The same sample number occurs in multiple heats.','Pass sample and heat to the reusable function.','=MAP(____,____,LAMBDA(sampleKey,heatKey,MeanEnergy(____,____,"LPA")))'),[`=MAP(Keys!A2:A11,Keys!B2:B11,LAMBDA(sampleKey,heatKey,${definition}(sampleKey,heatKey,"LPA")))`],`Define MeanEnergy in Name Manager as =${definition}`),
   T('Return TWA mean energy for every Keys row (10 × 1), retaining Missing and numeric zero.',values.map(r=>r[1]),'=MAP(Keys!A2:A11,Keys!B2:B11,LAMBDA(sampleKey,heatKey,MeanEnergy(sampleKey,heatKey,"TWA")))',['MAP','LAMBDA'],H('Use the TWA population; one pair has no numeric TWA result.','Reuse the same function with a different orientation argument.','=MAP(____,____,LAMBDA(sampleKey,heatKey,MeanEnergy(____,____,____)))'),[],`Use the same MeanEnergy definition as task 1.`),
   T('Assemble sample_no, heat_no, LPA_mean_J and TWA_mean_J for all Keys rows, in scaffold order without headers (10 × 4).',keys.map((k,i)=>[...k,...values[i]]),'=HSTACK(Keys!A2:B11,Answers!B2:B11,Answers!B14:B23)',['HSTACK'],H('Both identifier columns must remain beside their corresponding means.','Combine Keys and the two output columns.','=HSTACK(____,____,____)')),
   T('Count key pairs with at least one Missing orientation mean. Count a pair once if both orientations are missing.',values.filter(r=>r.includes('Missing')).length,'=SUM(BYROW(Answers!D26:E35,LAMBDA(orientations,--(SUM(--(orientations="Missing"))>0))))',['BYROW','LAMBDA','SUM'],H('A pair is one row, regardless of the number of missing orientations.','Sum Boolean comparisons inside each row-array, then count rows with a positive sum.','=SUM(BYROW(____,LAMBDA(orientations,--(____>0))))'),['=SUMPRODUCT(--(((Answers!D26:D35="Missing")+(Answers!E26:E35="Missing"))>0))']),
   T('Review SUMPRODUCT: count raw measured zero-energy records; blank cells must be excluded.',rows.filter(r=>r[3]===0).length,'=SUMPRODUCT(--ISNUMBER(Data!D2:D41),--(Data!D2:D41=0))',['SUMPRODUCT','ISNUMBER'],H('Excel equality to zero can also match blank cells; require numeric type.','Combine ISNUMBER with the zero comparison.','=SUMPRODUCT(--ISNUMBER(____),--(____=0))'))
  ];},rows=>[sheet('Keys',['sample_no','heat_no'],distinct(rows.map(r=>r.slice(0,2))))]);

 add(9,1,'Group production summaries','Kelvani Rolling records 48 fictitious batches for six heats and two shifts. Every batch contributes tonnes and cost; repeated keys aggregate. Report no headers or grand/subtotals, and sort grouping keys ascending.',['GROUPBY','SUM'],
  'Formula grouping creates a summary directly from repeated records. Explicit header and total settings prevent a summary from changing shape unexpectedly.',
  'Review HSTACK and ROUND. Current Microsoft 365 is required; if GROUPBY is unavailable, use a unique-key scaffold with SUMIFS. That alternative is accepted. Use field_relationship 1 for repeated complete key labels in flat reports.',
  [['Heat_no','One of six invented heat keys.'],['Shift','Day/Night grouping key.'],['Produced_t','Numeric production, metric tonnes.'],['Cost_CAD','Numeric batch cost, CAD.']],r=>Array.from({length:48},(_,i)=>[`KV-H${Math.floor(i/2)%6+1}`,i%2?'Night':'Day',r.int(50,150)/10,r.int(900,3000)]),
  (rows,T)=>{const group=indices=>distinct(rows.map(r=>indices.map(i=>r[i]))).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))).map(k=>{const matched=rows.filter(r=>indices.every((j,i)=>r[j]===k[i]));return[...k,round(sum(matched,2)),sum(matched,3)];}),byShift=group([1]),byHeat=group([0]),both=group([0,1]);return[
   T('Return Shift, total Produced_t and total Cost_CAD (2 × 3), shift ascending. Round tonnes to two decimals; no headers/totals.',byShift,'=GROUPBY(Data!B2:B49,Data!C2:D49,LAMBDA(values,ROUND(SUM(values),2)),0,0,1)',['GROUPBY','LAMBDA','ROUND','SUM'],H('Combine every batch for each shift.','Set headers and total depth to zero in GROUPBY.','=GROUPBY(____,____,LAMBDA(values,ROUND(SUM(values),2)),0,0,1)')),
   T('Return Heat_no, total Produced_t and total Cost_CAD (6 × 3), heat ascending. Round tonnes to two decimals; no headers/totals.',byHeat,'=GROUPBY(Data!A2:A49,Data!C2:D49,LAMBDA(values,ROUND(SUM(values),2)),0,0,1)',['GROUPBY','LAMBDA','SUM'],H('Summarize by heat rather than by shift.','Change the grouping range, keeping aligned measures.','=GROUPBY(____,Data!C2:D49,____,0,0,1)')),
   T('Return Heat_no, Shift, total Produced_t, total Cost_CAD for each combination (12 × 4), heat then shift ascending. Repeat both labels on every row. Round tonnes to two decimals; no headers/totals.',both,'=GROUPBY(Data!A2:B49,Data!C2:D49,LAMBDA(values,ROUND(SUM(values),2)),0,0,{1,2},,1)',['GROUPBY','LAMBDA'],H('Both fields identify each group; flat output repeats labels.','Use two row fields and table relationship 1.','=GROUPBY(____,____,____,0,0,{1,2},,____)')),
   T('Review reconciliation: return grouped total Cost_CAD from task 3 minus the independent raw Cost_CAD total. Submit numeric zero when reconciled.',sum(both,3)-sum(rows,3),'=SUM(Answers!E14:E25)-SUM(Data!D2:D49)',['SUM'],H('Compare grouped totals with a separate raw source total.','Subtract raw cost from task-3 grouped cost.','=SUM(____)-SUM(____)'),['=SUM(Answers!D6:D11)-SUM(Data!D2:D49)']),
   T('Review AVERAGE: return average batch Produced_t across all 48 raw records, rounded to three decimals.',round(sum(rows,2)/rows.length,3),'=ROUND(AVERAGE(Data!C2:C49),3)',['AVERAGE','ROUND'],H('Average raw batches, not unequal heat totals.','Use AVERAGE on the raw production column.','=ROUND(AVERAGE(____),3)'))
  ];});

 add(9,2,'Pivot Charpy orientations with duplicate means','Lervani Lab records 40 fictitious Charpy replicates. Pair_key contains text sample_no and heat_no separated by |; neither identifier contains that delimiter. Aggregate numeric replicates by both keys and normalized orientation; all-blank groups return Missing, and measured zero is retained.',['PIVOTBY','COUNT'],
  'A formula pivot organizes one key across rows and another across columns. A custom aggregation can distinguish numeric measurements from an all-blank group.',
  'Review LAMBDA, ROUND, DROP, TEXTBEFORE and TEXTAFTER. PIVOTBY retains an orientation-label row: remove it when the task requests data only. Use ascending row/column keys and zero total depths. If unavailable, use a key scaffold with guarded AVERAGEIFS; equivalent outputs are accepted.',
  [['sample_no','Leading-zero text identifier, reused across heats.'],['heat_no','Invented heat key.'],['Orientation','LPA/TWA with case and outer-space differences.'],['Energy_J','Numeric joules or blank unmeasured replicate.'],['Pair_key','Lossless sample_no|heat_no text key; delimiters never occur in either component.']],r=>charpy(r,'LV').map(row=>[...row,row[0]+'|'+row[1]]),
  (rows,T)=>{const keys=distinct(rows.map(r=>r.slice(0,2))).sort((a,b)=>(a[0]+'|'+a[1]).localeCompare(b[0]+'|'+b[1])),values=orientationMeans(rows,keys),pivot=keys.map((k,i)=>[k.join('|'),...values[i]]),counts=keys.map(k=>[k.join('|'),rows.filter(r=>r[0]===k[0]&&r[1]===k[1]&&numeric(r[3])).length]);return[
   T('Group by Pair_key and return Pair_key plus numeric Energy_J count (10 × 2). Sort key ascending; no headers/totals. Zero counts as numeric.',counts,'=GROUPBY(Data!E2:E41,IF(ISNUMBER(Data!D2:D41),Data!D2:D41,"Missing"),COUNT,0,0,1)',['GROUPBY','COUNT'],H('Count numeric replicates, not source rows.','Preserve blanks as text and use COUNT as the aggregator.','=GROUPBY(____,IF(ISNUMBER(____),____,"Missing"),____,0,0,1)')),
   T('Return Pair_key, LPA_mean_J and TWA_mean_J (10 × 3), key ascending, with no orientation-label row or totals. Round numeric means to two decimals; return Missing for all-blank groups.',pivot,'=DROP(PIVOTBY(Data!E2:E41,UPPER(TRIM(Data!C2:C41)),IF(ISNUMBER(Data!D2:D41),Data!D2:D41,"Missing"),LAMBDA(values,IF(COUNT(values)=0,"Missing",ROUND(AVERAGE(values),2))),0,0,1,0,1),1)',['PIVOTBY','LAMBDA','COUNT','DROP'],H('Use both identifiers through Pair_key and normalize the orientation axis.','Preserve blank status as text, guard the mean with COUNT, and DROP the column-label row.','=DROP(PIVOTBY(____,____,IF(ISNUMBER(____),____,"Missing"),LAMBDA(values,IF(____,"Missing",____)),0,0,1,0,1),1)')),
   T('Split the task-2 Pair_key and assemble sample_no, heat_no, LPA_mean_J and TWA_mean_J (10 × 4), same row order. Preserve text sample identifiers.',keys.map((k,i)=>[...k,...values[i]]),'=HSTACK(TEXTBEFORE(Answers!B14:B23,"|"),TEXTAFTER(Answers!B14:B23,"|"),Answers!C14:D23)',['HSTACK','TEXTBEFORE','TEXTAFTER'],H('Keep the leading zeros and separate both key components.','Split Pair_key at its guaranteed delimiter, then HSTACK.','=HSTACK(TEXTBEFORE(____,"|"),TEXTAFTER(____,"|"),____)'),['=HSTACK(LEFT(Answers!B14:B23,3),TEXTAFTER(Answers!B14:B23,"|"),Answers!C14:D23)']),
   T('Count Missing orientation means in the task-2 result. Do not count blank raw replicates.',values.flat().filter(v=>v==='Missing').length,'=COUNTIFS(Answers!C14:D23,"Missing")',['COUNTIFS'],H('A missing orientation mean is an aggregate result.','Count Missing within the two mean columns.','=COUNTIFS(____,"Missing")')),
   T('Review COUNT: return the number of numeric raw Energy_J measurements.',rows.filter(r=>numeric(r[3])).length,'=COUNT(Data!D2:D41)',['COUNT'],H('Zero remains numeric and blank replicates are excluded.','Count the original energy column.','=COUNT(____)'))
  ];});

 add(9,3,'Measure variation and inclusive percentiles','Mervali Inspection has 48 fictitious wall-thickness observations in mm, including unmeasured blank cells. Numeric observations alone form the descriptive sample. Training specification limits are 9.7–10.3 mm inclusive; these are not statistical control limits.',['STDEV.S','PERCENTILE.INC'],
  'A sample standard deviation describes spread using n−1. Inclusive percentiles interpolate between sorted numeric observations. Both describe this sample without proving process stability.',
  'Review COUNT, AVERAGE, ISNUMBER and ROUND. Ignore blanks consistently. Specification failures use strict less-than/greater-than comparisons because both limits are inclusive. Any valid formula is accepted; do not round the standard deviation.',
  [['Observation_no','Unique invented observation key.'],['Thickness_mm','Numeric wall thickness in mm, or blank unmeasured value.']],r=>Array.from({length:48},(_,i)=>[`MV-${i+1}`,i%12===0?'':i===1?9.7:i===2?10.3:r.int(960,1040)/100]),
  (rows,T)=>{const a=rows.map(r=>r[1]).filter(numeric);return[
   T('Return sample standard deviation of all numeric Thickness_mm observations. Submit unrounded mm.',sd(a),'=STDEV.S(Data!B2:B49)',['STDEV.S'],H('Use n−1 sample spread and exclude unmeasured cells.','Apply STDEV.S to the complete source range.','=STDEV.S(____)'),['=SQRT(SUM((FILTER(Data!B2:B49,ISNUMBER(Data!B2:B49))-AVERAGE(Data!B2:B49))^2)/(COUNT(Data!B2:B49)-1))']),
   T('Return the inclusive 50th percentile of numeric thickness, rounded to three decimals.',round(pct(a,.5),3),'=ROUND(PERCENTILE.INC(Data!B2:B49,0.5),3)',['PERCENTILE.INC','ROUND'],H('Use a percentile proportion of 0.5.','Round PERCENTILE.INC at the final stage.','=ROUND(PERCENTILE.INC(____,____),3)')),
   T('Return the inclusive 90th percentile of numeric thickness, rounded to three decimals.',round(pct(a,.9),3),'=ROUND(PERCENTILE.INC(Data!B2:B49,0.9),3)',['PERCENTILE.INC','ROUND'],H('Use inclusive linear interpolation at the 90th percentile.','Use k=0.9 rather than 90.','=ROUND(PERCENTILE.INC(____,____),3)')),
   T('Count numeric observations outside the inclusive 9.7–10.3 mm training specification. Exclude unmeasured cells.',a.filter(v=>v<9.7||v>10.3).length,'=SUMPRODUCT(--ISNUMBER(Data!B2:B49),--((Data!B2:B49<9.7)+(Data!B2:B49>10.3)>0))',['SUMPRODUCT','ISNUMBER'],H('Values exactly at 9.7 or 10.3 pass the specification.','Count a numeric-and-outside Boolean mask.','=SUMPRODUCT(--ISNUMBER(____),--((____<9.7)+(____>10.3)>0))')),
   T('Review AVERAGE: return numeric mean thickness rounded to three decimals.',round(mean(a),3),'=ROUND(AVERAGE(Data!B2:B49),3)',['AVERAGE','ROUND'],H('Average observations, excluding blank measurements.','Use AVERAGE then ROUND.','=ROUND(AVERAGE(____),3)'))
  ];});

 add(9,4,'Explore paired correlations responsibly','Nevrali Operations records 44 fictitious batches with production rate and energy per tonne. Some cells are unmeasured. Correlation uses only records with both values numeric; preserve row pairing, and describe association without claiming a causal effect.',['CORREL','ISNUMBER'],
  'Correlation measures linear association for aligned pairs. Independently dropping missing values from each column breaks those pairs and can produce a misleading result.',
  'Review LET, FILTER, ABS and IF. Create one complete-pair mask for both arrays. For this exercise only, |r| ≥ 0.5 receives the label Association only; below it receives Weak association. Neither label proves causation. Any valid formula is accepted.',
  [['Batch_no','Unique invented batch identifier.'],['Rate_t_per_h','Numeric production rate, t/h, or blank.'],['Energy_kWh_per_t','Numeric energy intensity, kWh/t, or blank.']],r=>Array.from({length:44},(_,i)=>{const rate=r.int(30,70);return[`NV-${i+1}`,i%11===0?'':rate,i%13===1?'':round(680-rate*3+r.int(-25,25))];}),
  (rows,T)=>{const pairs=rows.filter(r=>numeric(r[1])&&numeric(r[2])),value=corr(pairs.map(r=>r[1]),pairs.map(r=>r[2]));return[
   T('Count complete numeric pairs across all 44 records.',pairs.length,'=SUMPRODUCT(--ISNUMBER(Data!B2:B45),--ISNUMBER(Data!C2:C45))',['SUMPRODUCT','ISNUMBER'],H('Both variables must be numeric in the same row.','Combine the two ISNUMBER masks.','=SUMPRODUCT(--ISNUMBER(____),--ISNUMBER(____))')),
   T('Return Pearson correlation using complete pairs only. Submit unrounded r.',value,'=LET(ok,ISNUMBER(Data!B2:B45)*ISNUMBER(Data!C2:C45),CORREL(FILTER(Data!B2:B45,ok),FILTER(Data!C2:C45,ok)))',['CORREL','LET','FILTER'],H('The two filtered arrays must contain exactly the same records.','Reuse one complete-pair mask in both FILTER calls.','=LET(ok,____,CORREL(FILTER(____,ok),FILTER(____,ok)))')),
   T('For the first eight records, return Paired when both cells are numeric; otherwise Missing pair (8 × 1).',first(rows).map(r=>numeric(r[1])&&numeric(r[2])?'Paired':'Missing pair'),'=IF(AND(ISNUMBER(Data!B2),ISNUMBER(Data!C2)),"Paired","Missing pair")',['IF','AND','ISNUMBER'],H('One present variable does not form a pair.','Review AND on the numeric tests.','=IF(AND(____,____),"Paired","Missing pair")'),[],'Fill down eight records.'),
   T('Using unrounded task-2 r, return Association only when |r| ≥ 0.5; otherwise Weak association. This is a practice description, not a causal conclusion.',Math.abs(value)>=.5?'Association only':'Weak association','=IF(ABS(Answers!B5)>=0.5,"Association only","Weak association")',['IF','ABS'],H('Use the magnitude for this label; preserve the sign in task 2.','Classify ABS of the correlation.','=IF(ABS(____)>=____,"Association only","Weak association")'),['=IF(OR(Answers!B5>=0.5,Answers!B5<=-0.5),"Association only","Weak association")']),
   T('Review AVERAGE: return mean Energy_kWh_per_t for complete pairs only, rounded to two decimals.',round(mean(pairs.map(r=>r[2]))),'=ROUND(AVERAGE(FILTER(Data!C2:C45,ISNUMBER(Data!B2:B45)*ISNUMBER(Data!C2:C45))),2)',['AVERAGE','FILTER','ROUND'],H('Use the paired population, not all populated energy cells.','Reuse the same completeness mask.','=ROUND(AVERAGE(FILTER(____,____)),2)'))
  ];});

 add(9,5,'Calculate capability under stated assumptions','Orvani Lab provides 50 fictitious independent thickness observations. For illustration, assume a stable normal process and a separately supplied within-process sigma of 0.06 mm; these assumptions are not demonstrated by this sample. Specification limits and historical reference mean are on Assumptions.',['STDEV.S','AVERAGE'],
  'Sample spread and an assumed within-process sigma serve different purposes. Cp compares specification width with six sigma; Cpk also accounts for the sample mean’s distance from either specification.',
  'Review MIN and ROUND. Cp=(USL−LSL)/(6×sigma); Cpk=MIN((USL−mean)/(3×sigma),(mean−LSL)/(3×sigma)). Reference control limits are historical mean ± 3×sigma, for individual observations. They are not specification limits. These illustrative indices do not prove stability or production acceptance. Any valid formula is accepted.',
  [['Observation_no','Unique invented observation identifier.'],['Thickness_mm','Numeric individual thickness, mm.']],r=>Array.from({length:50},(_,i)=>[`OV-${i+1}`,r.int(989,1029)/100]),
  (rows,T,s)=>{const a=rows.map(r=>r[1]),[lsl,usl,sigma,ref]=s[0].rows.map(r=>r[1]);return[
   T('Return sample mean and sample STDEV.S as one 1 × 2 row. Submit both unrounded, in mm.',[[mean(a),sd(a)]],'=HSTACK(AVERAGE(Data!B2:B51),STDEV.S(Data!B2:B51))',['AVERAGE','STDEV.S','HSTACK'],H('Return mean first and n−1 sample standard deviation second.','Combine the two descriptive metrics with HSTACK.','=HSTACK(AVERAGE(____),STDEV.S(____))')),
   T('Calculate illustrative Cp using the supplied within-process sigma, not task-1 sample spread. Submit unrounded.',(usl-lsl)/(6*sigma),'=(Assumptions!B3-Assumptions!B2)/(6*Assumptions!B4)',['SUM'],H('Specification width is divided by six times the supplied sigma.','Read LSL, USL and within sigma from Assumptions.','=(____-____)/(6*____)'),['=LET(lsl,Assumptions!B2,usl,Assumptions!B3,sigma,Assumptions!B4,(usl-lsl)/(6*sigma))']),
   T('Calculate illustrative Cpk using the task-1 mean and supplied within-process sigma. Submit unrounded.',Math.min((usl-mean(a))/(3*sigma),(mean(a)-lsl)/(3*sigma)),'=MIN((Assumptions!B3-Answers!B2)/(3*Assumptions!B4),(Answers!B2-Assumptions!B2)/(3*Assumptions!B4))',['MIN'],H('Use the smaller distance to a specification, not the full width.','Calculate both one-sided ratios and take MIN.','=MIN((____-____)/(3*____),(____-____)/(3*____))')),
   T('Return lower and upper historical-reference control limits as one 1 × 2 row: Reference_mean_mm ± 3 × Within_sigma_mm. Round to three decimals. These are for individual observations, not subgroup averages.',[[round(ref-3*sigma,3),round(ref+3*sigma,3)]],'=HSTACK(ROUND(Assumptions!B5-3*Assumptions!B4,3),ROUND(Assumptions!B5+3*Assumptions!B4,3))',['HSTACK','ROUND'],H('Use the historical reference mean; do not replace these with specification limits.','Subtract/add three supplied sigma units around the reference.','=HSTACK(ROUND(____-3*____,3),ROUND(____+3*____,3))')),
   T('Review COUNTIFS: count sample thicknesses outside the inclusive specification limits.',a.filter(v=>v<lsl||v>usl).length,'=COUNTIFS(Data!B2:B51,"<"&Assumptions!B2)+COUNTIFS(Data!B2:B51,">"&Assumptions!B3)',['COUNTIFS'],H('Compare with specifications, not reference control limits.','Add counts below LSL and above USL.','=COUNTIFS(____,"<"&____)+COUNTIFS(____,">"&____)'))
  ];},()=>[sheet('Assumptions',['Parameter','Value_mm'],[['LSL_mm',9.7],['USL_mm',10.3],['Within_sigma_mm',.06],['Reference_mean_mm',10.02]])]);

 add(10,1,'Build a robust inspection summary','Pelvani Pipeworks records 60 fictitious inspections. Specs includes one deliberately duplicated grade; an absent/ambiguous grade or blank strength means Review. A unique specification and numeric strength produce Released at/above the training minimum, otherwise Hold.',['LET','FILTER'],
  'An integrated report should make input guards visible before a comparison. A successful lookup can still select an ambiguous specification unless cardinality is checked.',
  'Review COUNTIFS, XLOOKUP, ISNUMBER, IF, HSTACK and SORTBY. Practice combining at least four functions in the nested rule, then reuse its statuses for summaries and queues. Any equivalent formula is accepted. Training rules do not authorize production release.',
  [['Inspection_no','Unique padded inspection key.'],['Grade','G1/G2/G3 or deliberately unknown GX.'],['Strength_MPa','Numeric tensile strength, MPa, or blank.'],['Hold_cost_CAD','Fictitious potential hold cost in CAD.']],r=>Array.from({length:60},(_,i)=>[`PV-${String(i+1).padStart(3,'0')}`,['G1','G2','G3','GX'][i%4],i%11===0?'':i===4?450:r.int(420,520),r.int(100,1200)]),
  (rows,T,s)=>{const matches=grade=>s[0].rows.filter(r=>r[0]===grade),limit=r=>matches(r[1]).length===1?matches(r[1])[0][1]:'Review',status=r=>limit(r)==='Review'||!numeric(r[2])?'Review':r[2]>=limit(r)?'Released':'Hold',statuses=rows.map(status),held=rows.filter(r=>status(r)==='Hold').sort((a,b)=>b[3]-a[3]||a[0].localeCompare(b[0])),summary=[['Released','Hold','Review'].map(k=>statuses.filter(v=>v===k).length).concat(sum(held,3))];return[
   T('For the first eight rows, return a unique grade’s minimum strength or Review for an absent/duplicated key (8 × 1).',first(rows).map(limit),'=LET(grade,Data!B2,matches,COUNTIFS(Specs!$A$2:$A$5,grade),IF(matches=1,XLOOKUP(grade,Specs!$A$2:$A$5,Specs!$B$2:$B$5),"Review"))',['LET','COUNTIFS','IF','XLOOKUP'],H('Exactly one specification must match.','Name match count and guard the lookup.','=LET(grade,____,matches,COUNTIFS(____,grade),IF(____,XLOOKUP(____),"Review"))'),[],'Fill down eight records.'),
   T('Return Released, Hold or Review for all 60 inspections in source order. Equality to a unique minimum is Released; blank strength is Review.',statuses,'=LET(grade,Data!B2,strength,Data!C2,matches,COUNTIFS(Specs!$A$2:$A$5,grade),IF(OR(matches<>1,NOT(ISNUMBER(strength))),"Review",IF(strength>=XLOOKUP(grade,Specs!$A$2:$A$5,Specs!$B$2:$B$5),"Released","Hold")))',['LET','COUNTIFS','ISNUMBER','IF','XLOOKUP'],H('Do not compare until both specification and measurement are valid.','Guard cardinality and numeric type before the lookup comparison.','=LET(grade,____,strength,____,matches,____,IF(OR(____),"Review",IF(____,"Released","Hold")))'),[],'Fill down all source records.'),
   T('Return Released count, Hold count, Review count and total Hold_cost_CAD for Hold rows as one 1 × 4 row. Review costs are pending and excluded.',summary,'=HSTACK(COUNTIFS(Answers!B12:B71,"Released"),COUNTIFS(Answers!B12:B71,"Hold"),COUNTIFS(Answers!B12:B71,"Review"),SUMIFS(Data!D2:D61,Answers!B12:B71,"Hold"))',['HSTACK','COUNTIFS','SUMIFS'],H('The three counts partition all 60 rows; only Hold contributes cost.','Combine counts and conditional cost in one summary row.','=HSTACK(COUNTIFS(____,"Released"),COUNTIFS(____,"Hold"),COUNTIFS(____,"Review"),SUMIFS(____,____,"Hold"))')),
   T('Return full Data rows for Hold inspections, sorted by Hold_cost_CAD descending then Inspection_no ascending. No headers.',held,'=LET(held,FILTER(Data!A2:D61,Answers!B12:B71="Hold"),SORTBY(held,CHOOSECOLS(held,4),-1,CHOOSECOLS(held,1),1))',['LET','FILTER','SORTBY','CHOOSECOLS'],H('Review rows are not the confirmed Hold queue.','Filter Hold once and sort aligned columns with a tie key.','=LET(held,FILTER(____,____),SORTBY(held,____,-1,____,1))'),['=SORTBY(FILTER(Data!A2:D61,Answers!B12:B71="Hold"),FILTER(Data!D2:D61,Answers!B12:B71="Hold"),-1,FILTER(Data!A2:A61,Answers!B12:B71="Hold"),1)']),
   T('Review SUM: subtract the independent raw Hold-cost sum from the summary Hold cost; return numeric zero when reconciled.',0,'=Answers!E74-SUMIFS(Data!D2:D61,Answers!B12:B71,"Hold")',['SUMIFS'],H('Use the summary cost and an independent source-based conditional sum.','Subtract the selected raw costs.','=Answers!E74-SUMIFS(____,____,"Hold")'))
  ];},()=>[sheet('Specs',['Grade','Min_strength_MPa'],[['G1',450],['G2',460],['G2',470],['G3',480]])]);

 add(10,2,'Reconcile orders and partial shipments','Qervali Distribution has 40 fictitious orders and a Shipments table with partial and repeated dispatches. Aggregate all shipments by Order_no; shipments for absent orders are orphans and remain separate. Remaining units = ordered − shipped; negative means overshipment and must not be clamped to zero.',['LET','MAP'],
  'Reconciling tables requires aggregate joins when an order can have several shipments. A first-match lookup loses partial dispatches. Independent control totals expose orphan movements.',
  'Review SUMIFS, COUNTIFS, FILTER, HSTACK and SUM. Use the order scaffold to preserve source order. Return Short for positive remaining units, Over for negative, Balanced for zero. Any equivalent formula is accepted; all quantities are numeric.',
  [['Order_no','Unique padded order key.'],['Ordered_units','Nonnegative ordered quantity; a measured zero order is valid.'],['Price_CAD','Numeric price per unit, CAD.']],r=>Array.from({length:40},(_,i)=>[`QV-${String(i+1).padStart(3,'0')}`,i===0?0:r.int(10,70),r.int(20,90)]),
  (rows,T,s)=>{const shipments=s[0].rows,shipped=id=>sum(shipments.filter(r=>r[1]===id),2),report=rows.map(r=>{const n=shipped(r[0]),remaining=r[1]-n;return[r[0],r[1],n,remaining,remaining>0?'Short':remaining<0?'Over':'Balanced'];}),exceptions=report.filter(r=>r[3]!==0),matched=shipments.filter(r=>rows.some(o=>o[0]===r[1])),orphans=shipments.filter(r=>!rows.some(o=>o[0]===r[1]));return[
   T('Return total shipped units for the first eight order rows (8 × 1). Sum every partial shipment; absent shipments produce numeric zero.',first(rows).map(r=>shipped(r[0])),'=MAP(Data!A2:A9,LAMBDA(order,SUMIFS(Shipments!C2:C46,Shipments!B2:B46,order)))',['MAP','LAMBDA','SUMIFS'],H('Aggregate every matching dispatch.','MAP the order scaffold to a SUMIFS total.','=MAP(____,LAMBDA(order,SUMIFS(____,____,order)))')),
   T('Return Order_no, Ordered_units, Shipped_units, Remaining_units, Status for every order (40 × 5), source order. Preserve signed remaining units.',report,'=LET(orders,Data!A2:A41,ordered,Data!B2:B41,shipped,MAP(orders,LAMBDA(order,SUMIFS(Shipments!C2:C46,Shipments!B2:B46,order))),remaining,ordered-shipped,HSTACK(orders,ordered,shipped,remaining,IF(remaining>0,"Short",IF(remaining<0,"Over","Balanced"))))',['LET','MAP','SUMIFS','HSTACK','IF'],H('Keep overshipments negative and unmatched order shipments at zero.','Name the aggregate and signed difference before labeling.','=LET(orders,____,ordered,____,shipped,MAP(____),remaining,____,HSTACK(____,IF(remaining>0,"Short",IF(remaining<0,"Over","Balanced"))))')),
   T('From task 2, return every Short or Over row in original order order, without headers. Balanced rows are excluded.',exceptions,'=FILTER(Answers!B12:F51,Answers!E12:E51<>0,"None")',['FILTER'],H('Both positive and negative remaining quantities are exceptions.','Filter on nonzero signed remaining.','=FILTER(____,____<>0,"None")'),['=FILTER(Answers!B12:F51,Answers!F12:F51<>"Balanced","None")']),
   T('Return total ordered units, matched shipped units, orphan shipped units, and all shipped units − matched − orphan as one 1 × 4 row. The last value must reconcile to numeric zero.',[[sum(rows,1),sum(matched,2),sum(orphans,2),sum(shipments,2)-sum(matched,2)-sum(orphans,2)]],'=LET(known,COUNTIFS(Data!A2:A41,Shipments!B2:B46)>0,matched,SUM(FILTER(Shipments!C2:C46,known)),orphan,SUM(FILTER(Shipments!C2:C46,NOT(known))),HSTACK(SUM(Data!B2:B41),matched,orphan,SUM(Shipments!C2:C46)-matched-orphan))',['LET','COUNTIFS','FILTER','HSTACK','SUM'],H('Orphans are shipment records whose order is absent.','Partition raw shipments by order-key membership and reconcile both groups.','=LET(known,____,matched,SUM(FILTER(____,known)),orphan,SUM(FILTER(____,NOT(known))),HSTACK(____,matched,orphan,____-matched-orphan))')),
   T('Review COUNTIFS: count Over orders from task 2.',report.filter(r=>r[4]==='Over').length,'=COUNTIFS(Answers!F12:F51,"Over")',['COUNTIFS'],H('Count orders rather than dispatch records.','Count Over in the joined report.','=COUNTIFS(____,"Over")'))
  ];},rows=>[sheet('Shipments',['Shipment_no','Order_no','Shipped_units'],[...rows.map((r,i)=>[`QS-${i+1}`,r[0],i===0?5:i%4===0?r[1]:i%4===1?r[1]+3:Math.max(0,r[1]-4)]),['QS-41',rows[2][0],2],['QS-42',rows[3][0],6],['QS-43',rows[7][0],8],['QS-44','QV-999',11],['QS-45','QV-998',7]])]);

 add(10,3,'Audit a guarded formula chain','Rervani Costing has 36 fictitious inspection jobs, quoted costs and a Rates table. A rate is usable only when its grade key is unique; blank mass is unknown and numeric zero is valid. Correct cost is mass × unique rate, rounded to cents; a rounded quoted-minus-correct difference over 0.01 CAD in magnitude is Mismatch.',['LET','ROUND'],
  'A formula audit compares a corrected calculation with an independent quoted value. Keep ambiguous mappings and missing inputs visible before deciding whether a cost matches.',
  'Review COUNTIFS, XLOOKUP, ISNUMBER, ABS, FILTER and SORT. Practice combining at least four functions in the guarded cost rule. Missing mass or absent/duplicate rates produce Review. Quotes are numeric. Any equivalent formula is accepted.',
  [['Job_no','Unique padded job identifier.'],['Grade','Rate key; includes ambiguous and absent keys.'],['Mass_t','Numeric metric tonnes or blank unmeasured mass.'],['Quoted_CAD','Independent quoted cost, CAD.']],r=>Array.from({length:36},(_,i)=>{const grade=['G1','G2','G3','GX'][i%4],mass=i===0?0:i%9===0?'':r.int(20,100)/10,rate=grade==='G1'?120:grade==='G3'?160:140;return[`RV-${String(i+1).padStart(3,'0')}`,grade,mass,round((numeric(mass)?mass:3)*rate+(i===4?.01:i%5===0?2:0))];}),
  (rows,T,s)=>{const rates=s[0].rows,cost=r=>{const m=rates.filter(v=>v[0]===r[1]);return numeric(r[2])&&m.length===1?round(r[2]*m[0][1]):'Review';},status=r=>cost(r)==='Review'?'Review':Math.abs(round(r[3]-cost(r)))>.01?'Mismatch':'Match',report=rows.filter(r=>status(r)!=='Match').map(r=>[r[0],cost(r),r[3],status(r)]);return[
   T('For the first eight jobs, return corrected cost rounded to cents, or Review for absent/ambiguous rate or missing mass.',first(rows).map(cost),'=LET(grade,Data!B2,mass,Data!C2,matches,COUNTIFS(Rates!$A$2:$A$5,grade),IF(OR(matches<>1,NOT(ISNUMBER(Data!C2))),"Review",ROUND(mass*XLOOKUP(grade,Rates!$A$2:$A$5,Rates!$B$2:$B$5),2)))',['LET','COUNTIFS','IF','ISNUMBER','ROUND','XLOOKUP'],H('Zero mass is valid; blank mass and ambiguous keys need Review.','Check ISNUMBER on the original mass cell and rate cardinality before calculating.','=LET(grade,____,mass,____,matches,____,IF(OR(____),"Review",ROUND(____,2)))'),[],'Fill down eight jobs.'),
   T('For every job, return Review for an unavailable corrected cost; otherwise Mismatch when |ROUND(quoted − corrected,2)| > 0.01, or Match when ≤ 0.01. Source order (36 × 1).',rows.map(status),'=LET(grade,Data!B2,mass,Data!C2,matches,COUNTIFS(Rates!$A$2:$A$5,grade),IF(OR(matches<>1,NOT(ISNUMBER(Data!C2))),"Review",IF(ABS(ROUND(Data!D2-ROUND(mass*XLOOKUP(grade,Rates!$A$2:$A$5,Rates!$B$2:$B$5),2),2))>0.01,"Mismatch","Match")))',['LET','IF','ABS','ROUND','XLOOKUP'],H('Exactly one cent remains Match; round the difference before testing.','Check original-source completeness before comparing corrected amount with its independent quote.','=LET(grade,____,mass,____,matches,____,IF(OR(____),"Review",IF(ABS(ROUND(____,2))>0.01,"Mismatch","Match")))'),[],'Fill down all jobs.'),
   T('Return Job_no, Corrected_CAD, Quoted_CAD and Status for all Review/Mismatch jobs, sorted by Job_no ascending. Unavailable corrected cost is the text Review. No headers.',report,'=LET(grade,Data!B2:B37,mass,Data!C2:C37,known,(COUNTIFS(Rates!A2:A5,grade)=1)*ISNUMBER(Data!C2:C37),corrected,IF(known,ROUND(mass*XLOOKUP(grade,Rates!A2:A5,Rates!B2:B5,0),2),"Review"),SORT(FILTER(HSTACK(Data!A2:A37,corrected,Data!D2:D37,Answers!B12:B47),Answers!B12:B47<>"Match"),1,1))',['LET','XLOOKUP','FILTER','HSTACK','SORT'],H('Keep review reasons beside the independent quote.','Build a source-type guarded corrected-cost column and filter non-Match statuses.','=LET(grade,____,mass,____,known,____,corrected,IF(____),SORT(FILTER(HSTACK(____),____),1,1))')),
   T('Return the total corrected cost for jobs with unique rates and numeric mass. Exclude Review jobs; sum costs after each row is rounded to cents.',rows.reduce((n,r)=>n+(numeric(cost(r))?cost(r):0),0),'=SUM(MAP(Data!B2:B37,Data!C2:C37,ISNUMBER(Data!C2:C37),LAMBDA(grade,mass,massKnown,IF(AND(COUNTIFS(Rates!A2:A5,grade)=1,massKnown),ROUND(mass*XLOOKUP(grade,Rates!A2:A5,Rates!B2:B5),2),0))))',['SUM','MAP','LAMBDA','ROUND'],H('Aggregate known corrected costs only, after row-level rounding.','Pass original-source numeric flags into MAP, then sum the guarded rounded costs.','=SUM(MAP(____,____,ISNUMBER(____),LAMBDA(grade,mass,massKnown,IF(____,ROUND(____,2),0))))'),['=SUM(FILTER(ROUND(Data!C2:C37*XLOOKUP(Data!B2:B37,Rates!A2:A5,Rates!B2:B5,0),2),(COUNTIFS(Rates!A2:A5,Data!B2:B37)=1)*ISNUMBER(Data!C2:C37)))']),
   T('Review COUNTIFS: count Mismatch jobs from task 2.',rows.filter(r=>status(r)==='Mismatch').length,'=COUNTIFS(Answers!B12:B47,"Mismatch")',['COUNTIFS'],H('Review jobs cannot yet be declared cost mismatches.','Count only Mismatch in task 2.','=COUNTIFS(____,"Mismatch")'))
  ];},()=>[sheet('Rates',['Grade','Rate_CAD_per_t'],[['G1',120],['G2',130],['G2',150],['G3',160]])]);

 add(10,4,'Create a formula-driven business dashboard','Selvani Supplies has 45 fictitious monthly sales lines. Returns reverse units, revenue and per-unit cost; net units may be negative and must be preserved. Revenue = net units × selling price; profit = net units × (price − unit cost).',['LET','MAP'],
  'A dashboard combines traceable metrics at a common grouping level. A ratio such as margin belongs to the grouped totals rather than an average of line margins.',
  'Review SUMPRODUCT, HSTACK, FILTER, SORTBY and ROUND. Define net units once, aggregate by the Months/Product scaffold, and reconcile with independent raw calculations. Any equivalent formula is accepted; round money to cents and margin percentage numbers to two decimals.',
  [['Month','ISO year-month, one of three reporting months.'],['Product','One of five invented product keys.'],['Sold_units','Numeric sold units.'],['Returned_units','Numeric returned units; may exceed a line’s sales.'],['Price_CAD','Selling price per unit, CAD.'],['Unit_cost_CAD','Cost per unit, CAD.']],r=>Array.from({length:45},(_,i)=>{const sold=r.int(10,60);return[`2026-${['07','08','09'][Math.floor(i/15)]}`,`SV-P${i%5+1}`,sold,i%13===0?sold+5:r.int(0,8),r.int(30,60),i%5===0?80:r.int(12,35)];}),
  (rows,T,s)=>{const stats=matched=>{const units=matched.reduce((n,r)=>n+r[2]-r[3],0),rev=matched.reduce((n,r)=>n+(r[2]-r[3])*r[4],0),profit=matched.reduce((n,r)=>n+(r[2]-r[3])*(r[4]-r[5]),0);return[units,round(rev),round(profit),rev===0?'Zero revenue':round(profit/rev*100)];},monthly=s[0].rows.map(([month])=>[month,...stats(rows.filter(r=>r[0]===month))]),products=s[1].rows.map(([product])=>[product,...stats(rows.filter(r=>r[1]===product))]),loss=products.filter(r=>r[3]<0).map(r=>[r[0],r[3]]).sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0]));return[
   T('For the first eight lines, return Net_units, Net_revenue_CAD and Net_profit_CAD (8 × 3). Preserve negative net quantities; round money to cents.',first(rows).map(r=>[r[2]-r[3],round((r[2]-r[3])*r[4]),round((r[2]-r[3])*(r[4]-r[5]))]),'=LET(net,Data!C2:C9-Data!D2:D9,HSTACK(net,ROUND(net*Data!E2:E9,2),ROUND(net*(Data!E2:E9-Data!F2:F9),2)))',['LET','HSTACK','ROUND'],H('Returns reverse both revenue and matching unit cost.','Reuse the signed net-unit array in the two money calculations.','=LET(net,____,HSTACK(net,ROUND(____,2),ROUND(____,2)))')),
   T('Return Month, Net_units, Net_revenue_CAD, Net_profit_CAD and Margin_pct (3 × 5), Months order. Compute margin from monthly totals; Zero revenue for a zero monthly denominator.',monthly,'=LET(months,Months!A2:A4,net,Data!C2:C46-Data!D2:D46,units,MAP(months,LAMBDA(month,SUMPRODUCT(--(Data!A2:A46=month),net))),revenue,MAP(months,LAMBDA(month,SUMPRODUCT(--(Data!A2:A46=month),net,Data!E2:E46))),profit,MAP(months,LAMBDA(month,SUMPRODUCT(--(Data!A2:A46=month),net,Data!E2:E46-Data!F2:F46))),HSTACK(months,units,ROUND(revenue,2),ROUND(profit,2),IF(revenue=0,"Zero revenue",ROUND(profit/revenue*100,2))))',['LET','MAP','SUMPRODUCT','HSTACK','ROUND','IF'],H('Compute margin from selected total profit and total revenue.','Map each month to aligned raw totals before HSTACK.','=LET(months,____,net,____,units,MAP(____),revenue,MAP(____),profit,MAP(____),HSTACK(____,IF(revenue=0,"Zero revenue",____)))')),
   T('Aggregate across all months and return loss-making Product plus Net_profit_CAD (two columns), sorted by profit ascending then Product ascending. Include only strictly negative product profit.',loss,'=LET(products,Products!A2:A6,net,Data!C2:C46-Data!D2:D46,profit,MAP(products,LAMBDA(product,SUMPRODUCT(--(Data!B2:B46=product),net,Data!E2:E46-Data!F2:F46))),report,FILTER(HSTACK(products,ROUND(profit,2)),profit<0),SORTBY(report,CHOOSECOLS(report,2),1,CHOOSECOLS(report,1),1))',['LET','MAP','SUMPRODUCT','FILTER','SORTBY'],H('Select negative aggregated product profit, not individual loss lines.','Map products to totals, filter and sort with a tie key.','=LET(products,____,net,____,profit,MAP(____),report,FILTER(____,____),SORTBY(report,____,1,____,1))')),
   T('Return three independent reconciliations: monthly total net units minus raw net units, monthly revenue minus raw revenue, and monthly profit minus raw profit (1 × 3). Round money differences to cents; reconciled outputs are numeric zero.',[[0,0,0]],'=HSTACK(SUM(Answers!C12:C14)-SUM(Data!C2:C46)+SUM(Data!D2:D46),ROUND(SUM(Answers!D12:D14)-SUMPRODUCT(Data!C2:C46-Data!D2:D46,Data!E2:E46),2),ROUND(SUM(Answers!E12:E14)-SUMPRODUCT(Data!C2:C46-Data!D2:D46,Data!E2:E46-Data!F2:F46),2))',['HSTACK','SUM','SUMPRODUCT','ROUND'],H('Each grouped headline needs a separate raw source calculation.','Subtract raw units, revenue and profit from the respective monthly totals.','=HSTACK(____,ROUND(____,2),ROUND(____,2))'),['=LET(net,Data!C2:C46-Data!D2:D46,HSTACK(SUM(Answers!C12:C14)-SUM(net),SUM(Answers!D12:D14)-SUM(net*Data!E2:E46),SUM(Answers!E12:E14)-SUM(net*(Data!E2:E46-Data!F2:F46))))']),
   T('Review SUMPRODUCT: count raw lines with returns strictly greater than sold units by comparing the two quantities within each row.',rows.filter(r=>r[3]>r[2]).length,'=SUMPRODUCT(--(Data!D2:D46>Data!C2:C46))',['SUMPRODUCT'],H('Compare the two quantities within each row.','Sum the oversold-return Boolean mask.','=SUMPRODUCT(--(____>____))'))
  ];},()=>[sheet('Months',['Month'],[['2026-07'],['2026-08'],['2026-09']]),sheet('Products',['Product'],Array.from({length:5},(_,i)=>[`SV-P${i+1}`]))]);

 add(10,5,'Complete the integrated Charpy capstone','Tervali Pipe Lab has 48 fictitious Charpy replicates for twelve sample/heat pairs. Average numeric duplicate energies by both keys and normalized orientation; round means to two decimals. Training LPA/TWA minima are 27/20 J inclusive; missing means require Review, either low mean means Hold, otherwise Pass.',['LET','MAP'],
  'The capstone combines a key scaffold, guarded replicate means, a decision rule and a reconciled cost summary. Each intermediate result has an explicit shape and business meaning.',
  'Review SORT, UNIQUE, CHOOSECOLS, FILTER, ISNUMBER, ROUND, HSTACK, IF and SUMIFS. Practice combining at least four functions in the orientation-mean rule. Any equivalent formula is accepted. Numeric zero is measured, sample IDs remain text, and costs for Review pairs are pending. Training statuses do not authorize production release.',
  [['sample_no','Leading-zero text sample identifier reused in two heats.'],['heat_no','Invented heat key.'],['Orientation','LPA/TWA with inconsistent case/spaces.'],['Energy_J','Numeric joules, blank unmeasured, zero measured.']],r=>charpy(r,'TV',12),
  (rows,T,s)=>{const keys=distinct(rows.map(r=>r.slice(0,2))).sort((a,b)=>a[1].localeCompare(b[1])||a[0].localeCompare(b[0])),values=orientationMeans(rows,keys),statuses=values.map(v=>v.some(x=>x==='Missing')?'Review':v[0]<27||v[1]<20?'Hold':'Pass'),report=keys.map((k,i)=>[...k,...values[i],statuses[i]]),cost=k=>s[0].rows.find(r=>r[0]===k[0]&&r[1]===k[1])[2],summary=[['Pass','Hold','Review'].map(v=>statuses.filter(x=>x===v).length).concat(keys.reduce((n,k,i)=>n+(statuses[i]==='Hold'?cost(k):0),0))];return[
   T('Return unique sample_no and heat_no pairs (12 × 2), sorted by heat_no ascending then sample_no ascending. No headers; preserve text IDs.',keys,'=LET(keys,UNIQUE(CHOOSECOLS(Data!A2:D49,1,2)),SORTBY(keys,CHOOSECOLS(keys,2),1,CHOOSECOLS(keys,1),1))',['LET','UNIQUE','CHOOSECOLS','SORTBY'],H('Deduplicate complete two-column keys, not sample numbers alone.','UNIQUE the pair array and sort heat before sample.','=LET(keys,UNIQUE(CHOOSECOLS(____,____,____)),SORTBY(keys,____,1,____,1))')),
   T('In task-1 key order, return LPA_mean_J and TWA_mean_J (12 × 2). Average all numeric replicates, round means to two decimals, and return Missing when a numeric group is empty.',values,'=MAP(Answers!B2:B13,Answers!C2:C13,LAMBDA(sampleKey,heatKey,LET(mask,(Data!A2:A49=sampleKey)*(Data!B2:B49=heatKey)*(UPPER(TRIM(Data!C2:C49))="LPA")*ISNUMBER(Data!D2:D49),IF(SUM(mask)=0,"Missing",ROUND(AVERAGE(FILTER(Data!D2:D49,mask)),2)))))',['MAP','LAMBDA','LET','FILTER','ROUND','AVERAGE'],H('Use both identifiers and only numeric energies; blank replicates do not dilute a mean.','MAP the key scaffold to a guarded numeric FILTER mean.','=MAP(____,____,LAMBDA(sampleKey,heatKey,LET(mask,____,IF(SUM(mask)=0,"Missing",ROUND(AVERAGE(FILTER(____,mask)),2)))))'),[],'Enter the LPA column at its anchor; repeat with TWA in the second output column.'),
   T('Return sample_no, heat_no, LPA_mean_J, TWA_mean_J and Status (12 × 5), task-1 order. Review takes precedence over Hold; equal means at the training minima pass.',report,'=LET(lpa,Answers!B16:B27,twa,Answers!C16:C27,HSTACK(Answers!B2:C13,lpa,twa,IF((lpa="Missing")+(twa="Missing"),"Review",IF((lpa<27)+(twa<20),"Hold","Pass"))))',['LET','HSTACK','IF'],H('Do not compare missing means as if they were measured values.','Apply the missing guard before either below-limit test.','=LET(lpa,____,twa,____,HSTACK(____,IF(____,"Review",IF(____,"Hold","Pass"))))')),
   T('Return Pass count, Hold count, Review count and total Hold_cost_CAD for Hold pairs only (1 × 4). Join Costs by both identifiers; count each pair once. Review costs remain pending.',summary,'=LET(keys,Answers!B30:C41,status,Answers!F30:F41,cost,MAP(CHOOSECOLS(keys,1),CHOOSECOLS(keys,2),LAMBDA(sampleKey,heatKey,SUMIFS(Costs!C2:C13,Costs!A2:A13,sampleKey,Costs!B2:B13,heatKey))),HSTACK(COUNTIFS(status,"Pass"),COUNTIFS(status,"Hold"),COUNTIFS(status,"Review"),SUM(FILTER(cost,status="Hold",0))))',['LET','MAP','SUMIFS','COUNTIFS','HSTACK'],H('The cost join must match both sample and heat, and only Hold pairs contribute.','Map each pair to its cost, then select Hold.','=LET(keys,____,status,____,cost,MAP(____,____,LAMBDA(sampleKey,heatKey,SUMIFS(____))),HSTACK(____,SUM(FILTER(cost,____,0))))'),['=HSTACK(COUNTIFS(Answers!F30:F41,"Pass"),COUNTIFS(Answers!F30:F41,"Hold"),COUNTIFS(Answers!F30:F41,"Review"),SUM(MAP(Answers!B30:B41,Answers!C30:C41,Answers!F30:F41,LAMBDA(sampleKey,heatKey,status,IF(status="Hold",SUMIFS(Costs!C2:C13,Costs!A2:A13,sampleKey,Costs!B2:B13,heatKey),0)))))']),
   T('Review COUNTIFS: count Missing orientation mean cells in task 2.',values.flat().filter(v=>v==='Missing').length,'=COUNTIFS(Answers!B16:C27,"Missing")',['COUNTIFS'],H('Count missing orientation outputs, not raw blank replicates.','Apply COUNTIFS to the two mean columns.','=COUNTIFS(____,"Missing")'))
  ];},rows=>[sheet('Costs',['sample_no','heat_no','Hold_cost_CAD'],distinct(rows.map(r=>r.slice(0,2))).map((k,i)=>[...k,250+i*35]))]);
 return packages.sort((a,b)=>a.level-b.level||a.assignment-b.assignment);
}
