// Build-only lessons and answers; this directory is excluded from the publish tree.
const total = (rows, col) => rows.reduce((n, r) => n + r[col], 0);
const round = (n, d = 2) => Math.round((n + Number.EPSILON) * 10 ** d) / 10 ** d;
const clean = s => s.replace(/[\x00-\x1f]/g, '').trim().replace(/ +/g, ' ');
const vector = a => a.map(v => [v]);
const distinct = rows => [...new Map(rows.map(r => [JSON.stringify(r), r])).values()];
const col = n => String.fromCharCode(65 + n);
const FUNCTION = {
 XLOOKUP:['Find a key and return its corresponding value.','=XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])','Supply the key, aligned key and return ranges, optional missing label, match mode (0 exact, -1 next smaller, 1 next larger), and search direction (1 first, -1 last).','=XLOOKUP("P2",{"P1","P2"},{400,450},"Missing")',450,'Retrieve a specification or allowance.','Exact is the default. A first match does not aggregate duplicates. Binary search requires correctly sorted keys.'],
 INDEX:['Return the value at a row and column position.','=INDEX(array, row_num, [column_num])','array contains values; row_num selects its row and optional column_num selects its column.','=INDEX({20,30;40,50},2,1)',40,'Select an item in a specification matrix.','Row positions are relative to the selected array, not worksheet row numbers.'],
 MATCH:['Find the relative position of a value.','=MATCH(lookup_value, lookup_array, [match_type])','lookup_value is the key; lookup_array is one row or column; use match_type 0 for exact matching.','=MATCH("Night",{"Day","Night"},0)',2,'Find a row or column position for INDEX.','Omitting 0 requests approximate matching, which has ordering requirements.'],
 TRIM:['Remove outer spaces and repeated ordinary spaces.','=TRIM(text)','text is the string or cell to clean.','=TRIM("  A   B  ")','A B','Normalize imported identifiers.','Nonbreaking spaces are not ordinary spaces; replace them deliberately.'],
 CLEAN:['Remove ASCII control characters.','=CLEAN(text)','text is the string or reference containing unwanted control characters.','=CLEAN("A"&CHAR(9)&"B")','AB','Remove tabs from exported codes.','CLEAN does not remove every Unicode invisible character.'],
 UPPER:['Convert letters to uppercase.','=UPPER(text)','text is the input string or cell.','=UPPER("ab-7")','AB-7','Make a canonical product key.','It does not remove spaces or change numeric values.'],
 LEFT:['Extract the first characters.','=LEFT(text, [num_chars])','text is the source; num_chars is the count, defaulting to 1.','=LEFT("NX-410",2)','NX','Read a fixed-width prefix.','Count positions after cleaning the input.'],
 RIGHT:['Extract the last characters.','=RIGHT(text, [num_chars])','text is the source; num_chars is the count, defaulting to 1.','=RIGHT("NX-410",3)','410','Read a fixed-width suffix.','The returned digits are text until explicitly converted.'],
 MID:['Extract characters starting at a position.','=MID(text, start_num, num_chars)','text is the source; start_num is a 1-based position; num_chars is the count.','=MID("AB-12-Z",4,2)','12','Read a fixed-width code segment.','Position 1 is the first character; separators count too.'],
 TEXTBEFORE:['Read text before a delimiter.','=TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])','Provide input and delimiter; optional instance chooses occurrence, match_mode controls case, match_end treats end as delimiter, and if_not_found supplies a fallback.','=TEXTBEFORE("H7|S2","|")','H7','Extract the heat portion of a compound ID.','Negative instance numbers search from the end. Missing delimiters need an explicit fallback.'],
 TEXTAFTER:['Read text after a delimiter.','=TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])','Arguments mirror TEXTBEFORE: input, delimiter, occurrence, case mode, end matching, and missing fallback.','=TEXTAFTER("H7|S2","|")','S2','Extract a sample or order segment.','The first and last delimiter produce different results in multi-part keys.'],
 TEXTSPLIT:['Split text into a spilled array.','=TEXTSPLIT(text, col_delimiter, [row_delimiter], [ignore_empty], [match_mode], [pad_with])','Input and column delimiter are required. Optional row delimiter creates rows; ignore_empty omits empty fields, match_mode controls case and pad_with fills gaps.','=TEXTSPLIT("A|B|C","|")','A, B, C in three columns','Separate manifest fields.','Leave enough empty cells for the spill. Ignoring empty fields changes their positions.'],
 TEXTJOIN:['Join values with a chosen separator.','=TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)','delimiter separates values; ignore_empty is TRUE/FALSE; remaining arguments supply text or ranges.','=TEXTJOIN(" / ",TRUE,"A","","B")','A / B','Create readable lists.','Ignoring empty cells changes the output; choose deliberately.'],
 SUBSTITUTE:['Replace specified text.','=SUBSTITUTE(text, old_text, new_text, [instance_num])','Input, old text and replacement are required. Optional instance_num limits replacement to one occurrence.','=SUBSTITUTE("A_B_C","_","-")','A-B-C','Normalize separators.','Replacement is case-sensitive; it is not a wildcard search.'],
 TEXT:['Format a value as text.','=TEXT(value, format_text)','value is numeric/date data; format_text is a quoted Excel number-format code.','=TEXT(12.5,"0.00")','12.50','Include formatted measurements in a sentence.','The result is text and should not replace numeric calculation inputs.'],
 PROPER:['Capitalize each word.','=PROPER(text)','text is the string or reference.','=PROPER("nora vale")','Nora Vale','Present fictitious customer names.','Acronyms and mixed-case brands may need deliberate exceptions.'],
 DATE:['Construct an Excel date from components.','=DATE(year, month, day)','Supply a four-digit year, month number and day number.','=TEXT(DATE(2026,2,3),"yyyy-mm-dd")','2026-02-03','Build locale-independent dates.','Excel normalizes overflow days/months; validate unexpected components.'],
 EOMONTH:['Find a month-end date.','=EOMONTH(start_date, months)','start_date is a date; months is the forward/backward month offset.','=TEXT(EOMONTH(DATE(2026,2,3),0),"yyyy-mm-dd")','2026-02-28','Set a reporting cutoff.','It returns a date serial; apply a date format or TEXT for submission.'],
 EDATE:['Shift a date by whole months.','=EDATE(start_date, months)','Supply a start date and signed month offset.','=TEXT(EDATE(DATE(2026,1,31),1),"yyyy-mm-dd")','2026-02-28','Plan replenishment or contract renewal.','Shorter months clamp to their last day; 30 days is not one calendar month.'],
 NETWORKDAYS:['Count working days inclusively.','=NETWORKDAYS(start_date, end_date, [holidays])','Start and end dates are required. Optional holidays lists excluded dates; Saturday/Sunday are weekends.','=NETWORKDAYS(DATE(2026,9,7),DATE(2026,9,11))',5,'Measure an inclusive review window.','Both endpoints count when they are working days. Holiday dates must be real dates.'],
 WORKDAY:['Move by working days.','=WORKDAY(start_date, days, [holidays])','Start date and signed working-day offset are required; holidays optionally excludes dates.','=TEXT(WORKDAY(DATE(2026,9,7),5),"yyyy-mm-dd")','2026-09-14','Calculate a processing deadline.','The start day is not day 1 of the offset. It differs from inclusive NETWORKDAYS.'],
 WEEKNUM:['Assign a calendar week number.','=WEEKNUM(serial_number, [return_type])','serial_number is a date; return_type 2 means Monday-start weeks with the week containing January 1 as week 1.','=WEEKNUM(DATE(2026,1,1),2)',1,'Group activity into stated calendar weeks.','Return type 2 is not ISO week numbering; ISO uses return type 21.'],
 DATEDIF:['Count complete date intervals.','=DATEDIF(start_date, end_date, unit)','Use ordered dates and quoted unit "Y" for complete years or "M" for complete months.','=DATEDIF(DATE(2024,6,15),DATE(2026,6,14),"Y")',1,'Calculate completed employee service years.','End before start errors. Avoid the problematic MD unit; years are not elapsed days divided by 365.'],
 MOD:['Return the remainder after division.','=MOD(number, divisor)','number is the input and divisor the division base.','=MOD(3-22,24)',5,'Calculate overnight duration for shifts shorter than 24 hours.','MOD hides whole days; it is inappropriate for multi-day durations.'],
 TIME:['Construct a time from components.','=TIME(hour, minute, second)','Supply hours, minutes and seconds; output is a fraction of one day.','=TEXT(TIME(7,30,0),"hh:mm")','07:30','Build time values without locale-dependent text parsing.','Hours above 23 wrap; do not use TIME to preserve multi-day durations.'],
 FILTER:['Keep rows or columns meeting a condition.','=FILTER(array, include, [if_empty])','array supplies data, include is an aligned TRUE/FALSE condition array, and if_empty handles no matches.','=FILTER({2;7;9},{FALSE;TRUE;TRUE},"None")','7 and 9 in two rows','Extract inspection exceptions.','Blank output cells are needed. AND combines criteria with multiplication, OR with addition.'],
 SORT:['Sort a dynamic array.','=SORT(array, [sort_index], [sort_order], [by_col])','Choose the data, optional 1-based key column/row, order (1 ascending/-1 descending), and by_col TRUE to sort columns.','=SORT({9;2;7})','2, 7, 9 in three rows','Order a filtered report.','Sorting by one key leaves ties; use SORTBY for explicit secondary keys.'],
 SORTBY:['Sort by one or more aligned key arrays.','=SORTBY(array, by_array1, [sort_order1], [by_array2], [sort_order2], ...)','array is returned; each by_array and order pair supplies a primary or subsequent key.','=SORTBY({"A";"B"},{3;1},1)','B then A','Prioritize orders with a deterministic tie-break.','Key arrays must align with the returned rows.'],
 UNIQUE:['Return distinct values or rows.','=UNIQUE(array, [by_col], [exactly_once])','array supplies values; by_col TRUE compares columns; exactly_once TRUE returns only entries occurring once.','=UNIQUE({"A";"B";"A"})','A then B','Create distinct heat/sample pairs.','A two-column input distinguishes full row pairs, not each column independently.'],
 SEQUENCE:['Generate a numeric array.','=SEQUENCE(rows, [columns], [start], [step])','Specify rows; optional columns, starting value and increment determine the grid.','=SEQUENCE(3,1,10,2)','10, 12, 14','Number rows or create planned sample indices.','Rows and columns must be positive; these numbers do not become observations.'],
 CHOOSECOLS:['Select and reorder array columns.','=CHOOSECOLS(array, col_num1, [col_num2], ...)','Provide an array and 1-based column indices; negative indices count from its right edge.','=CHOOSECOLS({1,2,3;4,5,6},3,1)','3,1 then 6,4','Build a compact quality report.','Index zero or outside the width errors.'],
 CHOOSEROWS:['Select and reorder array rows.','=CHOOSEROWS(array, row_num1, [row_num2], ...)','Provide the array and 1-based row indices; negative indices count back from its last row.','=CHOOSEROWS({10;20;30},1,-1)','10 then 30','Inspect the first and last records.','Indices apply to the current array, after any filtering or sorting.'],
 VSTACK:['Append arrays vertically.','=VSTACK(array1, [array2], ...)','Supply arrays to append in order, preserving their column positions.','=VSTACK({1,2},{3,4})','1,2 then 3,4','Combine two aligned production extracts.','Different widths create padded #N/A cells; align the schema first.'],
 HSTACK:['Append arrays horizontally.','=HSTACK(array1, [array2], ...)','Supply arrays to append side by side, with matching row counts.','=HSTACK({1;2},{3;4})','1,3 then 2,4','Put orientation results beside sample keys.','Different heights cause #N/A padding; row identity must also agree.'],
 TAKE:['Keep leading or trailing rows/columns.','=TAKE(array, rows, [columns])','Signed rows selects first/last rows; optional signed columns selects first/last columns.','=TAKE({10;20;30},2)','10 then 20','Show a bounded priority list.','Zero rows errors; ensure enough rows for the requested result.'],
 DROP:['Remove leading or trailing rows/columns.','=DROP(array, rows, [columns])','Signed rows removes leading/trailing rows; optional columns does the same for columns.','=DROP({10;20;30},1)','20 then 30','Exclude a known first record in a combined extract.','Dropping the entire array leaves an empty-array error.']
};
export function phase2Packages(randomFor) {
 const packages=[];
 function add(level,assignment,title,scenario,names,intro,combine,headers,makeRows,makeTasks,sheets=[]) {
  const id=`L${level}-A${assignment}`,rows=makeRows(randomFor(id)), extra=typeof sheets==='function'?sheets(rows):sheets;
  let cursor=2;
  const T=(prompt,answer,model,formulas,hints,options={})=>{
   const matrix=Array.isArray(answer)?(Array.isArray(answer[0])?answer:vector(answer)):null;
   const h=matrix?.length||1,w=matrix?.[0]?.length||1,start=cursor;
   cursor+=h+2;
   const output=`Answers!B${start}`+(matrix?`:${col(w)}${start+h-1}`:'');
   const note=model.match(/ \[([^\]]+)\]$/)?.[1];
   return {public:{prompt,output,type:matrix?'array':typeof answer==='number'?'number':'text',formulas},private:{answer:matrix||answer,model:model.replace(/ \[[^\]]+\]$/,''),...(note?{note}:{}),alternatives:options.alternatives||[],tolerance:options.tolerance??1e-6,orderInsensitive:options.orderInsensitive||false,hints}};
  };
  const specs=makeTasks(rows,T,extra);specs.forEach((t,i)=>{t.public.id=t.private.id=i===specs.length-1?'bonus':`t${i+1}`;});
  const columns=headers.map(name=>({name,description:name.replaceAll('_',' ')+'. See scenario for business rules.'}));
  const lesson={intro,functions:names.map(name=>{const [purpose,syntax,args,example,result,useCase,mistake]=FUNCTION[name];return{name,purpose,syntax,arguments:args,example,result,useCase,mistake};}),combine};
  packages.push({id,level,assignment,title,formulas:names,minutes:30+(level-3)*10+assignment*5,scenario,lesson,columns,rows,parameters:[],sheets:extra,tasks:specs.slice(0,-1).map(t=>t.public),bonus:specs.at(-1).public,private:{version:1,tasks:specs.slice(0,-1).map(t=>({...t.private,prompt:t.public.prompt,output:t.public.output})),bonus:{...specs.at(-1).private,prompt:specs.at(-1).public.prompt,output:specs.at(-1).public.output},scenario,columns,rows,sheets:extra}});
 }
 const hints=(issue,technique,skeleton)=>[issue,technique,skeleton];
 const extra=(name,headers,rows)=>({name,headers,rows});
 const six=rows=>rows.slice(0,6);
 const iso=(y,m,d)=>new Date(Date.UTC(y,m-1,d)).toISOString().slice(0,10);
 const parsed=r=>new Date(Date.UTC(r[1],r[2]-1,r[3]));
 const day=ms=>new Date(ms).toISOString().slice(0,10);

 add(3,1,'Match a training specification','Arelvon Tube Lab has 24 invented tensile samples. Match each Product_code to the Specs sheet; a blank or unlisted code must return Missing, and repeated sample records remain separate. These limits are fictitious training rules, not a published standard.',['XLOOKUP','INDEX'],
  'A lookup connects records by an explicit key. Match exact product codes rather than assuming that sample and specification rows are in the same order.',
  'Reuse IF for a strength decision and ROUND when displaying a strength-to-limit ratio. A valid zero and a missing key are different; protect missing matches before doing arithmetic.',
  ['Sample_code','Product_code','Yield_MPa'],r=>Array.from({length:24},(_,i)=>[`AL-S${i+1}`,i===4?'':i===5?'AX-999':`AX-${[3,1,4,2][i%4]}`,r.int(360,480)]),
  (rows,T,s)=>{const lookup=c=>s[0].rows.find(x=>x[0]===c)?.[1]??'Missing';return[
   T('Look up Yield_min_MPa for the first sample’s Product_code.',lookup(rows[0][1]),'=XLOOKUP(Data!B2,Specs!A2:A5,Specs!B2:B5,"Missing")',['XLOOKUP'],hints('Match the product key, not the sample position.','Use exact XLOOKUP with an explicit missing label.','=XLOOKUP(Data!B2,____,Specs!B2:B5,"Missing")')),
   T('Return the second Specs row’s Yield_min_MPa by its position within the four-row specification array.',s[0].rows[1][1],'=INDEX(Specs!B2:B5,2)',['INDEX'],hints('The second array row is worksheet row 3.','Use INDEX on the data portion only.','=INDEX(Specs!B2:B5,____)')),
   T('For the first six samples, return Pass if Yield_MPa is at least the matched minimum, Hold if below it, or Missing if the product key is blank/unlisted. Keep dataset order.',six(rows).map(x=>lookup(x[1])==='Missing'?'Missing':x[2]>=lookup(x[1])?'Pass':'Hold'),'=IF(XLOOKUP(Data!B2,Specs!$A$2:$A$5,Specs!$B$2:$B$5,"Missing")="Missing","Missing",IF(Data!C2>=XLOOKUP(Data!B2,Specs!$A$2:$A$5,Specs!$B$2:$B$5),"Pass","Hold")) [fill down]',['XLOOKUP','IF'],hints('Blank and unlisted products cannot pass. Equality passes.','Guard the missing match before the IF strength comparison.','=IF(XLOOKUP(____)="Missing","Missing",IF(____,"Pass","Hold"))')),
   T('For the first sample, calculate Yield_MPa divided by its matched minimum, rounded to three decimals.',round(rows[0][2]/lookup(rows[0][1]),3),'=ROUND(Data!C2/XLOOKUP(Data!B2,Specs!A2:A5,Specs!B2:B5),3)',['XLOOKUP','ROUND'],hints('Use the first sample’s matched limit as the denominator.','Combine earlier ROUND with XLOOKUP.','=ROUND(Data!C2/____,3)')),
   T('Return the final specification row’s Product_code using its array position.',s[0].rows.at(-1)[0],'=INDEX(Specs!A2:A5,4)',['INDEX'],hints('Use position four within the data array.','INDEX can return text too.','=INDEX(Specs!A2:A5,____)'))
  ];},[extra('Specs',['Product_code','Yield_min_MPa'],[['AX-1',385],['AX-2',400],['AX-3',420],['AX-4',450]])]);

 add(3,2,'Match an employee allowance','Belvori Services has 26 invented employee expense records and six allowance codes. Duplicate employee names are legitimate; Employee_code identifies the record. One unknown and one blank Band_code must receive Missing.',['MATCH','INDEX'],
  'MATCH gives a position; INDEX uses that position to retrieve a value. This separates the key search from the return column and avoids the constraints of column-order lookup methods.',
  'Use MATCH(...,0) for exact keys and earlier IFERROR only for the stated Missing outcome. Reuse ROUND to compare a reimbursement with a monthly allowance; keep references fixed when filling down.',
  ['Employee_code','Employee_name','Band_code','Claim_CAD'],r=>Array.from({length:26},(_,i)=>[`BV-E${i+1}`,['Nora Talven','Iven Rellor','Sena Varyn'][i%3],i===4?'B9':i===5?'':`B${i%6+1}`,r.int(8500,52000)/100]),
  (rows,T,s)=>{const get=x=>s[0].rows.find(v=>v[0]===x)?.[1]??'Missing';return[
   T('Find the 1-based position of the first employee’s Band_code within Allowances!A2:A7.',1,'=MATCH(Data!C2,Allowances!A2:A7,0)',['MATCH'],hints('Return position, not dollars.','Use MATCH with exact mode 0.','=MATCH(Data!C2,____,0)')),
   T('Return the third allowance amount using its row position.',s[0].rows[2][1],'=INDEX(Allowances!B2:B7,3)',['INDEX'],hints('Select the amount array, excluding its header.','Use INDEX with row three.','=INDEX(____,3)')),
   T('For the first six employees, retrieve Monthly_allowance_CAD by exact Band_code, returning Missing for unknown or blank bands.',six(rows).map(x=>get(x[2])),'=IFERROR(INDEX(Allowances!$B$2:$B$7,MATCH(Data!C2,Allowances!$A$2:$A$7,0)),"Missing") [fill down]',['INDEX','MATCH','IFERROR'],hints('Names are not the allowance key. Preserve the missing-band label.','Nest exact MATCH inside INDEX, with IFERROR for the stated fallback.','=IFERROR(INDEX(____,MATCH(Data!C2,____,0)),"Missing")')),
   T('For the first employee, calculate Claim_CAD minus its matched allowance, rounded to two decimals.',round(rows[0][3]-get(rows[0][2])),'=ROUND(Data!D2-INDEX(Allowances!B2:B7,MATCH(Data!C2,Allowances!A2:A7,0)),2)',['INDEX','MATCH','ROUND'],hints('A negative value means the claim is below allowance.','Reuse ROUND around the claim minus lookup result.','=ROUND(Data!D2-INDEX(____),2)')),
   T('For the first employee, return Review when Claim_CAD exceeds the matched allowance, otherwise Within.',rows[0][3]>get(rows[0][2])?'Review':'Within','=IF(Data!D2>INDEX(Allowances!B2:B7,MATCH(Data!C2,Allowances!A2:A7,0)),"Review","Within")',['IF','INDEX','MATCH'],hints('The condition is strictly exceeds, not equals.','Use IF around the matched allowance comparison.','=IF(Data!D2>____,"Review","Within")'))
  ];},[extra('Allowances',['Band_code','Monthly_allowance_CAD'],Array.from({length:6},(_,i)=>[`B${i+1}`,200+i*45]))]);

 add(3,3,'Read a two-way specification matrix','Corvani Alloy Lab has 28 invented inspection records. Each required energy depends on both Grade_code and Orientation, using the Matrix sheet. A blank grade and an unknown orientation are included so an incomplete lookup cannot silently select a default.',['INDEX','MATCH'],
  'A two-way lookup finds both the row and column of a value. Search grade labels vertically and orientation labels horizontally; use their positions inside INDEX.',
  'Reuse IFERROR for Missing and IF for a training-only energy decision. Use exact MATCH for each dimension; matching only the grade can produce a plausible but wrong requirement.',
  ['Record_code','Grade_code','Orientation','Energy_J'],r=>Array.from({length:28},(_,i)=>[`CL-${i+1}`,i===4?'':`G${i%4+1}`,i===5?'ZZ':i%2?'TWA':'LPA',r.int(17,65)]),
  (rows,T,s)=>{const get=x=>{const g=s[0].rows.find(v=>v[0]===x[1]),c=s[0].headers.indexOf(x[2]);return g&&c>0?g[c]:'Missing';};return[
   T('Find the first record’s Grade_code position in Matrix!A2:A5.',1,'=MATCH(Data!B2,Matrix!A2:A5,0)',['MATCH'],hints('Search the grade labels only.','Use exact MATCH.','=MATCH(Data!B2,____,0)')),
   T('Find the first record’s Orientation position within Matrix!B1:C1.',1,'=MATCH(Data!C2,Matrix!B1:C1,0)',['MATCH'],hints('The orientation range has two data-column headers.','Use exact MATCH across the header row.','=MATCH(Data!C2,____,0)')),
   T('For the first six records, return their energy requirement in J from the two-dimensional matrix, or Missing for an absent grade/orientation.',six(rows).map(get),'=IFERROR(INDEX(Matrix!$B$2:$C$5,MATCH(Data!B2,Matrix!$A$2:$A$5,0),MATCH(Data!C2,Matrix!$B$1:$C$1,0)),"Missing") [fill down]',['INDEX','MATCH','IFERROR'],hints('Both keys must exist. Row/column indices refer to the numeric matrix.','Use two MATCH results as INDEX row and column arguments.','=IFERROR(INDEX(____,MATCH(____,0),MATCH(____,0)),"Missing")')),
   T('For the first record, return Pass if Energy_J meets or exceeds its two-way requirement, otherwise Hold.',rows[0][3]>=get(rows[0])?'Pass':'Hold','=IF(Data!D2>=INDEX(Matrix!B2:C5,MATCH(Data!B2,Matrix!A2:A5,0),MATCH(Data!C2,Matrix!B1:C1,0)),"Pass","Hold")',['IF','INDEX','MATCH'],hints('Use the requirement for the same grade and orientation.','Wrap the two-way result in an IF comparison.','=IF(Data!D2>=INDEX(____),"Pass","Hold")')),
   T('Return the difference between the first grade’s LPA and TWA requirements: LPA minus TWA.',s[0].rows[0][1]-s[0].rows[0][2],'=INDEX(Matrix!B2:C5,1,1)-INDEX(Matrix!B2:C5,1,2)',['INDEX'],hints('Both requirements belong to grade G1.','Subtract the second matrix column from the first.','=INDEX(____,1,1)-INDEX(____,1,2)'))
  ];},[extra('Matrix',['Grade_code','LPA','TWA'],[['G1',27,20],['G2',34,25],['G3',40,30],['G4',47,35]])]);

 add(3,4,'Map values to training bands','Delvori Logistics is pricing 30 invented shipments using ascending lower-bound mass bands. Each band includes its lower bound and continues up to the next bound; duplicate masses are valid observations. A negative mass is invalid and must not match a price band.',['XLOOKUP','MATCH'],
  'Approximate matching implements a stated interval rule. Lower-bound tables use the exact match or next smaller key; upper-bound tables require a different mode.',
  'Reuse IF to exclude negative mass and ROUND for freight cost. MATCH with type 1 requires ascending lower bounds. XLOOKUP match_mode -1 expresses exact-or-next-smaller; avoid binary search unless ordering is guaranteed.',
  ['Shipment_code','Mass_kg','Distance_km'],r=>Array.from({length:30},(_,i)=>[`DL-${i+1}`,i===0?25:i===1?50:i===2?100:i===5?-2:r.int(0,180),r.int(8,220)]),
  (rows,T,s)=>{const get=n=>n<0?'Invalid':s[0].rows.filter(x=>x[0]<=n).at(-1)[1];return[
   T('Return Rate_CAD_per_km for the first shipment’s mass using the stated lower-bound bands.',get(rows[0][1]),'=XLOOKUP(Data!B2,Bands!A2:A5,Bands!B2:B5,"Invalid",-1)',['XLOOKUP'],hints('A mass exactly on the lower bound belongs to that band.','Use exact-or-next-smaller XLOOKUP mode -1.','=XLOOKUP(Data!B2,____,Bands!B2:B5,"Invalid",____)')),
   T('Return the first mass’s 1-based band position within Bands!A2:A5.',2,'=MATCH(Data!B2,Bands!A2:A5,1)',['MATCH'],hints('The mass 25 is at the second lower bound.','Use ascending approximate MATCH type 1.','=MATCH(Data!B2,____,1)')),
   T('For the first six shipments, return the rate for each nonnegative mass and Invalid for negative mass.',six(rows).map(x=>get(x[1])),'=IF(Data!B2<0,"Invalid",XLOOKUP(Data!B2,Bands!$A$2:$A$5,Bands!$B$2:$B$5,"Invalid",-1)) [fill down]',['XLOOKUP','IF'],hints('Negative mass is invalid, rather than a zero-band shipment.','Guard the lookup with IF.','=IF(Data!B2<____,"Invalid",XLOOKUP(____,-1))')),
   T('For the first shipment, calculate Distance_km times the matched rate, rounded to cents.',round(rows[0][2]*get(rows[0][1])),'=ROUND(Data!C2*XLOOKUP(Data!B2,Bands!A2:A5,Bands!B2:B5,"Invalid",-1),2)',['ROUND','XLOOKUP'],hints('The rate is per km; the mass selects the band but is not another cost factor.','Multiply distance by the approximate lookup result, then ROUND.','=ROUND(Data!C2*____,2)')),
   T('Return Rate_CAD_per_km for a hypothetical 99.9 kg shipment.',1.5,'=XLOOKUP(99.9,Bands!A2:A5,Bands!B2:B5,"Invalid",-1)',['XLOOKUP'],hints('99.9 is below the 100 kg boundary.','Use the next-smaller lower-bound match.','=XLOOKUP(99.9,____,____,"Invalid",-1)'))
  ];},[extra('Bands',['Lower_kg','Rate_CAD_per_km'],[[0,.8],[25,1.1],[50,1.5],[100,2.2]])]);

 add(3,5,'Audit duplicate and absent keys','Esvani Inspection receives 32 invented sample records and a Limits table. A repeated product key in Limits is deliberately ambiguous; blank/unlisted keys are also present. Use a requirement only when exactly one matching specification row exists.',['XLOOKUP','INDEX','MATCH'],
  'A successful lookup is not evidence that a key is unique. Confirm cardinality first when duplicate specifications would make a decision ambiguous.',
  'Reuse COUNTIFS and IF to require exactly one limit record. Then use XLOOKUP or INDEX/MATCH to retrieve it. IFERROR alone does not detect duplicates because a first-match lookup can succeed.',
  ['Record_code','Product_code','Hardness_HB'],r=>Array.from({length:32},(_,i)=>[`EI-${i+1}`,['EX-1','EX-2','EX-3','EX-9','', 'EX-4'][i%6],r.int(155,245)]),
  (rows,T,s)=>{const matches=k=>s[0].rows.filter(x=>x[0]===k);const get=k=>matches(k).length===1?matches(k)[0][1]:'Review key';return[
   T('For the first six inspection rows, count matching Product_code entries in Limits, excluding its header.',six(rows).map(x=>matches(x[1]).length),'=COUNTIFS(Limits!$A$2:$A$6,Data!B2) [fill down]',['COUNTIFS'],hints('Count duplicate specification records separately.','Reuse COUNTIFS before trusting a lookup.','=COUNTIFS(____,Data!B2)')),
   T('Return the first unique product’s hardness limit using INDEX/MATCH.',get(rows[0][1]),'=INDEX(Limits!B2:B6,MATCH(Data!B2,Limits!A2:A6,0))',['INDEX','MATCH'],hints('Use exact matching and the hardness return range.','Put MATCH inside INDEX.','=INDEX(____,MATCH(Data!B2,____,0))')),
   T('For the first six rows, return the hardness limit only when exactly one Limits row matches; otherwise return Review key.',six(rows).map(x=>get(x[1])),'=IF(COUNTIFS(Limits!$A$2:$A$6,Data!B2)=1,XLOOKUP(Data!B2,Limits!$A$2:$A$6,Limits!$B$2:$B$6),"Review key") [fill down]',['IF','COUNTIFS','XLOOKUP'],hints('Both zero matches and multiple matches require review.','Test match count equals one before the lookup.','=IF(COUNTIFS(____)=____,XLOOKUP(____),"Review key")')),
   T('For the first six rows, return Pass for hardness at most a unique limit, Hold above it, or Review key for any ambiguous/absent key.',six(rows).map(x=>get(x[1])==='Review key'?'Review key':x[2]<=get(x[1])?'Pass':'Hold'),'=IF(COUNTIFS(Limits!$A$2:$A$6,Data!B2)<>1,"Review key",IF(Data!C2<=XLOOKUP(Data!B2,Limits!$A$2:$A$6,Limits!$B$2:$B$6),"Pass","Hold")) [fill down]',['IF','COUNTIFS','XLOOKUP'],hints('Do not compare hardness until the key is unique.','Use a cardinality guard around the earlier IF decision.','=IF(COUNTIFS(____)<>1,"Review key",IF(____,"Pass","Hold"))')),
   T('Count Limits rows with product EX-2.',2,'=COUNTIFS(Limits!A2:A6,"EX-2")',['COUNTIFS'],hints('Duplicate entries are separate rows.','Use COUNTIFS on the specified key.','=COUNTIFS(____,"EX-2")'))
  ];},[extra('Limits',['Product_code','Hardness_max_HB'],[['EX-1',200],['EX-2',210],['EX-2',220],['EX-3',230],['EX-4',240]])]);

 add(4,1,'Clean inspection identifiers','Felnori Mill has 44 invented imported inspection IDs. ASCII tab characters, ordinary outer spaces and inconsistent letter case are deliberate; no nonbreaking spaces occur. Repeated canonical IDs are legitimate retests and must remain separate records.',['TRIM','CLEAN','UPPER'],
  'Cleaning should target the actual messiness. Remove ASCII control characters, collapse ordinary spaces, then standardize case. Keep the raw identifier so the transformation can be traced.',
  'Reuse IF for a classification after cleaning and COUNTA for record counts. CLEAN and TRIM solve different problems; nesting them in the wrong order may preserve a separator you meant to remove.',
  ['Raw_inspection_id','Station','Length_mm'],r=>Array.from({length:44},(_,i)=>[i%3===0?`  fn\t-${i%20+101}  `:i%3===1?`FN-${i%20+101} `:`fn-${i%20+101}`,['Terral','Osvin'][i%2],r.int(5980,6040)]),
  (rows,T)=>[
   T('For the first six records, remove ASCII control characters, trim ordinary spaces and return uppercase canonical inspection IDs.',six(rows).map(x=>clean(x[0]).toUpperCase()),'=UPPER(TRIM(CLEAN(Data!A2))) [fill down]',['UPPER','TRIM','CLEAN'],hints('A tab must disappear; outer spaces and case also need handling.','Combine CLEAN, TRIM and UPPER.','=UPPER(TRIM(____(Data!A2)))')),
   T('Remove control characters and outer ordinary spaces from the first raw ID, preserving its original letter case.',clean(rows[0][0]),'=TRIM(CLEAN(Data!A2))',['TRIM','CLEAN'],hints('Remove the tab and outer spaces; preserve the lowercase letters.','Nest CLEAN inside TRIM.','=TRIM(CLEAN(____))')),
   T('For the first six records, return Retest when the canonical uppercase ID is FN-101, otherwise Other.',six(rows).map(x=>clean(x[0]).toUpperCase()==='FN-101'?'Retest':'Other'),'=IF(UPPER(TRIM(CLEAN(Data!A2)))="FN-101","Retest","Other") [fill down]',['IF','UPPER','TRIM','CLEAN'],hints('Classify the canonical key rather than the messy input.','Reuse IF around the cleaned uppercase ID.','=IF(UPPER(TRIM(CLEAN(____)))="FN-101","Retest","Other")')),
   T('Count populated raw inspection ID cells across all 44 rows. Retests still count as records.',rows.length,'=COUNTA(Data!A2:A45)',['COUNTA'],hints('Count records, not distinct identifiers.','Reuse COUNTA on the raw-ID range.','=COUNTA(____)')),
   T('Return the first cleaned uppercase ID followed by the literal text |CHECK.',clean(rows[0][0]).toUpperCase()+'|CHECK','=UPPER(TRIM(CLEAN(Data!A2)))&"|CHECK"',['UPPER','TRIM','CLEAN'],hints('The separator is a literal vertical bar.','Combine the canonical key with text using &.','=UPPER(TRIM(CLEAN(____)))&"|CHECK"'))
  ]);

 add(4,2,'Read fixed-width business codes','Gorvella Inventory has 48 invented item codes in the fixed pattern AA-NNN-Z. Outer ordinary spaces and mixed-case prefixes are present. Each row is an inventory observation, including repeats of the same SKU.',['LEFT','RIGHT','MID'],
  'Fixed-width codes can be decomposed by character position once their ordinary outer spaces are removed. Hyphens occupy positions just like letters and digits.',
  'Reuse TRIM/UPPER from the prior level-4 lesson, and IF from Level 1 to assign a category. The extracted number remains text; retain its leading zeros.',
  ['Raw_SKU','Stock_units','Unit_price_CAD'],r=>Array.from({length:48},(_,i)=>[` ${i%2?'gv':'GV'}-${String(7+i%30).padStart(3,'0')}-${['A','B','C'][i%3]} `,r.int(12,240),r.int(550,4890)/100]),
  (rows,T)=>[
   T('For the first six records, return the two-letter uppercase prefix after trimming.',six(rows).map(x=>clean(x[0]).slice(0,2).toUpperCase()),'=UPPER(LEFT(TRIM(Data!A2),2)) [fill down]',['LEFT','TRIM','UPPER'],hints('Trim first; otherwise the first character is a space.','Use LEFT with length two, then UPPER.','=UPPER(LEFT(____,2))')),
   T('For the first six records, return the three-character numeric segment as text, preserving leading zeros.',six(rows).map(x=>clean(x[0]).slice(3,6)),'=MID(TRIM(Data!A2),4,3) [fill down]',['MID','TRIM'],hints('The numeric segment starts at character four.','Use MID after TRIM.','=MID(TRIM(____),____,3)')),
   T('For the first six records, return the final one-letter suffix.',six(rows).map(x=>clean(x[0]).slice(-1)),'=RIGHT(TRIM(Data!A2),1) [fill down]',['RIGHT','TRIM'],hints('A trailing space is not the suffix.','Use RIGHT on trimmed input.','=RIGHT(____,1)')),
   T('For the first six records, return Priority for suffix A, otherwise Standard.',six(rows).map(x=>clean(x[0]).endsWith('A')?'Priority':'Standard'),'=IF(RIGHT(TRIM(Data!A2),1)="A","Priority","Standard") [fill down]',['IF','RIGHT','TRIM'],hints('Only suffix A triggers Priority.','Reuse IF with RIGHT.','=IF(RIGHT(____,1)="A","Priority","Standard")')),
   T('Calculate first-row stock value, rounded to cents.',round(rows[0][1]*rows[0][2]),'=ROUND(Data!B2*Data!C2,2)',['ROUND'],hints('Stock value is units times price.','Reuse ROUND on the product.','=ROUND(____,2)'))
  ]);

 add(4,3,'Split compound heat/sample keys','Hervani Testworks has 52 invented key strings HEAT|SAMPLE|ORIENTATION. Mixed orientation case and ordinary spaces are present; two malformed records lack delimiters. Return Missing for a malformed key rather than guessing its components.',['TEXTBEFORE','TEXTAFTER'],
  'Delimiter-based extraction works when segment lengths vary. Identify whether you need the first delimiter, last delimiter or a nested extraction. Validate the stated malformed case.',
  'Reuse IFERROR for Missing and TRIM/UPPER to normalize extracted text. Extraction alone is not validation: a delimiter-free string needs an explicit fallback.',
  ['Raw_key','Energy_J'],r=>Array.from({length:52},(_,i)=>[i===4||i===5?`BAD${i}`:` HV-H${900+Math.floor(i/4)}|S${i%4+1}|${i%2?'twa':'LPA'} `,r.int(16,76)]),
  (rows,T)=>{const part=(x,n)=>x.includes('|')?clean(x).split('|')[n]:'Missing';return[
   T('For the first six records, return the heat segment before the first |, trimmed; return Missing when no delimiter exists.',six(rows).map(x=>part(x[0],0)),'=TRIM(TEXTBEFORE(Data!A2,"|",1,0,0,"Missing")) [fill down]',['TEXTBEFORE','TRIM'],hints('Take the segment before the first delimiter.','Use TEXTBEFORE with if_not_found.','=TRIM(TEXTBEFORE(____,"|",1,0,0,"Missing"))')),
   T('For the first six records, return the orientation after the last |, trimmed and uppercase; preserve the mixed-case fallback Missing.',six(rows).map(x=>part(x[0],2)==='Missing'?'Missing':part(x[0],2).toUpperCase()),'=IFERROR(UPPER(TRIM(TEXTAFTER(Data!A2,"|",-1))),"Missing") [fill down]',['TEXTAFTER','UPPER','TRIM','IFERROR'],hints('The last delimiter precedes orientation. Uppercase the actual value, not the fallback.','Use negative occurrence -1 in TEXTAFTER inside IFERROR.','=IFERROR(UPPER(TRIM(TEXTAFTER(____,"|",____))),"Missing")')),
   T('For the first six records, return the sample segment between the two delimiters; return Missing for malformed keys.',six(rows).map(x=>part(x[0],1)),'=IFERROR(TEXTBEFORE(TEXTAFTER(TRIM(Data!A2),"|"),"|"),"Missing") [fill down]',['TEXTBEFORE','TEXTAFTER','IFERROR'],hints('Remove the heat prefix, then stop before the orientation separator.','Nest TEXTAFTER inside TEXTBEFORE.','=IFERROR(TEXTBEFORE(TEXTAFTER(____,"|"),"|"),"Missing")')),
   T('For the first six records, return Transverse when the normalized final orientation is TWA, Longitudinal for LPA, or Missing for a malformed key.',six(rows).map(x=>part(x[0],2)==='Missing'?'Missing':part(x[0],2).toUpperCase()==='TWA'?'Transverse':'Longitudinal'),'=IFERROR(IF(UPPER(TRIM(TEXTAFTER(Data!A2,"|",-1)))="TWA","Transverse","Longitudinal"),"Missing") [fill down]',['IF','TEXTAFTER','UPPER','IFERROR'],hints('Classify normalized orientations only after successful extraction.','Wrap the earlier IF decision in IFERROR.','=IFERROR(IF(UPPER(TRIM(TEXTAFTER(____)))="TWA","Transverse","Longitudinal"),"Missing")')),
   T('Return the first row’s heat segment plus / plus sample segment.',part(rows[0][0],0)+'/'+part(rows[0][0],1),'=TRIM(TEXTBEFORE(Data!A2,"|"))&"/"&TEXTBEFORE(TEXTAFTER(Data!A2,"|"),"|")',['TEXTBEFORE','TEXTAFTER','TRIM'],hints('Orientation is excluded from the new key.','Join the two extracted segments using &.','=TRIM(TEXTBEFORE(____))&"/"&TEXTBEFORE(TEXTAFTER(____),"|")'))
  ];});

 add(4,4,'Split and rebuild a manifest','Irvella Dispatch has 56 invented manifests in the three-field pattern ORDER|ZONE|PRIORITY. Some Zone fields are intentionally empty; their field positions must be preserved. Blank zones receive Unknown in the standardized display.',['TEXTSPLIT','TEXTJOIN'],
  'A split operation creates cells, while a join creates one text value. Empty-field handling controls whether the original schema remains intact.',
  'Reuse IF to handle empty zones and UPPER/TRIM to standardize display text. TEXTSPLIT ignore_empty FALSE preserves an empty middle field. TEXTJOIN ignore_empty TRUE deliberately removes empty entries from the readable summary.',
  ['Manifest','Cartons_units'],r=>Array.from({length:56},(_,i)=>[`IV-${500+i}|${i%4===0?'':['East','West'][i%2]}|${i%3?'Routine':'Urgent'}`,r.int(4,44)]),
  (rows,T)=>[
   T('Split the first manifest into three columns: order, zone and priority. Preserve the empty zone as an empty cell.',[rows[0][0].split('|')],'=TEXTSPLIT(Data!A2,"|",,FALSE)',['TEXTSPLIT'],hints('The empty middle field must keep its position.','Set ignore_empty FALSE in TEXTSPLIT.','=TEXTSPLIT(Data!A2,"|",,____)')),
   T('For the second manifest, return a readable summary joined with the exact delimiter space / space, ignoring empty fields.',rows[1][0].split('|').filter(Boolean).join(' / '),'=TEXTJOIN(" / ",TRUE,TEXTSPLIT(Data!A3,"|",,FALSE))',['TEXTJOIN','TEXTSPLIT'],hints('Use the stated spaces around the slash.','Feed the split array to TEXTJOIN.','=TEXTJOIN(" / ",____,TEXTSPLIT(____))')),
   T('For the first six manifests, return their middle zone; replace an empty zone with Unknown.',six(rows).map(x=>x[0].split('|')[1]||'Unknown'),'=IF(INDEX(TEXTSPLIT(Data!A2,"|",,FALSE),1,2)="","Unknown",INDEX(TEXTSPLIT(Data!A2,"|",,FALSE),1,2)) [fill down]',['IF','INDEX','TEXTSPLIT'],hints('The zone is field two, even when empty.','Reuse INDEX and IF on a split array preserving empty fields.','=IF(INDEX(TEXTSPLIT(____),1,2)="","Unknown",____)')),
   T('For the first manifest, rebuild all three fields using delimiter | and keeping empty fields; the result must equal the source.',rows[0][0],'=TEXTJOIN("|",FALSE,TEXTSPLIT(Data!A2,"|",,FALSE))',['TEXTJOIN','TEXTSPLIT'],hints('The consecutive delimiters represent a real empty field.','Set both split/join empty-handling options deliberately.','=TEXTJOIN("|",____,TEXTSPLIT(____,"|",,FALSE))')),
   T('Return the first manifest’s priority in uppercase.',rows[0][0].split('|')[2].toUpperCase(),'=UPPER(INDEX(TEXTSPLIT(Data!A2,"|",,FALSE),1,3))',['UPPER','INDEX','TEXTSPLIT'],hints('Priority is the third field.','Select field three from the split array, then UPPER.','=UPPER(INDEX(TEXTSPLIT(____),1,3))'))
  ]);

 add(4,5,'Build readable measurement messages','Jelvani Quality Services has 60 invented readings for a training report. Raw sample IDs use underscores and inconsistent case; numeric measurements must remain numeric in Data. Messages need stable decimal places and standardized text.',['SUBSTITUTE','TEXT','PROPER'],
  'Report text is a presentation layer. Normalize a separator deliberately, and format numeric values only when assembling a message. Preserve raw readings for analysis.',
  'Reuse ROUND for numeric results and IF for a training threshold. TEXT("0.00") controls displayed decimals, while ROUND changes the numeric value. PROPER is suitable for these invented plain names; it is not a universal name-correction rule.',
  ['Raw_sample','Technician_name','Reading_mm'],r=>Array.from({length:60},(_,i)=>[` jq_s_${i+1} `,['nora talven','iven rellor','sena varyn'][i%3],r.int(12101,13299)/1000]),
  (rows,T)=>[
   T('For the first six records, replace all underscores with hyphens, trim ordinary spaces and uppercase the sample ID.',six(rows).map(x=>clean(x[0]).replaceAll('_','-').toUpperCase()),'=UPPER(TRIM(SUBSTITUTE(Data!A2,"_","-"))) [fill down]',['SUBSTITUTE','TRIM','UPPER'],hints('Replace every underscore, not just the first.','Use SUBSTITUTE without an instance limit.','=UPPER(TRIM(SUBSTITUTE(____,"_","-")))')),
   T('For the first six records, return Reading_mm as text with exactly three decimals.',six(rows).map(x=>x[2].toFixed(3)),'=TEXT(Data!C2,"0.000") [fill down]',['TEXT'],hints('The output is text with trailing zeros when needed.','Use TEXT and a three-decimal format code.','=TEXT(____,"0.000")')),
   T('For the first six technicians, return title-case names.',six(rows).map(x=>x[1].replace(/\b\w/g,c=>c.toUpperCase())),'=PROPER(Data!B2) [fill down]',['PROPER'],hints('Capitalize both words.','Use PROPER on the name column.','=PROPER(____)')),
   T('For the first six records, create messages SAMPLE: 0.00 mm | STATUS, where SAMPLE is the normalized ID, STATUS is Review if the unrounded reading exceeds 13.00, otherwise Within. Use exactly the shown spaces and two displayed decimals.',six(rows).map(x=>`${clean(x[0]).replaceAll('_','-').toUpperCase()}: ${round(x[2]).toFixed(2)} mm | ${x[2]>13?'Review':'Within'}`),'=UPPER(TRIM(SUBSTITUTE(Data!A2,"_","-")))&": "&TEXT(Data!C2,"0.00")&" mm | "&IF(Data!C2>13,"Review","Within") [fill down]',['SUBSTITUTE','TEXT','IF','TRIM','UPPER'],hints('Compare the original numeric reading, then format it for display.','Combine standardized ID, TEXT and an earlier IF decision.','=UPPER(TRIM(SUBSTITUTE(____)))&": "&TEXT(____,"0.00")&" mm | "&IF(____,"Review","Within")')),
   T('Return the first reading rounded numerically to two decimals.',round(rows[0][2]),'=ROUND(Data!C2,2)',['ROUND'],hints('A numeric result differs from formatted report text.','Reuse ROUND.','=ROUND(____,2)'))
  ]);

 add(5,1,'Build a test reporting calendar','Kelvani Materials Lab has 44 invented test-date components. Dates are valid numeric year/month/day values, avoiding locale-dependent parsing. Reporting months use calendar month ends; repeated test dates remain separate samples.',['DATE','EOMONTH'],
  'Construct dates from explicit components rather than trusting a computer’s regional date interpretation. Date functions return serial values; submit ISO text where requested.',
  'Reuse TEXT from Level 4 to return yyyy-mm-dd and COUNTIFS from Level 2 for component counts. The reporting cutoff is month end, including leap-year rules handled by Excel.',
  ['Sample_code','Year','Month','Day','Energy_J'],r=>Array.from({length:44},(_,i)=>[`KM-${i+1}`,2026,i%3+7,i%27+1,r.int(22,82)]),
  (rows,T)=>[
   T('For the first six records, construct dates and return ISO text yyyy-mm-dd.',six(rows).map(x=>iso(x[1],x[2],x[3])),'=TEXT(DATE(Data!B2,Data!C2,Data!D2),"yyyy-mm-dd") [fill down]',['DATE','TEXT'],hints('Use year, month and day in the correct order.','Construct DATE, then format with TEXT.','=TEXT(DATE(____,____,____),"yyyy-mm-dd")')),
   T('For the first six records, return the calendar month-end cutoff as ISO text.',six(rows).map(x=>day(Date.UTC(x[1],x[2],0))),'=TEXT(EOMONTH(DATE(Data!B2,Data!C2,Data!D2),0),"yyyy-mm-dd") [fill down]',['EOMONTH','DATE','TEXT'],hints('Offset zero means the same month.','Use EOMONTH on the constructed date.','=TEXT(EOMONTH(DATE(____),____),"yyyy-mm-dd")')),
   T('For the first record, count calendar days from its test date to month end, excluding the starting date.',(Date.UTC(rows[0][1],rows[0][2],0)-parsed(rows[0]).getTime())/86400000,'=EOMONTH(DATE(Data!B2,Data!C2,Data!D2),0)-DATE(Data!B2,Data!C2,Data!D2)',['EOMONTH','DATE'],hints('Subtract date serials; do not add one.','Month end minus test date gives elapsed calendar days.','=EOMONTH(DATE(____),0)-DATE(____)')),
   T('Count all records whose Month component equals 7.',rows.filter(x=>x[2]===7).length,'=COUNTIFS(Data!C2:C45,7)',['COUNTIFS'],hints('Count rows, including repeated dates.','Reuse COUNTIFS on the Month component.','=COUNTIFS(____,7)')),
   T('Return the month end three calendar months after the first test date, as ISO text.',day(Date.UTC(rows[0][1],rows[0][2]+3,0)),'=TEXT(EOMONTH(DATE(Data!B2,Data!C2,Data!D2),3),"yyyy-mm-dd")',['EOMONTH','DATE','TEXT'],hints('Use an offset of three months, not 90 days.','Set the EOMONTH offset to three.','=TEXT(EOMONTH(DATE(____),____),"yyyy-mm-dd")'))
  ]);

 add(5,2,'Plan calendar-month replenishment','Lervella Stores has 48 invented replenishment records. Year, month and day are explicit components; first-row January 31 exercises a shorter-month boundary. Renewal_months are whole calendar months, not fixed 30-day intervals.',['EDATE','EOMONTH'],
  'Calendar-month offsets preserve the intended day where possible, clamping it when the destination month is shorter. Month-end reporting uses a separate function.',
  'Reuse DATE to build the source date and TEXT for ISO submission. Reuse ROUND for order value; keeping date and financial calculations separate makes their units clear.',
  ['SKU','Year','Month','Day','Renewal_months','Units','Unit_cost_CAD'],r=>Array.from({length:48},(_,i)=>[`LS-${i+1}`,2026,i===0?1:i%8+1,i===0?31:i%27+1,i%3+1,r.int(15,100),r.int(350,2450)/100]),
  (rows,T)=>{const shift=x=>{const m=x[2]-1+x[4],last=new Date(Date.UTC(x[1],m+1,0)).getUTCDate();return day(Date.UTC(x[1],m,Math.min(x[3],last)));};return[
   T('For the first six records, return the renewal date after Renewal_months calendar months, as ISO text.',six(rows).map(shift),'=TEXT(EDATE(DATE(Data!B2,Data!C2,Data!D2),Data!E2),"yyyy-mm-dd") [fill down]',['EDATE','DATE','TEXT'],hints('January 31 plus one month clamps to February month end.','Use EDATE, not a fixed day increment.','=TEXT(EDATE(DATE(____),____),"yyyy-mm-dd")')),
   T('For the first six records, return the month end of each renewal month as ISO text.',six(rows).map(x=>day(Date.UTC(x[1],x[2]+x[4],0))),'=TEXT(EOMONTH(DATE(Data!B2,Data!C2,Data!D2),Data!E2),"yyyy-mm-dd") [fill down]',['EOMONTH','DATE','TEXT'],hints('Return the final day of the shifted month.','Use EOMONTH with the row’s month offset.','=TEXT(EOMONTH(DATE(____),____),"yyyy-mm-dd")')),
   T('For the first record, calculate elapsed calendar days from the starting date to its renewal date.',(new Date(shift(rows[0])).getTime()-parsed(rows[0]).getTime())/86400000,'=EDATE(DATE(Data!B2,Data!C2,Data!D2),Data!E2)-DATE(Data!B2,Data!C2,Data!D2)',['EDATE','DATE'],hints('Calendar-month duration is not always 30 days.','Subtract the constructed start date from EDATE.','=EDATE(DATE(____),____)-DATE(____)')),
   T('Calculate first-row order value rounded to cents.',round(rows[0][5]*rows[0][6]),'=ROUND(Data!F2*Data!G2,2)',['ROUND'],hints('Multiply units by unit cost.','Reuse ROUND.','=ROUND(____,2)')),
   T('Return the first record’s month end one month before its starting date, as ISO text.',day(Date.UTC(rows[0][1],rows[0][2]-1,0)),'=TEXT(EOMONTH(DATE(Data!B2,Data!C2,Data!D2),-1),"yyyy-mm-dd")',['EOMONTH','DATE','TEXT'],hints('A negative offset goes backward.','Use EOMONTH offset -1.','=TEXT(EOMONTH(DATE(____),____),"yyyy-mm-dd")'))
  ];});

 const holidayDates=['2026-09-07','2026-09-16'];
 const isWork=ms=>{const d=new Date(ms);return d.getUTCDay()!==0&&d.getUTCDay()!==6&&!holidayDates.includes(day(ms));};
 const workOffset=(ms,n)=>{let left=n;while(left){ms+=86400000;if(isWork(ms))left--;}return day(ms);};
 add(5,3,'Calculate working-day review deadlines','Melvani Process Lab has 52 invented review starts and target working-day durations. Only the two dates in Holidays are excluded; they are invented shutdown days, not a statutory holiday calendar. Saturday and Sunday are weekends.',['WORKDAY','NETWORKDAYS'],
  'A working-day offset and an inclusive count answer different questions. The start day is excluded from WORKDAY’s positive offset, but included in NETWORKDAYS when eligible.',
  'Reuse DATE and TEXT. Build the Holidays cells into real Excel dates from the supplied components; text formatted to look like a date is insufficient. Reuse IF to flag a working-day count above a stated limit.',
  ['Review_code','Year','Month','Day','Target_workdays'],r=>Array.from({length:52},(_,i)=>[`MP-${i+1}`,2026,9,i%24+1,r.int(2,9)]),
  (rows,T)=>{const count=x=>{let n=0;const start=parsed(x).getTime(),end=new Date(workOffset(start,x[4])).getTime();for(let ms=start;ms<=end;ms+=86400000)if(isWork(ms))n++;return n;};return[
   T('First create Holidays!E2:E3 as real dates using the Year/Month/Day components in B:D. Then return those two dates as ISO text in their source order.',holidayDates,'=TEXT(DATE(Holidays!B2,Holidays!C2,Holidays!D2),"yyyy-mm-dd") [fill down; put DATE values in Holidays!E2:E3]',['DATE','TEXT'],hints('The holiday date cells used by later tasks must contain date serials.','Use DATE on each holiday’s components.','=TEXT(DATE(Holidays!____,Holidays!____,Holidays!____),"yyyy-mm-dd")')),
   T('For the first six reviews, return the deadline Target_workdays working days after the start date, excluding the stated shutdown dates. Submit ISO text.',six(rows).map(x=>workOffset(parsed(x).getTime(),x[4])),'=TEXT(WORKDAY(DATE(Data!B2,Data!C2,Data!D2),Data!E2,Holidays!$E$2:$E$3),"yyyy-mm-dd") [fill down]',['WORKDAY','DATE','TEXT'],hints('Do not count the start date as offset day one. Exclude both shutdown dates.','Use WORKDAY with the real holiday-date range.','=TEXT(WORKDAY(DATE(____),Data!E2,____),"yyyy-mm-dd")')),
   T('For the first six reviews, count working days inclusively from the start date through the computed deadline, excluding the stated shutdowns.',six(rows).map(count),'=NETWORKDAYS(DATE(Data!B2,Data!C2,Data!D2),WORKDAY(DATE(Data!B2,Data!C2,Data!D2),Data!E2,Holidays!$E$2:$E$3),Holidays!$E$2:$E$3) [fill down]',['NETWORKDAYS','WORKDAY','DATE'],hints('An eligible start day adds one to the offset count. A weekend/shutdown start does not.','Use NETWORKDAYS over the start and computed deadline.','=NETWORKDAYS(DATE(____),WORKDAY(____),____)')),
   T('For the first six reviews, return Extended when the inclusive working-day count exceeds 6, otherwise Standard.',six(rows).map(x=>count(x)>6?'Extended':'Standard'),'=IF(NETWORKDAYS(DATE(Data!B2,Data!C2,Data!D2),WORKDAY(DATE(Data!B2,Data!C2,Data!D2),Data!E2,Holidays!$E$2:$E$3),Holidays!$E$2:$E$3)>6,"Extended","Standard") [fill down]',['IF','NETWORKDAYS','WORKDAY'],hints('Apply the threshold to the inclusive count, not the offset parameter.','Reuse IF around NETWORKDAYS.','=IF(NETWORKDAYS(____)>____,"Extended","Standard")')),
   T('Return the first review’s deadline with no shutdown exclusions, as ISO text.',(()=>{let ms=parsed(rows[0]).getTime(),n=rows[0][4];while(n){ms+=86400000;if(![0,6].includes(new Date(ms).getUTCDay()))n--;}return day(ms);})(),'=TEXT(WORKDAY(DATE(Data!B2,Data!C2,Data!D2),Data!E2),"yyyy-mm-dd")',['WORKDAY','DATE','TEXT'],hints('This bonus deliberately omits shutdown dates, but keeps weekends excluded.','Use WORKDAY without the optional holidays range.','=TEXT(WORKDAY(DATE(____),____),"yyyy-mm-dd")'))
  ];},[extra('Holidays',['Shutdown_code','Year','Month','Day','Shutdown_date'],[['SD-A',2026,9,7,''],['SD-B',2026,9,16,'']])]);

 add(5,4,'Analyze completed employee service','Norvella Business Support has 56 invented employment records. Use the fixed reporting date October 1, 2026, not today. Dates are provided as explicit components; completed years/months exclude partial intervals.',['DATEDIF','WEEKNUM'],
  'Completed service is a calendar calculation. Use a fixed reporting date so the assignment’s answer remains reproducible. Calendar week rules must also be stated explicitly.',
  'Reuse DATE, IF and COUNTIFS. WEEKNUM return type 2 uses Monday-start weeks with the week containing January 1 numbered one; it is not ISO numbering. DATEDIF Y/M avoids the problematic MD unit.',
  ['Employee_code','Year','Month','Day'],r=>Array.from({length:56},(_,i)=>[`NB-${i+1}`,2020+i%6,i%12+1,i%27+1]),
  (rows,T)=>{const months=x=>(2026-x[1])*12+10-x[2]-(x[3]>1?1:0);const years=x=>Math.floor(months(x)/12);const week=x=>{const date=parsed(x),jan=new Date(Date.UTC(x[1],0,1));return Math.floor(((date-jan)/86400000+(jan.getUTCDay()+6)%7)/7)+1;};return[
   T('For the first six employees, return completed years of service through October 1, 2026.',six(rows).map(years),'=DATEDIF(DATE(Data!B2,Data!C2,Data!D2),DATE(2026,10,1),"Y") [fill down]',['DATEDIF','DATE'],hints('Partial years do not count. Use the fixed reporting date.','Use DATEDIF unit Y.','=DATEDIF(DATE(____),DATE(2026,10,1),____)')),
   T('For the first six employees, return completed months of service through the same fixed date.',six(rows).map(months),'=DATEDIF(DATE(Data!B2,Data!C2,Data!D2),DATE(2026,10,1),"M") [fill down]',['DATEDIF','DATE'],hints('Count complete calendar months, not days divided by 30.','Use DATEDIF unit M.','=DATEDIF(DATE(____),DATE(2026,10,1),____)')),
   T('For the first six start dates, return Monday-start calendar week numbers under WEEKNUM return type 2.',six(rows).map(week),'=WEEKNUM(DATE(Data!B2,Data!C2,Data!D2),2) [fill down]',['WEEKNUM','DATE'],hints('This is the January-1 week convention, not ISO.','Specify WEEKNUM return type 2.','=WEEKNUM(DATE(____),____)')),
   T('For the first six employees, return Established for at least three completed years, otherwise Developing.',six(rows).map(x=>years(x)>=3?'Established':'Developing'),'=IF(DATEDIF(DATE(Data!B2,Data!C2,Data!D2),DATE(2026,10,1),"Y")>=3,"Established","Developing") [fill down]',['IF','DATEDIF','DATE'],hints('Equality at three completed years qualifies.','Reuse IF around DATEDIF Y.','=IF(DATEDIF(____,"Y")>=____,"Established","Developing")')),
   T('Count employees with Year component 2025 across the entire register.',rows.filter(x=>x[1]===2025).length,'=COUNTIFS(Data!B2:B57,2025)',['COUNTIFS'],hints('Count source year values, rather than derived service years.','Reuse COUNTIFS on the Year column.','=COUNTIFS(____,2025)'))
  ];});

 add(5,5,'Measure overnight production shifts','Orvani Rolling has 60 invented shifts with start/end hour and minute components. Every shift lasts under 24 hours; a lower end time means it crosses midnight. Unpaid break minutes are subtracted once, and training Review means net hours strictly above 8.',['TIME','MOD'],
  'Excel times are fractions of a day. An overnight subtraction can be negative, so use a remainder modulo one day and multiply by 24 for hours.',
  'Reuse ROUND for reported hours and IF for the review flag. Divide break minutes by 60 before subtracting from hours. The stated under-24-hour assumption is essential: MOD cannot retain elapsed whole days.',
  ['Shift_code','Start_hour','Start_minute','End_hour','End_minute','Break_min'],r=>Array.from({length:60},(_,i)=>{const start=[6,14,22][i%3],duration=r.int(450,570),end=(start*60+duration)%1440;return[`OR-${i+1}`,start,0,Math.floor(end/60),end%60,30+i%3*15];}),
  (rows,T)=>{const gross=x=>((x[3]*60+x[4]-x[1]*60-x[2]+1440)%1440)/60;return[
   T('For the first six shifts, return the start time as text hh:mm.',six(rows).map(x=>`${String(x[1]).padStart(2,'0')}:${String(x[2]).padStart(2,'0')}`),'=TEXT(TIME(Data!B2,Data!C2,0),"hh:mm") [fill down]',['TIME','TEXT'],hints('Hours and minutes are separate components.','Construct TIME, then TEXT.','=TEXT(TIME(____,____,0),"hh:mm")')),
   T('For the first six shifts, calculate gross hours across midnight, rounded to two decimals.',six(rows).map(x=>round(gross(x))),'=ROUND(MOD(TIME(Data!D2,Data!E2,0)-TIME(Data!B2,Data!C2,0),1)*24,2) [fill down]',['MOD','TIME','ROUND'],hints('Convert day fractions to hours after applying MOD.','Use MOD of end-minus-start by one day.','=ROUND(MOD(TIME(____)-TIME(____),____)*24,2)')),
   T('For the first six shifts, calculate net hours after subtracting Break_min once, rounded to two decimals.',six(rows).map(x=>round(gross(x)-x[5]/60)),'=ROUND(MOD(TIME(Data!D2,Data!E2,0)-TIME(Data!B2,Data!C2,0),1)*24-Data!F2/60,2) [fill down]',['MOD','TIME','ROUND'],hints('Break minutes must be converted to hours before subtraction.','Subtract break/60 from the unrounded gross-hour calculation.','=ROUND(MOD(____,1)*24-____/60,2)')),
   T('For the first six shifts, return Review if unrounded net hours strictly exceed 8, otherwise Standard.',six(rows).map(x=>gross(x)-x[5]/60>8?'Review':'Standard'),'=IF(MOD(TIME(Data!D2,Data!E2,0)-TIME(Data!B2,Data!C2,0),1)*24-Data!F2/60>8,"Review","Standard") [fill down]',['IF','MOD','TIME'],hints('Use the unrounded net duration and a strict greater-than test.','Reuse IF around MOD-based net hours.','=IF(MOD(____,1)*24-____/60>8,"Review","Standard")')),
   T('Return the first shift’s gross duration in minutes as an unrounded number.',gross(rows[0])*60,'=MOD(TIME(Data!D2,Data!E2,0)-TIME(Data!B2,Data!C2,0),1)*1440',['MOD','TIME'],hints('One day contains 1440 minutes.','Multiply the MOD day fraction by 1440.','=MOD(____,1)*____'))
  ];});

 add(6,1,'Filter inspection exceptions','Pervani Tube Inspection has 64 invented length measurements. Blank Length_mm means not measured and must be excluded from threshold analysis; zero is not used as a substitute. Review rows are measured lengths strictly below 5985 mm.',['FILTER','SORT','CHOOSECOLS'],
  'Dynamic arrays return a whole report from one formula. FILTER chooses eligible observations; SORT orders the resulting numeric values. Keep the spill area empty.',
  'Reuse IF/COUNTIFS and ROUND where needed. A blank can behave like zero in numeric comparisons, so explicitly exclude blank readings before the threshold test. A filtered count should agree with the same eligible population.',
  ['Inspection_code','Line','Length_mm','Defects_units'],r=>Array.from({length:64},(_,i)=>[`PT-${i+1}`,i%2?'Neral':'Tovrin',i%9===0?'':r.int(5960,6030),r.int(0,4)]),
  (rows,T)=>{const bad=rows.filter(x=>x[2]!==''&&x[2]<5985);return[
   T('Return all Inspection_code values for measured Length_mm below 5985, preserving source order.',bad.map(x=>x[0]),'=FILTER(Data!A2:A65,(Data!C2:C65<>"")*(Data!C2:C65<5985),"None")',['FILTER'],hints('Exclude blank readings; do not interpret them as short pipes.','Use FILTER with both eligibility and threshold conditions.','=FILTER(Data!A2:A65,(____<>"")*(____<5985),"None")')),
   T('Return all measured Length_mm below 5985 sorted ascending, preserving duplicate observations.',bad.map(x=>x[2]).sort((a,b)=>a-b),'=SORT(FILTER(Data!C2:C65,(Data!C2:C65<>"")*(Data!C2:C65<5985),"None"),1,1)',['SORT','FILTER'],hints('Retain repeated numeric observations while sorting.','Nest FILTER inside SORT.','=SORT(FILTER(____,____,"None"),1,____)')),
   T('Count the measured rows below 5985 across the whole dataset.',bad.length,'=COUNTIFS(Data!C2:C65,"<5985",Data!C2:C65,"<>")',['COUNTIFS'],hints('Use exactly the same population as the filtered report.','Reuse COUNTIFS with nonblank and below-threshold criteria.','=COUNTIFS(____,"<5985",____,"<>")')),
   T('Return Inspection_code and Length_mm as two columns for Tovrin rows with measured Length_mm below 5985, in source order.',bad.filter(x=>x[1]==='Tovrin').map(x=>[x[0],x[2]]),'=FILTER(CHOOSECOLS(Data!A2:D65,1,3),(Data!B2:B65="Tovrin")*(Data!C2:C65<>"")*(Data!C2:C65<5985),"None")',['FILTER','CHOOSECOLS'],hints('The line, measured status and threshold must all apply to each row.','Use three AND conditions in FILTER and project the two requested columns.','=FILTER(CHOOSECOLS(____,1,3),(____="Tovrin")*(____<>"")*(____<5985),"None")')),
   T('Return None when filtering inspection codes for the nonexistent line Absent.', 'None','=FILTER(Data!A2:A65,Data!B2:B65="Absent","None")',['FILTER'],hints('The stated empty-result label is text.','Use FILTER’s if_empty argument.','=FILTER(____,____="Absent",____)'))
  ];});

 add(6,2,'Sort a business priority queue','Qervella Orders has 68 invented orders with Urgency_score and Order_value_CAD. Scores and values can repeat; Order_code ascending is the final tie-break. Blank Customer_code fields are intentional and do not remove an order from the queue.',['SORTBY','CHOOSEROWS'],
  'A reproducible queue needs explicit tie-breaks. SORTBY can order by urgency descending, value descending and code ascending while returning the original row columns.',
  'Reuse ROUND for values and IF for a review flag. CHOOSEROWS selects positions after sorting, not source worksheet row numbers. Keep related fields together so row identity survives sorting.',
  ['Order_code','Customer_code','Urgency_score','Order_value_CAD'],r=>Array.from({length:68},(_,i)=>[`QO-${String(101+i).padStart(3,'0')}`,i%7===0?'':`QC-${i%9+1}`,r.int(1,5),r.int(10,50)*25]),
  (rows,T)=>{const ordered=rows.slice().sort((a,b)=>b[2]-a[2]||b[3]-a[3]||a[0].localeCompare(b[0]));return[
   T('Return all Order_code values sorted by Urgency_score descending, Order_value_CAD descending, then Order_code ascending.',ordered.map(x=>x[0]),'=SORTBY(Data!A2:A69,Data!C2:C69,-1,Data!D2:D69,-1,Data!A2:A69,1)',['SORTBY'],hints('Both secondary and final tie-breaks matter.','Use three ordered SORTBY key pairs.','=SORTBY(Data!A2:A69,____,-1,____,-1,____,1)')),
   T('Return the first and last source Order_code values as a two-row column.',[rows[0][0],rows.at(-1)[0]],'=CHOOSEROWS(Data!A2:A69,1,-1)',['CHOOSEROWS'],hints('This task uses source order, not queue order.','Select first and last positions with CHOOSEROWS.','=CHOOSEROWS(____,1,____)')),
   T('Return the first three complete queue records (four columns) under the stated three-key ordering.',ordered.slice(0,3),'=CHOOSEROWS(SORTBY(Data!A2:D69,Data!C2:C69,-1,Data!D2:D69,-1,Data!A2:A69,1),1,2,3)',['CHOOSEROWS','SORTBY'],hints('Sort complete rows before taking queue positions.','Nest SORTBY inside CHOOSEROWS.','=CHOOSEROWS(SORTBY(____,____),1,2,3)')),
   T('For the first six source records, return High when Urgency_score is at least 4, otherwise Normal.',six(rows).map(x=>x[2]>=4?'High':'Normal'),'=IF(Data!C2>=4,"High","Normal") [fill down]',['IF'],hints('This task is in source order and includes the equality boundary.','Reuse IF.','=IF(____>=4,"High","Normal")')),
   T('Return the third record’s Order_code in the sorted queue.',ordered[2][0],'=INDEX(SORTBY(Data!A2:A69,Data!C2:C69,-1,Data!D2:D69,-1,Data!A2:A69,1),3)',['INDEX','SORTBY'],hints('Third refers to the sorted queue.','Reuse INDEX after SORTBY.','=INDEX(SORTBY(____),____)'))
  ];});

 add(6,3,'Create a distinct heat register','Relvani Melt Tracking has 72 invented sample records spanning six heat codes. Heat codes repeat across samples; one blank code represents an incomplete record and must be excluded from the distinct register. Sample counts must still reflect all valid records per heat.',['UNIQUE','SEQUENCE','HSTACK'],
  'UNIQUE constructs the key register; SEQUENCE supplies a separate display index. Neither function aggregates measurements by itself. Distinguish a missing key from a valid repeated heat.',
  'Reuse SORT for stable ascending heat order, FILTER to exclude blank keys, and COUNTIFS for counts aligned to the spilled register. Do not use exactly_once TRUE when all distinct heats are needed.',
  ['Sample_code','Heat_no','Tap_t'],r=>Array.from({length:72},(_,i)=>[`RM-${i+1}`,i===5?'':`RH-${[3,1,6,2,5,4][i%6]}`,r.int(8200,11500)/100]),
  (rows,T)=>{const heats=[...new Set(rows.map(x=>x[1]).filter(Boolean))].sort();return[
   T('Return distinct nonblank Heat_no values sorted ascending.',heats,'=SORT(UNIQUE(FILTER(Data!B2:B73,Data!B2:B73<>"")))',['UNIQUE','SORT','FILTER'],hints('Repeated heats should appear once; the blank key should not appear.','FILTER nonblank keys, then UNIQUE and SORT.','=SORT(UNIQUE(FILTER(____,____<>"")))')),
   T('Return display numbers 1 through 6 as a six-row column.',[1,2,3,4,5,6],'=SEQUENCE(6)',['SEQUENCE'],hints('Return a column, not a row.','Use SEQUENCE with six rows.','=SEQUENCE(____)')),
   T('Return the sample-record counts for the six sorted nonblank heats in the same order as the register.',heats.map(h=>rows.filter(x=>x[1]===h).length),'=COUNTIFS(Data!B2:B73,SORT(UNIQUE(FILTER(Data!B2:B73,Data!B2:B73<>""))))',['COUNTIFS','UNIQUE','FILTER','SORT'],hints('Count source records against each distinct sorted key.','Pass the spilled register into earlier COUNTIFS.','=COUNTIFS(Data!B2:B73,____)')),
   T('Return two columns: sorted nonblank Heat_no and its record count.',heats.map(h=>[h,rows.filter(x=>x[1]===h).length]),'=HSTACK(SORT(UNIQUE(FILTER(Data!B2:B73,Data!B2:B73<>""))),COUNTIFS(Data!B2:B73,SORT(UNIQUE(FILTER(Data!B2:B73,Data!B2:B73<>"")))))',['HSTACK','UNIQUE','COUNTIFS','FILTER','SORT'],hints('Counts must stay aligned to the exact same sorted heat keys.','HSTACK the register with its COUNTIFS result.','=HSTACK(____,COUNTIFS(Data!B2:B73,____))')),
   T('Count records with a blank Heat_no.',1,'=COUNTIFS(Data!B2:B73,"")',['COUNTIFS'],hints('The incomplete record is still part of the source table.','Reuse COUNTIFS with an empty-string criterion.','=COUNTIFS(____,"")'))
  ];});

 add(6,4,'Combine two stock extracts','Servella Stock Control has 40 invented warehouse-A observations and 40 separate warehouse-B observations on Secondary. Schemas and units are aligned; repeated SKU values across warehouses remain separate records. One blank SKU in each extract must not be included in the ranked report.',['VSTACK','HSTACK','TAKE','DROP'],
  'Stacking requires schema and identity alignment. VSTACK appends compatible observations; HSTACK combines columns only when they refer to the same row keys. TAKE and DROP then create bounded views.',
  'Reuse FILTER to exclude blank SKUs, SORTBY for stock descending with SKU ascending as the tie-break, and ROUND for value calculations. The raw combined extract keeps duplicates; aggregation would be a separate task.',
  ['SKU','Warehouse','Stock_units','Unit_cost_CAD'],r=>Array.from({length:40},(_,i)=>[i===5?'':`SV-${i%16+1}`,'A',r.int(20,180),r.int(150,1700)/100]),
  (rows,T,s)=>{const combined=rows.concat(s[0].rows),valid=combined.filter(x=>x[0]),sorted=valid.slice().sort((a,b)=>b[2]-a[2]||a[0].localeCompare(b[0])||a[1].localeCompare(b[1]));return[
   T('Return the first three Data records followed by the first three Secondary records, as six rows and four columns.',rows.slice(0,3).concat(s[0].rows.slice(0,3)),'=VSTACK(Data!A2:D4,Secondary!A2:D4)',['VSTACK'],hints('Preserve each source schema and the stated extract order.','Use VSTACK on two equally wide arrays.','=VSTACK(____,____)')),
   T('For the first five Data records, return two columns: SKU and Stock_units, aligned in source order.',rows.slice(0,5).map(x=>[x[0],x[2]]),'=HSTACK(Data!A2:A6,Data!C2:C6)',['HSTACK'],hints('Both columns must refer to the same five source rows.','Use HSTACK with equal-height aligned ranges.','=HSTACK(____,____)')),
   T('Return the first five records of the full combined raw extract (Data followed by Secondary), including all four columns.',combined.slice(0,5),'=TAKE(VSTACK(Data!A2:D41,Secondary!A2:D41),5)',['TAKE','VSTACK'],hints('This raw view preserves blank and duplicate keys.','Use TAKE after VSTACK.','=TAKE(VSTACK(____),____)')),
   T('Return the first three combined raw records after removing the first two records, as three rows and four columns.',combined.slice(2,5),'=TAKE(DROP(VSTACK(Data!A2:D41,Secondary!A2:D41),2),3)',['TAKE','DROP','VSTACK'],hints('Drop two first, then retain three.','Nest DROP inside TAKE.','=TAKE(DROP(VSTACK(____),____),3)')),
   T('Return the highest-stock valid record as four columns. Exclude blank SKUs; sort stock descending, SKU ascending, then Warehouse ascending to break ties.', [sorted[0]],'=TAKE(SORTBY(FILTER(VSTACK(Data!A2:D41,Secondary!A2:D41),VSTACK(Data!A2:A41,Secondary!A2:A41)<>""),FILTER(VSTACK(Data!C2:C41,Secondary!C2:C41),VSTACK(Data!A2:A41,Secondary!A2:A41)<>""),-1,FILTER(VSTACK(Data!A2:A41,Secondary!A2:A41),VSTACK(Data!A2:A41,Secondary!A2:A41)<>""),1,FILTER(VSTACK(Data!B2:B41,Secondary!B2:B41),VSTACK(Data!A2:A41,Secondary!A2:A41)<>""),1),1)',['TAKE','SORTBY','FILTER','VSTACK'],hints('Exclude blank keys before aligning every sort key.','Combine filtering, explicit tie-breaks and TAKE.','=TAKE(SORTBY(FILTER(VSTACK(____),____),____,-1,____,1,____,1),1)'))
  ];},()=>{const r=randomFor('L6-A4-secondary');return[extra('Secondary',['SKU','Warehouse','Stock_units','Unit_cost_CAD'],Array.from({length:40},(_,i)=>[i===7?'':`SV-${i%19+7}`,'B',r.int(25,200),r.int(220,1900)/100]))];});

 add(6,5,'Reshape Charpy orientations side by side','Tervani Charpy Lab has 80 invented records: 40 sample/heat pairs, each with LPA and TWA orientations. Sample_no repeats across four heats, so both keys are essential; orientation case/spaces vary and one TWA energy is blank. Missing energy must be reported as Missing, never zero.',['CHOOSECOLS','CHOOSEROWS','HSTACK'],
  'Reshaping requires a composite identity. Extract the sample/heat columns and use UNIQUE on whole row pairs. Bring each orientation’s result alongside that same pair, normalizing orientation labels first.',
  'Reuse XLOOKUP from Level 3, TRIM/UPPER from Level 4, and IF for missing energies. Use the two-column key register created by Task 1 as a helper spill. HSTACK preserves alignment only when both returned orientation columns use exactly those keys.',
  ['Sample_no','Heat_no','Orientation','Energy_J'],r=>Array.from({length:80},(_,i)=>[i%10+1,`TH-${7401+Math.floor(i/20)}`,i%20<10?' LPA ':'twa',i===10?'':r.int(16,79)]),
  (rows,T)=>{const pairs=distinct(rows.map(x=>x.slice(0,2)));const get=(p,o)=>{const row=rows.find(x=>x[0]===p[0]&&x[1]===p[1]&&clean(x[2]).toUpperCase()===o);return row&&row[3]!==''?row[3]:'Missing';};const orientation=o=>`=XLOOKUP(Answers!B2:B41&"|"&Answers!C2:C41&"|${o}",Data!A2:A81&"|"&Data!B2:B81&"|"&UPPER(TRIM(Data!C2:C81)),IF(Data!D2:D81="","Missing",Data!D2:D81),"Missing")`;return[
   T('Return the 40 distinct Sample_no and Heat_no row pairs as two columns, in first-occurrence order. Use the exact output B2:C41 as the helper register for later tasks.',pairs,'=UNIQUE(CHOOSECOLS(Data!A2:D81,1,2))',['UNIQUE','CHOOSECOLS'],hints('Sample_no alone repeats across heats. Use complete two-column pairs.','UNIQUE should operate on the two selected key columns.','=UNIQUE(CHOOSECOLS(____,____,____))')),
   T('Return the first and last source records, all four columns, as a two-row array.',[rows[0],rows.at(-1)],'=CHOOSEROWS(Data!A2:D81,1,-1)',['CHOOSEROWS'],hints('These are source rows, before reshaping.','Select row indices 1 and -1.','=CHOOSEROWS(____,1,____)')),
   T('Using the helper register B2:C41, return two columns: LPA energy and TWA energy for each pair, in helper order. Trim/uppercase orientations and return Missing for an absent or blank energy.',pairs.map(p=>[get(p,'LPA'),get(p,'TWA')]),`=HSTACK(${orientation('LPA').slice(1)},${orientation('TWA').slice(1)})`,['HSTACK','XLOOKUP','IF','TRIM','UPPER'],hints('Both sample and heat plus normalized orientation identify the energy. A blank energy is not zero.','Use composite-key XLOOKUP twice, with an IF-protected return array, then HSTACK.','=HSTACK(XLOOKUP(____,____,IF(____="","Missing",____),"Missing"),XLOOKUP(____))')),
   T('Return the complete 40-row report with four columns: Sample_no, Heat_no, LPA energy, TWA energy. Use the helper register and the two orientation columns from Task 3; keep helper order.',pairs.map(p=>[...p,get(p,'LPA'),get(p,'TWA')]),'=HSTACK(Answers!B2:C41,Answers!B48:C87)',['HSTACK'],hints('Attach the orientation columns to their exact matching two-column keys.','HSTACK the two helper arrays in the stated column order.','=HSTACK(____,____)')),
   T('For sample 1 in heat TH-7401, return Review if its TWA energy is missing, otherwise Measured.', 'Review','=IF(XLOOKUP("1|TH-7401|TWA",Data!A2:A81&"|"&Data!B2:B81&"|"&UPPER(TRIM(Data!C2:C81)),IF(Data!D2:D81="","Missing",Data!D2:D81),"Missing")="Missing","Review","Measured")',['IF','XLOOKUP','UPPER','TRIM'],hints('The first heat’s sample 1 has a blank TWA result.','Compare the protected lookup result to Missing.','=IF(XLOOKUP(____)="Missing","Review","Measured")'))
  ];});
 return packages;
}
