'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');
const slug='introduction-to-calculus-for-quality-and-reliability-engineers';
const route='/lessons/quality-engineering/'+slug;
const html=fs.readFileSync(path.join(root,route+'.html'),'utf8');
const guide=fs.readFileSync(path.join(root,'docs/LESSON_CREATION_GUIDE.md'),'utf8');
function load(){const dom=new JSDOM(html,{url:'https://upskillsprint.com'+route,runScripts:'outside-only'});dom.window.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{},set:()=>true});for(const s of dom.window.document.querySelectorAll('script:not([src])'))dom.window.eval(s.textContent);return dom;}
test('calculus lesson is public, registered, typeset and integrated with exact shared chrome',()=>{const dom=load(),d=dom.window.document;assert.ok(html.startsWith('<!DOCTYPE html>\n<html lang="en">\n<!-- UPSKILLSPRINT_LESSON_META'));const meta=JSON.parse(html.match(/UPSKILLSPRINT_LESSON_META\s*([\s\S]*?)-->/)[1]);assert.equal(meta.slug,slug);assert.equal(meta.title,d.querySelector('h1').textContent);assert.equal(d.body.dataset.category,'quality-engineering');assert.equal(d.body.hasAttribute('data-require-auth'),false);for(const s of ['/style.css','/lessons-theme.css','/theme.js','/site-sections.js'])assert.ok(html.includes('"'+s+'"'));for(const regex of [/```html\n(<input type="checkbox" id="mnav-check"[\s\S]*?<\/header>)\n```/,/```html\n(<footer class="site">[\s\S]*?<\/footer>)\n```/])assert.ok(html.includes(guide.match(regex)[1]));assert.ok(d.querySelectorAll('math').length>200);assert.ok(d.querySelector('mfrac'));assert.equal(d.querySelectorAll('.quiz-question').length,15);assert.ok(fs.readFileSync(path.join(root,'chi-square-lesson-library.js'),'utf8').includes("path: '"+route+"'"));const pdf=d.getElementById('download').getAttribute('href');assert.ok(pdf.startsWith('/assets/lessons/'+slug+'/'));assert.equal(fs.readFileSync(path.join(root,pdf)).subarray(0,5).toString(),'%PDF-');assert.equal(d.querySelectorAll('main').length,1);dom.window.close();});
test('calculus widgets handle endpoints, ordered bounds and changing hazard',()=>{const dom=load(),d=dom.window.document;const input=(id,v)=>{d.getElementById(id).value=v;d.getElementById(id).dispatchEvent(new dom.window.Event('input'));};assert.match(d.getElementById('aout').textContent,/Exact area = 9.0000/);input('nn','100');assert.match(d.getElementById('aout').textContent,/Left sum = 8.8654/);input('aa','3');assert.match(d.getElementById('aout').textContent,/Exact area = 0.0000/);input('bb','1');assert.equal(d.getElementById('aa').value,'1');input('sx','0');assert.match(d.getElementById('sout').textContent,/Tangent slope 2x = 0.00/);assert.match(d.getElementById('rout').textContent,/81.87%/);input('lam','0.01');input('tt','1000');assert.match(d.getElementById('rout').textContent,/MTTF = 100.0 h/);dom.window.close();});
test('canonical quiz emits accurate progress for unanswered, correct, wrong and reset states',()=>{const dom=load(),d=dom.window.document;let result;d.addEventListener('upskill-quiz-result',e=>result=e.detail);d.getElementById('quiz-submit').click();assert.equal(result.score,0);assert.equal(result.total,15);assert.match(d.getElementById('quiz-result').textContent,/15 unanswered/);for(const q of d.querySelectorAll('.quiz-question'))q.querySelector(`input[value="${q.dataset.answer}"]`).checked=true;d.getElementById('quiz-submit').click();assert.equal(result.score,15);assert.equal(d.querySelectorAll('.is-correct').length,15);const first=d.querySelector('.quiz-question');first.querySelector(`input:not([value="${first.dataset.answer}"])`).checked=true;d.getElementById('quiz-submit').click();assert.equal(result.score,14);assert.equal(d.querySelectorAll('.is-incorrect').length,1);d.getElementById('quiz-reset').click();assert.equal(d.querySelectorAll('input[type=radio]:checked').length,0);assert.equal(d.querySelectorAll('.quiz-feedback.show').length,0);dom.window.close();});
test('exponential round-trip example shows both derivations, limits and the initial condition',()=>{const dom=load(),d=dom.window.document;const example=d.getElementById('exponential-calculus-round-trip');assert.ok(example);assert.equal(example.querySelectorAll('h3').length,4);assert.ok(example.querySelectorAll('math').length>=30);const tex=Array.from(example.querySelectorAll('annotation')).map(a=>a.textContent).join('\n');for(const token of ['dw=-\\lambda','du=-\\frac{1}{\\lambda}','F(0)=0','C=1','\\left[-e^{-\\lambda u}\\right]_0^t','0.181269247'])assert.ok(tex.includes(token),token);dom.window.close();});
