'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom');const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const w={};w.window=w;vm.createContext(w);vm.runInContext(read('test-bank-mbb-set2.js'),w);const batches=JSON.parse(JSON.stringify(w.MBB_SET2_BATCHES)),b=batches[3],Q=n=>b[n-51];
const keys=[2,0,3,1,2,0,3,1,2,0,3,1,2,0,2,3,1,2,0,3,1,2,0,3,1];
const sort=o=>Array.isArray(o)?o.map(sort):o&&typeof o==='object'?Object.fromEntries(Object.keys(o).sort().map(k=>[k,sort(o[k])])):o;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const preserved=JSON.parse(read('docs/audits/mbb-set2-batch03/preservation.json'));
// Intentional later Batch 5 audit: enforce its recorded new hashes instead of silently skipping it.
// Intentional Batch 6 audit: pin its exact new hashes and the single Q150 B→D rekey.
const batch6Updated=JSON.parse(read('docs/audits/mbb-set2-batch06/updated-hashes.json'));
const batch7Updated=JSON.parse(fs.readFileSync(path.join(root,'docs/audits/mbb-set2-batch07/updated-hashes.json'),'utf8'));
const batch5Updated=JSON.parse(read('docs/audits/mbb-set2-batch05/updated-hashes.json'));
for(let i=0;i<25;i++)test(`Restored Q${i+51}: adjudicated key ${'ABCD'[keys[i]]} and rationale agree`,()=>{const q=b[i];assert.equal(q.answer,keys[i]);assert.ok(q.why.includes('<b>'+'ABCD'[keys[i]]+'. '+q.options[keys[i]]+'</b>'));assert.equal(new Set(q.options).size,4);assert.equal(q.optionRationales.length,4);});
test('All 150 non-Batch-3 records and all keys except the authorized Q150 repair are preserved',()=>{let count=0;for(const [id,qs] of Object.entries(batches)){if(id==='3')continue;for(const q of qs){assert.equal(sha(JSON.stringify(sort(q))),batch7Updated.stable_question_sha256[q.qid] || batch6Updated.stable_question_sha256[q.qid] || batch5Updated.stable_question_sha256[q.qid] || preserved.unmodifiedQuestionSha256[q.qid],q.qid);count++;}}assert.equal(count,150);assert.deepEqual(Object.keys(batches).sort((a,b)=>a-b).flatMap(k=>batches[k].map(q=>q.answer)),preserved.answerPositions.map((a,i)=>i===149?3:a));assert.deepEqual(batch6Updated.authorizedKeyChange,{qid:'mbb:set-2:original-150',from:1,to:3,reason:'Stored B contradicts the semantic solution, option wording and existing explanation.'});});
test('All 24 other asset files, including Batches 1, 2 and 4, are byte-identical',()=>{assert.equal(Object.keys(preserved.unmodifiedAssetsSha256).length,24);for(const [file,expected] of Object.entries(preserved.unmodifiedAssetsSha256))assert.equal(sha(fs.readFileSync(path.join(root,file))),batch7Updated.asset_sha256[file] || batch6Updated.asset_sha256[file] || batch5Updated.asset_sha256[file] || expected,file);});
test('Q61 exhaustively optimizes mandatory and data-ready indivisible projects',()=>{const rows=Q(61).chart.rows;const candidates=rows.filter(r=>r[4]==='Yes');const results=[];for(let mask=0;mask<1<<candidates.length;mask++){const picked=candidates.filter((_,i)=>mask&(1<<i));if(!picked.some(x=>x[0]==='R'))continue;const used=picked.reduce((s,r)=>s+Number(r[1]),0);if(used<=12)results.push({ids:picked.map(x=>x[0]).join(''),value:picked.reduce((s,r)=>s+parseFloat(r[2].slice(1)),0)});}results.sort((a,b)=>b.value-a.value);assert.equal(results[0].ids,'RAD');assert.ok(Math.abs(results[0].value-3.1)<1e-12);assert.doesNotMatch(Q(61).options[1],/three discretionary/);assert.equal(Q(61).chart.whatIf.baseline,12);});
test('Q64 cash and unsupported combined NPVs round correctly from supplied factor',()=>{assert.ok(Math.abs(420000*3.1699-1200000-131358)<1e-8);assert.equal(Math.round((670000*3.1699-1200000)/1000),924);assert.match(Q(64).stem,/per year.*same four years/);assert.match(Q(64).options[2],/\$924,000/);});
test('Q69 study SD ratio and variance contribution are different and unrounded',()=>{const [r,a,ix,part]=Q(69).chart.rows.map(x=>+x[1]);const grr=r*r+a*a+ix*ix,total=grr+part*part;assert.equal(grr,2);assert.equal(total,22.25);assert.ok(Math.abs(Math.sqrt(grr/total)*100-29.981267559)<1e-8);assert.ok(Math.sqrt(grr/total)*100<30);assert.ok(Math.abs(grr/total*100-8.988764045)<1e-8);assert.equal(Q(69).chart.columns.length,2);assert.match(Q(69).assumptions.join(' '),/unrounded/);});
test('Q70 and Q73 endpoints, tails and all histogram totals agree',()=>{assert.doesNotMatch(Q(70).stem,/p\s*[=<]/);assert.ok(Math.abs(Math.exp(-(2**1.4))-0.07143153635221014)<1e-10);assert.equal(Q(70).chart.counts.reduce((a,b)=>a+b),200);assert.equal(Q(73).chart.counts.reduce((a,b)=>a+b),2000);assert.equal(Q(73).chart.counts.slice(0,4).reduce((a,b)=>a+b)/2000,.155);});
test('Q71 pointwise scope is explicit and diagnostics do not choose a unique AR order',()=>{assert.equal(Q(71).chart.confidence,1.96/Math.sqrt(100));assert.match(Q(71).stem,/pointwise/);assert.match(Q(71).assumptions.join(' '),/not a simultaneous/);});
test('Q72 independent balanced-design SS, df, F and numerical F tail integration',()=>{const c=Q(72).chart,n=c.anova.replicatesPerCell,means=[c.lowLine,c.highLine],grand=means.flat().reduce((a,b)=>a+b)/4;const row=means.map(r=>(r[0]+r[1])/2),col=[0,1].map(i=>(means[0][i]+means[1][i])/2);const ssM=2*n*row.reduce((s,v)=>s+(v-grand)**2,0),ssW=2*n*col.reduce((s,v)=>s+(v-grand)**2,0),ssI=n*means.reduce((s,r,i)=>s+r.reduce((z,v,j)=>z+(v-row[i]-col[j]+grand)**2,0),0);assert.deepEqual([ssM,ssW,ssI],[810,1210,490]);assert.equal(4*(n-1),36);assert.equal(c.anova.meanSquareError*36,1764);
// F(1,36) tail equals the two-sided t(36) tail. Numerical Simpson integration
// of a separately coded density cross-checks the published six-place p-values.
let constant=1/6;for(let k=0;k<18;k++){constant*=k+.5;if(k>0)constant/=k;}
function tail(F){const lo=Math.sqrt(F),hi=100,N=20000,h=(hi-lo)/N,pdf=x=>constant*(1+x*x/36)**(-18.5);let sum=pdf(lo)+pdf(hi);for(let j=1;j<N;j++)sum+=(j%2?4:2)*pdf(lo+j*h);return 2*h*sum/3;}
[ssM,ssW,ssI].forEach((ss,i)=>{const F=ss/49;assert.ok(Math.abs(F-Number(c.anova.rows[i][3]))<.00005);assert.ok(Math.abs(tail(F)-Number(c.anova.rows[i][4]))<.00000051);});assert.match(Q(72).assumptions[0],/synthetic/);});
test('Q74 incidence is incomplete and every pair occurs together twice',()=>{const rows=Q(74).chart.rows;assert.equal(Q(74).chart.columns.length,5);for(let a=0;a<4;a++){assert.equal(rows[a].slice(1).filter(x=>x==='Test').length,3);for(let bb=a+1;bb<4;bb++)assert.equal(rows[a].slice(1).filter((x,i)=>x==='Test'&&rows[bb][i+1]==='Test').length,2);}});
function dom(){const d=new JSDOM('<!doctype html><head></head><body></body>',{runScripts:'outside-only'});d.window.eval(read('test-bank-mbb-batch3-ui.js'));return d;}
test('B3 conditions/rationales are scoped; other 150 questions never match renderer',()=>{const d=dom(),ui=d.window.__MBBBatch3UI;try{for(const [id,qs] of Object.entries(batches))for(const q of qs){assert.equal(ui.isQuestion(q),id==='3');if(id==='3'){assert.match(ui.conditions(q),/Stated conditions/);assert.match(ui.rationales(q),/Choice D/);}else assert.equal(ui.conditions(q),'');}}finally{d.window.close();}});
test('B3 native selectors, focused observations and capacity reset work without core hooks',()=>{const d=dom(),ui=d.window.__MBBBatch3UI;try{for(const n of [56,71]){d.window.document.body.innerHTML=ui.render(Q(n).chart);const select=d.window.document.querySelector('select');select.value='1';select.dispatchEvent(new d.window.Event('change',{bubbles:true}));assert.equal(d.window.document.querySelector('[data-mbb3-readout]').textContent,select.options[1].textContent);d.window.document.querySelector('[data-mbb3-point="0"]').dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(select.value,'0');}d.window.document.body.innerHTML=ui.render(Q(61).chart);const el=d.window.document.querySelector('input');el.value='16';el.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.match(d.window.document.body.textContent,/12 BB-months remain/);d.window.document.querySelector('button').click();assert.equal(el.value,'12');}finally{d.window.close();}});
test('Static B3 fallbacks retain all evidence without dead widgets or premature explanations',()=>{const d=new JSDOM(read('test-bank-assets/mbb-160/batch-03/static-fallbacks.html'));try{assert.equal(d.window.document.querySelectorAll('.fallback-card').length,10);assert.equal(d.window.document.querySelectorAll('select,input,button,[data-mbb3-point]').length,0);assert.equal(d.window.document.querySelectorAll('.mbb3-rationales').length,0);assert.equal(d.window.document.querySelectorAll('.mbb3-conditions').length,10);}finally{d.window.close();}});
