'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const factory=require('../test-bank-session-handoff.js');

function storage(){const m=new Map();return {get length(){return m.size;},key:i=>[...m.keys()][i]||null,getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(String(k),String(v)),removeItem:k=>m.delete(k),_m:m};}
function snapshot(epoch=0,selected=null){return {schemaVersion:1,contractVersion:'1.0.0',sessionId:'cssbb:session:s15',ownerId:'u1',examId:'cssbb',setId:'1',mode:'exam',bankVersion:'bank',blueprintVersion:'bp',configVersion:'cfg',gradingPolicyVersion:'single-select-v1',masteryPolicyVersion:'m',timingPolicyVersion:'t',expectedLength:2,siteTargetBps:7000,orderedItems:[{itemId:'i0',questionId:'cssbb:q1',questionRevision:'r1',domainId:'d',optionIds:['o0','o1'],optionOrder:['o0','o1'],selectedOptionId:selected,effectiveAnsweredAt:null},{itemId:'i1',questionId:'cssbb:q2',questionRevision:'r2',domainId:'d',optionIds:['o0','o1'],optionOrder:['o0','o1'],selectedOptionId:null,effectiveAnsweredAt:null}],state:'in_progress',sessionRevision:1,writerEpoch:epoch,resetEpochId:null,startedAt:'2026-09-10T00:00:00.000Z',deadlineAt:'2026-09-10T02:00:00.000Z',timed:true,limitSeconds:7200,reportingTimeZoneAtStart:'America/Regina',currentItemId:'i0',flags:[],versionPin:{sessionId:'cssbb:session:s15',ownerId:'u1',examId:'cssbb',mode:'exam',timed:true,startedAt:'2026-09-10T00:00:00.000Z',deadlineAt:'2026-09-10T02:00:00.000Z',orderedItems:[{itemId:'i0',questionId:'cssbb:q1',questionRevision:'r1',optionOrder:['o0','o1']},{itemId:'i1',questionId:'cssbb:q2',questionRevision:'r2',optionOrder:['o0','o1']}],contents:[{qid:'cssbb:q1',options:['A','B'],answer:0},{qid:'cssbb:q2',options:['A','B'],answer:1}]}};}
function envelope(s=snapshot()){return {schemaVersion:1,contractVersion:'1.0.0',kind:'core',ownerId:'u1',sessionId:s.sessionId,examId:'cssbb',mode:'exam',state:s.state,writerEpoch:s.writerEpoch,timed:true,startedAt:s.startedAt,deadlineAt:s.deadlineAt,payload:s};}
class Service{
  constructor(){this.row=null;this.calls=[];this.runtimeEpoch=0;this.runtimeRevision=4;}
  client(){return {rpc:(name,args)=>{this.calls.push({name,args:JSON.parse(JSON.stringify(args))});try{return Promise.resolve({data:this.call(name,args),error:null});}catch(e){return Promise.resolve({data:null,error:{message:e.message,code:e.code}});}}};}
  err(code,msg){const e=new Error(msg);e.code=code;throw e;}
  call(name,a){
    if(name==='fetch_test_bank_resumable_sessions_v1')return this.row&&(!a.p_session_id||a.p_session_id===this.row.session_id)?[JSON.parse(JSON.stringify(this.row))]:[];
    if(name==='save_test_bank_session_checkpoint_v1'){
      if(a.p_writer_epoch!==this.runtimeEpoch)this.err('40001','stale epoch');
      if(this.row){if(a.p_writer_client_id!==this.row.writer_client_id||a.p_expected_checkpoint_revision!==this.row.checkpoint_revision)this.err('40001','stale checkpoint');}
      else if(a.p_expected_checkpoint_revision!==0)this.err('40001','stale initial checkpoint');
      const rev=this.row?this.row.checkpoint_revision+1:1;
      this.row={session_id:a.p_session_id,exam_id:'cssbb',state:'in_progress',writer_epoch:this.runtimeEpoch,writer_client_id:a.p_writer_client_id,writer_device_id:a.p_writer_device_id,checkpoint_revision:rev,server_session_revision:this.runtimeRevision,snapshot:JSON.parse(JSON.stringify(a.p_snapshot)),updated_at:'2026-09-10T00:10:00Z',server_time:'2026-09-10T00:10:00Z'};return this.rpcRow();
    }
    if(name==='takeover_test_bank_session_v1'){
      if(!this.row)this.err('42501','no checkpoint');
      if(a.p_expected_writer_epoch!==this.runtimeEpoch||a.p_expected_checkpoint_revision!==this.row.checkpoint_revision)this.err('40001','stale takeover');
      if(a.p_writer_client_id===this.row.writer_client_id)return {...this.rpcRow(),applied:false};
      this.runtimeEpoch++;this.runtimeRevision++;this.row.writer_epoch=this.runtimeEpoch;this.row.writer_client_id=a.p_writer_client_id;this.row.writer_device_id=a.p_writer_device_id;this.row.checkpoint_revision++;this.row.server_session_revision=this.runtimeRevision;this.row.snapshot.writerEpoch=this.runtimeEpoch;this.row.updated_at='2026-09-10T00:11:00Z';return {...this.rpcRow(),applied:true};
    }
    throw new Error('unknown '+name);
  }
  rpcRow(){const r=this.row;return {sessionId:r.session_id,examId:r.exam_id,state:r.state,writerEpoch:r.writer_epoch,writerClientId:r.writer_client_id,writerDeviceId:r.writer_device_id,checkpointRevision:r.checkpoint_revision,serverSessionRevision:r.server_session_revision,snapshot:JSON.parse(JSON.stringify(r.snapshot)),updatedAt:r.updated_at,serverTime:r.server_time};}
}
function lifecycle(root,initial){let active=initial?JSON.parse(JSON.stringify(initial)):null;return {terminalStates:['completed','expired','abandoned'],validateSnapshot:s=>{assert.equal(s.contractVersion,'1.0.0');return true;},save:s=>{active=JSON.parse(JSON.stringify(s));return active;},load:id=>active&&(!id||id===active.sessionId)?JSON.parse(JSON.stringify(active)):null,resume:id=>({resumed:id}),status:()=>({active}),_get:()=>active};}
function root(service,initialLearning){const local=storage(),session=storage();local.setItem('tb-account-sync-device-v1','device-A');const learningState=initialLearning||{version:2,events:[],sessions:{},index:{knownEventIds:{},totals:{},seen:{}}};const r={localStorage:local,sessionStorage:session,navigator:{onLine:true},crypto:{randomUUID:(()=>{let n=0;return()=>`00000000-0000-4000-8000-${String(++n).padStart(12,'0')}`;})()},setTimeout,clearTimeout,AbortController,Date,queueMicrotask,UpskillAuth:{getUser:()=>({id:'u1'}),getClient:()=>service.client()},__TBLearning:{store:()=>learningState,sync:async()=>({pending:0}),startSession:i=>i&&i.returnResult?{saved:true,sessionId:i.sessionId}:i.sessionId,recordDraft:i=>({saved:true,sessionId:i.sessionId}),recordAnswer:i=>({saved:true,sessionId:i.sessionId}),completeSession:i=>({saved:true,sessionId:i.sessionId}),abandonSession:i=>({saved:true,sessionId:i.sessionId})},__TBSessionTiming:{recover:async()=>({ready:true}),isExpired:()=>false}};return r;}
async function seedCloud(api,service,s=snapshot()){const e=api.coreEnvelope(s);await api.saveCheckpoint(e);assert.ok(service.row);return service.row;}

test('checkpoint is owner-scoped, pins original deadline and starts writer epoch zero',async()=>{const svc=new Service(),r=root(svc),L=lifecycle(r,snapshot());const api=factory(r,L);await seedCloud(api,svc);assert.equal(svc.row.writer_epoch,0);assert.equal(svc.row.snapshot.deadlineAt,'2026-09-10T02:00:00.000Z');assert.equal(svc.row.snapshot.ownerId,'u1');});
test('same-client refresh reconciles the server revision before retrying a conflicted outbox',async()=>{const svc=new Service(),state={version:2,events:[],sessions:{'cssbb:session:s15':{id:'cssbb:session:s15',ownerId:'u1',status:'active',writerEpoch:0,serverRevision:0}},index:{knownEventIds:{},totals:{},seen:{}}},r=root(svc,state),L=lifecycle(r,snapshot()),api=factory(r,L);await seedCloud(api,svc);assert.equal(state.sessions['cssbb:session:s15'].serverRevision,0);const refreshed=await api.refresh('revision-recovery');assert.equal(refreshed.revisionRecovered,true);assert.equal(state.sessions['cssbb:session:s15'].serverRevision,svc.runtimeRevision);});
test('explicit takeover advances writer epoch exactly once and same-client retry is idempotent',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const old=svc.row.writer_client_id;const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const L2=lifecycle(r2,null),b=factory(r2,L2);await b.takeover('cssbb:session:s15');assert.equal(svc.runtimeEpoch,1);assert.notEqual(svc.row.writer_client_id,old);const expected=svc.runtimeEpoch;await b.takeover('cssbb:session:s15');assert.equal(svc.runtimeEpoch,expected);});
test('two contenders with same expected epoch produce one winner and one stale conflict',async()=>{const svc=new Service(),ra=root(svc),la=lifecycle(ra,snapshot()),a=factory(ra,la);await seedCloud(a,svc);const row=JSON.parse(JSON.stringify(svc.row));const args=id=>({p_session_id:row.session_id,p_writer_client_id:id,p_writer_device_id:id,p_expected_writer_epoch:row.writer_epoch,p_expected_checkpoint_revision:row.checkpoint_revision});const p1=svc.client().rpc('takeover_test_bank_session_v1',args('device-B:tab-B'));const p2=svc.client().rpc('takeover_test_bank_session_v1',args('device-C:tab-C'));const [x,y]=await Promise.all([p1,p2]);assert.equal([x,y].filter(z=>!z.error).length,1);assert.equal([x,y].filter(z=>z.error&&z.error.code==='40001').length,1);});
test('stale writer is blocked locally after ownership refresh and server remains authority',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const b=factory(r2,lifecycle(r2,null));await b.takeover('cssbb:session:s15');await a.refresh('test');assert.equal(a.authorityFor('cssbb:session:s15').phase,'stale');const out=r1.__TBLearning.recordDraft({sessionId:'cssbb:session:s15'});assert.equal(out.reason,'STALE_SESSION_WRITER');assert.equal(out.saved,false);});
test('a cloud-active session blocks a different local session before any new evidence is written',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const b=factory(r2,lifecycle(r2,null));await b.refresh('test');assert.equal(b.authorityFor('cssbb:session:s15').phase,'remote');const out=r2.__TBLearning.startSession({sessionId:'cssbb:session:new',examId:'cssbb',mode:'quick',returnResult:true});assert.equal(out.blocked,true);assert.equal(out.reason,'ACTIVE_CLOUD_SESSION_EXISTS');svc.row=null;await b.refresh('cloud-terminal');assert.equal(b.authorityFor('cssbb:session:s15'),null);assert.equal(r2.__TBLearning.startSession({sessionId:'cssbb:session:new',examId:'cssbb',mode:'quick',returnResult:true}).saved,true);});
test('takeover restores only cloud checkpoint, not stale device local draft',async()=>{const svc=new Service(),cloud=snapshot(0,null),r1=root(svc),L1=lifecycle(r1,cloud),a=factory(r1,L1);await seedCloud(a,svc,cloud);L1.save(snapshot(0,'o1'));const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const L2=lifecycle(r2,null),b=factory(r2,L2);await b.takeover('cssbb:session:s15');assert.equal(L2._get().orderedItems[0].selectedOptionId,null);assert.equal(svc.row.snapshot.payload.orderedItems[0].selectedOptionId,null);});
test('local divergence requires explicit cloud-state confirmation and preserves conflict evidence',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const b=factory(r2,lifecycle(r2,null));await b.takeover('cssbb:session:s15');await a.refresh('stale');L1.save(snapshot(0,'o1'));await assert.rejects(()=>a.takeover('cssbb:session:s15'),e=>e.code==='LOCAL_UNUPLOADED_CHANGES');await a.takeover('cssbb:session:s15',{confirmCloudState:true});assert.ok(a.conflicts('cssbb:session:s15').length>=1);});
test('unsynced stale learning events are preserved as conflicts and removed before adopting new epoch',async()=>{const svc=new Service(),state={version:2,events:[],sessions:{},index:{knownEventIds:{},totals:{'user:u1':{cssbb:{answerStates:{},answers:0}}},seen:{}}},r1=root(svc,state),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');const b=factory(r2,lifecycle(r2,null));await b.takeover('cssbb:session:s15');state.events.push({id:'pending-1',sessionId:'cssbb:session:s15',examId:'cssbb',questionId:'cssbb:q1',scope:'user:u1',type:'answer_recorded',syncedFor:[],payload:{status:'correct'}});state.index.knownEventIds['pending-1']=1;state.index.totals['user:u1'].cssbb.answerStates['cssbb:session:s15|cssbb:q1']={eventId:'pending-1',status:'correct'};state.index.totals['user:u1'].cssbb.answers=1;L1.save(snapshot(0,'o1'));await assert.rejects(()=>a.takeover('cssbb:session:s15'),e=>e.code==='LOCAL_UNUPLOADED_CHANGES');await a.takeover('cssbb:session:s15',{confirmCloudState:true});assert.equal(state.events.some(e=>e.id==='pending-1'),false);assert.equal(state.index.totals['user:u1'].cssbb.answers,0);assert.equal(a.conflicts('cssbb:session:s15').some(c=>c.pendingEvents.some(e=>e.id==='pending-1')),true);});
test('timed takeover re-verifies trusted time and never changes the pinned deadline',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');let recovered=0;r2.__TBSessionTiming.recover=async()=>{recovered++;return {ready:true};};const L2=lifecycle(r2,null),b=factory(r2,L2);await b.takeover('cssbb:session:s15');assert.equal(recovered,1);assert.equal(L2._get().deadlineAt,'2026-09-10T02:00:00.000Z');});
test('expired timed cloud session fails closed after takeover clock recovery',async()=>{const svc=new Service(),r1=root(svc),L1=lifecycle(r1,snapshot()),a=factory(r1,L1);await seedCloud(a,svc);const r2=root(svc);r2.localStorage.setItem('tb-account-sync-device-v1','device-B');r2.__TBSessionTiming.isExpired=()=>true;const b=factory(r2,lifecycle(r2,null));await assert.rejects(()=>b.takeover('cssbb:session:s15'),e=>e.code==='SESSION_DEADLINE_REACHED');});
test('another account cannot validate or adopt an owner-one checkpoint',()=>{const svc=new Service(),r=root(svc);r.UpskillAuth.getUser=()=>({id:'u2'});const api=factory(r,lifecycle(r,null));assert.throws(()=>api.validateEnvelope(envelope()),e=>e.code==='HANDOFF_OWNER_MISMATCH');});
test('adaptive checkpoint is explicitly untimed and uses the same durable learning session identity',()=>{const svc=new Service(),r=root(svc);const a={version:2,examId:'cssbb',learningSessionId:'cssbb:adaptive:s1',startedAt:Date.parse('2026-09-10T00:00:00Z'),complete:false,index:2,answers:{0:1},checked:{0:true},versionPin:{ownerId:'u1',examId:'cssbb',orderedItems:[{questionId:'cssbb:q1'}]}};r.localStorage.setItem('tb-adaptive-session-v2',JSON.stringify(a));r.__TBLearning.store().sessions[a.learningSessionId]={writerEpoch:3};const api=factory(r,lifecycle(r,null));const e=api.adaptiveEnvelope();assert.equal(e.kind,'adaptive');assert.equal(e.sessionId,a.learningSessionId);assert.equal(e.timed,false);assert.equal(e.deadlineAt,null);assert.equal(e.writerEpoch,3);});
test('offline takeover fails closed and cannot claim cloud continuation',async()=>{const svc=new Service(),r=root(svc),L=lifecycle(r,snapshot()),api=factory(r,L);await seedCloud(api,svc);r.navigator.onLine=false;await assert.rejects(()=>api.takeover('cssbb:session:s15'),e=>e.code==='HANDOFF_OFFLINE');});
