'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const V=require('../test-bank-versioning.js');
const {fixture,live,read}=require('./helpers/segment04-identity.cjs');
const {installDurableLearning}=require('./helpers/test-bank-durable-learning.js');
const {artifacts,readExams}=require('../scripts/exam-reliability/build-catalog.cjs');
const stamp=Date.UTC(2026,8,8,3);
function model(){const questions=[0,1,2].map(i=>({qid:'cssbb:test:'+i,sub:'a',stem:'Question '+i,options:['A','B','C','D'],answer:i,why:'Original explanation'}));const exam={questions:3,minutes:5,pass:70,bok:[{domain:'one',weight:3,subs:[{id:'a',w:3}]}],sets:{1:questions},bank:questions};return {questions,exam,catalog:V.createExamCatalog('cssbb',exam,{source:'synthetic'})};}
function pinned(m,input={}){return V.pin({examId:'cssbb',sessionId:'version-session-01',setId:'1',questions:m.questions,mode:'exam',timed:true,limitSeconds:300,startedAt:stamp,...input},m.exam,m.catalog);}
function records(m){return m.questions.map((question,i)=>({question,selected:[0,0,null][i],status:'correct'}));}
function ledger(t){const f=fixture(t);f.w.TextEncoder=require('node:util').TextEncoder;f.w.eval(read('test-bank-versioning.js'));f.w.__TB.examVersionPolicy='catalog-v1';f.w.__TBVersionCatalog={exams:{cssbb:f.w.__TBVersions.createExamCatalog('cssbb',f.exam,{source:'synthetic'})}};f.w.UpskillAuth={getUser:()=>({id:'version-owner'}),getClient:()=>null};f.w.eval(read('test-bank-learning-events.js'));return f;}
for(const text of ['', 'abc','你好 – Δ😀\ud800','a'.repeat(1000),'z'.repeat(65537)])test('SHA-256 matches independent node:crypto for '+text.length+' UTF16 units',()=>assert.equal(V.sha256(text),crypto.createHash('sha256').update(text).digest('hex')));
test('canonical serialization is key-order independent and rejects unsafe/non-JSON values',()=>{assert.equal(V.canonical({b:1,a:{z:2,x:3}}),V.canonical({a:{x:3,z:2},b:1}));for(const x of [NaN,Infinity,undefined,JSON.parse('{"__proto__":3}')])assert.throws(()=>V.canonical(x));});
test('each semantic correction changes revision without changing canonical identity',()=>{const m=model(),q=m.questions[0];for(const [field,value] of [['stem','Corrected'],['answer',1],['options',['B','A','C','D']],['why','Revised'],['sub','b'],['chart',{type:'chart',data:[1,2]}]]){const modified={...q,[field]:value};assert.equal(modified.qid,q.qid);assert.notEqual(V.digest('question-v1',V.content(q)),V.digest('question-v1',V.content(modified)));}});
test('bank reordering is not a content or membership revision; set change is a bank revision',()=>{const m=model();m.questions.reverse();assert.equal(V.createExamCatalog('cssbb',m.exam,{source:'synthetic'}).bankVersion,m.catalog.bankVersion);m.exam.sets[2]=[m.questions[0]];const changed=V.createExamCatalog('cssbb',m.exam,{source:'synthetic'});assert.notEqual(changed.bankVersion,m.catalog.bankVersion);assert.deepEqual(changed.questions,m.catalog.questions);});
test('configuration, blueprint, clock and site target are separately versioned',()=>{for(const change of [e=>e.pass=80,e=>e.minutes=6,e=>e.questions=2,e=>e.bok[0].weight=2,e=>e.fullExamQuestionsBySet={1:175}]){const m=model();change(m.exam);const c=V.createExamCatalog('cssbb',m.exam,{source:'synthetic'});assert.notEqual(c.configVersion,m.catalog.configVersion);assert.equal(c.bankVersion,m.catalog.bankVersion);}});
test('immutable snapshot contains the frozen C03 required fields',()=>{const m=model(),p=pinned(m);const c=JSON.parse(read('docs/exam-reliability/contracts/v1/contract.json'));for(const field of c.session.snapshotRequired)assert.ok(Object.hasOwn(p,field),field);for(const item of p.orderedItems)for(const field of c.session.itemRequired)assert.ok(Object.hasOwn(item,field),field);assert.equal(p.masteryPolicyVersion,c.mastery.policyVersion);assert.ok(Object.isFrozen(p.contents[0].options));assert.throws(()=>p.contents[0].answer=3);});
test('later content, key, length, target and taxonomy edits cannot rewrite the started session',()=>{const m=model(),p=pinned(m),original=V.grade(p,records(m));m.questions[0].answer=3;m.questions[0].stem='Different';m.exam.pass=0;m.exam.minutes=1;m.exam.questions=175;m.exam.bok[0].domain='new';assert.deepEqual(V.grade(p,records(m)),original);assert.equal(p.expectedLength,3);assert.equal(p.siteTargetBps,7000);assert.equal(p.deadlineAt,new Date(stamp+300000).toISOString());});
test('original score includes blanks once and uses exact count target arithmetic',()=>{const m=model(),p=pinned(m),g=V.grade(p,records(m));assert.deepEqual([g.total,g.correct,g.incorrect,g.unanswered],[3,1,1,1]);assert.equal(g.siteTargetMet,false);assert.equal(g.byDomain.one.total,3);const q=Array.from({length:165},(_,i)=>({...m.questions[0],qid:'cssbb:test:'+i}));m.exam.questions=165;m.exam.sets[1]=q;m.questions=q;m.catalog=V.createExamCatalog('cssbb',m.exam,{});const grade=V.grade(pinned(m),q.map((question,i)=>({question,selected:i<115?0:1})));assert.equal(Math.round(grade.scorePercent),70);assert.equal(grade.siteTargetMet,false);});
test('unknown target stays unknown, never defaults to 70',()=>{const m=model();m.exam.pass=null;m.catalog=V.createExamCatalog('cssbb',m.exam,{});assert.equal(V.grade(pinned(m),records(m)).siteTargetMet,null);assert.deepEqual(V.context({}),{provenance:'legacy-unknown',expectedLength:null,siteTargetBps:null,configVersion:null,bankVersion:null});});
for(const [label,mutate] of [['answer',p=>p.contents[0].answer=3],['configuration',p=>p.configuration.minutes=1],['domain',p=>p.orderedItems[0].domainId='wrong'],['revision',p=>p.orderedItems[0].questionRevision='f'.repeat(64)],['option permutation',p=>p.orderedItems[0].optionOrder=['o0','o0','o2','o3']],['deadline',p=>p.deadlineAt=new Date(stamp+600000).toISOString()]])test('serialized pin rejects corrupt '+label,()=>{const p=V.clone(pinned(model()));mutate(p);assert.throws(()=>V.checkedPin(p));});
test('completion rejects missing/reordered/foreign items and invalid options',()=>{const m=model(),p=pinned(m);for(const supplied of [records(m).slice(1),records(m).reverse(),records(m).map((r,i)=>i? r:{...r,question:{...r.question,qid:'cqe:test:0'}}),records(m).map(r=>({...r,selected:4})),records(m).map(r=>({...r,selected:'0'}))])assert.throws(()=>V.grade(p,supplied));});
test('unpublished revisions/configurations fail before starting; review/adaptive cannot be timed',()=>{for(const fn of [m=>m.questions[0].stem='Changed',m=>m.exam.pass=10]){const m=model();fn(m);assert.throws(()=>pinned(m));}for(const mode of ['adaptive','review','unknown'])assert.throws(()=>pinned(model(),{mode}));});
test('real ledger writes start version, grades pinned key, and retries return the unchanged original',t=>{const f=ledger(t),api=f.w.__TBLearning;const started=api.startSession({examId:'cssbb',questions:f.rows,mode:'quick',returnResult:true});assert.equal(started.saved,true);const current=f.rows[0];current.answer=3;current.stem='Later wording';f.exam.pass=99;const saved=api.recordAnswer({examId:'cssbb',sessionId:started.sessionId,question:current,index:0,selected:0,status:'incorrect'});assert.equal(saved.saved,true);const supplied=f.rows.map((question,i)=>({question,selected:i?null:0}));const result=api.completeSession({examId:'cssbb',sessionId:started.sessionId,records:supplied});assert.equal(result.correct,1);assert.equal(result.grading.siteTargetBps,7000);const again=api.completeSession({examId:'cssbb',sessionId:started.sessionId,records:f.rows.map(question=>({question,selected:3}))});assert.equal(again.correct,1);assert.equal(api.eventsForExam('cssbb').filter(e=>e.type==='session_completed').length,1);const start=api.eventsForExam('cssbb').find(e=>e.type==='session_started');assert.equal(start.payload.versionPin.items.length,2);assert.equal(result.versionPin.items,undefined,'completion references the start instead of duplicating its manifest');});
test('unknown session, cross-account reuse and invalid completion do not publish results',t=>{const f=ledger(t),api=f.w.__TBLearning;assert.equal(api.completeSession({examId:'cssbb',sessionId:'never-started',records:[]}).saved,false);const s=api.startSession({examId:'cssbb',questions:f.rows,mode:'quick',returnResult:true});assert.equal(api.completeSession({examId:'cssbb',sessionId:s.sessionId,records:[]}).saved,false);f.w.UpskillAuth.getUser=()=>({id:'another-owner'});assert.equal(api.completeSession({examId:'cssbb',sessionId:s.sessionId,records:[]}),null);assert.equal(api.eventsForExam('cssbb').filter(e=>e.type==='session_completed').length,0);});
test('new-only does not remotely claim an unpublished revision',async t=>{const f=ledger(t);let calls=0;f.w.UpskillAuth.getClient=()=>({rpc(){calls++;return Promise.resolve({data:[],error:null});}});f.rows[0].stem='Unpublished';const result=await f.w.__TBLearning.reserveNewQuestions({examId:'cssbb',questions:f.rows});assert.equal(result.reason,'invalid-exam-version');assert.equal(calls,0);});
test('missing catalogue fails visibly without creating a planned session',t=>{const f=ledger(t);delete f.w.__TBVersionCatalog;const before=JSON.stringify(f.w.__TBLearning.store());const r=f.w.__TBLearning.startSession({examId:'cssbb',questions:f.rows,mode:'quick',returnResult:true});assert.equal(r.saved,false);assert.equal(JSON.stringify(f.w.__TBLearning.store()),before);});
test('explicit aliases resolve retired canonical identities without guessing',()=>{assert.equal(V.resolveAlias('cssbb','old-hash',[{examId:'cssbb',alias:'old-hash',questionId:'cssbb:retired:1'}]),'cssbb:retired:1');assert.equal(V.resolveAlias('cssbb','missing',[]),'missing');assert.throws(()=>V.resolveAlias('cssbb','x',[{examId:'cssbb',alias:'x',questionId:'cqe:q'}]));assert.throws(()=>V.resolveAlias('cssbb','x',[{examId:'cssbb',alias:'x',questionId:'cssbb:q'},{examId:'cssbb',alias:'x',questionId:'cssbb:r'}]));});
test('all published sets retain 3189 identities; archives and exact generated artifacts validate',async()=>{const a=await artifacts();let count=0;for(const [id,c]of Object.entries(a.catalog.exams)){const bank=JSON.parse(a.out['exam-catalog/'+c.bankVersion+'.json']);assert.equal(V.validateArchive(bank,c.bankVersion,id).bankVersion,c.bankVersion);V.validateConfiguration(JSON.parse(a.out['exam-catalog/config-'+c.configVersion+'.json']),c.configVersion);count+=Object.keys(c.questions).length;}assert.equal(count,3189);for(const [name,text]of Object.entries(a.out))assert.equal(read(name),text,name);});
test('MBB Set 2/3 pin 175 items and 15750 seconds; mixed/set1 remain 100',async()=>{const exams=await readExams(),e=exams.mbb,c=V.createExamCatalog('mbb',e,{});for(const setId of ['1','2','3','mix']){const expected=['2','3'].includes(setId)?175:100;const p=V.pin({examId:'mbb',sessionId:'mbb-version-'+setId,questions:(e.sets[setId]||Object.values(e.sets).flat()).slice(0,expected),setId,mode:'exam',timed:true,limitSeconds:expected*90,startedAt:stamp},e,c);assert.equal(p.expectedLength,expected);assert.equal(p.limitSeconds,expected*90);}});
test('all published full sessions fit existing 64KiB wire payload with maximum event ID lengths',async()=>{const exams=await readExams();for(const [examId,e] of Object.entries(exams).filter(([_,e])=>e.sets)){const c=V.createExamCatalog(examId,e,{});for(const [setId,all]of Object.entries(e.sets)){const count=Math.min(all.length,e.fullExamQuestionsBySet?.[setId]||e.questions),qs=all.slice(0,count);const p=V.pin({examId,sessionId:'x'.repeat(180),questions:qs,setId,mode:'exam',timed:false,startedAt:stamp},e,c);const g=V.clone(V.grade(p,qs.map(question=>({question,selected:0}))));delete g.answers;const data={versionPin:V.reference(p),grading:g,answers:qs.map(q=>({questionId:q.qid,selected:0,status:'incorrect',sub:q.sub,firstExposure:false})),answerEventIds:qs.map(()=> 'a'.repeat(180))};assert.ok(Buffer.byteLength(JSON.stringify(data,null,1))<65536,examId+setId);assert.ok(Buffer.byteLength(JSON.stringify({versionPin:V.wire(p)},null,1))<65536);}}});
test('archive fetch fails closed; corrupt or unavailable history never becomes current content',async()=>{const {catalog,out}=await artifacts(),c=catalog.exams.cssbb;const ref={codec:1,contractVersion:'1.0.0',examId:'cssbb',configVersion:c.configVersion,bankVersion:c.bankVersion};const fetched=await V.loadHistory(ref,async url=>({ok:true,json:async()=>JSON.parse(out[url.slice(1)])}));assert.equal(fetched.bank.bankVersion,c.bankVersion);await assert.rejects(()=>V.loadHistory(ref,async()=>({ok:false})));const bad=V.clone(fetched.bank);Object.values(bad.contents)[0].content.answer=99;assert.throws(()=>V.validateArchive(bad,c.bankVersion,'cssbb'));await assert.rejects(()=>V.loadHistory({...ref,bankVersion:'../../file'},()=>{throw Error('must not fetch');}));});
test('actual shipped core uses pinned copies and original result after live bank/key/target changes',async t=>{const {dom,w}=await live();t.after(()=>dom.window.close());await installDurableLearning(w);const e=w.__TB.EXAMS.cssbb,qs=e.sets[1].slice(0,3),answers=qs.map(q=>q.answer);assert.equal(w.__TBSegment04Probe.begin(e,qs,'quick',false,null),true);qs.forEach(q=>{q.answer=(q.answer+1)%4;q.stem='Edited after start';});e.pass=0;e.questions=175;e.minutes=1;for(let i=0;i<3;i++){w.document.querySelector('[data-goto="'+i+'"]').click();assert.ok(!w.document.querySelector('.tb-quiz').textContent.includes('Edited after start'));w.document.querySelector('[data-opt="'+answers[i]+'"]').click();}w.document.querySelector('[data-submit]').click();assert.match(w.document.querySelector('.tb-resverd').textContent,/3 of 3 correctly/);const done=w.__TBLearning.eventsForExam('cssbb').find(x=>x.type==='session_completed');assert.equal(done.payload.versionPin.siteTargetBps,7000);assert.equal(done.payload.correct,3);});

test('stored option permutations preserve displayed option identity and original grading',()=>{const m=model(),p=V.clone(pinned(m));p.orderedItems[0].optionOrder=['o2','o0','o3','o1'];p.pinDigest=V.digest('session-pin-v1',V.wire(p));const q=V.questionFor(p,m.questions[0],0).question;assert.deepEqual(q.options,['C','A','D','B']);assert.equal(q.answer,1);const rs=records(m);rs[0].selected=1;assert.equal(V.grade(p,rs).correct,1);assert.equal(V.grade(p,rs).answers[0].selectedOptionId,'o0');});

test('versioned answer events preserve complete JSON content, not just the common text fields',t=>{const {w,exam,rows}=ledger(t);const q=rows[0];q.visualData={labels:['start','finish'],values:[1,2]};w.__TBVersionCatalog.exams.cssbb=w.__TBVersions.createExamCatalog('cssbb',exam,{source:'synthetic'});const start=w.__TBLearning.startSession({examId:'cssbb',sessionId:'snapshot-extended',mode:'quick',questions:[q],returnResult:true});assert.equal(start.saved,true);w.__TBLearning.recordAnswer({examId:'cssbb',sessionId:start.sessionId,question:q,index:0,selected:q.answer,status:'correct'});const event=w.__TBLearning.store().events.find(e=>e.type==='answer_recorded');assert.deepEqual(JSON.parse(JSON.stringify(event.payload.snapshot.visualData)),{labels:['start','finish'],values:[1,2]});q.visualData.values[0]=99;assert.equal(event.payload.snapshot.visualData.values[0],1);});

test('only an owned, acknowledged, projected terminal pin is compactable under quota recovery',()=>{const vm=require('node:vm'),source=read('test-bank-learning-events.js');const a=source.indexOf('  function compactConfirmedPayloads(state) {'),b=source.indexOf('\n  function mirrorSupported()',a);assert.ok(a>0&&b>a);const p=pinned(model()),sessions={};for(const name of ['active','pending','foreign','unprojected','accepted'])sessions[name]={status:name==='active'?'in_progress':'completed',masteryDerived:name!=='unprojected',ownerId:'A',versionPin:V.clone(p)};const completions=Object.fromEntries(Object.keys(sessions).map(k=>[k,{syncedFor:k==='pending'?[]:[k==='foreign'?'B':'A']} ]));const state={sessions,events:[]};const fn=vm.runInNewContext('('+source.slice(a,b).trim()+')',{window:{__TBVersions:V},completionEventForSession:(_,id)=>completions[id],asArray:x=>Array.isArray(x)?x:[]});fn(state);assert.equal(state.sessions.accepted.versionPin,null);assert.equal(state.sessions.accepted.archivedVersionPin.bankVersion,p.bankVersion);for(const k of ['active','pending','foreign','unprojected'])assert.ok(state.sessions[k].versionPin,k);});

test('every complete published question snapshot fits the deployed event payload limit',async()=>{const exams=await readExams();for(const [id,e] of Object.entries(exams)){for(const q of Object.values(e.sets||{}).flat()){const payload={index:199,status:'incorrect',selected:3,correctAnswer:q.answer,versionRef:{codec:1,configVersion:'f'.repeat(64),bankVersion:'f'.repeat(64),questionRevision:'f'.repeat(64)},mode:'diagnostic',timed:true,sub:q.sub,snapshot:q};assert.ok(Buffer.byteLength(JSON.stringify(payload,null,1))<65536,id+':'+q.qid);}}});


test('historical archive reconstruction preserves pinned option order and rejects malformed tuples',()=>{
  const m=model(),p=V.clone(pinned(m));p.orderedItems[0].optionOrder=['o2','o0','o3','o1'];p.pinDigest=V.digest('session-pin-v1',V.wire(p));
  const archive={schemaVersion:V.schemaVersion,examId:'cssbb',bankVersion:m.catalog.bankVersion,sets:m.catalog.sets,contents:Object.fromEntries(m.questions.map(q=>[q.qid,{revision:m.catalog.questions[q.qid],content:V.content(q)}]))};
  const manifest=V.wire(p),qs=V.historicalQuestions(manifest,archive);assert.deepEqual(qs[0].options,['C','A','D','B']);assert.equal(qs[0].answer,1);assert.ok(Object.isFrozen(qs[0].options));
  for(const change of [v=>v.items[0][2]=['o0','o0','o2','o3'],v=>v.items[0][2]=['o8','o1','o2','o3'],v=>v.items[1]=v.items[0],v=>delete v.items]){const bad=V.clone(manifest);change(bad);assert.throws(()=>V.historicalQuestions(bad,archive));}
});

test('actual adaptive restore preserves option mapping and refuses a foreign owner',()=>{
  const vm=require('node:vm'),source=read('test-bank-adaptive-mastery-hardening.js');const a=source.indexOf('  function restoreSession() {'),b=source.indexOf('\n  function ',a+20);assert.ok(a>0&&b>a);
  const m=model(),p=V.clone(pinned(m));p.ownerId='owner-A';p.orderedItems[0].optionOrder=['o2','o0','o3','o1'];p.pinDigest=V.digest('session-pin-v1',V.wire(p));let owner='owner-A';
  const context={restoreError:null,SESSION_KEY:'test',localStorage:{getItem:()=>JSON.stringify({examId:'cssbb',versionPin:p,complete:false})},examId:()=> 'cssbb',window:{__TBVersions:V,__TBLearning:{status:()=>({userId:owner})}}};
  const restore=vm.runInNewContext('('+source.slice(a,b).trim()+')',context),saved=restore();assert.deepEqual(JSON.parse(JSON.stringify(saved.items[0].options)),['C','A','D','B']);assert.equal(saved.items[0].answer,1);
  owner='owner-B';assert.equal(restore(),null);assert.match(context.restoreError.message,/another account/);
});
