'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const q=require('../scripts/exam-reliability/segment19-qualification.cjs');
function samples(n,v){return Array.from({length:n},()=>v);}
function automated(){return {schemaVersion:1,examIds:[...q.REQUIRED_EXAMS],modes:[...q.REQUIRED_MODES],workloads:{...q.profiles.workloads},budgets:q.profiles.budgets.filter(x=>x.enforcedFromSegment<=19).map(b=>({id:b.id,status:'passed'})),invariants:{...q.profiles.invariants},unresolvedConfirmedDefects:0,migrationRecovery:{freshInstall:true,backupRestore:true,rollbackSafe:true}};}
function physical(){return {schemaVersion:1,records:q.REQUIRED_PHYSICAL.map(id=>({id,physical:true,emulated:false,status:'passed',device:'physical fixture',os:'fixture-os',browser:'fixture-browser',executedAt:'2026-09-10T00:00:00Z',observer:'fixture-observer'}))};}
function realNetwork(){return {schemaVersion:1,environment:'real_network',synthetic:false,emulated:false,executedAt:'2026-09-10T00:00:00Z',observer:'fixture-observer',connection:'witnessed test connection',locationClass:'controlled test location',budgets:q.REQUIRED_REAL_NETWORK_BUDGETS.map(id=>{const b=q.profiles.budgets.find(x=>x.id===id),value=Math.max(0,b.limitMs-1);return {id,network:b.network,status:'passed',valueMs:value,samplesMs:samples(b.minimumSamples,value)};})};}
test('Segment19 qualification requires all five certifications and all seven modes',()=>assert.equal(q.validateAutomated(automated()),true));
test('frozen p95 uses nearest-rank and refuses inadequate samples',()=>{assert.equal(q.p95([1,2,3,4,5]),5);assert.throws(()=>q.evaluateBudget('quick_start',samples(29,1000)),/requires 30/);assert.equal(q.evaluateBudget('quick_start',samples(30,1999)).status,'passed');assert.equal(q.evaluateBudget('quick_start',[...samples(28,1000),2001,3000]).status,'failed');});
test('every frozen Segment19 budget is mandatory and cannot be silently dropped',()=>{const x=automated();x.budgets.pop();assert.throws(()=>q.validateAutomated(x),/budget coverage mismatch/);});
test('frozen workload floors cannot be weakened',()=>{for(const k of ['normalRemoteEvents','stressRemoteEvents','pendingOperations','completedSessions','concurrentDevices']){const x=automated();x.workloads[k]=q.profiles.workloads[k]-1;assert.throws(()=>q.validateAutomated(x),/below frozen workload/);}});
test('zero-loss, zero-duplicate, zero-cross-account and reconciliation invariants are release blockers',()=>{for(const k of ['acknowledgedDataLoss','duplicateCanonicalCompletions','unauthorizedRows','pageReloadsForSync']){const x=automated();x.invariants[k]=1;assert.throws(()=>q.validateAutomated(x),/invariant failed/);}const x=automated();x.invariants.knownFirstPlusRepeatPlusUnknownEqualsAnswers=false;assert.throws(()=>q.validateAutomated(x),/reconciliation/);});
test('confirmed in-scope defects or incomplete migration recovery block qualification',()=>{let x=automated();x.unresolvedConfirmedDefects=1;assert.throws(()=>q.validateAutomated(x),/defects remain/);x=automated();x.migrationRecovery.backupRestore=false;assert.throws(()=>q.validateAutomated(x),/recovery/);});
test('browser emulation cannot satisfy physical iPhone/iPad/laptop evidence',()=>{const x=physical();assert.equal(q.validatePhysical(x),true);x.records[0].emulated=true;assert.throws(()=>q.validatePhysical(x),/cannot be emulated/);});
test('real-network evidence requires exact profiles, provenance, sample floors and recomputed values',()=>{const x=realNetwork();assert.equal(q.validateRealNetwork(x),true);const synthetic=realNetwork();synthetic.synthetic=true;assert.throws(()=>q.validateRealNetwork(synthetic),/not accepted/);const short=realNetwork();short.budgets[0].samplesMs.pop();assert.throws(()=>q.validateRealNetwork(short),/inadequate samples/);const altered=realNetwork();altered.budgets[0].valueMs+=1;assert.throws(()=>q.validateRealNetwork(altered),/does not match samples/);});
test('release status cannot promote emulation or missing WAN evidence to qualified',()=>{assert.equal(q.releaseStatus(automated(),{schemaVersion:1,records:[]},realNetwork()).status,'pending_physical');assert.equal(q.releaseStatus(automated(),physical(),{schemaVersion:1}).status,'pending_network');assert.equal(q.releaseStatus(automated(),physical(),realNetwork()).status,'qualified');});
