'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('node:assert/strict'),test=require('node:test');
const {JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const c={};c.window=c;vm.createContext(c);vm.runInContext(read('test-bank-mbb-set2.js'),c);const b=JSON.parse(JSON.stringify(c.MBB_SET2_BATCHES)),Q=n=>b[6][n-126];
const keys=[1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3,0,3];
const sort=x=>Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x,h=x=>crypto.createHash('sha256').update(x).digest('hex');
for(let n=126;n<=150;n++)test(`Q${n} independent adjudication, complete choices and source scope`,()=>{const q=Q(n);assert.equal(q.answer,keys[n-126]);assert.equal(q.optionRationales.length,4);assert.equal(new Set(q.options).size,4);assert.ok(q.why.includes('<b>'+'ABCD'[q.answer]+'. '+q.options[q.answer]+'</b>'));assert.equal(q.auditRevision,'final-audit-v1');assert.match(q.why,/not reverified/);});
test('Q150 rejects original B and accepts D with correctly indexed rationale',()=>{assert.equal(Q(150).answer,3);assert.doesNotMatch(Q(150).optionRationales[1],/^Correct/);assert.match(Q(150).optionRationales[3],/^Correct/);});
test('Q130 readiness, capacity and net value independently enumerated',()=>{const results=[];for(let bits=0;bits<4;bits++){let used=4+5*(!!(bits&1))+5*(!!(bits&2)),value=.7+.9*(!!(bits&1))+1.2*(!!(bits&2));if(used<=10)results.push({bits,used,value});}results.sort((a,b)=>b.value-a.value);assert.equal(results[0].bits,2);assert.equal(results[0].used,9);assert.ok(Math.abs(results[0].value-1.9)<1e-12);assert.equal(Q(130).chart.rows[3][2],'Not monetized');assert.doesNotMatch(Q(130).options[0],/three/);});
test('Q136 paths and Q139 subtotal arithmetic are consistent',()=>{const c=Q(136).chart,d=id=>c.nodes[id].dur;assert.equal(d('A')+d('B')+d('D')+d('E'),13);assert.equal(d('A')+d('C')+d('E'),11);assert.equal(c.durationUnit,'working weeks');assert.match(Q(139).options[1],/1\.5M/);assert.match(Q(139).stem,/realized/);});
test('Q146 table independently reproduces Cohen kappa and class rates',()=>{const rows=Q(146).chart.rows.map(r=>r.slice(1).map(v=>+v.replaceAll(',',''))),[[tp,fn],[fp,tn]]=rows,po=(tp+tn)/2000,pe=((tp+fn)*(tp+fp)+(fp+tn)*(fn+tn))/2000**2;assert.equal(po,.96);assert.ok(Math.abs((po-pe)/(1-pe)-.3830968538)<1e-9);assert.equal(tp/(tp+fn),.3375);assert.equal(tn/(fp+tn),.9859375);});
test('Q147 pointwise bounds have stated sample size',()=>{assert.ok(Math.abs(1.96/Math.sqrt(80)-.22)<.001);assert.match(Q(147).assumptions.join(' '),/pointwise/);});
function dom(){const d=new JSDOM('<head></head><body></body>',{runScripts:'outside-only'});d.window.eval(read('test-bank-mbb-final-audit-ui.js'));return d;}
test('Every Q148 contour coordinate solves its labelled equation',()=>{const d=dom();try{for(const level of [70,76,81,84])for(const[x,y]of d.window.__MBBFinalAuditUI.contourCoordinates(level)){const value=82+6*x+4*y-3*x*x-2*y*y-2*x*y;assert.ok(Math.abs(value-level)<1e-10);}assert.ok(Math.abs(82+6*.8+4*.6-3*.8**2-2*.6**2-2*.8*.6-85.6)<1e-10);}finally{d.window.close();}});
test('All audited evidence tables retain column headers and both keyboard selectors/reset work',()=>{const d=dom(),ui=d.window.__MBBFinalAuditUI;try{for(const q of b[6].filter(q=>q.chart)){d.window.document.body.innerHTML=ui.render(q.chart);assert.ok(d.window.document.querySelector('.mbbF-evidence'));assert.doesNotMatch(d.window.document.body.innerHTML,/NaN|undefined/);if(q.chart.type==='data-table')assert.equal(d.window.document.querySelectorAll('thead th').length,q.chart.columns.length);}for(const n of [134,147]){d.window.document.body.innerHTML=ui.render(Q(n).chart);const s=d.window.document.querySelector('select');s.value='1';s.dispatchEvent(new d.window.Event('change',{bubbles:true}));assert.equal(d.window.document.querySelector('output').textContent,s.options[1].textContent);d.window.document.querySelector('[data-mbbf-point="0"]').dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(s.value,'0');}d.window.document.body.innerHTML=ui.render(Q(130).chart);const inp=d.window.document.querySelector('input');inp.value='13';inp.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.match(d.window.document.querySelector('output').textContent,/13/);d.window.document.querySelector('button').click();assert.equal(inp.value,'10');}finally{d.window.close();}});
test('Static evidence retains nine visuals and no dead controls',()=>{const d=new JSDOM(read('test-bank-assets/mbb-160/batch-06/static-fallbacks.html'));try{assert.equal(d.window.document.querySelectorAll('.fallback-card').length,9);assert.equal(d.window.document.querySelectorAll('input,select,button,[data-mbbf-point]').length,0);}finally{d.window.close();}});
test('Only Q150 is rekeyed; all 150 outside records and 24 outside assets are preserved',()=>{const p=JSON.parse(read('docs/audits/mbb-set2-batch06/preservation.json')),all=Object.values(b).flat();assert.equal(all.length,175);for(const q of all)if(q.batch!==6)assert.equal(h(JSON.stringify(sort(q))),p.questions[q.qid],q.qid);const keys=all.map(q=>q.answer),expected=p.keys.slice();assert.equal(expected[149],1);expected[149]=3;assert.deepEqual(keys,expected);for(const[f,hash]of Object.entries(p.assets))assert.equal(h(fs.readFileSync(path.join(root,f))),hash,f);});
