'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const L=require('../test-bank-session-lifecycle.js');
require('../test-bank-session-lifecycle-finalization.js')(globalThis,L);
function storage(){const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
function snap(state='in_progress'){return {schemaVersion:1,contractVersion:'1.0.0',sessionId:'s1',ownerId:'u1',examId:'cssbb',setId:'1',mode:'exam',bankVersion:'b',blueprintVersion:'bp',gradingPolicyVersion:'g',masteryPolicyVersion:'m',timingPolicyVersion:'t',expectedLength:2,siteTargetBps:7000,orderedItems:[{itemId:'s1:0',questionId:'cssbb:q1',questionRevision:'r1',domainId:'d',optionIds:['o0','o1'],optionOrder:['o1','o0'],selectedOptionId:null,effectiveAnsweredAt:null},{itemId:'s1:1',questionId:'cssbb:q2',questionRevision:'r2',domainId:'d',optionIds:['o0','o1'],optionOrder:['o0','o1'],selectedOptionId:null,effectiveAnsweredAt:null}],state,sessionRevision:0,writerEpoch:0,resetEpochId:null,startedAt:'2026-09-09T05:00:00.000Z',deadlineAt:'2026-09-09T07:00:00.000Z',timed:true,reportingTimeZoneAtStart:'America/Regina',currentItemId:'s1:0',flags:[],versionPin:{}};}
function durablePin(){const s=snap();return {sessionId:'s1',examId:'cssbb',ownerId:'u1',setId:'1',mode:'exam',bankVersion:'b',blueprintVersion:'bp',configVersion:'cfg',gradingPolicyVersion:'g',masteryPolicyVersion:'m',timingPolicyVersion:'t',expectedLength:2,siteTargetBps:7000,orderedItems:s.orderedItems,sessionRevision:0,writerEpoch:0,resetEpochId:null,startedAt:s.startedAt,deadlineAt:s.deadlineAt,timed:true,limitSeconds:7200,reportingTimeZoneAtStart:'America/Regina',contents:[{qid:'cssbb:q1',answer:0},{qid:'cssbb:q2',answer:1}]};}
test('legal lifecycle transitions are explicit and terminals cannot reopen',()=>{let s=snap('created');s=L.transition(s,'start');assert.equal(s.state,'in_progress');s=L.transition(s,'submit');assert.equal(s.state,'finalizing');s=L.transition(s,'accept_completion');assert.equal(s.state,'completed');assert.throws(()=>L.transition(s,'resume'),e=>e.code==='ILLEGAL_SESSION_TRANSITION');});
test('timed sessions cannot pause and untimed sessions can pause/resume',()=>{assert.throws(()=>L.transition(snap(),'pause'),e=>e.code==='TIMED_PAUSE_FORBIDDEN');let s=snap();s.timed=false;s.deadlineAt=null;s=L.transition(s,'pause');assert.equal(s.state,'paused');assert.equal(L.transition(s,'resume').state,'in_progress');});
test('save/load is owner scoped and terminal state clears active pointer',()=>{const st=storage();L.save(snap(),{storage:st,ownerId:'u1'});assert.equal(L.load(null,{storage:st,ownerId:'u1'}).sessionId,'s1');assert.equal(L.load(null,{storage:st,ownerId:'u2'}),null);let s=L.transition(snap(),'abandon');L.save(s,{storage:st,ownerId:'u1'});assert.equal(L.load(null,{storage:st,ownerId:'u1'}),null);assert.equal(L.load('s1',{storage:st,ownerId:'u1'}).state,'abandoned');});
test('draft update uses canonical question identity and revision-local option order',()=>{const old=global.__TBQuestionRegistry;global.__TBQuestionRegistry={idFor:(_e,q)=>q.qid};try{let s=snap();s=L.updateDraft(s,{examId:'cssbb',index:0,question:{qid:'cssbb:q1'},selected:0});assert.equal(s.orderedItems[0].selectedOptionId,'o1');assert.equal(s.currentItemId,'s1:0');assert.throws(()=>L.updateDraft(s,{examId:'cssbb',index:0,question:{qid:'cssbb:other'},selected:0}),e=>e.code==='SESSION_ITEM_MISMATCH');}finally{global.__TBQuestionRegistry=old;}});
test('validation rejects duplicate item identity and current-position corruption',()=>{const s=snap();s.orderedItems[1].itemId='s1:0';assert.throws(()=>L.validateSnapshot(s),e=>e.code==='DUPLICATE_SESSION_ITEM');const c=snap();c.currentItemId='missing';assert.throws(()=>L.validateSnapshot(c),e=>e.code==='INVALID_CURRENT_ITEM');});
test('expiry and abandonment are terminal, finalizing permits retry only',()=>{let s=L.transition(snap(),'deadline_reached');assert.equal(s.state,'finalizing');assert.equal(L.transition(s,'retry').state,'finalizing');s=L.transition(s,'accept_expiry');assert.equal(s.state,'expired');assert.throws(()=>L.transition(s,'submit'));let a=L.transition(snap(),'abandon');assert.equal(a.state,'abandoned');assert.throws(()=>L.transition(a,'start'));});
test('snapshot from durable start preserves pinned order, timing policy and revisions',()=>{const pin=durablePin();const out=L.snapshotFromStart({examId:'cssbb',mode:'exam',setId:'1'},{sessionId:'s1',versionPin:pin});assert.deepEqual(out.orderedItems.map(x=>x.questionId),['cssbb:q1','cssbb:q2']);assert.equal(out.deadlineAt,pin.deadlineAt);assert.equal(out.timingPolicyVersion,'t');assert.equal(out.currentItemId,'s1:0');});
test('runtime synchronization persists the rendered current question after navigation repaint',()=>{const st=storage();const old={localStorage:global.localStorage,UpskillAuth:global.UpskillAuth,__TB:global.__TB,__TBQuestionRegistry:global.__TBQuestionRegistry,document:global.document};global.localStorage=st;global.UpskillAuth={getUser:()=>({id:'u1'})};global.__TBQuestionRegistry={idFor:(_exam,q)=>q.qid};global.__TB={getFeedbackSnapshot:()=>({sessionId:'s1',examId:'cssbb',records:[{question:{qid:'cssbb:q1'},selected:null,flagged:false},{question:{qid:'cssbb:q2'},selected:null,flagged:false}]})};global.document={querySelector:selector=>selector==='.tb-navcell.cur[data-goto]'?{dataset:{goto:'1'}}:null};try{L.save(snap());const updated=L.syncFromRuntime();assert.equal(updated.currentItemId,'s1:1');assert.equal(L.load('s1').currentItemId,'s1:1');}finally{Object.assign(global,old);}});
test('finalizing inputs are frozen; compact lifecycle retry resolves the durable version pin',()=>{const st=storage();const old={localStorage:global.localStorage,UpskillAuth:global.UpskillAuth,__TBVersions:global.__TBVersions,__TBLearning:global.__TBLearning};global.localStorage=st;global.UpskillAuth={getUser:()=>({id:'u1'})};const pin=durablePin();global.__TBVersions={checkedPin:candidate=>candidate,questionFor:(p,q,i)=>({question:p.contents[i]}),classify:(q,selected)=>selected==null?'unanswered':selected===q.answer?'correct':'incorrect'};let calls=0;global.__TBLearning={store:()=>({sessions:{s1:{id:'s1',versionPin:pin}}}),completeSession:input=>{calls++;assert.equal(input.sessionId,'s1');assert.equal(input.records.length,2);return {saved:true};}};try{let s=snap();delete s.versionPin;s.orderedItems[0].selectedOptionId='o1';s=L.transition(s,'submit',{completionReason:'submitted'});L.save(s);assert.throws(()=>L.abandonSaved('s1'),e=>e.code==='ILLEGAL_SESSION_TRANSITION');const result=L.retryFinalization('s1');assert.equal(result.saved,true);assert.equal(calls,1);}finally{Object.assign(global,old);}});
