'use strict';
const withFinalMetadata = require('./helpers/mbb-final-metadata-fingerprints');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
let c={};c.window=c;vm.createContext(c);vm.runInContext(read('test-bank-mbb-set2.js'),c);const all=JSON.parse(JSON.stringify(c.MBB_SET2)),batch=all.slice(150),Q=n=>batch[n-151];
// Independently adjudicated answers, not taken from the production key.
const keys=[3,0,1,2,3,0,1,2,3,2,1,0,3,0,1,2,3,0,1,2,3,0,1,2,3];
const stable=o=>Array.isArray(o)?o.map(stable):o&&typeof o==='object'?Object.fromEntries(Object.keys(o).sort().map(k=>[k,stable(o[k])])):o;
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} differs from ${b}`);
for(let i=0;i<25;i++)test(`Batch 7 Q${151+i}: independent key ${'ABCD'[keys[i]]} and complete decision evidence`,()=>{
 const q=batch[i];assert.equal(q.qid,`mbb:set-2:original-${151+i}`);assert.equal(q.answer,keys[i]);assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.equal(q.optionRationales.length,4);
 assert.ok(q.why.includes(`<b>${'ABCD'[keys[i]]}. ${q.options[keys[i]]}</b>`));assert.ok(q.assumptions.length>0);assert.match(q.sourceDocument,/2012/);assert.ok(q.bok.code);assert.doesNotMatch(q.why,/TBD|undefined|placeholder/);
});
test('Q155 independently enumerates all 16 subsets with funding, capacity and dependency',()=>{
 const rows=Q(155).chart.rows;const feasible=[];for(let mask=0;mask<16;mask++){const chosen=rows.filter((r,i)=>mask&(1<<i));const months=chosen.reduce((s,r)=>s+ +r[1],0),cost=chosen.reduce((s,r)=>s+ +r[2],0),value=chosen.reduce((s,r)=>s+ +r[3],0);if(months<=10&&cost<=300&&(!(mask&8)||(mask&2)))feasible.push({set:chosen.map(r=>r[0]).join(''),months,cost,value});}
 const best=feasible.sort((a,b)=>b.value-a.value);assert.deepEqual(best[0],{set:'BD',months:10,cost:280,value:540});assert.ok(best[0].value>best[1].value);assert.deepEqual(best.find(r=>r.set==='BC'),{set:'BC',months:9,cost:220,value:410});assert.match(Q(155).options[1],/9 Belt-months, \$220,000 funding, \$410,000/);assert.doesNotMatch(Q(155).formula,/BC=430/);
});
test('Q161 avoids intermediate rounding and separates cost from earned-value schedule variance',()=>{near(480/550,48/55);near(480/600,.8);near(1200000/(480/550),1375000);assert.equal(480000-550000,-70000);assert.equal(480000-600000,-120000);assert.match(Q(161).why,/unrounded CPI/);});
test('Q165 does not identify three effects from three identical intervention columns',()=>{const x=[[0,0,0],[0,0,0],[1,1,1],[1,1,1]];assert.ok(x.every(r=>r[0]===r[1]&&r[1]===r[2]));assert.match(Q(165).why,/collinear/);assert.match(Q(165).stem,/no variation/);});
test('Q168 preserves modeled residual uncertainty rather than labeling it pure repeatability',()=>{assert.equal(3*5*2,30);assert.equal(18+6,24);near(Math.sqrt(.24)*100,48.98979485566356);assert.match(Q(168).stem,/not demonstrated/);assert.match(Q(168).chart.rows[1][0],/Residual/);assert.match(Q(168).why,/heterogeneity/);assert.doesNotMatch(Q(168).chart.rows[1][0],/repeatability/i);});
test('Q169 keeps probabilities and capability indices dimensionless',()=>{assert.match(Q(169).why,/dimensionless/);assert.match(Q(169).why,/do not back-transform/);assert.match(Q(169).stem,/transformed observations/);assert.doesNotMatch(Q(169).stem,/normal residuals/);});
function ols(ch){const p=ch.points,n=p.length,xbar=p.reduce((a,p)=>a+p.x,0)/n,ybar=p.reduce((a,p)=>a+p.y,0)/n,sxx=p.reduce((a,p)=>a+(p.x-xbar)**2,0),sxy=p.reduce((a,p)=>a+(p.x-xbar)*(p.y-ybar),0),b=sxy/sxx,a=ybar-b*xbar,mse=p.reduce((s,p)=>s+(p.y-a-b*p.x)**2,0)/(n-2),h=1/n+(ch.proposal.x-xbar)**2/sxx;return {a,b,mse,h,mean:a+b*ch.proposal.x};}
test('Q170 OLS derives from exactly eight observations, excluding the unobserved proposal',()=>{const ch=Q(170).chart,f=ols(ch);assert.equal(ch.points.length,8);assert.deepEqual(ch.points.map(p=>p.x),[10,18,25,34,42,51,60,70]);assert.deepEqual(ch.points.map(p=>p.y),[24,29,31,39,43,49,56,61]);near(f.a,ch.model.intercept);near(f.b,ch.model.slope);near(f.mse,ch.model.mse);near(f.mean,ch.proposal.mean);near(f.h,ch.proposal.newPointLeverage);assert.equal(ch.model.df,6);assert.ok(f.h>1);assert.equal(ch.proposal.x,105);});
test('Q170 confidence and prediction intervals independently recompute with distinct variances',()=>{const ch=Q(170).chart,f=ols(ch),t=2.4469118511449786;const meanMargin=t*Math.sqrt(f.mse*f.h),predMargin=t*Math.sqrt(f.mse*(1+f.h));for(const[i,s]of [[0,-1],[1,1]]){near(ch.proposal.meanCI[i],f.mean+s*meanMargin);near(ch.proposal.predictionInterval[i],f.mean+s*predMargin);}assert.ok(predMargin>meanMargin);near(ch.proposal.mean,83.38430089942764);});
test('Q171 logistic interaction is interpreted conditionally, without converting odds into probability changes',()=>{assert.match(Q(171).why,/exp\(beta_T \+ beta_TS\*s\)/);assert.match(Q(171).stem,/Y=1/);assert.match(Q(171).why,/No causal effect/);});
test('Q172 series product and all three absolute increments independently recompute',()=>{const r=Q(172).chart.components.map(c=>c.reliability);near(r.reduce((a,b)=>a*b,1),.90307);const gain=r.map((v,i)=>.01*r.filter((_,j)=>j!==i).reduce((a,b)=>a*b,1));near(gain[0],.009215);near(gain[1],.009506);near(gain[2],.00931);assert.equal(gain.indexOf(Math.max(...gain)),1);assert.equal(Q(172).chart.series,undefined);assert.match(Q(172).assumptions.join(' '),/No additional common-mode/);});
test('Q173 does not invent a replacement stockout probability or infer a complete copula from correlation',()=>{assert.match(Q(173).why,/correlation coefficient do not uniquely determine/);assert.match(Q(173).why,/does not determine the true/);assert.match(Q(173).assumptions.join(' '),/not supplied/);});
function matrixRank(rows){let a=rows.map(r=>r.slice()),rank=0;for(let j=0;j<a[0].length&&rank<a.length;j++){let k=rank;while(k<a.length&&Math.abs(a[k][j])<1e-10)k++;if(k===a.length)continue;[a[k],a[rank]]=[a[rank],a[k]];let z=a[rank][j];a[rank]=a[rank].map(x=>x/z);for(let i=0;i<a.length;i++)if(i!==rank){let v=a[i][j];a[i]=a[i].map((x,p)=>x-v*a[rank][p]);}rank++;}return rank;}
const designModel=r=>[1,...r,r[0]*r[1],r[0]*r[2],r[0]*r[3],r[1]*r[2],r[1]*r[3],r[2]*r[3]];
test('Q174 defining relation, AB/CD alias and aliased factorial effect recompute',()=>{const r=Q(174).chart.designRows;assert.equal(r.length,8);for(const row of r){assert.equal(row.reduce((a,b)=>a*b),1);assert.equal(row[0]*row[1],row[2]*row[3]);}assert.equal((62+66-78-80)/2,-15);assert.match(Q(174).why,/not necessarily the same physical effect/);});
test('Q174 all-factor reversal repeats the fraction while D-only foldover supplies rank 11',()=>{const r=Q(174).chart.designRows,mirror=r.map(a=>a.map(v=>-v)),fold=r.map(a=>a.map((v,i)=>i===3?-v:v));assert.deepEqual(mirror.map(JSON.stringify).sort(),r.map(JSON.stringify).sort());assert.equal(matrixRank(r.map(designModel)),8);assert.equal(matrixRank([...r,...fold].map(designModel)),11);assert.ok(fold.every(a=>a.reduce((x,y)=>x*y)===-1));assert.match(Q(174).options[2],/reverse D alone/);});
function dom(){const d=new JSDOM('<!doctype html><head></head><body></body>',{runScripts:'outside-only'});d.window.eval(read('test-bank-mbb-batch7-ui.js'));return d;}
test('Renderer scope covers only Q151–175 and never changes earlier questions',()=>{const d=dom();try{const u=d.window.__MBBBatch7UI;for(const q of all){assert.equal(u.isQuestion(q),q.batch===7);if(q.batch===7){assert.match(u.conditions(q),/Stated conditions/);assert.match(u.rationales(q),/Choice D/);}else assert.equal(u.conditions(q),'');}}finally{d.window.close();}});
test('Every final-batch visual has semantic evidence without pre-answer rationales',()=>{const d=dom();try{for(const q of batch.filter(q=>q.chart)){d.window.document.body.innerHTML=d.window.__MBBBatch7UI.render(q.chart);assert.ok(d.window.document.querySelector('caption'));assert.ok(d.window.document.querySelector('th[scope="col"]'));assert.ok(d.window.document.querySelector('th[scope="row"]'));assert.equal(d.window.document.querySelectorAll('.mbb7-rationales').length,0);assert.doesNotMatch(d.window.document.body.innerHTML,/NaN|undefined/);}}finally{d.window.close();}});
test('Q170 geometry includes the actual interval and a distinct unobserved proposal marker',()=>{const d=dom();try{d.window.document.body.innerHTML=d.window.__MBBBatch7UI.render(Q(170).chart);assert.equal(d.window.document.querySelectorAll('[data-mbb7-point]').length,9);assert.equal(d.window.document.querySelector('[data-mbb7-point="8"]').tagName,'path');const line=d.window.document.querySelector('[data-mbb7-mean-ci] line');const p=Q(170).chart.proposal;near(+line.getAttribute('x1'),82+(105-10)/100*(668-82));near(+line.getAttribute('y1'),330-(p.meanCI[0]-20)/80*(330-68));near(+line.getAttribute('y2'),330-(p.meanCI[1]-20)/80*(330-68));}finally{d.window.close();}});
test('Four interactions support native controls, keyboard focus, Enter and Space',()=>{const d=dom(),u=d.window.__MBBBatch7UI;try{for(const[n,count]of [[158,24],[170,9],[174,4]]){d.window.document.body.innerHTML=u.render(Q(n).chart);const select=d.window.document.querySelector('select');assert.equal(select.options.length,count);select.value='1';select.dispatchEvent(new d.window.Event('change',{bubbles:true}));assert.equal(d.window.document.querySelector('output').textContent,select.options[1].textContent);for(const key of ['Enter',' ']){d.window.document.querySelector('[data-mbb7-point="0"]').dispatchEvent(new d.window.KeyboardEvent('keydown',{key,bubbles:true}));assert.equal(select.value,'0');}}d.window.document.body.innerHTML=u.render(Q(155).chart);const input=d.window.document.querySelector('input');input.value='12';input.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.match(d.window.document.querySelector('output').textContent,/12 Belt-months/);d.window.document.querySelector('button').click();assert.equal(input.value,'10');assert.doesNotMatch(d.window.document.querySelector('.mbb7-capacity').textContent,/B plus D|B\+D/);}finally{d.window.close();}});
test('Q172 endpoint-only plot does not fabricate an intermediate lifetime model',()=>{const d=dom();try{d.window.document.body.innerHTML=d.window.__MBBBatch7UI.render(Q(172).chart);assert.match(d.window.document.body.textContent,/no lifetime curve/);assert.equal(d.window.document.querySelectorAll('svg circle').length,3);}finally{d.window.close();}});
test('Static fallbacks contain nine complete figures and no dead interactive controls',()=>{const d=new JSDOM(read('test-bank-assets/mbb-160/batch-07/static-fallbacks.html'));try{assert.equal(d.window.document.querySelectorAll('.fallback-card').length,9);assert.equal(d.window.document.querySelectorAll('.mbb7-conditions').length,9);assert.equal(d.window.document.querySelectorAll('input,button,select,[data-mbb7-point]').length,0);assert.equal(d.window.document.querySelectorAll('.mbb7-rationales').length,0);assert.match(d.window.document.head.textContent,/prefers-color-scheme/);}finally{d.window.close();}});
test('Generated semantic checks do not masquerade as completed browser or source verification',()=>{const v=JSON.parse(read('test-bank-assets/mbb-160/batch-07/validation.json'));for(const row of Object.values(v.questions)){assert.equal(row.validationStatus,'semantic-checks-passed');assert.deepEqual(row.breakpoints,[]);}for(const q of batch.filter(q=>q.visual))assert.deepEqual(q.visual.breakpointsValidated,[]);});
test('All 150 previous records, all 175 keys including Q150, and 24 other asset files are preserved',()=>{const p=withFinalMetadata(JSON.parse(read('docs/audits/mbb-set2-batch07/preservation.json')));assert.equal(all.length,175);assert.equal(Object.keys(p.questions_sha256).length,150);assert.equal(Object.keys(p.asset_sha256).length,24);for(const q of all.slice(0,150))assert.equal(hash(JSON.stringify(stable(q))),p.questions_sha256[q.qid],q.qid);for(const[f,h]of Object.entries(p.asset_sha256))assert.equal(hash(fs.readFileSync(path.join(root,f))),h,f);assert.deepEqual(all.map(q=>q.answer),p.answerPositions);assert.equal(all[149].answer,3);});
test('Updated question and asset fingerprints support explicit historical-test reconciliation',()=>{const u=withFinalMetadata(JSON.parse(read('docs/audits/mbb-set2-batch07/updated-hashes.json')));assert.equal(Object.keys(u.question_sha256).length,25);for(const q of batch){assert.equal(hash(JSON.stringify(q)),u.question_sha256[q.qid]);assert.equal(hash(JSON.stringify(stable(q))),u.stable_question_sha256[q.qid]);}for(const[f,h]of Object.entries(u.asset_sha256))assert.equal(hash(fs.readFileSync(path.join(root,f))),h);});
test('The answer-length shortcut is reduced without padding distractors to a forced ratio',()=>{const n=batch.filter(q=>q.options.every((o,i)=>i===q.answer||o.length<q.options[q.answer].length)).length;assert.ok(n<=8,`${n} longest keyed options`);});

test('Q174 rendered means use the declared 55–85 response domain and distinct disclosure labels',()=>{const d=dom(),q=Q(174);try{d.window.document.body.innerHTML=d.window.__MBBBatch7UI.render(q.chart);const circles=[...d.window.document.querySelectorAll('[data-mbb7-point]')];[62,78,80,66].forEach((v,i)=>near(+circles[i].getAttribute('cy'),330-(v-55)/30*(330-68)));const labels=[...d.window.document.querySelectorAll('summary')].map(x=>x.textContent);assert.deepEqual(labels,['View the plotted cell means','View the coded eight-run design']);}finally{d.window.close();}});

test('Every Batch 7 review uses explicit, aligned exam-trap and distractor feedback',()=>{
 const d=new JSDOM('<!doctype html><head></head><body></body>',{runScripts:'outside-only',url:'https://upskillsprint.com/'});
 try{
  d.window.eval(read('test-bank-deep-feedback.js'));
  for(const q of batch){assert.ok(q.trap.length>60);assert.deepEqual(q.distractors,q.optionRationales);assert.equal(d.window.__TBDeepFeedback.trapText(q),q.trap);}
 }finally{d.window.close();}
});
