'use strict';
// Deterministic release artifact builder; never infers new identity from text.
// --check is read-only. Old content-addressed archives must never be removed.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const V=require('../../test-bank-versioning.js');
const ROOT=path.resolve(__dirname,'../..');
const BANKS=['test-bank-cmq-set1.js','test-bank-mbb-set1.js','test-bank-mbb-set2.js','test-bank-mbb-set3.js','test-bank-cssgb-set1.js','test-bank-cssgb-set2.js'];
async function readExams(){
  const vc=new VirtualConsole();
  let html=fs.readFileSync(path.join(ROOT,'test-bank.html'),'utf8');
  for(const f of BANKS)html=html.replace('<script src="/'+f+'"></script>','<script>'+fs.readFileSync(path.join(ROOT,f),'utf8')+'</script>');
  const dom=new JSDOM(html,{url:'https://catalog-build.invalid',runScripts:'dangerously',virtualConsole:vc});
  try {dom.window.eval(fs.readFileSync(path.join(ROOT,'test-bank-question-registry.js'),'utf8'));const exams=dom.window.__TB.EXAMS;for(const id of Object.keys(exams)){if(exams[id].bank||exams[id].sets)assert.equal(dom.window.__TBQuestionRegistry.validate(id).valid,true,id);}
    return JSON.parse(JSON.stringify(exams));
  } finally {dom.window.close();}
}
async function artifacts(){
  const exams=await readExams(),provenance=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/exam-reliability/catalog/v1/provenance.json'),'utf8'));
  const publications=[];
  const catalog={schemaVersion:'1.0.0',provenanceVersion:V.digest('provenance-v1',provenance),exams:{}},out={};
  for(const id of Object.keys(provenance.exams).sort()){
    const e=exams[id],c=V.createExamCatalog(id,e,{...provenance.exams[id],scoring:provenance.scoring});catalog.exams[id]=c;
    const contents={};Object.values(e.sets||{bank:e.bank}).flat().forEach(q=>{const qid=q.qid||q.questionId||q.id;contents[qid]={revision:c.questions[qid],content:V.content(q)};});
    out['exam-catalog/config-'+c.configVersion+'.json']=V.canonical({schemaVersion:'1.0.0',examId:id,configVersion:c.configVersion,config:c.config,provenance:c.provenance})+'\n';
    out['exam-catalog/'+c.bankVersion+'.json']=V.canonical({schemaVersion:'1.0.0',examId:id,bankVersion:c.bankVersion,sets:c.sets,contents})+'\n';
    publications.push({schemaVersion:'1.0.0',examId:id,configVersion:c.configVersion,blueprintVersion:c.blueprintVersion,bankVersion:c.bankVersion,config:c.config,provenance:c.provenance,
      canonicalConfig:V.canonical({config:c.config,provenance:c.provenance}),canonicalBlueprint:V.canonical(c.config.bok),canonicalManifest:V.canonical({examId:id,questions:c.questions,sets:c.sets}),
      contents:Object.fromEntries(Object.entries(contents).map(([qid,row])=>[qid,{...row,canonicalContent:V.canonical(row.content)}]))});
  }
  out['test-bank-version-catalog.js']='/* Generated by scripts/exam-reliability/build-catalog.cjs. Do not edit. */\nwindow.__TBVersionCatalog='+V.canonical(catalog)+';\n';
  out['docs/exam-reliability/catalog/v1/release-manifest.json']=JSON.stringify({schemaVersion:'1.0.0',sourceIdentityCommit:'64b25d19d9c148bd769d88b2eb13db4450b0843c',provenanceVersion:catalog.provenanceVersion,exams:Object.fromEntries(Object.entries(catalog.exams).map(([id,c])=>[id,{bankVersion:c.bankVersion,configVersion:c.configVersion,blueprintVersion:c.blueprintVersion,questions:Object.keys(c.questions).length,archive:'exam-catalog/'+c.bankVersion+'.json'}]))},null,2)+'\n';
  out['supabase/catalog/segment05-catalog.sql']='-- Generated publication seed. Schema first; human-authorized catalog publication before client deployment.\nBEGIN;\n'+publications.map(p=>"SELECT public.publish_test_bank_catalog('"+V.canonical(p).replace(/'/g,"''")+"'::jsonb);").join('\n')+'\nCOMMIT;\n';
  return {out,catalog,publications};
}
async function main(){const {out}=await artifacts();const check=process.argv.includes('--check');for(const [file,text]of Object.entries(out)){const dest=path.join(ROOT,file);if(check){assert.equal(fs.readFileSync(dest,'utf8'),text,'Stale catalog: '+file);}else{fs.mkdirSync(path.dirname(dest),{recursive:true});if(file.startsWith('exam-catalog/')&&fs.existsSync(dest))assert.equal(fs.readFileSync(dest,'utf8'),text,'Immutable archive conflict');fs.writeFileSync(dest,text);}}console.log(JSON.stringify({check,artifacts:Object.keys(out).length}));}
module.exports={readExams,artifacts};if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});
