'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..');
const profiles=require('../../docs/exam-reliability/verification/v1/profiles.json');
const lanes=['node','mutations','database',...profiles.automation.map(p=>'browser-'+p.id)];
const minima=Object.fromEntries(lanes.map(l=>[l,l==='node'?1858:l==='mutations'?3:l==='database'?32:19]));
function commit(){const sha=execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim();if(!/^[a-f0-9]{40}$/.test(sha))throw Error('Missing exact revision');return sha;}
function output(){const out=path.resolve(ROOT,process.env.SEG03_OUT||'.segment03-results');fs.mkdirSync(out,{recursive:true});return out;}
function write(lane,body){if(!lanes.includes(lane))throw Error('Unknown lane');const r={schemaVersion:1,lane,exactCommit:commit(),node:process.version,environment:'isolated',...body};fs.writeFileSync(path.join(output(),lane+'.json'),JSON.stringify(r,null,2)+'\n');return r;}
function budget(id,samples,segment=3){const b=profiles.budgets.find(x=>x.id===id);if(!b)throw Error('Unknown budget');if(!Number.isInteger(segment)||segment<3||segment>20)throw Error('Invalid segment');if(segment<b.enforcedFromSegment)return {status:'not_due',requiredFrom:b.enforcedFromSegment};if(samples.length<b.minimumSamples||samples.some(x=>!Number.isFinite(x)||x<0))throw Error('Insufficient or invalid performance samples');const s=[...samples].sort((a,b)=>a-b),value=b.statistic==='maximum'?s.at(-1):s[Math.ceil(.95*s.length)-1];return {status:value<=b.limitMs?'passed':'failed',value,limitMs:b.limitMs,samples:s.length};}
function gate(reports,sha){const seen=new Set();for(const r of reports){if(!lanes.includes(r.lane)||seen.has(r.lane))throw Error('Unexpected or duplicate lane');seen.add(r.lane);if(r.exactCommit!==sha||r.status!=='passed'||!Number.isInteger(r.tests)||r.tests<minima[r.lane]||r.failures!==0||r.skipped!==0)throw Error('Missing, stale or failed evidence: '+r.lane);if(r.environment!=='isolated')throw Error('Emulation must not claim physical evidence');const cases=r.lane.startsWith('browser-')?r.checks:r.lane==='database'?r.passed:null;if(cases&&(!Array.isArray(cases)||cases.length!==r.tests||new Set(cases).size!==cases.length))throw Error('Incomplete case evidence');if((r.lane.startsWith('browser-')||r.lane==='database')&&!cases)throw Error('Missing case evidence');if(r.lane==='mutations'&&(!Array.isArray(r.trials)||r.trials.length!==3||r.trials.some(t=>t.detected!==true)))throw Error('Missing mutation evidence');}for(const lane of lanes)if(!seen.has(lane))throw Error('Missing mandatory lane: '+lane);return {status:'passed',lanes:[...seen],exactCommit:sha,scope:'Segment03 framework; not release or physical-device sign-off'};}
function digest(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
module.exports={ROOT,profiles,lanes,minima,commit,output,write,budget,gate,digest};
