# Reviewed original scenarios; additions are visible assumptions, not sourced company facts.
P=[]
def add(number,stem,options,why,rationales,issues,refs,locator):
    assert len(options)==len(rationales)==4
    P.append(dict(number=number,stem=stem,options=options,why=why,optionRationales=rationales,issues=issues,refs=refs,locator=locator))
add(101,
"Two champions request the same Black Belt's full available time for overlapping project work. The MBB may facilitate and recommend allocations, but the portfolio council holds final resource authority. Neither project has an immediate safety or regulatory emergency. What coaching response best resolves the conflict without exceeding the MBB's authority?",
["Give each champion half the Belt's time immediately, then ask the council to confirm that equal allocation at its next meeting.","Choose the project with the larger forecast benefit and instruct the Belt to prioritize it before the council reviews the competing demands.","Ask the Belt to negotiate separate commitments with each champion, leaving any resulting schedule conflicts to the two project teams.","Coach both champions to present capacity, dependencies and shared priority criteria jointly; facilitate a recommendation and route unresolved allocation decisions to the council."],
"The conflict requires both a feasible resource decision and coaching on how champions use governance. The MBB can help frame the competing demands, test assumptions and facilitate agreement, while the council resolves decisions outside the MBB's delegated authority. Neither equal splitting nor larger forecast benefit automatically yields a feasible allocation. Escalation to the MBB is not inherently improper; unilateral allocation without authority is the issue.",
["Incorrect. Equal sharing can leave both tasks infeasible and implements a resource decision before the named authority approves it.","Incorrect. Benefit is relevant evidence, but one estimate does not establish priority or grant the MBB allocation authority.","Incorrect. Separate negotiations place incompatible commitments on the Belt and fail to resolve the cross-project tradeoff through governance.","Correct. It combines facilitated evidence-based resolution, champion development and a decision by the authority specified in this case."],
["Cross-question reference removed; authority and urgency made explicit; escalation to MBB is not universally improper; differentiated from generic matrix allocation."],["bok"],"V.A.1 Scoping and resourcing; V.A.4 Feedback")
add(102,
"An MBB has reviewed three executive presentations in which a champion describes team-delivered improvements solely as personal achievements. Contributions are documented, but the MBB has not established the champion's intent or any effect on retention. What is the most appropriate first coaching action?",
["Publish the contribution records to the executive group before speaking with the champion, so the correction is visible to every original audience member.","Privately recognize the Belt team while retaining the champion's executive narrative, because recognition below executive level resolves the attribution problem.","Discuss specific presentation examples privately, hear the champion's perspective, and agree accurate shared attribution and a proportionate correction of misleading records.","Tell the champion that the pattern has already caused employee turnover and require a standard public apology as the immediate remedy."],
"Feedback should address observed attribution, not invent intent or a proven retention effect. A private, specific conversation allows the champion to respond and supports accurate future recognition and correction of materially misleading records. Follow-up should verify the agreed behavior. Public correction can become necessary, but its form should fit the facts rather than being automatic punishment or a substitute for initial fact-based coaching.",
["Incorrect. Immediate broad publication can escalate unnecessarily before checking context; a proportionate correction can be agreed after the initial conversation.","Incorrect. Private thanks do not correct an inaccurate executive record or the champion's recurring presentation behavior.","Correct. It addresses documented behavior, allows clarification and establishes accurate attribution and follow-up without making unsupported causal claims.","Incorrect. No turnover effect has been established, and a predetermined public remedy bypasses a proportionate fact-based response."],
["Cross-question dependence and unsupported recognition-to-turnover causation removed; added correction of misleading records."],["bok","icf"],"V.A.3 Leadership and communication; V.A.4 Feedback")
add(103,
"A technically strong Black Belt repeatedly dismisses frontline operators' concerns about how Measure-phase data are collected. Operators have now declined further interviews, and the team cannot establish coverage of all shifts. What coaching plan should the MBB prioritize?",
["Assign another person to all operator contact permanently while the Belt continues the analysis, judging the Belt's development only by statistical accuracy.","Use observed examples to coach listening and facilitation; help the Belt repair operator engagement, review data-coverage risks, and verify improvement in later sessions.","Require the operators to complete the planned interviews before addressing the Belt's behavior, so the measurement schedule remains the first priority.","Enroll the Belt in a general leadership course and keep the existing data plan unchanged until the course has been completed."],
"The behavior has created an immediate stakeholder and measurement-coverage problem. Specific feedback, practiced listening, supported repair and follow-up address the demonstrated skill gap while the MBB checks whether the data remain representative. Generic training alone or forced cooperation does not repair the current problem. Reassignment can be necessary if harm persists, but permanent removal of stakeholder duties is not the first developmental response in this case.",
["Incorrect. This may temporarily separate people but avoids developing the missing skill and leaves the representativeness concern unresolved.","Correct. It addresses the specific behavior, its current effect on data collection and observable evidence that the coaching is working.","Incorrect. Schedule pressure does not justify ignoring the behavior or relying on cooperation obtained without repairing the engagement problem.","Incorrect. A general course delays action on the current gap and does not establish that the existing sampling coverage is adequate."],
["Added immediate data-coverage and relationship repair; replaced implausible distractors and unsupported permanent-removal framing."],["bok","icf"],"V.B.1 Belt coaching and mentoring; V.B.3 Team facilitation and meeting management")
add(104,
"A Green Belt reports that the current data do not support the champion's preferred root-cause hypothesis. The MBB has not yet reviewed the study design or uncertainty. There is no reported retaliation, falsification order or immediate safety threat, and the champion has been receptive to evidence in previous reviews. What should the MBB coach the Belt to do next?",
["Bypass the normal review and submit a formal misconduct allegation, treating the difference between the hypothesis and current data as proof of interference.","Replace the current hypothesis with the champion's explanation in the report, while keeping the contradictory analysis in the Belt's private working notes.","Check the analysis and its limitations, then present the evidence honestly with a proposed next test; offer MBB support and escalate if pressure to misrepresent emerges.","State that the preferred root cause has been disproved permanently and recommend closing the project without investigating alternative explanations."],
"Analytical integrity requires an honest, qualified account of what the data support. The MBB should first help check design, uncertainty and interpretation, then support a constructive evidence review and next step. Lack of support is not necessarily proof that the hypothesized effect is absent. Direct conversation is appropriate under the stated circumstances, but it must not become a mandatory prerequisite when retaliation, misconduct or safety concerns require protected escalation.",
["Incorrect. The stated evidence does not establish misconduct; appropriate protected escalation remains available if the circumstances change.","Incorrect. Private retention of contradictory evidence does not make a knowingly misleading report acceptable.","Correct. It protects integrity, addresses uncertainty and gives the Belt both a practical review path and support against inappropriate pressure.","Incorrect. An unsupported hypothesis is not necessarily conclusively disproved, and alternative explanations or better evidence may warrant investigation."],
["Added analysis review, uncertainty and escalation exceptions; avoided treating nonsupport as proof of no effect."],["bok","icf"],"V.B.1 Belt coaching and mentoring; V.B.2 Project reviews")
add(105,
"During a cross-functional review, a Black Belt repeatedly interrupts a quieter member who holds essential operating knowledge. The member is willing to contribute, and the next meeting must identify failure mechanisms before ranking solutions. Which coaching suggestion best protects input without treating equal speaking time as evidence that every claim is equally valid?",
["Let the Belt present a complete solution first, then ask the quieter member to approve it by email without reopening the meeting discussion.","Replace the review with a vote in which each member has one ballot, using the vote totals to establish which failure mechanism is correct.","Have the MBB lead all future meetings personally, removing the Belt's facilitation responsibility so the same interruption pattern cannot recur.","Coach non-interruption and structured turn-taking with a pass option, invite the operating evidence, then evaluate competing claims using common criteria."],
"Structured participation protects access to the discussion; it does not make all proposed causes equally supported. The MBB should coach the interruption behavior and a concrete meeting process, then check whether the Belt elicits and evaluates relevant evidence. Turn-taking can include a pass or written contribution so participation is not coercive. Majority preference and post-hoc approval do not replace examination of failure mechanisms.",
["Incorrect. An approval request after the solution is fixed gives the operating expertise little opportunity to shape the causal analysis.","Incorrect. Equal voting rights do not establish technical truth or resolve the evidence behind a failure mechanism.","Incorrect. Taking over permanently avoids development of the Belt's facilitation capability rather than addressing the specific behavior.","Correct. It combines inclusive participation with evidence-based assessment and a concrete behavior the coach can observe."],
["Cross-question reference removed; structured participation distinguished from consensus proof; pass/written input and follow-up clarified."],["bok","icf"],"V.B.3 Team facilitation and meeting management")
add(106,
"A Green Belt with two validated project successes expresses self-doubt about advancing within the employer's internal Belt-development program. Advancement also requires competencies not necessarily demonstrated by those two projects. The individual asks for coaching rather than a mental-health assessment. What is the most appropriate response?",
["Approve advancement solely from the two successful outcomes and avoid discussing the concern, since outcomes are a complete measure of competence.","Acknowledge the concern, review specific demonstrated competencies against the internal criteria, identify remaining evidence or development needs, and agree a supported next step.","Delay advancement until the individual reports no self-doubt, using confidence rather than the competency criteria as the primary readiness measure.","Diagnose an impostor syndrome from this conversation and make treatment completion a prerequisite for any further professional development."],
"Coaching should respect the person's experience while checking concrete evidence against the actual advancement requirements. Two successful outcomes support some competencies but do not automatically satisfy the full standard. A development plan can recognize strengths and target remaining evidence without letting confidence alone decide readiness. The MBB should remain within the coaching role and should not diagnose a condition from this statement.",
["Incorrect. Project outcomes alone do not establish every advancement competency stated in the scenario.","Correct. It combines supportive listening with criterion-based evidence and an agreed, actionable development path.","Incorrect. Absence of self-doubt is not the internal competency standard and can indefinitely block otherwise justified advancement.","Incorrect. The information does not support a diagnosis or a treatment condition imposed by a workplace coach."],
["Clarified internal credential and evidence limits; removed automatic-certification inference and diagnostic implication."],["bok","icf"],"V.B.1 Belt coaching and mentoring")
add(107,
"A Black Belt asks for help choosing a DOE design. There is time for guided development before authorization, and no urgent safety issue requires the MBB to take over. The MBB supplies a finished design without discussing the reasoning or checking the Belt's understanding. What change would best meet the coaching objective?",
["Provide the finished design with a detailed written explanation and consider the learning objective met once the Belt confirms receipt.","Require the Belt to solve the design alone without access to examples, expert review or discussion so that the work is genuinely independent.","Assign all future DOE design decisions to the MBB while allowing the Belt to manage logistics and present the results to management.","Elicit the objective and constraints, guide the Belt's design choices, review a justified draft, and check transfer on a comparable design decision."],
"The missing element is active development and verification of the Belt's reasoning. Questions, examples and direct instruction can all support coaching when the Belt applies the reasoning and receives feedback. Supplying a worked example is not inherently wrong, nor must an MBB refuse expert work in an emergency. Under the stated conditions, a finished answer without learner application leaves the specific capability gap untested.",
["Incorrect. Receiving an explanation does not demonstrate that the Belt can apply the design reasoning independently.","Incorrect. Withholding support is not required for learning and abandons the requested coaching opportunity.","Incorrect. Permanent dependence on the MBB does not meet the objective of developing the Belt's design competence.","Correct. Guided reasoning, a reviewed draft and a transfer check provide evidence of learning rather than merely completion of this design."],
["Qualified coach-not-doer absolute; distinguished scaffolding/direct instruction from unverified takeover; added transfer check."],["bok","icf"],"V.B.1 Belt coaching and mentoring")
add(108,
"A Black Belt candidate from an underrepresented background tells the MBB that informal networking appears to determine desirable project assignments. The candidate requests discretion. The MBB has not established how assignments are made or whether exclusion occurred. Which response best combines fair investigation, confidentiality and an actionable process improvement?",
["Clarify confidentiality limits and the candidate's wishes; examine assignment criteria and outcomes through appropriate channels, then address evidenced access barriers with transparent criteria.","Announce the candidate's account to the whole team as a confirmed finding, asking everyone to explain why the candidate was excluded.","Promise absolute secrecy in all circumstances and personally assign the candidate the next high-profile project without reviewing the allocation process.","Recommend more networking practice for the candidate and defer review of the assignment process until a second person reports the same concern."],
"The concern warrants respectful examination, not dismissal or a premature finding. The MBB should explain applicable confidentiality limits, avoid unnecessary identifying disclosures and use appropriate organizational channels to assess the process. Transparent, relevant selection criteria and review of access can address supported barriers. A demographic characteristic alone does not prove discrimination, and individual networking advice does not substitute for examining the reported process.",
["Correct. It preserves a fair fact-finding process, respects confidentiality boundaries and links corrective action to supported assignment barriers.","Incorrect. It breaches discretion unnecessarily and labels an unverified account as an established conclusion.","Incorrect. Absolute secrecy may conflict with applicable obligations, and a unilateral exception does not establish fair allocation.","Incorrect. It shifts responsibility to the candidate and imposes an unsupported threshold before examining a credible concern."],
["Added confidentiality boundaries, consent and appropriate channels; allegations distinguished from findings without dismissing concern."],["bok","icf"],"V.B.1 Belt coaching and mentoring; V.B.3 Team facilitation and meeting management")
add(109,
"After a first-project Analyze-phase setback, a Green Belt says, 'I do not think I can do this.' No immediate safety concern is present. The MBB has not yet clarified whether the obstacle is technical, resource-related or a misunderstanding of expectations. What is the best immediate coaching response?",
["Reassign the project immediately and use a later performance review to explain that frustration indicates the Belt is not suited to improvement work.","Begin a detailed statistical lecture without discussing the concern, assuming that more technical information will resolve the obstacle.","Promise that the project will succeed and tell the Belt to repeat the same analysis until the results support the original hypothesis.","Acknowledge the frustration, clarify the obstacle with the Belt, agree a manageable next action and suitable support, and arrange a follow-up check."],
"The coach should first understand the obstacle and the person's concern rather than assume a technical deficiency or a fixed lack of ability. A specific next action and appropriate support make the conversation useful, while follow-up tests whether the barrier is being addressed. Reassurance need not promise success. Reassignment may become appropriate after assessment, but this statement alone does not justify it.",
["Incorrect. The statement does not establish inability, and immediate reassignment bypasses assessment and development.","Incorrect. The barrier has not been diagnosed and may not be resolved by a technical lecture.","Incorrect. Success cannot be guaranteed, and repeating analysis to obtain a desired conclusion compromises analytical integrity.","Correct. It responds to the immediate concern while identifying a feasible evidence-based next step and checking progress."],
["Removed assumed technical cause and universal emotional diagnosis; added barrier clarification and follow-up."],["bok","icf"],"V.B.1 Belt coaching and mentoring")
add(110,
"An experienced Black Belt mentor spends most sessions describing past projects. The new Green Belt leaves without an agreed next action on the current project, although some of the examples are relevant. Which coaching adjustment should the MBB recommend and subsequently evaluate?",
["Standardize a sequence of the mentor's past projects and measure session quality by the number of examples covered each month.","Ask the Green Belt to listen without interruption and submit written questions only after the mentor has finished the planned stories.","Start with the mentee's current goal and questions, use relevant experience selectively, and finish with a mentee-owned action and a later application check.","Replace all mentoring discussion with a repository of case studies and let download counts indicate whether the Green Belt is developing."],
"Mentoring can legitimately include advice and experience, but those resources should serve the learner's current needs. An agreed goal, open questions, selective examples and an owned next action connect the discussion to application. Later review should examine progress and learning rather than story counts or downloads. This corrects the observed pattern without claiming that all storytelling is inappropriate.",
["Incorrect. Counting examples measures delivery activity rather than whether the current challenge is being addressed.","Incorrect. It further delays exploration of the mentee's needs and retains the one-way structure causing the problem.","Correct. It preserves useful mentoring expertise while centering the current goal, action and evidence of application.","Incorrect. A resource repository can supplement mentoring but download counts do not demonstrate competence or problem resolution."],
["Qualified storytelling prohibition; added goal setting, action ownership and measured follow-up."],["bok","icf"],"V.B.1 Belt coaching and mentoring")
add(111,
"A torque-wrench gage R&R study uses representative parts and a valid variance-component model. Measurement-system variance is 22% of total observed variance. The site's adopted guideline rejects greater than 30% study variation, equivalent to greater than 9% variance contribution. Which interpretation and response are justified before using this system for process capability decisions?",
["It is conditionally acceptable at 22% study variation; use it for capability decisions and defer improvement until the variance contribution exceeds 30%.","It is unacceptable under the adopted guideline: study variation is about 46.9%; investigate the error components, improve the system and verify adequacy before relying on capability.","It is acceptable because parts account for 78% of observed variance; a majority part contribution is sufficient evidence of measurement adequacy.","It is unacceptable because measurement variation consumes 22% of the engineering tolerance; replace the wrench immediately without examining repeatability or reproducibility."],
"The reported percentage divides variances, not standard deviations. The study-variation fraction is sqrt(0.22), so %Study Variation is approximately 46.9%, above the site's 30% screening limit. The variance contribution also exceeds 9%. The study does not provide engineering tolerance or identify which measurement component dominates; investigate those components and validate improvements rather than prescribe replacement without evidence. This is the stated guideline, not a universal ban on every possible measurement use.",
["Incorrect. It applies a standard-deviation threshold directly to a variance percentage; 22% contribution is not 22% study variation.","Correct. Taking the square root gives the appropriate scale, and component-based improvement followed by verification matches the stated decision rule.","Incorrect. A majority part contribution is not the adopted criterion; measurement-system variation still exceeds the stated threshold.","Incorrect. No tolerance percentage can be derived from the given variance contribution, and the cause of error has not been localized."],
["Made representative sampling and adopted guideline explicit; independently converted variance to SD; removed universal application claim and predetermined fix."],["bok","grr"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control; VI.B.6 Components of variation")
add(112,
"A gage R&R report lists %Study Variation = 28% and ndc = 2. Both allegedly use the same nonnegative components, with total variance = part variance + gage variance and no historical-SD substitution. Use ndc = floor(1.41 × SDpart / SDgage); the site seeks at least 5 categories. Which MBB review conclusion is correct?",
["The two values are consistent; ndc = 2 adds independent evidence that cannot be checked from the stated study-variation percentage.","The correct ndc is 5 after rounding 1.41 times the part-to-gage SD ratio to the nearest integer, so the stated requirement is met.","The correct ndc is 3 because part SD is 72% of total SD and the ratio is 1.41 × 72 / 28.","The values are inconsistent: the formula gives ndc = 4, still below 5; reconcile the report and investigate discrimination and sampling adequacy before approval."],
"Let total SD be 1. Gage SD is 0.28, and part SD is sqrt(1 - 0.28 squared) = 0.96. Thus 1.41 × 0.96 / 0.28 = 4.8343, which truncates to ndc = 4, not 2 or 5. Standard deviations do not add linearly. Under this common component model, ndc and %Study Variation are related rather than independent evidence. Verify report settings and part representativeness; the corrected value still misses the site's five-category screen.",
["Incorrect. With the specified common components the relationship is checkable and the reported pair is mathematically inconsistent.","Incorrect. The stated formula truncates rather than rounds; 4.8343 gives four categories, not five.","Incorrect. Variances add under the stated model; subtracting standard-deviation percentages gives the wrong part SD.","Correct. The calculation gives four categories, identifies the report inconsistency and does not mistake correction of the report for measurement adequacy."],
["Confirmed numerical contradiction: 28% study variation implies ndc4, not2; converted flawed output into an explicit reconciliation task; corrected claim of independent information."],["bok","ndc","grr"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control; VI.B.6 Components of variation")
add(113,
"Two inspectors independently classify the same 100 items once as pass or fail. The paired counts are shown below; no reference classifications are available. The site's screening criterion is Cohen's kappa at least 0.75. Using observed agreement and agreement expected from the marginal proportions, which conclusion should the MBB report?",
["Kappa is 0.70, so only a five-percentage-point increase in overall agreement is needed to satisfy the site's 0.75 kappa criterion.","Kappa is 0.40, which establishes that 40% of the items were classified correctly and that the remaining 60% require reinspection.","Kappa is 0.40 and observed agreement is 70%; the screen is not met. Review disagreements and validate against reference classifications before claiming inspection accuracy.","Kappa is 0.40, but Inspector 2's 60% fail rate proves that this inspector is correct more often and should become the reference assessor."],
"Observed agreement is (30 + 40) / 100 = 0.70. Inspector 1's pass/fail proportions are 0.50/0.50 and Inspector 2's are 0.40/0.60, giving expected agreement 0.50. Kappa is (0.70 - 0.50) / (1 - 0.50) = 0.40, below the stated screen. Agreement is not accuracy: without reference truth the error rate and better inspector cannot be identified. Review ambiguous criteria, collect appropriate reference and repeatability evidence, and consider uncertainty and category prevalence before validation.",
["Incorrect. It confuses raw agreement with chance-adjusted kappa; a five-point change in one does not automatically yield the stated kappa.","Incorrect. Kappa is not a percentage of correct classifications, and no reference truth is supplied.","Correct. Both numerical results follow from the table, and the action distinguishes insufficient agreement from unmeasured classification accuracy.","Incorrect. A higher fail rate does not establish correct decisions or qualify an inspector as the reference standard."],
["Corrected ragged two-column/three-cell table; replaced universal moderate/inadequate labels with explicit site criterion; added agreement versus accuracy and uncertainty limits."],["bok","kappa"],"VI.A.2 Attribute (discrete) measurement systems")
add(114,
"A stable, approximately normal diameter process has adequate measurement capability. Specifications are LSL = 38 mm and USL = 62 mm; estimated mean = 51 mm and within-subgroup SD = 4 mm. The customer's stated Cpk target is 1.33. Calculate the point estimate to two decimals and select the appropriate conclusion; no confidence interval is requested.",
["Cpk = 1.00; because Cp also equals 1.00, the process is centered and no adjustment of its location is indicated.","Cpk = 1.08; use the larger one-sided index because the lower specification is farther from the process mean.","Cpk = 0.92; the upper specification is nearer and the point estimate misses 1.33. Capability below target does not mean the process is unstable.","Cpk = 1.33; the mean is inside specifications and this is sufficient to establish that the customer's capability target is met."],
"Cpu = (62 - 51) / (3 × 4) = 0.9167 and Cpl = (51 - 38) / (3 × 4) = 1.0833. Cpk takes the smaller index, so the point estimate is 0.92. Cp = (62 - 38) / (6 × 4) = 1.00; the mean lies above the specification midpoint of 50 mm. Even recentering alone leaves Cp below 1.33. Stability is a separate question and is given here; sample information would be needed for an uncertainty interval, not for this point calculation.",
["Incorrect. The value 1.00 is Cp, which ignores centering; the estimated mean is 1 mm above the specification midpoint.","Incorrect. Cpk uses the smaller, limiting one-sided index rather than the larger one.","Correct. The minimum is 11/12, which rounds to 0.92; it misses the stated requirement despite the stipulated stability.","Incorrect. Having a mean between the specifications does not establish the required tail clearance relative to process variation."],
["Added units, within-SD, normality, stability and explicit customer target; corrected marginal-capable label and control-versus-capability conflation; strengthened distractors."],["bok","capability"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(115,
"A Phase II fill-weight chart uses fixed limits from a previously validated stable baseline: subgroup size n = 5, baseline grand mean 50 g, baseline average range 2.9 g, A2 = 0.577, D3 = 0 and D4 = 2.115. Eight new subgroups are plotted. With the one-point-beyond-3-sigma rule enabled, which interpretation and response are appropriate?",
["Widen both charts using the eight new subgroups immediately; this makes the range signal part of the current estimate of normal process variation.","Release the process as stable because the subgroup means remain inside their limits; range-chart signals matter only when the mean chart also signals.","Investigate subgroup 6's range signal and assess affected output. Do not claim overall stability or automatically recalculate the valid historical limits from this new signal.","Delete subgroup 6 from both plots without checking its records, then use the remaining seven subgroups to replace the historical baseline."],
"The mean limits are 50 ± 0.577 × 2.9 = 48.3267 and 51.6733 g. The range UCL is 2.115 × 2.9 = 6.1335 g, with LCL 0. New subgroup 6 has range 7.8 g and signals; the eight means are within the fixed mean limits. A new Phase II signal does not retroactively invalidate a sound historical baseline. Investigate the cause and output risk, document any exclusion or process change, and rebaseline only when justified. Stability of dispersion must not be ignored.",
["Incorrect. Re-estimating limits immediately can absorb the special-cause signal and hide a change rather than explain it.","Incorrect. A dispersion signal is evidence against overall stability even when subgroup averages have not crossed their limits.","Correct. It recognizes the specific range signal, preserves the meaning of fixed historical limits and calls for investigation and risk assessment.","Incorrect. An unexplained point cannot be deleted simply because it signals, and seven remaining subgroups do not justify this automatic rebaseline."],
["Corrected inconsistent chart constants/limits; made PhaseII baseline explicit; removed automatic recalculation and retroactive-baseline-invalidity claims."],["bok","xbar","spc"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(116,
"A claims-cycle-time boxplot uses Tukey's 1.5 × IQR rule. Its quartiles are 3.4 and 5.1 days, median 4.2 days, and largest observation inside the upper fence 6.8 days. Three observations are 9.2, 10.1 and 11.4 days. Before excluding any records, what should the MBB conclude and investigate?",
["The three observations exceed the 7.65-day upper fence. Check records, timing and claim mix; a boxplot flag alone proves neither bad data nor an SPC special cause.","The upper fence is 6.8 days, so all values above the whisker are confirmed recording errors that should be removed before further analysis.","The three observations demonstrate that the process was out of statistical control at those times, even without time-order or baseline evidence.","The median of 4.2 days makes the high observations irrelevant to service performance, so only the central half of claims should be retained."],
"IQR = 5.1 - 3.4 = 1.7 days, so the upper fence is 5.1 + 1.5 × 1.7 = 7.65 days. The upper whisker ends at the largest observation inside that fence, 6.8 days; it is not the dataset maximum, which is 11.4. All three flagged values warrant context and record checks. They may be legitimate observations from a skewed distribution or a different case mix. Do not infer a time-based special cause or remove data solely from a boxplot flag.",
["Correct. It calculates the fence correctly and preserves the distinction between a descriptive outlier flag and evidence of an error or special cause.","Incorrect. The whisker endpoint is an observed value inside the fence, not the fence itself or proof that other records are erroneous.","Incorrect. A distributional display without appropriate time-order and baseline evidence does not establish statistical-control violations.","Incorrect. Long-cycle claims can be central to service risk even when a robust median changes little; discarding them changes the population being assessed."],
["Specified whisker rule, units and fence; corrected max-versus-whisker semantics and outlier-to-special-cause inference."],["bok","boxplot"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(117,
"A normal probability plot displays all 24 purity-assay results in mass percent. Twenty-two values range from 12.1% to 13.4%, while two are 8.9% and 9.1%. The central observations are near a straight reference trend; the low tail departs markedly. Which conclusion best guides the MBB's next analysis?",
["The plot proves a second raw-material population; fit two distributions immediately and omit the low observations from the main capability report.","Because 22 of 24 values appear roughly linear, the complete sample has demonstrated normality and the low values need no investigation.","Check the two low results and their lot/time context, retaining valid observations; the pattern questions a single normal model but does not establish a specific cause.","Discard all 24 observations and restart sampling because any departure from the reference line makes the entire measurement study unusable."],
"The two low measurements are present in the actual plotted dataset, not inferred from an unlabeled sketch. Their separation makes them a useful focus for record, measurement and process-context checks. The display raises doubt about a single normal model for the whole sample, but it does not identify a lot effect or prove a mixture. A straight central portion is not proof that the full population is normal. Keep valid records and choose subsequent modeling or stratification based on evidence rather than deletion to improve a fit.",
["Incorrect. The plot does not identify provenance or prove a mixture, and automatic deletion would bias the assessed population.","Incorrect. Apparent linearity of a selected central subset does not validate normality for all 24 observations.","Correct. It links the visible tail deviation to appropriate investigation without overclaiming its cause or discarding valid evidence.","Incorrect. A model-assumption concern does not make every recorded observation invalid or require wholesale replacement of the study."],
["Corrected typo and full-sample normality overclaim; retained24 actual values; real inverse-normal positions, labelled units and numeric alternative specified."],["bok","normal"],"VI.A.5 Process capability for non-normal data")
add(118,
"Four illustrative target panels A–D show repeated measurement errors relative to a reference at the center. Their coordinate scale is identical. A proposed correction can shift a panel's mean error but cannot change its repeatability spread. Which panel best represents high precision with substantial systematic offset, making a validated offset correction the first candidate rather than averaging alone?",
["Panel A: the clustered results near the reference indicate that a substantial offset correction is needed before any further use.","Panel B: the widely dispersed results centered near the reference indicate a large constant offset but little repeatability error.","Panel C: the results cluster tightly away from the reference; assess an offset correction and verify residual bias and repeatability afterward.","Panel D: the widely dispersed, displaced results indicate that shifting their average alone will also make the individual readings precise."],
"Panel C combines small repeatability spread with a displaced mean relative to the reference. A suitable validated correction may address that systematic component, but averaging alone does not remove a constant bias. Panel A is already clustered near the reference; B has large spread with a near-centered average; D combines large spread with offset. Accuracy is broader than mean centering: an on-target average does not make imprecise individual measurements accurate. This schematic does not quantify uncertainty for a real instrument.",
["Incorrect. Panel A's mean is near the reference; the diagram does not support a substantial offset correction there.","Incorrect. Panel B's main displayed problem is spread, not a large mean offset.","Correct. Panel C shows the specified combination; a correction must still be validated rather than assumed to eliminate all error.","Incorrect. Moving the mean of panel D does not reduce its large repeatability spread."],
["Upgraded recall to corrective-action judgment; made panel labels deterministic and scale identical; distinguished accuracy/trueness/precision without labelling answers in diagram."],["bok","bias"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(119,
"An illustrative gage study uses traceable references of 10, 50 and 90 mm. Mean readings from repeated measurements are 12, 52 and 92 mm. Repeatability and reference uncertainty still require validation; no regression significance test is provided. Which interpretation and next step are justified by these observed means?",
["The observed biases are +2 mm at all three levels. Evaluate a constant-offset correction and validate it across the intended range; the means alone do not prove zero linearity error.","The observed bias increases from 12 to 92 mm across the range, so a constant-offset correction is ruled out by the data.","The means rise with the references, which proves the gage is unbiased and eliminates the need for reference-uncertainty or repeatability checks.","Subtract 2% from every reading and declare the system calibrated, because a constant absolute offset is equivalent to a constant relative error."],
"Bias is measured mean minus reference: 12 - 10, 52 - 50 and 92 - 90 each equal +2 mm. These observed means suggest an additive offset, not an increasing absolute bias. They do not establish the statistical absence of a slope, adequate repeatability, or performance between and beyond the tested levels. Investigate calibration and uncertainty, apply only a justified correction, and verify residual errors. A 2% multiplicative correction is not a 2 mm additive correction.",
["Correct. It correctly computes the three biases and treats constant-offset calibration as a candidate requiring validation, not a proven complete fix.","Incorrect. It substitutes the raw measurement means for bias; the reference values must first be subtracted.","Incorrect. Tracking increasing references does not demonstrate absence of bias; the displayed means all exceed their references.","Incorrect. The offset is in millimetres, not percent, and calibration adequacy cannot be declared from these three means alone."],
["Replaced generic diagram with explicit measured/reference means; qualified fixed-offset remedy and no-linearity inference; units and uncertainty limits added."],["bok","bias"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(120,
"A capability report uses a conventional within-subgroup Cpk of 1.5 to predict a normal-tail nonconformance rate. Stability and measurement adequacy are supported, but the same data's normal probability plot has a strong systematic S-shape. Which action should the MBB require before accepting the predicted rate?",
["Reject the process as incapable immediately; any non-normal pattern means the process must fail its specifications regardless of its observed tails.","Add 1.5 to the reported Cpk to offset the non-normality and retain the report's predicted normal-tail rate.","Withhold the normal-tail prediction; investigate distributional fit and use a justified transformation with transformed limits, a suitable distributional model or a defensible alternative.","Accept the prediction because the Cpk arithmetic can be computed for these data, which makes normal-tail probabilities valid for any distribution shape."],
"The Cpk formula can be evaluated algebraically without a normal distribution, but its usual normal-tail interpretation needs an appropriate model. A systematic probability-plot departure challenges the report's tail prediction; it does not by itself prove poor capability or identify a specific distribution. Check fit in the relevant tails and model uncertainty. Any transformation must also be applied consistently to the specification limits. Empirical tail estimates or nonnormal methods require adequate data rather than an automatic distribution choice.",
["Incorrect. Nonnormality challenges a model assumption, not necessarily the process's ability to meet specifications.","Incorrect. Adding a constant to Cpk has no basis for correcting distributional shape or tail risk.","Correct. It separates computable index arithmetic from unsupported tail inference and requires a method appropriate to the data and limits.","Incorrect. Existence of an arithmetic ratio does not validate a normal-distribution probability calculation."],
["Corrected claim that Cpk arithmetic itself requires normality; distinguished tail interpretation, transformation of specs and stability."],["bok","capability","normal"],"VI.A.5 Process capability for non-normal data")
add(121,
"A fill-weight chart uses fixed baseline limits and a preselected Western Electric rule: eight consecutive points strictly on one side of the centerline trigger investigation. After 40 baseline points with no configured signals, points 41–48 are all above the centerline but inside the 3-sigma limits. The display shows only points 37–48. What is the appropriate interpretation?",
["The configured eight-point rule signals at point 48; investigate a possible upward shift while retaining the baseline limits unless a justified change supports rebaselining.","No signal is present because a valid run must contain at least one point beyond a 3-sigma limit before it can be investigated.","The chart must wait for a ninth point above the centerline because every run-rule system uses nine, regardless of the preselected rule.","The eight points prove a permanent new mean, so replace the centerline and limits immediately using only these latest eight observations."],
"The displayed points 41–48 are eight consecutive values strictly above 500 g, so the stated rule signals at point 48 without requiring a limit exceedance. This is evidence warranting investigation, not proof of a specific cause or a permanent shift. Western Electric's eight-point rule is distinct from rule sets that use nine. The figure is explicitly the final 12-point excerpt; it does not misrepresent 12 points as all 48 observations. Avoid automatic recalculation that absorbs the signal.",
["Correct. It applies the configured rule and proposes investigation without automatically redefining the baseline.","Incorrect. The run rule is an additional signal rule and does not require a 3-sigma exceedance.","Incorrect. It substitutes a different run length for the one explicitly selected in the question.","Incorrect. A signal alone does not establish a permanent regime or justify estimating a new baseline from only these eight points."],
["Reconciled12 plotted points with40+8 narrative; labelled37–48; explicit WE8 rule and no automatic limit reset."],["bok","spc"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(122,
"An engineer proposes replacing an X-bar chart's 3-sigma limits with the individual-unit engineering specifications to 'catch defects sooner.' The chart plots subgroup means, and separate checks are available for unit conformance. Which response best addresses both the statistical and operational flaw?",
["Use specifications as control limits whenever the sample size exceeds five, because larger subgroups make average and individual-unit variation equivalent.","Replace the limits only when specifications are tighter, since tighter decision boundaries necessarily preserve the chart's designed false-alarm behavior.","Retain limits appropriate to subgroup means for stability monitoring and use specifications for unit conformance; equal numerical values must not be imposed, although they can coincide.","Widen the product specifications until they match the current chart limits, allowing a single boundary set to govern both monitoring and customer acceptance."],
"Control limits describe the expected behavior of a plotted statistic under the monitoring model. Engineering specifications describe required product performance. Subgroup means and individual units have different spreads, so substituting individual specifications can miss nonconforming units or change detection and false-alarm properties. Keep stability monitoring and conformance assessment distinct. The boundaries can coincide numerically by chance, but forcing equality or changing requirements to fit the process has no statistical justification.",
["Incorrect. Increasing subgroup size does not make the distribution of means equal to the distribution of individual measurements.","Incorrect. Changing the boundaries changes their signal probabilities; tighter specifications do not automatically preserve the designed false-alarm rate.","Correct. It distinguishes both purpose and statistical scale without asserting that independently derived limits can never coincide.","Incorrect. Customer or engineering requirements cannot be widened merely to make the process or chart appear acceptable."],
["Added subgroup-mean versus individual-unit distinction; corrected absolute cannot-equal assertion and conflation of alarms with defect detection."],["bok","spc"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
add(123,
"Two single-sampling plans use the binomial model for large homogeneous lots with independent item outcomes. Plan A samples n = 200 and accepts at most 10 defectives; Plan B uses n = 50 and accepts at most 2. The OC curves and selected exact probabilities are provided. At 1% defective the lot is designated good; at 10% it is designated poor. Which comparison is justified?",
["The steepness of A proves that it has a higher acceptance probability at every defect level and requires fewer inspected items than B.","At the two designated quality levels, A has lower producer and consumer risks than B; its sharper transition costs a larger sample, and slope alone would not establish both risks.","A's larger sample proves its consumer risk is higher at 10% defective, regardless of the acceptance numbers or the displayed probabilities.","B's smaller sample guarantees equal discrimination at both designated quality levels because both plans use the same binomial distribution family."],
"For each plan, Pa(p) is the sum of binomial probabilities for 0 through c defectives. At 1% defective, Pa is approximately 0.999993 for A and 0.986183 for B, so producer risk 1 - Pa is smaller for A. At 10%, Pa is about 0.008071 for A and 0.111729 for B, so consumer risk is also smaller for A there. These comparisons use actual quality levels and curve locations, not steepness alone. A inspects 200 items rather than 50; neither risk statement is a claim of dominance at every possible quality level.",
["Incorrect. A uses the larger sample, and a steep decline does not imply higher acceptance everywhere; at poor quality lower acceptance is desirable.","Correct. The probabilities at the named good and poor quality levels establish the two risk comparisons, with a clear sample-size tradeoff.","Incorrect. Consumer risk is the acceptance probability at the designated poor quality and is lower for A in the supplied comparison.","Incorrect. Sharing a distributional model does not make different n and c values yield equal OC curves or risks."],
["Replaced unsupported slope-to-both-risks inference and placeholder curves with explicit binomial plans, quality points and reproducible probabilities."],["bok","oc"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control (related acceptance-sampling application; not a separately named BoK subtopic)")
add(124,
"A grouped multi-vari display shows four diameter observations from each of three machines, measured in millimetres with the same adequate gage. Within each machine the span is 0.02 mm; the machine groups are separated. Lot, operator and collection-time effects have not been controlled. What conclusion and follow-up are most defensible?",
["Machine-group differences dominate the displayed spread; investigate setup and measurement conditions with a balanced or blocked follow-up before attributing causation to machine identity.","The display proves the machine mechanisms caused the offsets, so adjust all three machines to the pooled mean without checking product or setup differences.","The 0.02 mm within-machine spans dominate the overall variation, so ignore the differences between machine means and study only individual handling.","The display identifies time drift as the dominant source because connecting observations within each group establishes their chronological sequence across machines."],
"The group means are 10.02, 10.15 and 9.88 mm, a 0.27 mm spread, while each within-group range is 0.02 mm. Thus between-group separation is the main displayed feature. These descriptive differences do not identify machine identity as the causal mechanism: lot, time, operator or setup may be confounded. Review the production context and collect an appropriate balanced or blocked comparison, with replication and measurement checks, before adjusting equipment or generalizing to the full process.",
["Correct. It quantifies the visible source of separation while requiring a design that can distinguish machine effects from confounding.","Incorrect. Descriptive grouping does not prove cause, and automatic centering may be inappropriate if groups differ in product or intended setup.","Incorrect. The 0.27 mm spread of group means is much larger than each 0.02 mm within-group span in these displayed data.","Incorrect. The group order does not establish a time trend; collection-time confounding remains unassessed."],
["Added mm units and uncontrolled-factor caveat; removed machine-root-cause assertion; independently checked means/ranges and follow-up design."],["bok","components"],"VI.B.5 General linear models; VI.B.6 Components of variation")
add(125,
"A Black Belt claims sustained 'Six Sigma capability' from Cp = 2.0 calculated with within-subgroup variation on one shift. The report omits the process mean, stability over representative operation and overall performance across shifts. What should the MBB require before accepting the sustained-performance claim?",
["Accept the claim because Cp = 2.0 establishes both adequate centering and the long-term defect rate, regardless of how the observations were collected.","Subtract exactly 0.5 from Cp and call the result Ppk, using an assumed 1.5-sigma shift in place of collecting overall performance data.","Require only a longer run of the same shift at the same settings; overall variation then necessarily equals within-subgroup variation without a centering check.","Check centering with Cpk, measurement adequacy, stability and representative overall performance with Ppk or suitable tail analysis; do not assume a universal shift or ordering of estimates."],
"Cp measures specification width relative to within-subgroup spread and ignores the mean. Even a high Cp cannot establish actual tail clearance without centering information. Cpk adds centering, while Ppk uses overall rather than within-subgroup variation; the data must cover the operating conditions relevant to a sustained claim. These are estimator definitions, not guarantees of short or long observation duration. A fixed 1.5-sigma shift and a universal Ppk ordering cannot substitute for evidence, and neither index alone validates a defect rate when model assumptions fail.",
["Incorrect. Cp ignores the mean and does not by itself establish sustained performance or a defect probability.","Incorrect. A conventional shift assumption is not a measurement of overall variation and does not define Ppk for these data.","Incorrect. More data from one narrow operating condition may remain unrepresentative, and centering is still unassessed.","Correct. It identifies missing centering and representative performance evidence while avoiding unsupported conversion or ordering rules."],
["Added Cp-centering omission; corrected universal1.5shift implication and short/long-term estimator conflation; no assumed Ppk<Cp."],["bok","capability","ppk"],"VI.A Measurement Systems Analysis (MSA), Process Capability, and Control")
assert [p['number'] for p in P]==list(range(101,126))
