# Reviewed Batch 7 content. Executed only in guarded staging against PR170.
import json, copy, re, hashlib, subprocess
from pathlib import Path
root=Path.cwd()
source=(root/'test-bank-mbb-set3.js').read_text()
bank=json.loads(subprocess.check_output(['node','-e',"const c={window:{}};require('vm').runInNewContext(require('fs').readFileSync('test-bank-mbb-set3.js','utf8'),c);console.log(JSON.stringify(c.window.MBB_SET3))"],text=True))
original=copy.deepcopy(bank)
assert len(bank)==175
revisions=[]
ASQ={'title':'ASQ Certified Master Black Belt Body of Knowledge','url':'https://www.asq.org/cert/resource/pdf/certification/cmbb-cert-insert.pdf','locator':'VI.C–E; topic alignment, not authorship or endorsement'}
refs={
 'doe':{'title':'NIST: Two-level full factorial designs','url':'https://www.itl.nist.gov/div898/handbook/pri/section3/pri3331.htm','locator':'5.3.3.3.1'},
 'data':{'title':'UK Government Data Quality Framework: guidance','url':'https://www.gov.uk/government/publications/the-government-data-quality-framework/the-government-data-quality-framework-guidance','locator':'Data quality dimensions: completeness, uniqueness, consistency and timeliness'},
 'sql':{'title':'PostgreSQL: Table Expressions','url':'https://www.postgresql.org/docs/current/queries-table-expressions.html','locator':'7.2.1.1 Joined Tables; inner/outer join multiplicity'},
 'encoding':{'title':'scikit-learn: Target Encoder internal cross fitting','url':'https://scikit-learn.org/stable/auto_examples/preprocessing/plot_target_encoder_cross_val.html','locator':'Cross fitting and high-cardinality overfitting example'},
 'qfd':{'title':'ASQ: Quality Function Deployment','url':'https://asq.org/quality-resources/qfd-quality-function-deployment','locator':'House of Quality and customer-driven product/service requirements'},
 'hoq':{'title':'ASQ: House of Quality','url':'https://asq.org/quality-resources/house-of-quality','locator':'House of Quality framework and technical benchmarking'},
 'verify':{'title':'NASA Systems Engineering Handbook: Product Realization','url':'https://www.nasa.gov/reference/5-0-product-realization/','locator':'5.3 Product Verification and 5.4 Product Validation; tailored methods and configuration evidence'},
 'matrix':{'title':'NASA Systems Engineering Handbook: Requirements Verification Matrix','url':'https://www.nasa.gov/reference/appendix-d-requirements-verification-matrix/','locator':'Appendix D: unique requirements, source and verification approach'},
 'robust':{'title':'NIST: What are Taguchi designs?','url':'https://www.itl.nist.gov/div898/handbook/pri/section5/pri56.htm','locator':'5.5.6 Parameter Design; selection of tolerances by sensitivity and cost'},
 'capability':{'title':'NIST: What is Process Capability?','url':'https://www.itl.nist.gov/div898/handbook/pmc/section1/pmc16.htm','locator':'6.1.6; stable process and distribution/variation basis'},
 'reliability':{'title':'NIST: Accelerated life tests','url':'https://www.itl.nist.gov/div898/handbook/apr/section3/apr314.htm','locator':'8.3.1.4; acceleration models, stress cells and projection to use conditions'},
 'fta':{'title':'NRC: Fault Tree Handbook, NUREG-0492','url':'https://www.nrc.gov/reading-rm/doc-collections/nuregs/staff/sr0492/index','locator':'Publication identity and fault-tree methodology; probability calculation independently derived, no unverified page locator'}
}
def item(n,stem,options,solution,rat,trap,findings,refnames=(),bok=None):
 q=bank[n-1];assert q['qid']=='mbb:set-3:d6-'+str(n-110).zfill(3)
 assert len(options)==len(rat)==4
 q.update(stem=stem,options=options,why=solution,optionRationales=rat,distractors=rat.copy(),trap=trap)
 assert rat[q['answer']].startswith('Correct.') and sum(x.startswith('Correct.') for x in rat)==1
 a=copy.deepcopy(ASQ);a['locator']=bok or ('VI.C.3' if n<=152 else 'VI.D.1–2' if n<=162 else 'VI.E; related design-quality application')
 q['auditSources']=[a]+[refs[k] for k in refnames]
 q['why']+=' Source alignment: ASQ CMBB '+a['locator']+'. Case conclusions follow from the stated assumptions.'
 revisions.append({'number':n,'qid':q['qid'],'original':original[n-1],'corrected':q,'findings':findings,'independentSolution':solution,'keyIndexChanged':False})
item(151,
 'A completed balanced 2³ etching DOE has the eight observed corner means below, in nm/min. The sponsor wants a spatial display of the same results; replicate variability and uncertainty intervals are not supplied in this excerpt. Which use of a cube plot adds value without claiming information the table does not contain?',
 ['Place each mean at its factor combination to compare conditional patterns; retain the table and obtain uncertainty evidence before drawing inferential conclusions.',
  'Connect the corner means and use unequal edge differences as proof of statistically significant interactions, without needing replicate variability or uncertainty intervals.',
  'Replace observed corner values with values predicted by an additive model so that the cube reveals the experiment’s original interaction pattern more clearly.',
  'Identify the largest observed corner and certify it as the global optimum, including untested intermediate settings, because the design includes all eight corners.'],
 'A cube reorganizes the same eight means; it adds a spatial view, not independent measurements or an error estimate. For example, raising A changes the mean by 9 nm/min at low B and C, but by 18 nm/min at high B and C. That difference is a descriptive conditional pattern, not a significance result. The largest observed mean is 89 nm/min at the all-high corner; the excerpt does not identify the best untested interior setting or establish robustness.',
 ['Correct. Spatial organization supports comparisons while preserving the actual evidence and its uncertainty limits.','Unequal edge differences show estimated patterns, but significance requires a defensible error model and information on variability.','An additive fit can remove the very interaction pattern being reviewed; replacing observations is not a faithful display of the data.','A maximum among the eight observed means does not establish a global optimum, practical desirability or reliable out-of-sample performance.'],
 'A different display is not a new experiment. Distinguish the best observed corner and descriptive effects from significance, robustness and an untested optimum.',
 ['Authoring-rationale leakage removed.','Qualified claims of immediate interaction recognition and supplied units/uncertainty context.','Replaced implausible distractors with inference and data-provenance errors.'],('doe',))
c=bank[150]['chart'];c.update(title='Observed corner means — balanced 2³ etching DOE',altText='Eight observed mean etch rates in nm/min; no replicate variability is provided.');c['columns'][-1]='Mean etch rate (nm/min)'
item(152,
 'A team can run 30 independent trials to investigate three continuous factors. It proposes an unreplicated full factorial with five levels per factor instead of two, arguing that more levels are automatically preferable. Curvature is plausible, and confirmation is required. Which recommendation correctly addresses the run budget and information needs?',
 ['Use the five-level full factorial, because 3 × 5 = 15 settings leaves another 15 trials for replication and independent confirmation.',
  'Use eight two-level corners and claim they identify all three pure-quadratic coefficients, leaving the remaining trials solely for confirmation.',
  'Use the eight two-level corners and repeat one corner until the budget is exhausted, because more replication supplies the missing intermediate factor levels.',
  'Reject the 125-setting full factorial; plan a budgeted sequential or response-surface design that addresses curvature, error estimation and confirmation.'],
 'The full factorial requires 5³ = 125 settings versus 2³ = 8, before any replication or extra confirmation. The ratio is 15.625 and the difference is 117 settings. A 30-trial budget therefore cannot accommodate the proposed 125-setting design. Extra levels can characterize nonlinear behavior, but the design should be chosen for its model and precision requirements. Two-level corners alone do not separate pure-quadratic terms, and replication at an existing corner adds precision rather than a new factor level. No uniquely optimal 30-run plan follows from the information given.',
 ['Multiplying the number of factors by levels is not the full-factorial count; all combinations are required.','At two levels, each squared coded factor is constant, so separate pure-quadratic coefficients are not identified by the corners.','Replication can estimate variability but does not create the intermediate settings needed to resolve curvature.','Correct. It recognizes the actual run count and calls for an estimable, adequately validated design within the budget.'],
 'Count combinations before allocating replication. Additional levels, replicated observations and confirmation runs supply different kinds of information.',
 ['Qualified a universal two-level default.','Specified budget and curvature needs; independently checked 125 versus 8.'],('doe','robust'))
item(153,
 'Three departments publish an on-time-delivery percentage. One tests delivery against the original customer promise, another against a revised promise, and a third measures dispatch timeliness. Leadership needs a comparable enterprise measure but must retain legitimate local metrics. What should the MBB establish first?',
 ['Rename all three fields “on-time delivery” and average their percentages, leaving the original promise and event definitions unchanged.',
  'Agree a versioned enterprise definition, eligible population, promise rule, event timestamp and ownership; map local variants before combining comparable records.',
  'Adopt the department with the highest percentage as the standard, then treat its historical percentages as equivalent to the other two series.',
  'Require immediate deletion of all local metrics and histories before defining the enterprise reporting purpose or examining available source timestamps.'],
 'A common label is not a common operational definition. The reporting purpose must determine the promised-date convention, unit of analysis, eligible denominator, event, exclusions and handling of revised commitments. Named ownership and versioning support consistent implementation. Local variants may remain useful if clearly labeled and reconciled. Some historical records may not contain the fields needed to restate them; mark that limitation rather than fabricate comparability. The issue prevents the intended enterprise comparison, not every possible local analysis.',
 ['Averaging incompatible percentages does not align their events, populations or promise-date rules.','Correct. It establishes the semantic and accountability foundation while retaining legitimate, labeled local uses.','A favorable result is not a defensible definition-selection criterion, and it cannot retroactively align unlike histories.','Destroying valid local history is unnecessary and can eliminate the very evidence needed for mapping and transition.'],
 'Define the event, denominator and promise-date rule—not merely the metric name. A local metric can be valid while unsuitable for direct enterprise aggregation.',
 ['Removed absolute claim that all reporting must stop.','Added denominator, promise-date, lineage and historical-restatement limitations.'],('data',))
item(154,
 'A defect dashboard unions records from three source systems. Review confirms that 8% of the combined rows are extra representations of defect events already represented elsewhere; repeated defects on the same asset are legitimate separate events. Source-local IDs are not globally unique. Which control best prevents inflated event counts?',
 ['Deduplicate by asset ID and retain only one lifetime defect record per asset, because every repeated asset ID represents the same event.',
  'Apply DISTINCT to the full combined rows and accept the result, even when the same event has different timestamps or descriptions in different systems.',
  'Trust the largest source and discard all events found only in smaller sources, because the most populated system must have complete coverage.',
  'Define event identity and cross-system mappings, reconcile counts and attributes, and quarantine ambiguous matches before publishing corrected event totals.'],
 'The required grain is one defect event, not one asset or one source row. Cross-system identity needs a business event key or a documented matching process; source-local ID collisions and differing representations both require attention. Reconciliation should preserve provenance, distinguish repeat events from replicated representations and resolve uncertain matches. The stated 8% uses combined rows as its denominator; it is not automatically the percentage overstatement relative to the corrected unique count. With only duplicate removal and complete coverage, that relative overstatement would be 0.08/0.92, about 8.70%.',
 ['One asset can have multiple genuine defects, so this rule discards valid events and biases the total downward.','DISTINCT detects identical rows, not all differently represented copies of the same business event.','Source size alone establishes neither completeness nor authority and may discard legitimate source-only events.','Correct. It validates event-level identity and reconciles the integrated result without silently deleting uncertain cases.'],
 'Differentiate entity identity, event identity and row identity. The duplicate share of imported rows and overstatement of the corrected total use different denominators.',
 ['Specified duplicate denominator and business grain.','Removed assumption that source-local unique IDs identify cross-system events.','Added ambiguous-match handling and explicit reconciliation.'],('data','sql'))
item(155,
 'A dashboard labeled “real time” refreshes every 24 hours, but operators use it for within-shift decisions. Neither source-event time nor coverage is shown. Some upstream feeds also arrive late. What recommendation addresses both immediate misuse and a durable decision-support requirement?',
 ['Show actual event coverage and freshness, restrict decisions unsupported by stale data, and agree end-to-end latency and failure alerts with process owners.',
  'Show the current browser-refresh time prominently but leave source coverage hidden, because a fresh screen timestamp establishes current production information.',
  'Refresh at each shift boundary and permit all within-shift decisions, because shift-level use means changes inside a shift cannot affect the decision.',
  'Retain the daily feed with a small staleness note and continue all operational uses, because disclosure alone makes old data fit for any decision.'],
 'A display refresh does not establish that source events are current or complete. The immediate control is to remove misleading real-time claims, show coverage and age, and prevent unsupported decisions or provide an approved current alternative. The durable design specifies the maximum acceptable end-to-end age for each decision, feed-latency monitoring, visible failure states and accountable response. Updating once per shift may still be inadequate for a decision made within the shift. Disclosure informs use; it does not repair unsuitable evidence.',
 ['Correct. It controls current misuse and sets a decision-specific requirement for timely, complete information.','The browser timestamp says when the screen rendered, not the latest event included or completeness of the source feeds.','The timing requirement depends on the particular decision and could be much shorter than a whole shift.','A note cannot make stale information adequate for a decision that requires current conditions; use must also be controlled.'],
 'Trace freshness from source event to decision, not just from dashboard refresh to screen. Transparent staleness is necessary but may not be sufficient.',
 ['Removed cross-bank reference.','Corrected implication that a timestamp alone fixes operational fitness.','Distinguished upstream coverage from display-refresh time.'],('data',))
item(156,
 'A model flags 200 of 10,000 assets, while the team can inspect 50 this week. For these 200 assets, calibrated failure probabilities refer to the same next-week horizon; inspection effort is equal, but consequences and the fraction of loss preventable by follow-up differ. Mandatory safety actions are handled separately. Which ranking best supports the remaining discretionary allocation?',
 ['Rank by failure probability alone, treating a likely low-consequence failure as more important than any less-likely high-consequence failure.',
  'Rank by total asset replacement value alone, treating every failure as a total loss and every inspection as equally effective prevention.',
  'Rank by expected preventable loss over the common horizon, accounting for probability, consequence and feasible follow-up; review uncertainty and constraints.',
  'Inspect all 200 before acting on any finding, spreading the inspections over four weeks without revisiting the next-week risk predictions.'],
 'A binary flag loses ranking information, but a calibrated failure probability is still not consequence severity or intervention benefit. Under the stipulated equal inspection effort and additive, separable benefits, probability × loss conditional on failure × fraction preventable by the feasible action supports an expected-benefit ranking. Mandatory constraints remain outside this discretionary comparison. Uncertain consequences, calibration, dependencies, changing horizons and action capacity require review; the largest raw score is not a universal optimum. Four weekly batches would use different risk horizons and must be reassessed.',
 ['Probability-only ranking ignores the explicitly different consequences and the ability to prevent the losses.','Replacement value is not necessarily the loss if failure occurs, and the question states that intervention effectiveness differs.','Correct. It uses the information needed for the stated allocation objective, while retaining operational and uncertainty checks.','Deferring all follow-up can forfeit preventable benefit, and a one-week prediction cannot be frozen across a four-week queue.'],
 'Risk probability, failure consequence and preventable loss are different. A capacity ranking needs a common horizon, feasible actions and explicit mandatory constraints.',
 ['Corrected conflation of probability score with severity.','Added horizon, calibration, consequence, effort and action-feasibility assumptions.'],('data',),'VI.D.2; VI.B.8–9 as related allocation/reliability concepts')
item(157,
 'An attrition model uses more than 400 ZIP-code categories, most represented by one or two customers. The team proposes replacing each ZIP code with its observed attrition rate before splitting the dataset for validation. How should the MBB evaluate this remedy?',
 ['Approve full-dataset target means because compressing 400 categories into one numeric column eliminates all information leakage and overfitting.',
  'Encode ZIP codes as consecutive integers and interpret their numerical distances as geographic proximity without checking what those labels mean.',
  'Remove every categorical predictor, including well-supported ones, because a sparse ZIP-code field establishes that categorical data cannot generalize.',
  'Reject outcome encoding before the split; validate regularized or grouped alternatives within training folds, handle unseen categories and assess subgroup performance.'],
 'Sparse high-cardinality categories can support unstable memorization. Encoding them using outcomes from validation cases leaks those outcomes into their features. Any learned preprocessing must be fit within the development split and cross-validation procedure; outcome-based encoders need suitable out-of-fold construction for training examples as well. Grouping or regularization are candidates, not guaranteed cures, and unseen regions need defined handling. Geography may also act as a proxy for sensitive attributes, so assess relevant subgroup performance and permitted use rather than assuming universal exclusion or universal acceptability.',
 ['A single column can still leak validation outcomes and memorize nearly unique categories; dimensionality reduction alone is not protection.','Arbitrary numeric codes impose an unsupported ordering and distance structure rather than resolving sparsity.','A defect in one sparse feature does not show that all categorical predictors are unsuitable.','Correct. It prevents validation leakage and evaluates alternatives under the intended deployment conditions rather than assuming a remedy works.'],
 'A supervised encoding is part of model training. Split first, prevent each training row from encoding its own outcome, and keep validation outcomes out of all fitted preprocessing.',
 ['Upgraded recall to a specific leakage diagnosis.','Added unseen-category and subgroup checks without claiming ZIP code is always prohibited.'],('encoding',))
item(158,
 'An enterprise data lake retains every personal and operational record indefinitely. There is no documented purpose-based retention schedule, access review or disposal process. No jurisdiction-specific retention periods have yet been established. Which MBB recommendation addresses the governance gap without inventing a legal deadline?',
 ['Set a universal 12-month deletion rule immediately, including records subject to preservation requirements, because shorter retention is always compliant.',
  'Work with data owners and privacy, security and records specialists to set justified retention, access, preservation and disposal rules by data class.',
  'Keep all records indefinitely but improve search indexes, because faster retrieval removes privacy exposure and establishes an appropriate lifecycle.',
  'Archive all records permanently and treat archive status as anonymization, even though identifiers and broad user access remain unchanged.'],
 'Indefinite uncontrolled retention increases exposure and can undermine purpose, access and lineage controls. It is not automatically unlawful in every setting, and old records are not automatically inaccurate or analytically irrelevant. Relevant obligations, preservation needs and defensible business purposes must determine schedules and access. Archiving changes storage or access arrangements; it does not necessarily anonymize data or resolve retention obligations. No specific legal period can be derived from the scenario, so qualified organizational review is required before implementing deletion rules.',
 ['The question supplies no legal basis for 12 months, and preservation requirements can override routine disposal.','Correct. It assigns the lifecycle decision to relevant accountable roles and requires a justified, documented policy instead of an invented deadline.','Search performance does not control data-purpose, exposure, access or retention requirements.','An archive can still contain identifiable data with unchanged access; it is not inherently anonymized or compliant.'],
 'Retention is not a choice between keeping everything and deleting everything. Specify purpose, ownership and preservation exceptions before applying a lifecycle schedule.',
 ['Removed unsupported legal implication and age-equals-poor-quality claim.','Distinguished archival status, anonymization, retention and access.'],('data',),'VI.D.1: data life-cycle management, privacy, security and metadata')
item(159,
 'Five product lines have different volumes and complexity. Their dashboard uses one common definition of first-pass yield: units passing the specified first inspection without rework divided by units first inspected. Leadership uses only the pooled percentage to compare lines and to judge month-to-month improvement despite changing product mix. What redesign is most defensible?',
 ['Report only the highest line yield, because the best process represents what the pooled operation could achieve without any mix adjustment.',
  'Take the unweighted average of the five percentages and label it the pooled unit yield, regardless of differences in the denominators.',
  'Rank the lines solely by their raw yields and attribute every difference to management performance, ignoring the stated product-complexity differences.',
  'Show each line’s counts and yield with a valid pooled ratio; distinguish within-line changes from mix changes and qualify performance comparisons.'],
 'The pooled unit yield is total first-pass units divided by total first-inspected units, not usually the unweighted average of line percentages. It remains useful for its stated aggregate purpose, but can hide opposing within-line trends or change because product mix changes. Stratified numerators, denominators and uncertainty support diagnosis. Complexity adjustment or common-mix comparisons may be appropriate when supported; stratification alone does not make managerial comparisons causally fair. This metric is not automatically rolled-throughput yield across several process stages.',
 ['The best line is not representative of all units and does not provide the organization’s pooled yield.','Equal weighting estimates an average-line quantity, not pooled unit yield when denominators differ.','Raw line differences do not isolate management effects from complexity, measurement or operating conditions.','Correct. It retains a valid aggregate and adds the detail needed to separate mix from within-line performance.'],
 'Keep the numerator, denominator and aggregation target explicit. Pooled unit yield, average-line yield and within-line improvement are different quantities.',
 ['Removed cross-question references.','Added pooled-denominator and mix effects, while retaining legitimate aggregate reporting.'],('data',))
item(160,
 'A reporting table should retain one row per defect event after an INNER JOIN to a classification lookup. The lookup has two rows for event E1’s key, no row for E2’s key, and one row for E3’s key. The three input events have amounts 100, 200 and 300 respectively. The joined output still has three rows. Which validation best detects the problem?',
 ['Accept the join because unchanged total row count proves both event coverage and one-to-one enrichment were preserved.',
  'Check lookup-key uniqueness, unmatched events, per-event match counts and amount reconciliation; total row count alone can hide offsetting losses and duplication.',
  'Apply DISTINCT only to the three selected numeric amounts and assume that doing so recovers every missing event and its classification.',
  'Replace the INNER JOIN with a LEFT JOIN and omit all other checks, because a LEFT JOIN cannot duplicate left-side events.'],
 'The output contains E1 twice, E3 once and no E2. Its amount total is 100 + 100 + 300 = 500 rather than the original 600, even though both row counts are three. An inner join can drop unmatched events while another key multiplies rows. Validate the intended grain, key uniqueness, match multiplicity, unmatched coverage and business totals. A LEFT JOIN preserves unmatched left rows but still multiplies them when several right-side matches exist. Non-unique joins are not inherently wrong; they are wrong here because they violate the specified one-event grain.',
 ['The extra E1 and missing E2 offset in the total row count, so this check falsely passes the corrupt result.','Correct. These complementary checks identify multiplicity, missing coverage and distorted measures at the intended grain.','DISTINCT on amounts is not event reconciliation and cannot restore E2 or its absent lookup match.','LEFT JOIN prevents loss of unmatched left rows but does not prevent multiple matches for E1.'],
 'Unchanged row count is necessary for some transformations, not sufficient evidence of correctness. Test identity and measures as well as volume.',
 ['Corrected claim that row-count validation alone would catch the defect.','Specified intended grain and a concrete cancellation counterexample.'],('sql','data'))
item(161,
 'An enterprise has trusted dashboards and trained analysts, but reviews end without named decision owners, action thresholds, due dates or later outcome checks. The sponsor asks whether buying a prescriptive analytics package is the necessary next step. What should the MBB recommend?',
 ['Purchase optimization software first and treat a generated recommendation as an authorized operational decision even when no accountable owner is named.',
  'Redesign colors and chart types while preserving the same review process, because visual sophistication alone resolves missing decision accountability.',
  'Define decision rights, escalation criteria, action ownership and outcome follow-up; then assess which additional analytical tools those decisions actually require.',
  'Assign an automatic improvement action to every dashboard fluctuation, regardless of uncertainty, thresholds or the process owner’s decision authority.'],
 'The demonstrated gap is between evidence and governed action, not proof of a missing software class or a formally scored maturity level. A decision process needs accountable roles, appropriate triggers, explicit decisions—including justified no-action decisions—and verification of follow-through. Uncertainty and practical consequences should inform triggers. Once the process is defined, optimization or other tools may help where they meet a real need. A recommendation is not automatically an authorized decision, and every fluctuation need not provoke adjustment.',
 ['Software recommendations cannot supply missing authority, ownership and accountability by themselves.','Visual refinements may help communication but do not create the missing decision and follow-up process.','Correct. It addresses the demonstrated process gap before prescribing a tool or claiming a formal maturity classification.','Automatic action on every fluctuation can induce overreaction and bypasses the needed uncertainty and authority checks.'],
 'Differentiate a dashboard, an analytical recommendation and an authorized decision. A documented decision to monitor rather than intervene can also be appropriate.',
 ['Removed unsupported formal maturity framing.','Added no-action decisions, authority and outcome follow-up rather than tool purchasing.'],('data',),'VI.D.1–2; I.C deployment governance as a related application')
item(162,
 'An enterprise metric has an approved canonical definition and owner. Two departments also need distinct local variants for legitimate operational uses. A proposed variant changes the eligible denominator but would retain the canonical metric’s name and identifier. Which ownership rule best prevents renewed confusion?',
 ['Approve the variant under the canonical identifier and let each consuming report infer its meaning from the department that produced it.',
  'Give the first requesting department sole authority to change the enterprise denominator without consulting affected downstream report owners.',
  'Prohibit all local variants, even when they answer different documented questions and never enter the enterprise comparison.',
  'Give variants distinct labels and identifiers, document lineage and denominator differences, and route canonical changes through the accountable owner and impact review.'],
 'Canonical reporting and local analysis can coexist when their semantic identities, purposes and ownership are clear. A changed denominator changes the quantity measured; retaining the same identifier creates silent ambiguity. Versioned definitions, lineage, explicit permissions and downstream impact review make changes auditable. A canonical change may require historical restatement or a marked break in series; neither is implied automatically. This item concerns change control after a definition exists, not repeating the initial definition exercise.',
 ['Consumers should not have to infer undocumented semantics; the shared identifier would conceal different denominators.','Local demand does not establish authority to redefine a cross-enterprise measure or remove the need for impact review.','Legitimate separately identified local measures need not be prohibited to preserve canonical consistency.','Correct. It protects semantic identity, accountability and traceability while permitting justified local uses.'],
 'A denominator change is a metric change. Protect identifiers, ownership and version history rather than forcing every legitimate question into one number.',
 ['Removed reference to another enterprise scenario.','Differentiated this task from Q153 by testing versioning and change authority.'],('data',))
item(163,
 'A DFSS team developing a portable medical sensor has translated customer needs into technical characteristics. Its house-of-quality review sketch below shows the technical-correlation roof as “not assessed”; the team has no equivalent analysis elsewhere. Which review action most directly addresses the missing information?',
 ['Assess reinforcing and conflicting technical relationships and their rationale, then resolve important trade-offs; retain valid work in the rest of the matrix.',
  'Treat the roof’s blank state as proof that all technical characteristics are independent, and release the design on the existing customer-priority ranking.',
  'Discard every customer need and requirement already recorded, because an unfinished roof establishes that the entire voice-of-customer analysis is invalid.',
  'Replace technical relationships with customer-importance weights, because both describe the same pairs of characteristics and therefore contain identical information.'],
 'The roof addresses relationships among technical characteristics, whereas the body links customer needs to technical characteristics. Missing roof analysis can leave design conflicts or synergies unexamined. The omission does not prove independence or invalidate every other entry. Such roof assessments may initially be engineering judgments: they are not automatically measured Pearson correlations or experimentally established causal effects. Record the rationale, uncertainty and follow-up evidence for material trade-offs. The visual is a review-status sketch, not measured clinical performance or a complete safety assessment.',
 ['Correct. It supplies the missing technical-relationship review without throwing away unrelated valid work or treating judgment as measured proof.','An empty analysis is missing evidence, not evidence of independence or suitability for release.','The missing technical review does not logically invalidate all customer needs and requirements already established.','Customer importance ranks needs; it does not identify interactions between pairs of technical characteristics.'],
 'The roof relates technical characteristics to each other; the body relates needs to characteristics. Missing entries are not zero correlations.',
 ['Replaced the unparameterized generic diagram with an explicit incomplete review-status sketch.','Distinguished technical judgments from measured correlations and preserved valid partial work.'],('qfd','hoq'))
bank[162]['chart']={'type':'house-of-quality','title':'House of quality — review-status sketch','altText':'Triangular technical-correlation roof: not assessed. Below are technical characteristics and the customer-to-technical review body. This is a simplified status sketch, not measured performance.','evidence':{'type':'data-table','title':'House-of-quality review status','altText':'The roof has not been assessed; the other named sections are recorded.','columns':['Section','Recorded content','Review status'],'rows':[['Technical-correlation roof','Pairs of technical characteristics','Not assessed'],['Technical characteristics','Battery capacity; housing thickness; mass','Recorded'],['Customer needs','Operating duration; durability; portability','Recorded'],['Customer-to-technical body','Need-to-characteristic relationships','Recorded']]}}
item(164,
 'A financial-services DFSS team has recorded the need “fast account opening” but no measurable CTQ. It proposes an average completion time under 90 seconds, measured only for successful applications, even though users complain about long waits and timeouts. Which next step best develops a defensible requirement?',
 ['Agree a customer-supported tail-time target, start/end events, eligible cases and treatment of timeouts, with acceptance criteria and a verification method.',
  'Approve the proposed average and exclude timeouts permanently, because successful cases alone establish the experience of all eligible applicants.',
  'Adopt 90 seconds as a universal requirement for financial services without customer or operational validation, because a numeric target is sufficient.',
  'Select a faster database immediately and treat the architecture choice as the completed CTQ, without defining the customer-facing performance measure.'],
 'A CTQ must translate the need into a verifiable requirement with an appropriate population, statistic, boundary and criterion. An average among successful cases can hide poor tail performance and excludes the failure experience. A percentile or time-based success target may be suitable, but its value must be agreed from customer and operational evidence rather than invented by the auditor. Define timeouts and excluded cases explicitly and retain other needs such as accuracy and accessibility. Exploratory design can continue, but requirements cannot be claimed complete without this definition.',
 ['Correct. It operationalizes the customer concern and avoids a biased successful-cases-only measure.','Conditioning only on successful completions can conceal timeouts and severe delays experienced by the eligible population.','A number is not customer evidence; the scenario does not justify a universal 90-second threshold.','An implementation choice is a proposed solution, not the measurable customer-facing CTQ needed to assess it.'],
 'Measurable is more than numeric. Define the event boundaries, eligible population, tail behavior and failure handling before accepting a service-speed CTQ.',
 ['Qualified invented target and verification/validation terminology.','Added tail metric and timeout/denominator ambiguity for an MBB-level decision.'],('matrix','verify'))
item(165,
 'A consumer-product DFSS team has approved CTQs but plans to enter design verification with an informal list of convenient tests. There is no mapping to requirement IDs, operating conditions, acceptance criteria or the exact design configuration. No particular document title is mandated. What should the MBB require before claiming verification readiness?',
 ['Rename the existing list “DVP” and approve it without checking coverage, because the formal title itself establishes requirement traceability.',
  'Test only the easiest CTQs and use the average pass rate to claim that all critical requirements were verified.',
  'Require physical testing for every requirement, rejecting suitable analysis, inspection or demonstration regardless of the requirement and evidence quality.',
  'Create a controlled requirement-to-method plan with conditions, criteria, configuration, ownership and evidence records, and separately plan intended-use validation.'],
 'A design verification plan or equivalent controlled record should show how each applicable requirement will be checked and how results support the claimed configuration. The need is traceable evidence, not a specific title or paperwork volume. Verification methods can include test, analysis, inspection or demonstration where suitable; sampling and uncertainty must fit the claim. Validation asks whether the product serves intended users and use conditions, not merely whether written specifications were met. Missing coverage and acceptance criteria should be resolved before readiness is claimed.',
 ['Changing a document name does not repair missing traceability, coverage or acceptance criteria.','An aggregate pass rate cannot substitute for evidence on an untested critical requirement.','Appropriate verification can use several methods; requiring physical tests universally is neither stated nor technically necessary.','Correct. It closes the actual planning gaps and keeps verification of requirements distinct from validation of intended use.'],
 'A DVP is not evidence because of its title. Look for requirement coverage, decision criteria, configuration traceability and suitable methods.',
 ['Removed universal named-document claim.','Added method tailoring, configuration control and verification versus validation distinction.'],('matrix','verify'))
item(166,
 'A DFSS team shortlists Concept C using the weighted concept-scoring adaptation shown below. Scores range from −2 to +2 relative to a zero baseline; higher is better. This is not the classical plus/same/minus-only Pugh scale. Every released design must also meet a separate absolute safety acceptance criterion, which has not yet been evaluated for C. Which conclusion is justified?',
 ['Reject C solely because safety scores −1; any performance below the baseline necessarily proves failure of the separate absolute safety criterion.',
  'Release C because its weighted score is positive; favorable cost and performance scores compensate for an unverified mandatory safety requirement.',
  'Treat the weighted score as a 105% probability that C meets all requirements, because percentage weights convert judgment scores into probabilities.',
  'C scores +1.05, but remains provisional; evaluate the absolute safety gate and design trade-offs before selection or release.'],
 'The weighted score is 0.25(2) + 0.30(2) + 0.20(1) + 0.25(−1) = 1.05. It is a judgment-based comparative index, not a probability or a verified safety result. A safety score below baseline does not itself prove failure of an absolute limit, but an unverified mandatory requirement cannot be offset by favorable scores elsewhere. Evaluate the safety evidence and resolve any failing requirement before release. No other concepts’ scores are supplied, so the table does not independently establish that C is the best of four.',
 ['A comparative decrement and failure of an absolute threshold are different; the necessary absolute evidence is not supplied.','An aggregate preference score cannot waive or verify a mandatory safety condition.','A weighted sum of ordinal judgment scores is not a probability, and 1.05 here has no percent-success interpretation.','Correct. The arithmetic is right and the interpretation separates comparative preference from the mandatory safety decision.'],
 'Calculate the score, then apply the gate. Relative performance versus a baseline neither establishes absolute compliance nor allows a mandatory requirement to be traded away.',
 ['Corrected Pugh scale terminology.','Removed unsupported ranking across absent alternatives.','Added absolute safety gate and independently verified +1.05.'],('verify',))
c=bank[165]['chart'];c.update(title='Weighted concept-scoring adaptation — Concept C',altText='Judgment scores on a −2 to +2 scale; these are comparative scores, not absolute safety verification.');c['columns']=['Criterion (weight)','Baseline score','Concept C score']
item(167,
 'A DFSS team faces a fixed development deadline. One candidate meets nominal CTQ targets, but performance under expected environmental and manufacturing variation has not been established. It is debating a large optimization DOE versus immediate release. Which MBB recommendation best addresses the decision?',
 ['Release the nominal design if expected sales volume is low, treating low volume as a waiver of mandatory safety and performance requirements.',
  'Require a full factorial covering every proposed setting before any decision, regardless of existing evidence, model needs or a smaller informative design.',
  'Choose whichever concept has the best nominal mean, because passing one point proves robustness throughout the operating envelope.',
  'Identify the consequential evidence gaps and use a feasible risk-based verification and design study; release only when applicable acceptance criteria are supported.'],
 'The choice is not necessarily exhaustive optimization versus unsupported release. Use failure consequences, uncertainty, existing evidence, feasible designs and schedule to determine the additional work required. A targeted sequential DOE, focused robustness study or other suitable evidence may resolve key gaps more efficiently. High consequence does not prescribe one particular design, and low sales volume does not waive mandatory requirements. Optimize only where the expected information and design benefit justify it, while retaining necessary verification and validation before release.',
 ['Volume affects economic exposure but cannot, by itself, waive applicable mandatory acceptance requirements.','A large full factorial is not universally necessary or efficient; the design must fit the information needs.','Nominal success does not establish the response under environmental or manufacturing variation.','Correct. It avoids the false binary choice and preserves non-negotiable release evidence while tailoring the study.'],
 'Separate optimization from required verification. Time pressure changes how evidence is obtained, not whether unsupported performance can be declared proven.',
 ['Removed cross-bank prosthetics reference and false binary framing.','Qualified risk/volume trade-off and preserved mandatory requirements.'],('verify','robust'))
item(168,
 'A simplified fault tree defines total power loss during a specified mission as A AND B, where A and B mean the primary and backup supplies are unavailable during that mission. No other path is included. The table gives P(A), P(B) and P(B given A); the events are not independent. What is the modeled top-event probability and correct timing interpretation?',
 ['0.0006; multiplying the two marginal probabilities is valid because an AND gate itself guarantees independent failure events.',
  '0.0500; add the marginal probabilities because either unavailable supply alone meets the stated AND condition.',
  '0.0020; use the conditional joint probability, and require both unavailability states—not failures beginning at the identical instant.',
  '0.0480; subtract the joint term from the sum, because that union probability represents the stated AND output.'],
 'An AND output is the intersection of its input events. Here P(A and B) = P(A) × P(B given A) = 0.02 × 0.10 = 0.0020, or 0.20%. Multiplying the marginals would give 0.0006, but independence is explicitly contradicted by P(B given A) = 0.10 versus P(B) = 0.03. The union probability would be 0.02 + 0.03 − 0.002 = 0.048. Both defined unavailability states must be present; a static AND gate does not require identical failure onset times or specify sequence. The simplified tree is not a complete aircraft safety assessment.',
 ['An AND gate specifies logical intersection, not statistical independence; the supplied conditional probability rules out this product.','Adding marginals corresponds to a union approximation and does not implement the stated AND condition.','Correct. It uses the supplied dependence information and distinguishes concurrent event states from simultaneous failure onset.','0.048 is the union probability; it would concern A OR B, not the defined top event.'],
 'Gate logic and probabilistic dependence are separate. Use the event definitions and conditional probability; “both unavailable” does not mean “failed at the same instant.”',
 ['Corrected simultaneous-onset implication.','Removed answer-revealing gate-definition table and replaced it with scenario probability evidence.','Added dependence and independently calculated joint probability.'],('fta',),'VI.B.9: reliability modeling; related DFSS risk analysis')
bank[167]['chart']={'type':'data-table','title':'Mission-level probability inputs — simplified power-loss model','altText':'Probabilities apply to the same defined mission: primary unavailable 0.02, backup unavailable 0.03, backup unavailable conditional on primary unavailable 0.10.','columns':['Input event or condition','Probability'],'rows':[['A: primary supply unavailable','0.02'],['B: backup supply unavailable','0.03'],['B given A: backup unavailable when primary unavailable','0.10']]}
item(169,
 'A sensor-housing team has identified feasible design settings and representative laboratory levels of temperature, humidity and vibration that vary in service. It has not yet compared settings across those noise conditions. Which study most directly supports robust parameter selection rather than merely documenting nominal performance?',
 ['Cross candidate settings with representative noise conditions, assess both target performance and sensitivity, and confirm the chosen setting under intended use.',
  'Test only the current setting across noise conditions and claim this alone identifies the best alternative setting, without testing or modeling those alternatives.',
  'Choose the setting with the smallest spread regardless of whether its mean meets the functional target or any mandatory operating limit.',
  'Choose the best nominal result and assume averaging later field measurements will remove design sensitivity to temperature, humidity and vibration.'],
 'Robust parameter design seeks controllable settings that perform acceptably despite relevant noise, not simply settings with the best nominal mean. A planned control-by-noise comparison can expose sensitivity and important interactions while evaluating the target level and constraints. Testing only one configuration may assess it, but cannot by itself identify the best untested alternative. Laboratory coverage, replication and confirmation must support the intended-use claim; no finite set of noise levels proves performance under every possible field condition.',
 ['Correct. It compares controllable choices under the relevant variation and evaluates target performance together with sensitivity.','This can characterize the current design but does not supply a comparison of the untested alternatives.','Low variability is not useful if the mean or another requirement is unacceptable.','Averaging observations does not remove an underlying design response to environmental variation.'],
 'Noise testing characterizes a design; control-by-noise comparison helps select a robust design. Low spread must still accompany acceptable target performance.',
 ['Distinguished robustness assessment from robust parameter selection.','Added control/noise comparison, mean-target trade-off and coverage limits.'],('robust',),'VI.C.3; VI.E as related robust design application')
item(170,
 'Before prototypes exist, a DFSS scorecard reports predicted Cpk from engineering tolerance widths alone. The analyst has not specified component distributions, centering, correlations or how tolerance limits relate to manufacturing standard deviations. What is the most defensible review conclusion?',
 ['Treat each drawing half-tolerance as exactly three standard deviations and certify production capability without documenting or validating that assumption.',
  'Use capability prediction only as a conditional design model after specifying the variation basis and sensitivity; validate it later with representative measured performance.',
  'Discard all early tolerance analysis, because a model can never provide useful information before a physical prototype has been manufactured.',
  'Treat any positive predicted Cpk as proof of process stability and the exact defect rate, regardless of the assumed manufacturing distribution.'],
 'Specification or tolerance limits constrain allowed geometry; they do not uniquely determine a manufacturing distribution or its standard deviation. A model-based capability forecast needs a justified mean, variation and dependence model, with explicit uncertainty and intended conditions. It can guide early design choices and sensitivity analysis, but is not an observed production-capability result. Empirical evidence is needed to validate the model and assess stable, representative operation. Even a numerically defined Cpk does not by itself establish a distribution-based tail probability or future stability.',
 ['Tolerance equals three standard deviations only under an extra modeling assumption; it is not guaranteed by the drawing.','Correct. It preserves the value of early analysis while making its assumptions, sensitivity and later validation explicit.','Conditional modeling can help compare designs and expose risks; the absence of prototypes does not make all analysis worthless.','Cpk alone proves neither stability nor a distribution-free exact defect rate.'],
 'A tolerance width is not a measured standard deviation. A predicted capability index must identify its variation model and remain distinguishable from observed capability.',
 ['Corrected tolerance-to-SD assumption gap.','Separated conditional predicted index, stability, empirical capability and tail probability.'],('capability','robust'),'VI.A.1 and VI.E as related design-capability applications')
item(171,
 'Five component deviations add directly with sensitivity +1 to an assembly dimension. Each listed symmetric half-tolerance is a hard allowable bound. The customer requires the assembly within ±0.25 mm for every permitted combination; no statistical tolerance alternative is authorized. Component 1 is cheapest to tighten, but marginal cost curves are unavailable. How should the MBB assess the proposed allocation?',
 ['Approve the allocation because its root-sum-square half-width is about 0.1594 mm, which guarantees all permitted combinations remain inside ±0.25 mm.',
  'Approve the allocation because the average component half-tolerance is 0.064 mm, so that average is the worst-case assembly deviation.',
  'Tighten component 1 to zero half-tolerance and approve the other four unchanged, because eliminating the cheapest contribution meets the assembly requirement.',
  'The worst-case half-width is 0.32 mm and fails; optimize the contributions jointly, since tightening component 1 alone cannot meet ±0.25 mm.'],
 'For the stated additive geometry and hard-bound guarantee, the worst-case half-width is 0.02 + 0.05 + 0.10 + 0.10 + 0.05 = 0.32 mm, exceeding 0.25 mm by 0.07 mm. Even eliminating component 1’s entire 0.02 mm contribution leaves 0.30 mm. Root-sum-square gives about 0.1594 mm but is not an all-combinations guarantee; statistical interpretations would need a permitted probabilistic criterion and justified distributions and dependencies. Optimize using sensitivities, feasible manufacturing capability and marginal costs. Qualitative cost labels alone do not prove a unique cost optimum.',
 ['Root-sum-square does not bound all permitted combinations when every component can reach its same-direction tolerance limit.','Averaging component limits is not propagation through an additive assembly dimension.','Removing 0.02 mm leaves 0.30 mm, which still exceeds the required 0.25 mm half-width.','Correct. It checks feasibility before cost allocation and identifies why the cheapest component alone cannot close the gap.'],
 'Choose the tolerance model from the requirement. A worst-case guarantee and a statistical yield target are not interchangeable; low tightening cost does not prove adequate contribution.',
 ['Supplied missing assembly equation and acceptance limit.','Corrected implied feasibility and cost-optimality of the original illustrative allocation.','Retained original component tolerances and independently checked all 32 extreme combinations.'],('robust',),'VI.A.1: propagation; VI.E as related tolerance-design application')
c=bank[170]['chart'];c.update(title='Proposed hard-bound allocation — additive assembly','altText':'Proposed component bounds, not an approved allocation. Assembly requirement is a ±0.25 mm hard bound.');c['columns']=['Component','Relative tightening cost','Proposed hard bound'];c['rows'][0][0]='1'
item(172,
 'A DFSS reliability model based on component data predicts that the assembled product meets its specified mission target. No integrated-product evidence yet supports the assumed environmental stresses, interfaces or common-cause behavior. The team proposes a single high-stress test with no justified acceleration model. What should the MBB recommend?',
 ['Accept the component prediction as the release demonstration, because favorable component failure rates exclude assembly interactions and common causes.',
  'Convert high-stress hours directly into use-condition hours using an arbitrary fixed multiplier, then claim the mission target from that equivalent exposure.',
  'Plan mission- and failure-mode-relevant integrated evidence with acceptance criteria and uncertainty; use acceleration only where its model and mechanisms are justified.',
  'Reject every component-level prediction and prohibit its use in test planning, even if it contains relevant verified information about individual failure mechanisms.'],
 'A component model is useful evidence but does not resolve unsupported assembly interactions, environments and dependence. The verification strategy should define the mission, configuration, relevant failure modes, confidence or other uncertainty treatment and acceptance criteria. Integrated tests or justified combinations of evidence must address the actual gaps. Accelerated testing requires a defensible stress-life relationship and should not introduce unrelated mechanisms; a single arbitrary high-stress exposure is not automatically a use-life demonstration. No universal accelerated-test requirement or multiplier can be inferred from this case.',
 ['Component-level rates do not exclude interactions, shared stresses or common-cause failures at the assembled-product level.','The scenario provides no basis for a conversion factor; unsupported equivalent hours create false precision.','Correct. It targets the missing system evidence and requires a defensible extrapolation model instead of equating stress with proof.','Relevant component information can guide both the model and an efficient validation plan; it need not be discarded.'],
 'Accelerated exposure is not automatically equivalent use life. Match failure mechanisms, mission conditions, configuration and uncertainty to the reliability claim.',
 ['Removed implication that accelerated testing is universally required or sufficient.','Added mission, dependence, failure-mechanism and uncertainty requirements.'],('reliability','verify'),'VI.B.9; VI.E as related reliability-design application')
item(173,
 'A next-generation product charter says only “better than the current model.” The sponsor now requests authorization for design freeze, but customer needs, baseline comparisons, measurable targets and non-negotiable constraints have not been agreed. What should the MBB recommend?',
 ['Agree customer-linked measurable objectives, comparison conditions, constraints and acceptance criteria before design freeze; continue only suitably bounded discovery meanwhile.',
  'Freeze the design once engineers privately agree it is better, leaving the sponsor to define measurable acceptance after seeing the finished product.',
  'Choose a convenient 20% weight reduction without customer evidence and use it as the only requirement, regardless of strength, cost or operating conditions.',
  'Ban all exploratory research until every requirement is final, because an initial directional goal can never support any legitimate discovery work.'],
 'A directional aspiration can initiate discovery but cannot support a claim that a frozen design satisfies agreed needs. The team and sponsor should operationalize objectives, baselines, measurement conditions, constraints and acceptance evidence. Targets should follow from customer and business evidence rather than arbitrary percentages, and competing requirements must remain visible. This does not require pretending every uncertainty is resolved before exploratory work; it requires matching authorization and claims to the maturity of the requirements.',
 ['Correct. It makes the freeze decision evidence-based while permitting explicitly bounded discovery appropriate to unresolved requirements.','Private engineering agreement does not supply shared customer-linked objectives or a fair prospective acceptance standard.','A convenient target is not established by the scenario and may sacrifice other critical requirements.','An initial aspiration can legitimately guide discovery; the problem is unsupported design freeze, not all exploratory work.'],
 'Match the decision to requirement maturity. A direction can support exploration, but acceptance targets should not be invented after the design is frozen.',
 ['Removed explicit cross-bank dependence.','Qualified blanket prohibition on all design work before measurable goals.','Distinguished discovery from design freeze.'],('matrix','verify'))
item(174,
 'At final DFSS review, a customer requirement has changed after concept selection. The QFD, CTQ definitions, tolerance analysis and test reports each appear complete but reference different requirement and design versions. Which MBB action best reconnects the tools to a defensible release decision?',
 ['Count completed templates and approve release if every named DFSS tool appears at least once, regardless of version consistency or supporting evidence.',
  'Repeat every DFSS tool in a universal fixed sequence, even where an impact assessment would show that valid results are unaffected by the change.',
  'Trace the changed need through requirements, design decisions and evidence; reconcile versions, reassess affected work and close gaps before release.',
  'Update only the final scorecard label to the latest requirement, assuming older calculations and tests remain valid without examining what changed.'],
 'The connecting principle is traceability from intended needs through measurable requirements and design decisions to relevant verification and validation evidence. DFSS tools do not impose one universal linear sequence, and a CTQ tree does not necessarily start from specifications already generated by QFD. A change-impact review should identify which assumptions, analyses and tests remain valid and which must be revised or repeated. Completed documents from inconsistent versions are not a coherent evidence package. Updating labels without reassessment would conceal the missing support.',
 ['Template completion is activity evidence, not proof that the current configuration meets the current requirements.','A rigid universal sequence is not established and can waste valid work; affected evidence should be identified through impact analysis.','Correct. It restores configuration and requirement traceability, preserves unaffected valid work and resolves real evidence gaps.','Relabeling a scorecard does not validate calculations or tests performed against different requirements or configurations.'],
 'Trace evidence, not paperwork. A completed tool is useful only when its assumptions and configuration support the actual release claim.',
 ['Corrected rigid sequential toolchain and CTQ-tree ordering overclaims.','Removed author-level capstone commentary.','Differentiated from verification-plan recall by testing change impact and configuration evidence.'],('matrix','verify','qfd'))
item(175,
 'A team adapts QFD and CTQ trees to a software diagnostic service. Users need timely, dependable results, while engineering proposes “average response under one second” as the only CTQ. Load varies sharply and some requests return errors. Which coaching response best applies the tools beyond hardware?',
 ['Require a physical prototype before documenting any digital-service requirements, because QFD relationships must be expressed as material dimensions.',
  'Accept the average response time alone and exclude errored requests, because speed establishes both dependable diagnostic output and complete user experience.',
  'Translate needs into measurable service and output-quality requirements, defining load, eligible requests, failure handling and validation conditions rather than hardware-only measures.',
  'Use software test coverage percentage as the customer CTQ and treat full line coverage as proof that output quality and response-time requirements are met.'],
 'QFD’s customer-to-technical translation applies to products and services; the measurable characteristics must fit the context. Tail response times, availability and output correctness may matter, but the team must agree values, populations, references and conditions rather than assume a universal target. Average latency among successes can conceal overload and failed requests. Test coverage describes exercised code, not proof of requirement satisfaction or intended-use performance. This is a requirements-method question, not a claim that the tool’s diagnostic accuracy or clinical suitability has been established.',
 ['A physical artifact is not a prerequisite for translating software users’ needs into measurable requirements.','Average speed among successful requests neither captures failure experience nor establishes output dependability.','Correct. It retains customer traceability and adapts measurement and validation to the actual digital-service context.','Code coverage does not prove correctness, timing performance or suitability for intended users and conditions.'],
 'Adapt the measured characteristics, not the evidence standard. A fast response can still be wrong or inaccessible, and successful-case averages can hide failures.',
 ['Replaced hardware-versus-software recall with specific operationalization and denominator checks.','Qualified diagnostic accuracy and avoided unverified universal thresholds.'],('qfd','verify'))
# Original numeric content is retained where valid. New case assumptions are explicit in stems.
assert len(revisions)==25
D=root/'docs/audits/mbb-set3-batch07';D.mkdir(parents=True,exist_ok=True)
starts=[m.start() for m in re.finditer(r'^  \{$',source,re.M)];assert len(starts)==175
trailer=source[source.rfind('  ];'):]
protected=source[:starts[150]]
updated=protected+''.join('  '+json.dumps(q,ensure_ascii=False,indent=2).replace('\n','\n  ')+',\n' for q in bank[150:])+trailer
assert updated[:len(protected)]==protected
(root/'test-bank-mbb-set3.js').write_text(updated)
sha=lambda s:hashlib.sha256(s.encode()).hexdigest()
(D/'preservation.json').write_text(json.dumps({'baseline':'3d4ea284e1493ef200c167eb926670073d325637','protectedPrefixSHA256':sha(protected),'protectedTrailerSHA256':sha(trailer),'ids':[q['qid'] for q in original],'keys':[q['answer'] for q in original]},indent=2)+'\n')
(D/'revisions.json').write_text(json.dumps(revisions,ensure_ascii=False,indent=2)+'\n')
(D/'sources.json').write_text(json.dumps({'verifiedOn':'2026-09-07','bodyOfKnowledge':ASQ,'references':refs,'limits':['Sources establish principles, not ASQ authorship or endorsement.','ASQ VI.E explicitly names QFD and other concept-generation tools; additional DFSS applications are cross-mapped rather than invented as named subtopics.','NUREG landing page verifies publication identity only; event-probability results are independent derivations. No unverified textbook page is cited.','Added mission probabilities, acceptance limits and decision conditions are original illustrative assumptions disclosed in the questions.']},ensure_ascii=False,indent=2)+'\n')
(D/'question-audit-tracker.json').write_text(json.dumps({'batch':7,'range':[151,175],'status':'Content corrected; rendered validation pending','items':[{'number':r['number'],'qid':r['qid'],'contentReview':'Complete','independentAnswer':'Complete','sourceAlignment':'Reviewed with explicit source limits','renderReview':'Pending','status':'Pending rendered validation'} for r in revisions]},indent=2)+'\n')
print('Batch 7 content applied; protected Q1–150 SHA256',sha(protected))
