import json, pathlib, subprocess
root=pathlib.Path.cwd()
original=json.loads(subprocess.check_output(['node','-e',"const fs=require('fs'),vm=require('vm');let c={window:{}};vm.runInNewContext(fs.readFileSync('test-bank-mbb-set3.js','utf8'),c);console.log(JSON.stringify(c.window.MBB_SET3.slice(50,75)))"]).decode())
records=[]
def q(n,stem,options,why,rationales,trap,bok,findings):
 old=original[n-51];records.append(dict(number=n,qid=old['qid'],answer=old['answer'],stem=stem,options=options,why=why,optionRationales=rationales,trap=trap,bok=bok,findings=findings))
q(51,
"A B2B laundry service assigns account teams responsibility for hospital and hotel service agreements, but all accounts share the same washing process. Account teams can change delivery arrangements; a central process owner controls washing standards and equipment. How should the MBB assign improvement ownership without creating conflicting process changes?",
["Assign every project to the central washing owner and let account teams advise after solutions are selected, because shared equipment makes customer-specific delivery authority unnecessary.","Let account teams own customer-specific improvements and the central process owner own shared-process changes, with explicit interface decisions, common standards and coordinated priorities.","Give each account team independent authority to change shared washing standards and equipment, while using quarterly reporting to reconcile conflicting local changes after implementation.","Allocate Belts to accounts in proportion to revenue and let the highest-revenue account approve all shared-process changes, regardless of obligations to the other accounts."],
"The account and process owners have different, explicitly stated authority. Account-level ownership should preserve customer responsiveness, while changes to the common washing process require shared standards and coordinated approval. A hybrid arrangement is defensible because it connects these rights rather than assuming that either complete centralization or independent local control will fit every decision.",
["This removes account teams from decisions within their own delivery authority and delays customer input.","Correct. It preserves account accountability while preventing incompatible changes to the common process.","Independent changes to shared equipment can conflict; retrospective reporting is not prior coordination.","Revenue ranking does not grant authority to override other accounts' requirements or process controls."],
"Align ownership with the decision being made. Customer-account accountability and shared-process authority must both be explicit; the organization chart alone does not settle their interfaces.",
"II.A.1; II.D.4",["Cross-question references","Length-cued distractors","Unspecified interface authority"])
q(52,
"Scientists at a veterinary diagnostics laboratory object to an MBB's proposal to replace their validated analytical models with a standard introductory Six Sigma toolkit. They support reducing specimen turnaround time but question whether the proposed methods address the laboratory's data structure. What response best combines technical rigor with deployment leadership?",
["Adopt the introductory toolkit for every analysis to ensure standardization, permitting specialist models only after the first project has been completed and compared with a second project.","Jointly evaluate the data, assumptions and decision needs; retain validated specialist methods where fit for purpose, and use DMAIC to structure the improvement work and its controls.","Exempt the scientists from common problem definition, validation and control requirements because their qualifications make a shared improvement structure unnecessary for laboratory projects.","Resolve the objection through an executive mandate before discussing method fit, treating the disagreement as a commitment problem rather than a potentially legitimate technical concern."],
"The objection concerns a specific mismatch between proposed methods and the data, not a demonstrated lack of statistical knowledge. DMAIC does not require replacing a suitable validated model with an elementary technique. Joint assessment should determine fitness for purpose while retaining shared objectives, evidence review and sustainment controls. Advanced methods are not automatically superior merely because they are more complex.",
["Uniformity does not justify using a method with unsuitable assumptions for the current decision.","Correct. It tests method suitability and uses the scientists' expertise within a common improvement process.","Technical qualifications do not remove the need for shared goals, validation or sustainment controls.","Mandating acceptance before addressing a substantive technical concern confuses compliance with method validity."],
"Evaluate the actual methodological objection rather than attributing resistance to a professional group. Use the simplest adequate method, not automatically the simplest or most complex available method.",
"II.C.1; II.C.2; II.D.3",["Cross-question framing","Incorrect II.D title","Expertise stereotype and method-fit overclaim","Length-cued distractors"])
q(53,
"An urgent-care patient-flow project requires clinical protocol decisions from a clinical director and scheduling-system decisions from an operations director. Neither can authorize the other's changes, and no available single sponsor has authority over both. Both directors support the objective, but their priorities can conflict. Which sponsorship arrangement best closes the authority gap?",
["Appoint only the operations director as sponsor and classify clinical protocol decisions as project-team recommendations, so one reporting line replaces the need for clinical approval.","Appoint both directors as sponsors but leave approval boundaries and disagreements informal, assuming shared support for patient flow will prevent conflicting instructions during implementation.","Use both directors as sponsors with documented approval boundaries, a named coordinating lead and an agreed escalation route, so cross-domain decisions have authority and clear accountability.","Assign the Black Belt final approval over both domains and ask the directors to provide technical advice, treating responsibility for project delivery as sufficient authority over their resources."],
"Co-sponsorship addresses the two separate authority domains in this stated case, but only with explicit responsibilities and a way to resolve disputes. It is not a universal rule that cross-functional projects require two sponsors: a sufficiently empowered single sponsor could work in another case. The Black Belt's delivery role does not confer clinical or operational approval authority.",
["An operations reporting line cannot remove the clinical approval right explicitly required by the case.","Shared objectives do not resolve conflicting priorities without decision boundaries and escalation.","Correct. The arrangement covers both authority domains and prevents ambiguous joint accountability.","Responsibility for analysis and delivery does not automatically grant authority over either director's domain."],
"Choose governance that covers actual decision rights. Multiple sponsors need clear accountability and arbitration; they are not inherently better than one adequately empowered sponsor.",
"II.B.1; II.B.2; II.C.3",["Co-sponsorship overgeneralization","Missing accountability and conflict resolution","Length-cued distractors"])
q(54,
"A plant manager attributes low participation in a packaging improvement project to employees being inherently resistant to change. The same employees engaged positively in six major changes during the preceding year. No interviews or workload assessment have been conducted for the new project. What is the MBB's most defensible next step?",
["Treat the six earlier successes as proof that current resistance cannot exist, and launch the new project unchanged while reporting that the manager's concern is statistically disproven.","Conclude that the six changes caused change fatigue and suspend the project, without checking its specific risks, employees' concerns or their remaining capacity to participate.","Require refresher change-management training for all employees before reviewing the project, treating the manager's description as an established diagnosis of their attitude.","Investigate project-specific concerns, participation conditions and cumulative change workload, using earlier successes as context rather than proof of either a fixed trait or a single alternative cause."],
"The history weakens an unsupported fixed-trait explanation but does not identify the present cause. Employees may have concerns about this change, capacity constraints, cumulative fatigue or other barriers. Interviews and workload evidence are needed before selecting an intervention. Six successful changes are contextual evidence, not a statistical test or proof that further change must be welcomed.",
["Past engagement does not disprove current concerns, and no inferential test has been performed.","Cumulative fatigue is plausible but not established by the count of previous changes alone.","A training prescription assumes the attitude diagnosis before investigating its evidence.","Correct. It tests competing explanations rather than substituting a new unsupported label."],
"Evidence against one explanation does not prove another. Prior change success can coexist with legitimate new concerns or accumulated workload and fatigue.",
"II.C.1; II.D.3",["Unwarranted project-specific causal inference","Change-fatigue omission","Length-cued distractors"])
q(55,
"Ambulance crews say they withhold details during protocol-deviation reviews because every deviation is routed directly to individual disciplinary review, without examining dispatch information or equipment access. Mandatory incident reporting and urgent safety escalation must continue. Which redesign best improves learning while preserving justified accountability?",
["Offer absolute anonymity and immunity for every deviation, including reckless conduct, so crews can discuss events without any possibility of an individual accountability decision.","Add prompt, facilitated systems-focused debriefs, clear reporting and escalation routes, and a fair behavior-based accountability process; communicate confidentiality limits and track corrective actions.","Collect identifiable written statements only after the disciplinary outcome, so the decision about individual fault is finalized before operational contributors are considered.","Ask crews to resolve deviations informally within each shift and submit only aggregate trends, replacing incident-level escalation with a monthly learning report."],
"A learning-oriented review examines system conditions without assuming that every deviation is misconduct. It also preserves required reporting, urgent escalation and fair behavior-based accountability. Confidentiality must not be promised beyond what the process can provide. Facilitated debriefs and tracked corrective actions make this an operational learning-system design, not merely a label for a blame-free culture.",
["Absolute immunity removes appropriate accountability; anonymity may also be impossible to guarantee.","Correct. It combines event-level learning, action follow-through and explicit accountability safeguards.","Deferring systems evidence until after discipline risks a premature and biased judgment.","Aggregate monthly trends cannot replace required incident reporting or urgent safety escalation."],
"A learning system needs usable reporting, timely systems review and action closure. Just culture does not mean ignoring reckless conduct or promising confidentiality beyond actual limits.",
"II.D.6; II.E.2",["Cross-question dependence","Incorrect II.D title","Near-duplicate just-culture recall task","Missing reporting and confidentiality safeguards","Length-cued distractors"])
q(56,
"A ceramics manufacturer sells through distributors and online across several language groups. Its feedback team has limited response capacity, and some customers want to submit anonymous feedback. Repeat buyers dominate the current contact list. Which design best improves coverage and follow-through without making commitments the system cannot meet?",
["Use the repeat-buyer email list with translated questions and promise an individual resolution to every submission, including anonymous messages with no return contact channel.","Open separate feedback channels for every distributor but leave eligibility rules, prioritization and action ownership to each channel, assuming broad access ensures representative evidence.","Replace external feedback with inspection results and collect customer comments annually, because the inspection system already measures all customer experience dimensions consistently.","Include lapsed and underrepresented customers, test language accessibility and comparability, triage by risk, assign action owners and response targets, and publish aggregate follow-up for anonymous submissions."],
"Feedback coverage should extend beyond surviving repeat buyers, and translation alone does not establish comparable interpretation or response scales. Finite capacity requires prioritization and realistic service targets. Contactable submissions can receive individual acknowledgment; anonymous submissions without a return channel need another closure route, such as aggregate action updates. No design guarantees complete representativeness merely by offering many channels.",
["It retains survivor selection and promises a direct response where no contact route exists.","More channels do not assure comparable definitions, representative coverage or action ownership.","Inspection measures cannot fully substitute for customer experience and loss-of-customer feedback.","Correct. It addresses selection, language fit, capacity and credible closure for different submission types."],
"Separate acknowledgment, investigation and resolution. A promise to respond individually to every anonymous submission is not credible without a return channel.",
"II.E.1; II.E.2",["Cross-question dependence","Impossible universal response guarantee","Missing triage and ownership","Length-cued distractors"])
q(57,
"A mobile-phone repair chain is reviewing the current scorecard shown below. Stores differ in repair complexity, arrival volume and staffing. Management wants faster service without increasing repeat repairs. Which redesign best supports comparable, actionable review rather than rewarding throughput at the expense of quality?",
["Keep daily repair totals as the ranking measure and add a named owner; use the monthly callback count as a tie-breaker without aligning follow-up periods or denominators.","Combine all measures into one weighted score immediately; allow higher throughput to offset any deterioration in repeat repairs, even when customer-quality thresholds are breached.","Pair an effort-aware throughput measure with defined repeat-repair rates, review workload and repair mix, assign accountable owners, and use timely reviews with explicit quality safeguards.","Rank stores by callbacks per day and retain raw repair totals only for information; treat differences in repair mix and the number of completed repairs as irrelevant to quality comparisons."],
"Raw throughput confounds staffing, arrivals and repair difficulty. Callback counts also require a defined eligible repair population and consistent follow-up window before comparisons are meaningful. Pairing suitable productivity and quality measures, examining case mix and assigning owners supports action without treating an adjustment as proof of causation. Quality safeguards should not disappear inside a compensating weighted average.",
["Naming an owner does not repair non-comparable callback counts or unadjusted workload differences.","An aggregate score can hide unacceptable quality deterioration behind a throughput gain.","Correct. It addresses comparability, counter-metrics, ownership and response timing together.","Callbacks per day still lack the relevant repair denominator and comparable follow-up exposure."],
"A common dashboard does not guarantee comparable measures. Align operational definitions, eligible denominators and follow-up windows, and preserve quality safeguards alongside productivity.",
"II.F.2; II.E.1",["Cross-question dependence","Answer-revealing table","Stem-table cadence and owner mismatch","Benchmarking described as confound control","Length-cued distractors"])
q(58,
"A credit union has conflicting matrix assignments, inconsistent sponsor follow-through, skeptical experienced loan officers, sales-only incentives despite a member-first value, uniformly positive identifiable member surveys, and observed shortcuts under a loans-per-week target. No causal links among these findings have been established. Which initial recovery plan is most defensible?",
["Contain harmful shortcuts, secure accountable sponsorship and priority decisions, and coordinate an evidence-based review of incentives, feedback, paired metrics and model fit with frontline participation.","Treat sales incentives as the proven cause of every finding and complete their redesign before addressing harmful shortcuts, sponsor decisions or the validity of the member-survey evidence.","Replace loans per week with a composite score and publish revised rankings, relying on the better metric to resolve reporting conflicts, survey candor and skepticism about statistical models.","Delay leadership and governance involvement until the loan officers endorse statistical models, leaving the existing target and survey mechanism unchanged throughout the engagement exercise."],
"Observed harmful shortcuts warrant containment, while sponsorship and decision rights enable coordinated recovery. The findings do not establish a single root cause or justify delaying governance until an incentive redesign is complete. A positive member survey cannot be explained simply by assuming staff fear: respondent selection, question design, confidentiality and actual member experience need assessment. Involve loan officers in evaluating model fit rather than treating expertise as obstruction.",
["Correct. It prioritizes demonstrated harm and enabling governance while testing possible causes together.","The causal claim is unsupported and the proposed sequence delays immediate harm containment.","A new score alone does not establish authority, trustworthy feedback or appropriate model use.","Frontline involvement matters, but postponing accountable leadership leaves harmful conditions in place."],
"Do not infer one root cause from coexisting symptoms or confuse member survey responses with employee reporting. Contain known harm while establishing the authority and evidence needed for coordinated recovery.",
"II.B.1; II.C.3; II.D.6; II.E.2; II.F.2",["Cross-question dependence","Unsupported causal chain and rigid priority order","Member-versus-employee survey confusion","Length-cued distractors"])
q(59,
"At a shipbuilder's Measure-to-Analyze gate, a gauge R&R report is labeled marginal. The team has not defined acceptable measurement error for the intended defect analysis or assessed whether the gauge can distinguish the differences that matter. The Black Belt wants approval solely to recover schedule. What should the MBB do next?",
["Withhold approval for measurement-dependent conclusions until fitness for the intended use is assessed and documented; improve or replace the method if needed, while allowing explicitly bounded independent work.","Approve unrestricted Analyze work because any marginal gauge R&R result is acceptable for root-cause analysis, reserving measurement validation for final product acceptance decisions.","Require replacement of the gauge immediately because the word marginal always means the instrument is unusable, without considering decision risk, study design or alternatives.","Increase the number of readings and approve the gate on that basis alone, assuming larger samples automatically eliminate bias, operator differences and inadequate resolution."],
"A marginal label is not an application-specific acceptance decision. Assess the study design, error components, discrimination and consequences of wrong decisions against the intended use. Schedule pressure alone cannot establish adequacy. Measurement-dependent conclusions remain on hold until that assessment supports them; data-independent planning can proceed under explicit limits. More observations can reduce some random error but do not automatically correct bias or resolution problems.",
["Correct. It establishes fit-for-use evidence before authorizing dependent conclusions without an unnecessary universal work stop.","Marginal results are not automatically adequate for every analytical decision.","Immediate replacement is not justified by a label without an application-specific assessment.","Sample size alone does not eliminate systematic error, operator effects or inadequate discrimination."],
"Gauge R&R is evidence about measurement variation, not a universal pass/fail label. Acceptance must match the analysis purpose and decision risk; neither schedule pressure nor a larger sample substitutes for that assessment.",
"III.A.1; III.A.2; VI.A",["Marginal MSA equated with universal failure","Missing intended-use criteria","Unverified textbook chapter attribution","Length-cued distractors"])
q(60,
"A watch manufacturer's annual portfolio board repeatedly discovers product and supplier changes after affected projects have committed their next quarter's resources. Project teams already report weekly delivery status. Which governance change best addresses the delayed allocation decisions without confusing portfolio decisions with routine task monitoring?",
["Introduce reviews before major resource commitments plus material-change triggers, with the authority to resequence or stop work; adjust the interval using observed decision needs and review cost.","Require daily portfolio re-ranking from every weekly status update, with unchanged decision authority, so frequent reporting alone resolves delayed funding and resource decisions.","Keep the annual allocation decision but add weekly status presentations, without allowing changes to commitments between meetings, to preserve consistency in approved rankings.","Delegate all cross-project resource reallocations to individual project leaders, retaining only an annual summary because each team knows its own delivery risks most accurately."],
"The gap is the timing and authority of allocation decisions, not simply a shortage of status reports. Reviews should occur before consequential commitments and when material conditions change. A quarterly rhythm may suit the example, but the evidence does not establish a universal optimal interval. Individual teams need portfolio-level arbitration when their resource changes affect other projects.",
["Correct. It links review timing and decision rights to consequential commitments and changing assumptions.","Daily re-ranking can add noise and effort, and reporting frequency cannot create missing authority.","More presentations without interim decision rights leave the identified allocation delay intact.","Independent reallocations can conflict where projects share constrained resources."],
"Distinguish reporting cadence from decision cadence. A useful portfolio review must be timely enough to change a commitment and have the authority to do so.",
"III.B.1; III.B.6; III.B.8",["Cross-question framing","Universal cadence implications","Recall-level distractors"])
q(61,
"Three of a pharmacy benefit manager's 15 projects require the same vendor claims-system release, as shown below. Their separate risk logs name the dependency, but no one consolidates it or coordinates responses. Which portfolio-level intervention best addresses this shared exposure without assuming the three projects should become one?",
["Require each project to add its own contingency allowance and leave the logs separate, assuming three allowances make the shared vendor event independent across the portfolio.","Link the shared dependency across project logs, name a portfolio owner, assess affected milestones together and agree escalation and contingency responses with the vendor and project leads.","Merge the three projects and sum their stated benefits and contingencies immediately, assuming a common prerequisite also establishes a common scope and eliminates correlated risk.","Retain separate logs and inform executives only after the release is late, because an external dependency cannot be monitored or mitigated before its delivery date."],
"A single vendor event can affect several projects together. Consolidation should expose this common cause, assign ownership and coordinate assumptions, escalation and contingencies. Project-level logs remain useful inputs, but disconnected logs do not provide the portfolio view. A shared prerequisite does not prove common scope, independent risks, additive contingency needs or inevitable delays to every final completion date; available float and alternatives must be assessed.",
["Separate allowances do not make one common event independent or reveal overlapping contingency needs.","Correct. It provides connected visibility and accountable coordination while retaining distinct project scopes.","A common dependency does not justify merging otherwise distinct objectives or double-counting benefits.","External delivery can still be monitored and its potential impacts prepared for before a delay occurs."],
"Shared dependencies create correlated exposure. Consolidate the dependency and response, not automatically the project scopes; assess float and alternatives before predicting completion delays.",
"III.B.1; III.B.2; I.F.4",["Unspecified durations in original network","Project-level risk visibility overclaim","Length-cued distractors"])
q(62,
"A zoo has four Black Belts assigned nine projects as shown below. For this planning example only, each project requires 10 Belt-hours per week, each Belt has 20 available hours per week after other duties, and work is transferable without skill restrictions. At the 20-hour baseline, which interpretation should guide intake of another project? The slider explores scenarios; it does not change the question's baseline.",
["Total demand is 90 hours against 80 available, but moving one project to Belt 3 eliminates both individual overloads and the total shortfall, so another project can start.","Belts 1 and 4 each exceed capacity by 10 hours; Belt 3 has 10 spare hours, but aggregate demand exceeds capacity by 10, so redistribution alone cannot absorb all current work.","Only Belt 1 exceeds capacity by 10 hours; Belt 4's three projects are covered by the unused time on Belt 3, leaving the portfolio with 10 hours available for intake.","All nine projects fit because average allocation is 2.25 projects per Belt and the average is close to two; individual loading is not needed before approving new intake."],
"The equal-effort assumption converts assignments of 3, 2, 1 and 3 into 30, 20, 10 and 30 hours per week. With 20 hours each, total demand is 90 versus capacity 80. Local excesses total 20 hours and spare capacity is 10, giving a net shortfall of 10. Moving one project can remove one overload but cannot remove aggregate excess. Real projects need time-phased effort and skill constraints, not a universal project-count limit.",
["Reallocation preserves total demand and capacity; it cannot remove the 10-hour aggregate deficit.","Correct. It distinguishes two local overloads from the smaller net portfolio capacity deficit.","Capacity cannot be counted twice, and Belt 4 still requires its own reassignment or relief.","A near-looking average does not establish feasibility, and 2.25 exceeds the stipulated two-project capacity."],
"Capacity is a time-phased resource quantity. Local overload and aggregate shortfall differ; spare time elsewhere can offset some overload only when work can actually be reassigned.",
"III.B.8; III.A.1",["Project-count proxy lacked effort and time basis","Recall upgraded to workload interpretation","Interactive baseline unclear","Length-cued distractors"])
q(63,
"A medical billing company compares projects M and N for one explicitly defined first-year screen. M has $300,000 first-year cash benefits and $150,000 implementation cost; N has $900,000 and $600,000. These are complete incremental cash amounts for that year; ignore taxes and discounting. Define benefit–cost ratio as benefits divided by cost. Which statement correctly distinguishes ratio ranking from absolute first-year net value?",
["M has the higher ratio, 2.0 versus 1.5, and therefore also has the higher first-year net value; the ratio alone establishes the final choice under any capital constraint.","M has the higher ratio, 2.0 versus 1.5, but N has higher first-year net value, $300,000 versus $150,000; review feasibility and later cash flows before final selection.","N has the higher ratio, 2.0 versus 1.5, and higher first-year net value, $300,000 versus $150,000; both measures therefore favor N in the stated screen.","M has the higher ratio, 2.0 versus 1.5, while N produces $300,000 more net value in every future year; the first-year figures establish the same recurring difference."],
"M: 300,000/150,000 = 2.0 and first-year net value = $150,000. N: 900,000/600,000 = 1.5 and first-year net value = $300,000. N's first-year net value exceeds M's by $150,000, not $300,000. Subtracting a one-time implementation cost does not define recurring annual net benefit. The stipulated one-year screen is not a multi-year NPV model or an automatic capital-constrained selection rule.",
["A higher benefit–cost ratio does not imply higher absolute net value or solve every budget constraint.","Correct. It calculates both measures on the stated common horizon and limits the conclusion accordingly.","The stated ratio calculations are reversed; N's ratio is 1.5, not 2.0.","Later benefits and costs are unspecified, and the first-year net difference is $150,000."],
"Match the time horizon of benefits and costs. A first-year cash surplus after a one-time cost is not a recurring annual saving, and ratio ranking is not absolute-value ranking.",
"III.C.1; II.F.1",["Benefit–cost terminology reversed","Recurring versus first-year net benefit ambiguity","Missing common financial horizon","Length-cued distractors"])
