import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

// Builds sitemap.xml from the staged public site so it always matches what is
// deployed: one extensionless URL per indexable page, taken from its canonical.
// The root sitemap.xml is a committed snapshot of this output for local checks;
// the deployed copy in public-site/ is always regenerated by npm run build:site.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const SITE = 'https://upskillsprint.com';
// Sub-pages (iframes, report stubs, raw assets) and error pages are never listed.
export const excludedPrefixes = ['assets/', 'lessons/assets/', 'test-bank-assets/', 'netlify/'];
export const excludedFiles = new Set([
  '404.html', 'lesson-template.html', 'upskillsprint_lesson_theme_reference.html',
  'How to Add a New Lesson.dc.html', 'test-bank-report-form.html'
]);

export function pageUrl(relPath) {
  let path = '/' + relPath.split(sep).join('/');
  path = path.replace(/\/index\.html$/, '/').replace(/\.html$/, '');
  return SITE + path;
}

export function normalizeUrl(url) {
  return url.replace(/\/index\.html$/, '/').replace(/\.html$/, '');
}

export function sitemapEntry(relPath, html) {
  const head = html.split(/<\/head>/i)[0];
  if (/<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i.test(head)) return null;
  if (/<meta[^>]+http-equiv=["']refresh["']/i.test(head)) return null;
  const canonical = head.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1];
  if (canonical && !canonical.startsWith(SITE)) return null;
  return canonical ? normalizeUrl(canonical) : pageUrl(relPath);
}

async function* htmlFiles(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* htmlFiles(full);
    else if (entry.name.endsWith('.html')) yield full;
  }
}

export async function buildSitemap(siteDir = join(root, 'public-site')) {
  const urls = new Set();
  for await (const file of htmlFiles(siteDir)) {
    const rel = relative(siteDir, file).split(sep).join('/');
    if (excludedFiles.has(rel) || excludedPrefixes.some(prefix => rel.startsWith(prefix))) continue;
    const url = sitemapEntry(rel, await readFile(file, 'utf8'));
    if (url) urls.add(url);
  }
  const sorted = [...urls].sort((a, b) => (a === SITE + '/' ? -1 : b === SITE + '/' ? 1 : a.localeCompare(b)));
  const xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
    + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + sorted.map(url => `  <url><loc>${url.replace(/&/g, '&amp;')}</loc></url>`).join('\n')
    + '\n</urlset>\n';
  await writeFile(join(siteDir, 'sitemap.xml'), xml);
  console.log(`Wrote sitemap.xml with ${sorted.length} URLs.`);
  return sorted;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await buildSitemap();
